/* blog-data-4.jsx — wpisy przeniesione z Wix, partia 4 (I–II 2026). Dołącza do window.BLOG. */
window.BLOG.push(
  {
    slug: 'slup-rura-kable-na-dzialce-bez-umowy-bezumowne-korzystanie',
    title: 'Słup, rura lub kable na działce bez umowy? Sprawdź, czy należy Ci się wynagrodzenie za bezumowne korzystanie',
    excerpt: 'Jesteś właścicielem działki, płacisz za nią podatki, dbasz o nią. Ale przez środek Twojego ogrodu biegnie linia energetyczna albo pod ziemią zakopana jest rura gazowa. Nigdy nie wyraziłeś na to zgody, a na Twoje konto nie wpływa z tego tytułu ani złotówka. Czy przedsiębiorstwo przesyłowe może korzystać z Twojej własności „za darmo”?',
    date: '20 stycznia 2026', iso: '2026-01-20', readTime: '3 min',
    category: 'Służebność przesyłu', tags: ['Bezumowne korzystanie', 'Słupy na działce', 'Art. 224 KC'],
    cover: 'assets/blog-bezumowne-korzystanie.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/słup-rura-lub-kable-na-działce-bez-umowy-sprawdź-czy-należy-ci-się-wynagrodzenie-za-bezumowne-kor',
    related: ['bezumowne-korzystanie', 'odszkodowanie-sluzebnosc-przesylu'],
    body: [
      ['lead', 'Wyobraź sobie sytuację: jesteś właścicielem działki, płacisz za nią podatki, dbasz o nią. Ale przez środek Twojego ogrodu biegnie linia energetyczna, albo pod ziemią zakopana jest rura gazowa. Nigdy nie wyraziłeś na to zgody, nie podpisałeś żadnej umowy, a na Twoje konto nie wpływa z tego tytułu ani złotówka.'],
      ['p', 'Czy przedsiębiorstwo przesyłowe może korzystać z Twojej własności „za darmo”? Czy jako właściciel masz prawo żądać pieniędzy za przeszłość?'],
      ['p', 'Jako adwokat specjalizujący się w nieruchomościach, często słyszę te pytania.'],
      ['p', 'Odpowiedź brzmi: **tak, co do zasady masz prawo walczyć o swoje**, choć droga prawna wymaga precyzji. W dzisiejszym wpisie wyjaśnię, jak wygląda to w świetle aktualnego orzecznictwa.'],
      ['h2', 'Czym jest „bezumowne korzystanie” w kontekście służebności?'],
      ['p', 'W języku prawniczym sytuację, w której ktoś (np. zakład energetyczny) korzysta z Twojej rzeczy bez tytułu prawnego (czyli bez umowy, decyzji administracyjnej czy orzeczenia sądu), nazywamy **bezumownym korzystaniem**.'],
      ['p', 'Zgodnie z Kodeksem cywilnym, właściciel może żądać od posiadacza służebności wynagrodzenia za bezumowne korzystanie z rzeczy. Podstawą prawną są tutaj przepisy o tzw. roszczeniach uzupełniających (art. 224 § 2 i art. 225 k.c.) stosowane odpowiednio do posiadaczy służebności.'],
      ['p', 'Mówiąc prościej: jeśli firma przesyłowa zachowuje się tak, jakby miała służebność (np. trzyma swoje urządzenia na Twoim gruncie, konserwuje je, wchodzi na teren), ale formalnie tej służebności nie ma – powinna Ci zapłacić.'],
      ['h2', 'Czy właściciel musi być całkowicie pozbawiony władztwa nad ziemią?'],
      ['p', 'To był przez lata punkt sporny. Przedsiębiorstwa przesyłowe często broniły się argumentem: „Przecież ten słup zajmuje tylko kawałek pola, rolnik może orać ziemię pod drutami, więc nie zabraliśmy mu ziemi całkowicie”.'],
      ['p', 'W przeszłości zdarzały się orzeczenia sugerujące, że jeśli właściciel nie został całkowicie pozbawiony władztwa, to wynagrodzenie mu się nie należy. **Jednak obecnie dominuje pogląd korzystny dla właścicieli.**'],
      ['p', 'Sądy, w tym Sąd Najwyższy, stoją na stanowisku, że:'],
      ['ul', [
        'właściciel może żądać wynagrodzenia nawet wtedy, gdy nie został pozbawiony faktycznego władztwa nad rzeczą, a jedynie ograniczony w korzystaniu z niej;',
        'fakt, że pod liniami energetycznymi można np. uprawiać zboże, nie oznacza, że przedsiębiorstwo nie musi płacić; stopień ograniczenia własności wpływa jedynie na **wysokość** wynagrodzenia, a nie na samą zasadę jego przyznania;',
        'odmowa przyznania takiego roszczenia mogłaby naruszać konstytucyjne prawo do ochrony własności.',
      ]],
      ['p', '**Ważne: Roszczenie o wynagrodzenie za bezumowne korzystanie z nieruchomości powinno obejmować taki sam teren, jak wynagrodzenie za ustanowienie służebności.**'],
      ['h2', 'Historia Pana Marka – przykład z życia'],
      ['p', 'Pan Marek odziedziczył działkę pod miastem. Przez jej róg przechodziła stara linia energetyczna wybudowana w latach 90. Zakład energetyczny regularnie przysyłał ekipy do wycinki drzew pod linią, niszcząc przy tym ogrodzenie Pana Marka. Kiedy Pan Marek zażądał okazania umowy, firma stwierdziła, że „zasiedziała” prawo, ale nie przedstawiła na to dowodów.'],
      ['p', 'Pan Marek, z moją pomocą, wystąpił z dwoma żądaniami:'],
      ['ol', [
        'ustanowienie służebności przesyłu na przyszłość (za odpowiednim wynagrodzeniem);',
        'zapłata za bezumowne korzystanie z gruntu za ostatnie 10 lat (ponieważ roszczenia te przedawniają się z reguły po 10 latach).',
      ]],
      ['p', 'Sąd przyznał rację Panu Markowi, potwierdzając, że wyłączną przyczyną roszczeń uzupełniających jest samo posiadanie cudzej rzeczy przez przedsiębiorstwo bez tytułu prawnego.'],
      ['h2', 'Jak oblicza się wysokość wynagrodzenia?'],
      ['p', 'Tu musimy być realistami. Kwoty, które można uzyskać, rzadko odpowiadają pełnym stawkom czynszu dzierżawnego. Dlaczego? Ponieważ posiadanie służebności jest specyficzne – „słabsze” niż pełne posiadanie.'],
      ['p', 'Sąd Najwyższy wskazuje, że punktem odniesienia nie mogą być wprost stawki czynszu najmu lub dzierżawy całej nieruchomości, ponieważ stopień ingerencji przedsiębiorstwa jest mniejszy. Jeśli masz słup na polu, nadal możesz z tego pola korzystać w ograniczonym zakresie. Wynagrodzenie musi być więc **odpowiednie** do stopnia tego ograniczenia i uciążliwości.'],
      ['h2', 'Podsumowanie – co możesz zrobić?'],
      ['p', 'Mimo pewnych rozbieżności w orzecznictwie w przeszłości, obecnie linia orzecznicza jest ugruntowana: **właścicielowi należy się wynagrodzenie od posiadacza służebności (przedsiębiorstwa) za korzystanie z rzeczy bez umowy**.'],
      ['p', 'Pamiętaj jednak, że każda sprawa jest inna. Kluczowe jest ustalenie, czy przedsiębiorstwo nie dysponuje tzw. decyzją wywłaszczeniową z lat minionych lub czy nie doszło do zasiedzenia służebności.'],
      ['h3', 'Sprawdź swoją sytuację prawną bez ryzyka'],
      ['p', 'Masz wątpliwości, czy w Twoim przypadku walka o odszkodowanie ma sens? Nie chcesz wchodzić w koszty bez wstępnej analizy?'],
      ['p', '**Opisz sprawę w formularzu poniżej — bezpłatna wstępna analiza w ciągu 24 h.** W odpowiedzi:'],
      ['ul', [
        'ocenię potencjał Twojej sprawy;',
        'wyjaśnię, jakie dokumenty będą potrzebne;',
        'powiem Ci szczerze, czy gra jest warta świeczki.',
      ]],
    ],
  },
  {
    slug: 'sluzebnosc-przesylu-jak-obliczyc-wynagrodzenie',
    title: 'Służebność przesyłu: jak obliczyć wynagrodzenie za słupy i rury na działce? Praktyczny poradnik',
    excerpt: 'Czy na Twojej działce stoi słup energetyczny, a może pod ziemią biegnie rura z gazem? Jeśli tak, przedsiębiorstwo przesyłowe korzysta z Twojej własności. Zgodnie z prawem należy Ci się za to „odpowiednie” wynagrodzenie. Problem w tym, że przepisy nie podają gotowego wzoru na jego wyliczenie.',
    date: '5 stycznia 2026', iso: '2026-01-05', readTime: '3 min',
    category: 'Służebność przesyłu', tags: ['Wynagrodzenie', 'Rzeczoznawca', 'Strefa ochronna'],
    cover: 'assets/blog-wynagrodzenie-przesyl.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/służebność-przesyłu-jak-obliczyć-wynagrodzenie-za-słupy-i-rury-na-działce-praktyczny-poradnik',
    related: ['odszkodowanie-sluzebnosc-przesylu', 'bezumowne-korzystanie'],
    body: [
      ['lead', 'Czy na Twojej działce stoi słup energetyczny, a może pod ziemią biegnie rura z gazem? Jeśli tak, przedsiębiorstwo przesyłowe korzysta z Twojej własności. Zgodnie z prawem, należy Ci się za to „odpowiednie” wynagrodzenie.'],
      ['p', '**Problem w tym, że przepisy nie podają gotowego wzoru na jego wyliczenie. W dzisiejszym wpisie wyjaśniam, jak sądy podchodzą do wyceny służebności przesyłu i jakie czynniki decydują o tym, czy otrzymasz tysiąc, czy kilkadziesiąt tysięcy złotych.**'],
      ['h2', 'Czym jest służebność przesyłu i dlaczego należą Ci się pieniądze?'],
      ['p', 'Służebność przesyłu to ograniczone prawo rzeczowe. W uproszczeniu: to sytuacja, w której Ty jesteś właścicielem gruntu, ale firma (np. energetyczna lub gazownicza) ma prawo korzystać z jego fragmentu, aby przesyłać prąd, gaz czy wodę. Ma też prawo wchodzić na Twój teren, aby naprawiać lub konserwować swoje urządzenia.'],
      ['p', 'Zasadą jest, że ustanowienie tej służebności jest **odpłatne**. Co ważne, nawet jeśli urządzenia stoją na działce od lat, a Ty tolerowałeś ten stan, nie oznacza to, że zrzekłeś się prawa do zapłaty.'],
      ['h2', 'Wynagrodzenie to więcej niż odszkodowanie'],
      ['p', 'Wielu klientów myli pojęcia, żądając „odszkodowania”. Tymczasem w prawie cywilnym mówimy o **wynagrodzeniu** za ustanowienie służebności. To pojęcie szersze:'],
      ['ul', [
        '**odszkodowanie** naprawia konkretną szkodę majątkową (stratę);',
        '**wynagrodzenie** jest ekwiwalentem za to, że musisz znosić cudze urządzenia na swoim terenie. Ma ono pokryć wszystkie niedogodności, jakie w przyszłości Cię dotkną.',
      ]],
      ['p', 'Sąd Najwyższy jasno wskazuje: wynagrodzenie powinno stanowić ekwiwalent wszystkich korzyści, których jako właściciel zostaniesz pozbawiony w związku z obciążeniem działki.'],
      ['h2', 'Jak oblicza się wysokość wynagrodzenia? Brak „sztywnego cennika”'],
      ['p', 'Niestety, Kodeks cywilny nie zawiera tabeli stawek ani matematycznego wzoru. Ustawodawca mówi jedynie o wynagrodzeniu „odpowiednim”. Co to oznacza w praktyce? Każdy przypadek musi być oceniany **indywidualnie**.'],
      ['p', 'W orzecznictwie sądowym wypracowano jednak konkretne metody i czynniki, które biorą pod uwagę biegli rzeczoznawcy. Oto najważniejsze z nich:'],
      ['h3', '1. Różnica w wartości nieruchomości'],
      ['p', 'Najczęstszym sposobem wyliczenia jest sprawdzenie, ile warta byłaby Twoja działka **bez** obciążeń, a ile jest warta **z** rurą lub słupem. Różnica ta może stanowić podstawę wynagrodzenia.'],
      ['quote', 'Uwaga: Jeśli kupiłeś działkę, na której urządzenia już były, i zapłaciłeś za nią niższą cenę (uwzględniającą ten „defekt”), sąd może uznać, że nie należy Ci się zwrot różnicy wartości, bo nie poniosłeś tej konkretnej straty. Wtedy kluczowe staje się kryterium utraty użyteczności.'],
      ['h3', '2. Stopień ingerencji w Twoje prawo własności'],
      ['p', 'Wynagrodzenie zależy od tego, jak bardzo urządzenia przeszkadzają Ci w życiu. Sąd bierze pod uwagę:'],
      ['ul', [
        '**Przeznaczenie działki:** Czy to pole uprawne, czy działka budowlana?',
        '**Lokalizacja urządzeń:** Rura przy granicy działki to mniejszy problem niż rura biegnąca przez sam środek, która uniemożliwia budowę domu.',
        '**Uciążliwość:** Czy urządzenia hałasują? Czy trzeba do nich często dojeżdżać?',
        '**Pas ochronny:** Wokół gazociągów i linii wysokiego napięcia istnieją strefy, w których nie można nic budować ani sadzić drzew. To realnie wyłącza Twój grunt z użytkowania.',
      ]],
      ['h3', '3. Walory estetyczne („wątpliwa estetyka”)'],
      ['p', 'To ciekawy i często pomijany aspekt. Sąd Najwyższy zauważył, że wysoki słup na polu rolnym może nie przeszkadzać, ale ta sama konstrukcja na działce rekreacyjnej lub przy domu mieszkalnym jest istotną niedogodnością ze względu na „wątpliwe walory estetyczne”. Za to również należy się rekompensata.'],
      ['h3', '4. Perspektywa właściciela, a nie zysk przedsiębiorstwa'],
      ['p', 'Często słyszę argument: „Panie Mecenasie, oni zarabiają miliony na przesyłaniu tego prądu, niech się podzielą!”. Niestety, sądy stoją na stanowisku, że wynagrodzenia nie wylicza się na podstawie zysków przedsiębiorstwa (bo trudno je precyzyjnie przypisać do konkretnego słupa). Oceniamy stratę i dyskomfort **właściciela gruntu**.'],
      ['h2', 'Przykład z życia wzięty: Pan Marek i gazociąg'],
      ['p', 'Mój Klient posiada działkę pod miastem. W planie zagospodarowania jest to teren pod budownictwo jednorodzinne. Przez środek działki biegnie jednak gazociąg.'],
      ['ul', [
        'Pan Marek nie może wybudować domu tam, gdzie chciał, bo ogranicza go strefa ochronna.',
        'Działka straciła na atrakcyjności – potencjalny kupiec zapłaciłby za nią znacznie mniej niż za sąsiednią działkę „czystą”.',
        'Pan Marek nie może sadzić drzew w pasie gazociągu.',
      ]],
      ['p', 'W takiej sytuacji Panu Markowi należy się wynagrodzenie, które zrekompensuje mu **obniżenie wartości działki** oraz **trwałe ograniczenie w możliwości jej zabudowy**.'],
      ['h2', 'Czy warto iść do sądu?'],
      ['p', 'Sprawy o służebność przesyłu są skomplikowane i wymagają powołania biegłego rzeczoznawcy. To biegły w swojej opinii wylicza konkretne kwoty, biorąc pod uwagę wszystkie czynniki, o których wspomniałem wyżej (współczynniki korygujące, strefy ochronne, charakter działki).'],
      ['p', 'Pamiętaj jednak, że wynagrodzenie nie może przewyższyć wartości samej nieruchomości.'],
      ['h3', 'Twoja nieruchomość jest obciążona? Sprawdźmy to!'],
      ['p', 'Walka z gigantami energetycznymi czy gazowymi wydaje się trudna, ale prawo stoi po Twojej stronie. Kluczem jest odpowiednie sformułowanie roszczeń i rzetelna wycena szkody.'],
      ['p', 'Nie musisz od razu decydować się na proces. **Opisz sprawę w formularzu poniżej — bezpłatna wstępna analiza w ciągu 24 h.** W odpowiedzi:'],
      ['ul', [
        'spojrzę na mapę Twojej działki;',
        'ocenię, czy masz szansę na uzyskanie wynagrodzenia;',
        'podpowiem, jakie dokumenty warto zgromadzić na start.',
      ]],
    ],
  },
  {
    slug: 'kara-umowna-za-opoznienie-dewelopera-uchwala-sn',
    title: 'Kara umowna za opóźnienie dewelopera to nie wszystko. Przełomowa uchwała Sądu Najwyższego',
    excerpt: 'Opóźnienie dewelopera to dla Ciebie konkretne straty finansowe: dłuższy najem, wyższe raty kredytu. Zaglądasz do umowy, a tam deweloper wpisał karę umowną za każdy dzień zwłoki. Wydaje się, że jesteś chroniony, prawda? Często to tylko prawna pułapka — ale Sąd Najwyższy stanął właśnie po stronie kupujących.',
    date: '23 lutego 2026', iso: '2026-02-23', readTime: '3 min',
    category: 'Spory z deweloperem', tags: ['Kara umowna', 'Sąd Najwyższy', 'Klauzule abuzywne'],
    cover: 'assets/blog-kara-umowna-deweloper.png',
    source: 'https://www.mecenasodnieruchomosci.pl/post/kara-umowna-za-opóźnienie-dewelopera-to-nie-wszystko-przełomowa-uchwała-sądu-najwyższego',
    related: ['kary-za-opoznienie-dewelopera', 'sprawdzenie-umowy-deweloperskiej'],
    body: [
      ['lead', 'Kupno wymarzonego mieszkania to ogromny stres, a oczekiwanie na odbiór kluczy potrafi ciągnąć się w nieskończoność. Opóźnienie dewelopera to dla Ciebie konkretne straty finansowe, ponieważ musisz dłużej wynajmować dotychczasowe lokum lub płacić wyższe raty kredytu. Zaglądasz do umowy, a tam deweloper wpisał karę umowną za każdy dzień zwłoki. Wydaje się, że jesteś chroniony, prawda? Niestety, często to tylko prawna pułapka, ale Sąd Najwyższy stanął właśnie po stronie kupujących.'],
      ['h2', 'Pułapka w umowach deweloperskich'],
      ['p', 'Wielu deweloperów stosuje w umowach sprytny zabieg. Zastrzegają na rzecz kupującego karę umowną za zwłokę, ale celowo pomijają jedno kluczowe prawo: możliwość dochodzenia odszkodowania przenoszącego wysokość tej kary. Jest to niezwykle ważne, ponieważ zgodnie z Kodeksem cywilnym, jeśli strony wpisały do umowy karę umowną na wypadek niewykonania lub nienależytego wykonania zobowiązania, żądanie odszkodowania przenoszącego jej wysokość nie jest dopuszczalne, chyba że strony postanowiły inaczej. W praktyce deweloper wpisuje mikroskopijną karę, blokując Ci w ten sposób drogę do odzyskania rzeczywistych strat.'],
      ['p', 'Należy wyraźnie podkreślić ważny fakt: zastrzeżenie kary umownej na rzecz konsumenta bez jednoczesnego ustanowienia uprawnienia do żądania odszkodowania przenoszącego jej wysokość, to klasyczny przykład wykorzystania przez dewelopera braku doświadczenia lub rozeznania słabszej strony.'],
      ['h2', 'Przełomowa uchwała Sądu Najwyższego (III CZP 22/25)'],
      ['p', 'Sytuacja nabywców uległa drastycznej poprawie dzięki uchwale Sądu Najwyższego z dnia 31 października 2025 r. W sprawie o sygnaturze III CZP 22/25 Sąd Najwyższy pochylił się nad tym nieuczciwym procederem i wydał bardzo korzystne dla konsumentów stanowisko. Najważniejsze wnioski z uchwały kształtują się następująco:'],
      ['ul', [
        'po pierwsze, zapis ograniczający odszkodowanie wyłącznie do zastrzeżonej kary umownej za każdy dzień zwłoki w przeniesieniu własności lokalu uważa się w razie wątpliwości za niedozwolone postanowienie umowne, czyli tak zwaną szarą klauzulę;',
        'po drugie, takie „kadłubowe” postanowienia w nieuczciwy sposób ograniczają odpowiedzialność przedsiębiorcy za nienależyte wykonanie zobowiązania względem konsumenta, kształtując jego prawa w sposób sprzeczny z dobrymi obyczajami;',
        'po trzecie, omawiany zapis jest szczególnie niedozwolony wtedy, gdy deweloper ustalił stawkę kary umownej na rażąco niskim poziomie.',
      ]],
      ['p', 'Dzięki tej uchwale Twoja sytuacja diametralnie się zmienia, ponieważ postanowienie uznane za abuzywne (niedozwolone) nie wiąże konsumenta, co otwiera drogę do dochodzenia pełnego odszkodowania na zasadach ogólnych, niezależnie od symbolicznej kwoty zapisanej w akcie notarialnym.'],
      ['h2', 'Przykład z wokandy i 125 tysięcy złotych strat'],
      ['p', 'Aby lepiej to zobrazować, warto prześledzić historię z wokandy, która doprowadziła do podjęcia tej uchwały. Powodowie domagali się od dewelopera zapłaty kwoty 125 000 zł odszkodowania. Suma ta wynikała z faktu, że przez niewykonanie zobowiązania przez dewelopera musieli oni niekorzystnie sprzedać inną nieruchomość, co wygenerowało szkodę w wysokości 69 800 zł, a dodatkowo utracili korzyści z czynszu najmu w kwocie 55 200 zł. Deweloper bronił się umową z 10 maja 2016 r., w której sprytnie wpisano karę umowną wynoszącą zaledwie 0,01% wpłaconych kwot za każdy dzień zwłoki w ustanowieniu własności lokalu, z pominięciem prawa do wyższego odszkodowania. Ostatecznie uznano, że takie ograniczenie zmierza do zawężenia odpowiedzialności dewelopera, rażąco narusza interesy konsumentów będących słabszą stroną i jest sprzeczne z dobrymi obyczajami.'],
      ['h2', 'Nie odpuszczaj swoich pieniędzy'],
      ['p', 'Opóźnienie dewelopera to nie jest „taki urok rynku”. To zwykłe nienależyte wykonanie umowy, za które przysługuje Ci pełna rekompensata. Jeśli Twoja umowa zawiera niedozwolone zapisy, otwiera się przed Tobą droga do żądania zwrotu utraconych pieniędzy. Zastanawiasz się, czy postanowienia w Twojej umowie deweloperskiej są abuzywne?'],
      ['p', '**Prześlij umowę w formularzu poniżej — bezpłatnie, w ciągu 24 h ocenię, czy deweloper naruszył Twoje prawa i w jaki sposób możemy odzyskać Twoje pieniądze.**'],
    ],
  },
  {
    slug: 'jawne-ceny-nieruchomosci-rejestr-cen',
    title: 'Jawne ceny nieruchomości: czy każdy może sprawdzić, za ile kupiłeś mieszkanie?',
    excerpt: 'Od połowy lutego dostęp do Rejestru Cen Nieruchomości (RCN) stał się w pełni darmowy. W internecie zaczęły wyrastać portale, które masowo publikują dane o transakcjach. Z jednej strony to potężne narzędzie negocjacyjne dla kupujących. Z drugiej – cios w prywatność. Czy Twój sąsiad może teraz sprawdzić, co do złotówki, ile zapłaciłeś za swoje M4?',
    date: '24 lutego 2026', iso: '2026-02-24', readTime: '3 min',
    category: 'Rynek nieruchomości', tags: ['Rejestr Cen Nieruchomości', 'RODO', 'Prywatność'],
    cover: 'assets/blog-jawne-ceny.png',
    source: 'https://www.mecenasodnieruchomosci.pl/post/jawne-ceny-nieruchomości-czy-każdy-może-sprawdzić-za-ile-kupiłeś-mieszkanie',
    related: ['obsluga-zakupu', 'negocjacje-nieruchomosci'],
    body: [
      ['lead', 'Ostatnie zmiany w prawie otworzyły szeroko drzwi, które dla wielu z nas powinny pozostać zamknięte z napisem „prywatne”. Od połowy lutego dostęp do Rejestru Cen Nieruchomości (RCN) stał się w pełni darmowy. W efekcie w internecie zaczęły jak grzyby po deszczu wyrastać portale, które masowo publikują dane o transakcjach. Z jednej strony to ukłon w stronę kupujących, którzy zyskują potężne narzędzie negocjacyjne. Z drugiej – potężny cios w naszą prywatność. Czy faktycznie Twój sąsiad może teraz sprawdzić, co do złotówki, ile zapłaciłeś za swoje M4?'],
      ['h2', 'Co dokładnie trafiło do sieci?'],
      ['p', 'Autorzy nowelizacji prawa geodezyjnego i kartograficznego argumentowali, że zniesienie opłat wyrówna szanse na rynku i ułatwi kupującym zorientowanie się w realnych cenach. To standard w wielu państwach – np. we Francji działa rządowa baza DVF, a w USA portale takie jak Zillow pokazują historię cen bezpośrednio przy ogłoszeniach.'],
      ['p', 'Jednak polska realizacja tego pomysłu budzi ogromne kontrowersje. W darmowym RCN (który czerpie dane bezpośrednio z aktów notarialnych) nie znajdziemy co prawda imienia i nazwiska kupującego czy sprzedającego. Znajdziemy tam jednak:'],
      ['ul', [
        'dokładny adres nieruchomości – w tym numer mieszkania;',
        'powierzchnię, liczbę pokoi (izb) oraz kondygnację;',
        'dokładną datę transakcji i zapłaconą cenę.',
      ]],
      ['p', 'Jak słusznie zauważają eksperci Polskiej Federacji Stowarzyszeń Rzeczoznawców Majątkowych, połączenie dokładnego adresu z ceną sprawia, że identyfikacja, za ile dany właściciel nabył swój majątek, jest banalnie prosta. Wystarczy wiedzieć, kto mieszka pod danym adresem.'],
      ['h2', 'Czy to legalne? RODO i Konstytucja w obronie prywatności'],
      ['p', 'Jako adwokat często spotykam się z pytaniem: „Panie Mecenasie, przecież to narusza moje RODO!”. I rzeczywiście, z prawniczego punktu widzenia sprawa jest wysoce dyskusyjna.'],
      ['p', 'Z jednej strony mamy przepisy wspierające transparentność (finansowane z podatków dane powinny służyć społeczeństwu). Z drugiej, Konstytucja RP w art. 47 gwarantuje nam prawo do prywatności, a w art. 51 zakazuje władzom gromadzenia i udostępniania informacji o obywatelach innych, niż jest to niezbędne w państwie prawnym. Pytanie, czy publikacja w internecie ceny Twojego konkretnego mieszkania jest „niezbędna”? Wielu ekspertów uważa, że absolutnie nie.'],
      ['p', 'Co więcej, udostępnianie tych danych przez prywatne portale bez informowania o tym zainteresowanych osób może naruszać art. 14 ust. 1-3 unijnego rozporządzenia RODO. Właściciele takich portali często odrzucają wnioski o usunięcie danych, jednak prawnicy wskazują, że obywatele mają pełne prawo żądać ich wykasowania.'],
      ['h3', 'Światełko w tunelu: rządowy portal „Dom”'],
      ['p', 'Ciekawostką jest fakt, że równolegle Ministerstwo Rozwoju i Technologii pracuje nad własnym portalem „Dom”, który ma ruszyć w przyszłym roku. Choć cel jest ten sam (walka z asymetrią informacji i zawodnością rynku), wykonanie ma być zupełnie inne. Pod wpływem interwencji Urzędu Ochrony Danych Osobowych (UODO), rządowy portal nie pokaże cen pojedynczych mieszkań. Będzie prezentował jedynie średnią cenę obliczoną z minimum sześciu transakcji. Ten mechanizm ma zagwarantować anonimowość nabywców. Skoro więc sam rząd widzi problem i anonimizuje dane, dlaczego prywatne portale pobierające informacje z RCN mogą je publikować bez skrępowania? To luka, która prędzej czy później będzie musiała zostać załatana przez UODO.'],
      ['h2', 'Przykład z życia wzięty'],
      ['p', 'Pan Tomasz w styczniu kupił mieszkanie w nowym apartamentowcu w Lublinie. Wynegocjował świetną cenę, ponieważ sprzedawcy zależało na szybkiej gotówce. Pod koniec lutego sąsiad z klatki, podczas przypadkowej rozmowy w windzie, rzucił: „No, widziałem w internecie, że ubił pan niezły interes na tym lokalu numer 14”. Pan Tomasz poczuł się odarty z prywatności. Nigdy nikomu nie chwalił się swoimi finansami, a teraz jego akt notarialny stał się de facto wiedzą publiczną.'],
      ['h2', 'Zadbaj o swoje bezpieczeństwo prawne'],
      ['p', 'Obecna sytuacja prawna to klasyczne starcie dwóch wartości: prawa do informacji z prawem do prywatności. Jeśli czujesz, że publikacja danych o Twojej transakcji uderza w Twoje poczucie bezpieczeństwa, narusza Twoje dobra osobiste lub (w przypadku przedsiębiorców) tajemnicę przedsiębiorstwa, nie musisz składać broni.'],
      ['p', '**Czy wiesz, jakie masz możliwości prawne w walce o usunięcie swoich danych z sieci?** Opisz sytuację w formularzu poniżej — bezpłatnie, w ciągu 24 h, na chłodno i bez prawniczego żargonu ocenię Twoją sytuację i podpowiem, jakie kroki możemy podjąć, aby chronić Twoją prywatność.'],
    ],
  },
  {
    slug: 'czy-sasiad-moze-zablokowac-budowe',
    title: 'Czy sąsiad może zablokować Twoją budowę? Prawo inwestora a interesy osób trzecich',
    excerpt: 'Masz świetny projekt, zabezpieczone finansowanie, działkę i nagle pojawia się mur. Sąsiedzi obawiają się hałasu, a urząd, zamiast wydać zgodę, piętrzy przed Tobą trudności. Czy czyjeś niezadowolenie może przekreślić Twoje plany? Przekładam na „ludzki” język przepisy i najnowsze orzecznictwo — gdzie kończą się prawa sąsiada, a zaczyna Twoje prawo do zabudowy.',
    date: '26 lutego 2026', iso: '2026-02-26', readTime: '3 min',
    category: 'Proces budowlany', tags: ['Pozwolenie na budowę', 'Sąsiad', 'Hałas'],
    cover: 'assets/blog-sasiad-budowa.png',
    source: 'https://www.mecenasodnieruchomosci.pl/post/czy-sąsiad-może-zablokować-twoją-budowę-prawo-inwestora-a-interesy-osób-trzecich',
    related: ['pozwolenie-na-budowe', 'nadzor-budowlany-pinb'],
    body: [
      ['lead', 'Rozumiem, jak ogromnie stresującym momentem w procesie inwestycyjnym jest oczekiwanie na pozwolenie na budowę. Masz świetny projekt, zabezpieczone finansowanie, działkę i nagle pojawia się mur. Sąsiedzi obawiają się hałasu, a urząd, zamiast wydać zgodę, piętrzy przed Tobą trudności. Zastanawiasz się pewnie, czy czyjeś niezadowolenie może przekreślić Twoje plany. Dzisiaj przełożymy na „ludzki” język przepisy i najnowsze orzecznictwo sądów administracyjnych, aby pokazać Ci, gdzie kończą się prawa sąsiada, a zaczyna Twoje prawo do zabudowy.'],
      ['h2', 'Prawo do budowy to Twoje święte prawo'],
      ['p', 'Zacznijmy od absolutnej podstawy, mianowicie polskie Prawo budowlane stoi po stronie inwestora. Prawo zabudowy własnej nieruchomości gruntowej jest nierozerwalnie związane z prawem własności. Każdy ma prawo zabudowy nieruchomości gruntowej, jeżeli wykaże prawo do dysponowania nieruchomością na cele budowlane, pod warunkiem zgodności zamierzenia budowlanego z przepisami. Prawo to może być ograniczone wyłącznie ustaleniami miejscowego planu zagospodarowania przestrzennego lub, w przypadku jego braku, warunkami określonymi w decyzji o warunkach zabudowy oraz powszechnie obowiązującymi przepisami.'],
      ['p', 'Co niezwykle istotne dla Ciebie jako inwestora, konstrukcja przepisów, na podstawie których wydawane jest pozwolenie na budowę, wskazuje, że decyzja ta nie ma charakteru uznaniowego, ale przeciwnie, jest decyzją związaną. Oznacza to, że jeśli spełniasz wszystkie wymogi prawne, urząd po prostu musi wydać Ci pozwolenie. Organy administracji mogą ingerować w planowaną zabudowę nieruchomości tylko w zakresie wyznaczonym przepisami prawa.'],
      ['h2', 'Interes prawny a „widzimisię” sąsiada'],
      ['p', 'Urzędy mają obowiązek chronić uprawnienia osób trzecich, jednak wyznacznikiem zakresu tej ochrony są przepisy prawa materialnego. Ochrona uzasadnionych interesów osób trzecich nie może być zatem rozumiana w sposób absolutny. Z reguły każda inwestycja powoduje uciążliwości dla sąsiednich nieruchomości, na przykład ogranicza światło, widok, emituje hałas czy powoduje zwiększony ruch pieszy lub drogowy. Nie chodzi tu jednak o wszelkie utrudnienia, jakie może przynosić planowane przedsięwzięcie, a jedynie o takie, które mogą dotyczyć naruszeń interesów prawnych, a nie interesów faktycznych innych osób.'],
      ['p', 'W sytuacji, gdy nie można mówić o naruszeniu konkretnych przepisów prawa, w tym norm warunków technicznych i prawa o ochronie środowiska, organ architektoniczno-budowlany nie może odmówić wydania decyzji o pozwoleniu na budowę. Poszanowanie interesów osób trzecich polega po prostu na umożliwieniu tym podmiotom skorzystania z prawa zabudowy w takim zakresie, w jakim przysługuje ono inwestorowi. Niezbędne jest wyraźne sprecyzowanie konkretnego przepisu prawa administracyjnego, wykluczającego bądź ograniczającego zagospodarowanie działki sąsiedniej ze względu na powstanie projektowanej zabudowy.'],
      ['h2', 'Analiza hałasu a decyzja urzędu w świetle orzecznictwa'],
      ['p', 'Bardzo częstą kością niezgody jest potencjalny hałas. Zgodnie z niedawnym, niezwykle ważnym wyrokiem Wojewódzkiego Sądu Administracyjnego w Gliwicach z 7 stycznia 2026 r., sygnatura akt II SA/Gl 1068/25, ochrona osób trzecich przed uciążliwościami nie może prowadzić do nieuzasadnionego ograniczenia prawa inwestora do zabudowy nieruchomości. Dopuszczalne poziomy hałasu w środowisku są ściśle określone w przepisach i dla terenów zabudowy mieszkaniowej jednorodzinnej wynoszą 50 dB w ciągu dnia i 40 dB w nocy. Z kolei dla terenów zabudowy mieszkaniowo-usługowej dopuszczalny poziom hałasu wynosi 55 dB w ciągu dnia i 45 dB w nocy.'],
      ['p', 'Jeżeli w toku postępowania dostarczysz rzetelną analizę emisji hałasu, z której wynika, że poziom hałasu w żadnym punkcie terenu planowanego przedsięwzięcia nie powinien przekraczać wartości dozwolonej, urząd nie może jej zignorować. Aby skutecznie podważyć treść przedstawionej przez Ciebie ekspertyzy, nie jest wystarczające wskazywanie odmiennej tezy. O ile organ lub sąsiad zarzuca ekspertyzie stronniczość, konieczne jest przedłożenie kontrdowodów na okoliczność, iż ekspertyza ta jest wadliwa.'],
      ['h2', 'Krótki przykład z życia wzięty'],
      ['p', 'Pan Tomasz planował budowę sali zabaw dla dzieci oraz sklepu na swojej działce, jednak sąsiad złożył protest, twierdząc, że hałas zniszczy jego spokój. Urząd nakazał udowodnić, że inwestycja nie zakłóci najbliższego sąsiedztwa i nie będzie stanowić zagrożenia dla zdrowia. Pan Tomasz przedłożył analizę dotyczącą poziomu hałasów, która wykazywała spełnienie obowiązujących norm. Mimo to organ I instancji odmówił pozwolenia na budowę, opierając się na ogólnikowych sformułowaniach i nie odnosząc się w ogóle do złożonych wyjaśnień. Takie stanowisko niezasadnie zaakceptował również organ II instancji. Sprawa trafiła do sądu, który uznał skargę za zasadną i uchylił krzywdzące inwestora decyzje. Sąd wyraźnie wskazał, że ocena dowodów, w tym analiza hałasu, nie została przeprowadzona przez urzędników zgodnie z regułami wynikającymi z Kodeksu postępowania administracyjnego.'],
      ['h2', 'Podsumowanie'],
      ['p', 'Twój sąsiad ma prawo patrzeć Ci na ręce, ale nie ma prawa bezpodstawnie wstrzymywać Twojej inwestycji. Sam fakt potencjalnych uciążliwości dla sąsiedztwa nie może stanowić podstawy odmowy pozwolenia, jeżeli nie dochodzi do naruszenia konkretnych przepisów prawa. Jeżeli napotykasz opór w urzędzie lub mierzysz się z nieuzasadnionymi skargami sąsiadów, warto niezwłocznie skonsultować się z prawnikiem.'],
      ['p', 'Zamiast tracić czas na przepychanki pismami, **opisz sprawę w formularzu poniżej — bezpłatna wstępna analiza w ciągu 24 h**. W odpowiedzi:'],
      ['ul', [
        'przeanalizuję dotychczasową korespondencję z urzędem architektoniczno-budowlanym;',
        'sprawdzę zasadność zarzutów podnoszonych przez sąsiadów;',
        'zaproponuję strategię obrony Twojego interesu prawnego.',
      ]],
    ],
  },
  {
    slug: 'odszkodowanie-za-plan-ogolny',
    title: 'Odszkodowanie za plan ogólny – czy gmina zapłaci za spadek wartości działki?',
    excerpt: 'Reforma planowania przestrzennego narzuciła gminom obowiązek zastąpienia starego studium planem ogólnym. Dla wielu osób brzmi to jak czysta biurokracja, ale w rzeczywistości może drastycznie zmienić wartość Twojej działki. Czy jeśli gmina „odbierze” Ci prawo do budowy domu, możesz liczyć na pieniądze?',
    date: '9 lutego 2026', iso: '2026-02-09', readTime: '2 min',
    category: 'Planowanie przestrzenne', tags: ['Plan ogólny', 'Odszkodowanie', 'Art. 36 u.p.z.p.'],
    cover: 'assets/blog-odszkodowanie-plan-ogolny.png',
    source: 'https://www.mecenasodnieruchomosci.pl/post/odszkodowanie-plan-ogolny',
    related: ['oplaty-odszkodowania-planistyczne', 'plan-ogolny'],
    body: [
      ['lead', 'Uchwalenie planu ogólnego to obecnie jedno z największych wyzwań dla właścicieli nieruchomości w Polsce. Reforma planowania przestrzennego narzuciła gminom obowiązek zastąpienia starego studium nowym dokumentem – planem ogólnym. Dla wielu osób zmiana ta brzmi jak czysta biurokracja, ale w rzeczywistości może ona drastycznie zmienić wartość Twojej działki. Czy jeśli gmina „odbierze” Ci prawo do budowy domu, możesz liczyć na pieniądze?'],
      ['h2', 'Czym właściwie jest plan ogólny?'],
      ['p', 'Do tej pory kierunki rozwoju gminy określało studium. Był to dokument wewnętrzny, który nie wiązał wprost przy wydawaniu decyzji o warunkach zabudowy (tzw. „WZ-ek”). **Plan ogólny zmienia zasady gry.** Będzie on aktem prawa miejscowego. Oznacza to, że jeśli plan ogólny przewidzi na Twoim terenie funkcję przyrodniczą, nie otrzymasz „WZ-ki” na dom, nawet jeśli sąsiedzi już dawno się wybudowali.'],
      ['h2', 'Odszkodowanie za plan ogólny – co mówią przepisy?'],
      ['p', 'W polskim prawie (ustawa o planowaniu i zagospodarowaniu przestrzennym) istnieje mechanizm roszczeń odszkodowawczych. Standardowo, jeśli uchwalenie lub zmiana **miejscowego planu zagospodarowania przestrzennego (MPZP)** uniemożliwia korzystanie z nieruchomości w dotychczasowy sposób, właściciel może żądać:'],
      ['ol', [
        'odszkodowania za poniesioną rzeczywistą szkodę;',
        'wykupienia nieruchomości przez gminę.',
      ]],
      ['p', '**Gdzie pojawia się haczyk?**'],
      ['p', 'Obecne przepisy koncentrują się na roszczeniach wynikających z ustaleń planu miejscowego (MPZP). Plan ogólny jest dokumentem o wyższym stopniu ogólności. Istnieje poważny spór prawny dotyczący tego, czy samo uchwalenie planu ogólnego – bez zmiany planu miejscowego – daje bezpośrednią ścieżkę do odszkodowania.'],
      ['p', 'Ważne: jeśli plan ogólny zamknie drogę do uzyskania decyzji o warunkach zabudowy (która wcześniej była realna), mamy do czynienia z ograniczeniem prawa własności. Dochodzenie odszkodowania w takiej sytuacji jest trudniejsze, ale nie niemożliwe – wymaga jednak wykazania bezpośredniego związku między nowym prawem a stratą finansową.'],
      ['h2', 'Przykład z życia: działka „budowlana” tylko z nazwy'],
      ['p', 'Wyobraźmy sobie pana Marka, który w 2022 roku kupił działkę z myślą o budowie domu. Gmina nie miała planu miejscowego, ale sąsiedzi bez problemu dostawali „WZ-ki”. W 2025 roku gmina uchwaliła plan ogólny, w którym teren pana Marka znalazł się w strefie zieleni niepodlegającej zabudowie.'],
      ['p', 'Wartość rynkowa gruntu spadła o 60%. Pan Marek nie może się wybudować, a działka stała się niemal niesprzedawalna. W takim przypadku pan Marek stoi przed szansą walki o odszkodowanie, argumentując, że gmina arbitralnie pozbawiła go potencjału inwestycyjnego nieruchomości.'],
      ['h2', 'Jak zabezpieczyć swoje interesy?'],
      ['p', 'Jeśli obawiasz się, że nowa reforma uderzy w Twoją kieszeń, musisz działać szybko:'],
      ['ul', [
        '**Monitoruj proces uchwalania planu:** masz prawo składać wnioski i uwagi do projektu planu ogólnego.',
        '**Sprawdź przeznaczenie w projekcie:** jeśli Twoja działka nagle „zmienia kolor” na mapie na taki, który wyklucza budowę – reaguj natychmiast.',
        '**Zbieraj dowody:** operaty szacunkowe sprzed i po zmianie przepisów będą kluczowe w sądzie.',
      ]],
      ['h3', 'Niepewność prawna to Twój największy wróg'],
      ['p', 'Sytuacja wokół planów ogólnych jest dynamiczna i, nie ukrywajmy, kontrowersyjna. Gminy będą bronić się przed wypłatami, argumentując, że plan ogólny to tylko „ramy”. Jednak jako właściciel masz prawo chronić swój majątek.'],
      ['p', '**Chcesz dowiedzieć się, czy w Twoim przypadku walka o odszkodowanie ma sens?** Opisz sytuację działki w formularzu poniżej — bezpłatnie, w ciągu 24 h przeanalizuję ją i wskażę, jakie kroki prawne możesz podjąć, aby nie stracić na reformie.'],
    ],
  }
);
window.BLOG.sort((a, b) => (b.iso || '').localeCompare(a.iso || ''));
