/* blog-data-3.jsx — wpisy przeniesione z Wix, partia 3 (XII 2025). Dołącza do window.BLOG. */
window.BLOG.push(
  {
    slug: 'odszkodowanie-od-dewelopera-za-wady',
    title: 'Odszkodowanie od dewelopera za wady – co można zyskać?',
    excerpt: 'Odbiór kluczy do nowego mieszkania to moment, na który czekamy miesiącami, a czasem latami. Euforia jednak szybko mija, gdy na wymarzonych ścianach pojawiają się pęknięcia, w garażu stoi woda, a wentylacja zamiast wyciągać powietrze – wdmuchuje je do środka.',
    date: '17 grudnia 2025', iso: '2025-12-17', readTime: '3 min',
    category: 'Spory z deweloperem', tags: ['Rękojmia', 'Wady lokalu', 'Obniżenie ceny'],
    cover: '/assets/blog-odszkodowanie-deweloper-wady.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/odszkodowanie-od-dewelopera-za-wady-co-można-zyskać',
    related: ['rekojmia-wady-lokalu', 'wady-czesci-wspolnych', 'usuniecie-wad-protokol'],
    body: [
      ['lead', 'Odbiór kluczy do nowego mieszkania to moment, na który czekamy miesiącami, a czasem latami. Euforia jednak szybko mija, gdy na wymarzonych ścianach pojawiają się pęknięcia, w garażu stoi woda, a wentylacja zamiast wyciągać powietrze – wdmuchuje je do środka.'],
      ['p', 'Jeśli deweloper ignoruje Twoje wezwania do naprawy lub twierdzi, że „ten typ tak ma”, musisz wiedzieć jedno: **prawo stoi po Twojej stronie**. W tym artykule wyjaśnię, o co dokładnie możesz walczyć i dlaczego odszkodowanie to często coś więcej niż tylko zwrot kosztów gładzi.'],
      ['h2', 'Nie tylko naprawa – Twoje uprawnienia z rękojmi'],
      ['p', 'Jako nabywca nieruchomości jesteś chroniony przez instytucję **rękojmi za wady fizyczne**. To potężne narzędzie prawne zapisane w Kodeksie cywilnym. Wiele osób myśli, że jedynym rozwiązaniem jest proszenie dewelopera o przysłanie ekipy remontowej. To błąd.'],
      ['p', 'Jeśli Twoje mieszkanie ma wady, masz prawo wyboru. Możesz żądać:'],
      ['ol', [
        '**Usunięcia wady** (czyli naprawy przez dewelopera).',
        '**Obniżenia ceny nieruchomości** (zwrotu części pieniędzy).',
        '**Odstąpienia od umowy** (tylko w przypadku wad istotnych – to „broń atomowa”, stosowana rzadko).',
      ]],
      ['h2', 'O co toczy się gra? Pieniądze, o których nie mówi deweloper'],
      ['p', 'Najciekawszym z punktu widzenia finansowego rozwiązaniem – zwłaszcza gdy stracisz zaufanie do ekip dewelopera – jest żądanie **obniżenia ceny**.'],
      ['p', 'Co realnie możesz zyskać? Kwota ta powinna odzwierciedlać różnicę między wartością mieszkania bez wad a wartością mieszkania z wadami. W praktyce składa się na to:'],
      ['ul', [
        '**Koszt prac naprawczych:** Realna wycena rynkowa (nie stawki dewelopera!) usunięcia usterek.',
        '**Koszt materiałów:** Wszystko, co jest potrzebne do przywrócenia stanu zgodnego z umową.',
        '**Utrata wartości handlowej:** Jeśli wady są nieusuwalne (np. zbyt niska wysokość pomieszczeń, krzywe stropy, fatalna akustyka ścian, której nie da się poprawić), należy Ci się rekompensata za to, że Twój lokal jest po prostu mniej wart na rynku.',
      ]],
      ['quote', 'Ważne: Oprócz rękojmi, możesz dochodzić odszkodowania na zasadach ogólnych. Oznacza to, że jeśli przez opieszałość dewelopera musiałeś np. dłużej wynajmować inne mieszkanie, płacić za osuszanie lokalu lub zniszczeniu uległy Twoje meble – te koszty również mogą zostać pokryte.'],
      ['h2', 'Jak to wygląda w praktyce? Historia Pana Marka'],
      ['p', 'Aby lepiej zobrazować sytuację, posłużę się przykładem z mojej kancelarii (dane zmienione).'],
      ['p', 'Pan Marek kupił apartament na parterze z ogródkiem. Po pierwszym większym deszczu okazało się, że izolacja przeciwwilgociowa została wykonana wadliwie – w salonie pojawił się grzyb, a parkiet zaczął puchnąć.'],
      ['p', 'Deweloper dwukrotnie wysyłał ekipę, która jedynie zamalowywała skutki, nie usuwając przyczyny. Pan Marek miał dość. Zleciliśmy prywatną opinię rzeczoznawcy budowlanego, który wycenił koszt poprawnego wykonania izolacji (co wiązało się z rozkuciem tarasu) oraz wymiany podłogi na **45 000 zł**. Dodatkowo wyceniliśmy szkodę związaną z niemożnością korzystania z salonu przez 3 miesiące.'],
      ['p', '**Efekt?** Zamiast kolejnej „pudrowanej” naprawy, wynegocjowaliśmy ugodę. Deweloper wypłacił Panu Markowi **52 000 zł**. Pan Marek wynajął własną, sprawdzoną ekipę, która zrobiła to raz, a dobrze.'],
      ['h2', 'Kiedy warto iść do sądu, a kiedy negocjować?'],
      ['p', 'Nie każda sprawa musi kończyć się w sądzie. Z mojego doświadczenia wynika, że **profesjonalne wezwanie do zapłaty**, poparte rzetelną opinią techniczną i podpisem adwokata, często wystarcza, by deweloper zmienił ton rozmowy. Deweloperzy to przedsiębiorcy – potrafią liczyć. Wiedzą, że w sądzie dojdą im koszty procesu, biegłych i odsetki.'],
      ['h2', 'Twoja lista kontrolna – co musisz zrobić?'],
      ['p', 'Zanim podejmiesz kroki prawne, zadbaj o dowody:'],
      ['ul', [
        '**dokumentuj wszystko:** zdjęcia, filmy, e-maile. Każda usterka musi być „na papierze”;',
        '**pilnuj terminów:** odpowiedzialność dewelopera z tytułu rękojmi trwa co do zasady **5 lat** od wydania nieruchomości;',
        '**nie odpuszczaj przy odbiorze:** nawet jeśli podpisałeś protokół bez uwag, a wady wyszły później – nadal masz prawo do roszczeń (tzw. wady ukryte).',
      ]],
      ['h2', 'Masz dość walki z wiatrakami? Sprawdźmy Twoją sytuację'],
      ['p', 'Walka z deweloperem, który dysponuje sztabem prawników, może wydawać się trudna. Ale nie musisz być w tym sam. Często wystarczy jeden celny ruch prawny, by odzyskać spokój i pieniądze należne na naprawę.'],
      ['p', 'Nie jesteś pewien, czy Twoje wady kwalifikują się do odszkodowania?'],
      ['p', '**Opisz sprawę w formularzu poniżej.** W ciągu 24 h roboczych odpiszę, co trzeba zrobić — np. wezwanie dewelopera do usunięcia wad, prywatna opinia rzeczoznawcy czy pozew o odszkodowanie — i od razu prześlę ofertę z ceną i terminem. Do akceptacji oferty nic nie płacisz.'],
    ],
  },
  {
    slug: 'farma-fotowoltaiczna-na-dzialce-rolnej',
    title: 'Czy na każdej działce rolnej można postawić farmę fotowoltaiczną?',
    metaTitle: 'Farma fotowoltaiczna na działce rolnej – kiedy można?',
    excerpt: 'Fotowoltaika w Polsce przeżywa boom, a widok paneli słonecznych na polach powoli staje się elementem naszego krajobrazu. Dla wielu właścicieli gruntów rolnych wydzierżawienie ziemi pod farmę PV to wizja stałego, bezpiecznego i atrakcyjnego dochodu pasywnego. Odpowiedź prawnika rzadko jest prosta, ale w tym przypadku brzmi ona: nie, nie na każdej działce rolnej postawisz farmę fotowoltaiczną.',
    date: '18 grudnia 2025', iso: '2025-12-18', updated: '7 października 2026', updatedIso: '2026-10-07', readTime: '4 min',
    category: 'Grunty rolne i OZE', tags: ['Fotowoltaika', 'Klasa gruntu', 'MPZP'],
    cover: '/assets/blog-farma-pv-dzialka-rolna.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/czy-na-każdej-działce-rolnej-można-postawić-farmę-fotowoltaiczną',
    related: ['dzierzawa-oze', 'odrolnienie', 'warunki-zabudowy'],
    body: [
      ['lead', 'Fotowoltaika w Polsce przeżywa boom, a widok paneli słonecznych na polach powoli staje się elementem naszego krajobrazu. Dla wielu właścicieli gruntów rolnych wydzierżawienie ziemi pod farmę PV to wizja stałego, bezpiecznego i – co tu ukrywać – atrakcyjnego dochodu pasywnego. Często trafiają do mnie Klienci z pytaniem: „Panie Mecenasie, mam 2 hektary po dziadkach, klasa ziemi słaba, czy mogę tam stawiać panele?”'],
      ['note', 'Aktualizacja 7.10.2026: Od 1 września 2026 r. studium uwarunkowań i kierunków zagospodarowania przestrzennego (dawny dokument planistyczny dla całej gminy) nie obowiązuje już w żadnej gminie. Dlatego farma fotowoltaiczna inwestora na użytkach rolnych klas I–IV albo na gruntach leśnych wymaga dziś miejscowego planu zagospodarowania przestrzennego (MPZP). Na podstawie decyzji o warunkach zabudowy (WZ) może powstać tylko na innych gruntach i przy mocy do 1000 kW, a nową WZ (z wniosku złożonego od 1 września 2026 r.) wydaje się tylko w gminie, w której wszedł w życie plan ogólny (nowy dokument planistyczny dla całej gminy). Według tych zasad zaktualizowałem opis obu ścieżek, historię Pana Tomasza i listę kontrolną.'],
      ['p', 'Odpowiedź prawnika rzadko jest prosta, ale w tym przypadku brzmi ona: **nie, nie na każdej działce rolnej postawisz farmę fotowoltaiczną.**'],
      ['p', 'Co decyduje o sukcesie takiej inwestycji? W tym artykule przeprowadzę Cię przez gąszcz przepisów – od klasy ziemi po Miejscowy Plan Zagospodarowania Przestrzennego.'],
      ['h2', '1. Ochrona gruntów rolnych – klasa ziemi ma znaczenie'],
      ['p', 'Pierwszym „sitem”, przez które musi przejść Twoja działka, jest jakość gleby. W Polsce grunty rolne podlegają ochronie prawnej, co oznacza, że państwo woli, aby na żyznych ziemiach rosło zboże, a nie stały konstrukcje stalowe.'],
      ['p', '**Złota zasada jest prosta:**'],
      ['ul', [
        '**grunty klas I, II, III (a, b):** są pod ścisłą ochroną. Uzyskanie zgody na ich odrolnienie (przeznaczenie w planie miejscowym na cele nierolnicze), a potem zezwolenia na wyłączenie z produkcji rolniczej pod farmę fotowoltaiczną jest procesem niezwykle trudnym, kosztownym, a często wręcz niemożliwym.',
        '**grunty klas IV, V, VI:** to właśnie te tereny są „ziemią obiecaną” dla inwestorów OZE. Grunty słabej jakości zazwyczaj nie wymagają skomplikowanych procedur odrolnieniowych (choć wciąż trzeba dopełnić formalności, a na ziemi klasy IV farma inwestora wymaga dziś miejscowego planu zagospodarowania przestrzennego – piszę o tym niżej) i są preferowane pod inwestycje.',
      ]],
      ['quote', 'Ważne: Zanim zaczniesz planować inwestycję, zajrzyj do wypisu z rejestru gruntów i sprawdź klasę bonitacyjną swojej działki.'],
      ['h2', '2. MPZP czy Warunki Zabudowy?'],
      ['p', 'Kolejnym kluczowym krokiem jest sprawdzenie statusu planistycznego działki. Tutaj mamy dwie możliwe ścieżki:'],
      ['h3', 'Ścieżka A: Istnieje Miejscowy Plan Zagospodarowania Przestrzennego (MPZP)'],
      ['p', 'Jeśli Twoja działka jest objęta MPZP, sprawa jest jasna, ale często bolesna. Musisz sprawdzić, jakie przeznaczenie ma Twoja działka w planie.'],
      ['ul', [
        'Jeśli jest oznaczona jako **R (rolna)** z zakazem zabudowy innej niż zagrodowa – **nie postawisz tam farmy**, chyba że doprowadzisz do zmiany planu (co trwa latami).',
        'Aby budowa była możliwa, plan musi dopuszczać na Twojej działce lokalizację instalacji odnawialnych źródeł energii, np. farmy fotowoltaicznej.',
      ]],
      ['h3', 'Ścieżka B: Brak MPZP (Warunki Zabudowy)'],
      ['p', 'To sytuacja częstsza na terenach wiejskich. W teorii, przy braku planu, staramy się o **Decyzję o Warunkach Zabudowy (WZ)**. Jest to jednak procedura obarczona ryzykiem. Przy farmie fotowoltaicznej urząd nie bada tzw. zasady dobrego sąsiedztwa (czyli tego, czy na sąsiedniej działce stoi zabudowa, do której nowa inwestycja musi się dopasować; art. 61 ust. 3 ustawy o planowaniu i zagospodarowaniu przestrzennym, dalej: u.p.z.p.). Może natomiast odmówić wydania „Wuzetki” m.in. wtedy, gdy farma będzie niezgodna z przepisami odrębnymi (czyli przepisami spoza tej ustawy, np. o ochronie przyrody) albo z planem ogólnym gminy (nowym dokumentem planistycznym dla całej gminy).'],
      ['p', 'Co więcej, od 1 września 2026 r. w żadnej gminie nie obowiązuje już studium uwarunkowań i kierunków zagospodarowania przestrzennego (dawny dokument planistyczny dla całej gminy, poprzednik planu ogólnego). Odkąd studium przestało obowiązywać, wolnostojąca farma fotowoltaiczna wymaga MPZP, a nie WZ, jeżeli ma powstać na użytkach rolnych klas I–III albo na gruntach leśnych. Na użytkach rolnych klasy IV MPZP jest potrzebny, gdy farma ma moc większą niż 150 kW albo służy działalności gospodarczej w zakresie wytwarzania energii elektrycznej (tak jest praktycznie zawsze, gdy buduje ją inwestor). Na pozostałych gruntach MPZP jest potrzebny, gdy farma ma moc większą niż 1000 kW (art. 14 ust. 6a pkt 2 u.p.z.p.; art. 58 i art. 65 ust. 1 ustawy z 7 lipca 2023 r. o zmianie ustawy o planowaniu i zagospodarowaniu przestrzennym). Farma inwestora może więc powstać na podstawie WZ tylko poza użytkami rolnymi klas I–IV i gruntami leśnymi (np. na ziemi klasy V–VI) i tylko przy mocy do 1000 kW. Do tego przy wniosku złożonym od 1 września 2026 r. WZ wydaje się tylko w gminie, w której wszedł w życie plan ogólny (art. 59 ust. 3 ustawy z 7 lipca 2023 r.). To znacznie ogranicza możliwości inwestycyjne na „dzikich” działkach.'],
      ['h2', '3. Dostęp do sieci energetycznej – „cichy zabójca” projektów'],
      ['p', 'Możesz mieć idealną działkę klasy VI i sprzyjający plan zagospodarowania, ale Twoja inwestycja nie powstanie bez **Warunków Przyłączenia**.'],
      ['p', 'Sieci energetyczne w Polsce są przeciążone. Operatorzy Systemu Dystrybucyjnego (OSD) masowo odmawiają przyłączenia nowych farm fotowoltaicznych, argumentując to brakiem mocy przyłączeniowych w danym rejonie. Bez gwarancji przyłączenia do sieci (i sprzedaży prądu), farma jest bezużyteczna.'],
      ['h2', 'Przykład z życia wzięty: historia Pana Tomasza'],
      ['p', 'Pan Tomasz odziedziczył 3 hektary ziemi klasy IVb w województwie lubelskim. Znalazł inwestora, który obiecał mu świetny czynsz dzierżawny – 12 tys. zł rocznie za hektar przez 25 lat. Pan Tomasz, widząc zera na kalkulatorze, podpisał przedwstępną umowę dzierżawy, która blokowała jego grunt na 2 lata, aby inwestor mógł załatwić formalności. Problem: Gmina nie posiadała MPZP. Inwestor wystąpił o Warunki Zabudowy, ale urząd zawiesił postępowanie, bo rada gminy przystąpiła do sporządzania MPZP. Teren miał w nim pozostać ściśle rolniczy (dziś farma inwestora na ziemi klasy IV wymaga MPZP, a WZ nie wystarczy). Dodatkowo, operator energetyczny odmówił przyłączenia ze względu na przestarzały transformator w okolicy. Efekt: Pan Tomasz przez 2 lata nie mógł uprawiać ziemi (czekał na budowę), nie dostał ani grosza czynszu (bo ten należał się dopiero od momentu uruchomienia farmy), a ostatecznie umowa wygasła.'],
      ['p', '**Wniosek:** Sama chęć i posiadanie gruntu to za mało. Umowy dzierżawy pod fotowoltaikę są skomplikowane i często przenoszą całe ryzyko niepowodzenia na właściciela gruntu.'],
      ['h2', 'Podsumowanie – co musisz sprawdzić?'],
      ['p', 'Zanim podpiszesz jakąkolwiek umowę z deweloperem farm PV, zweryfikuj te 4 punkty:'],
      ['ol', [
        '**Klasa bonitacyjna:** czy to klasa IV, V lub VI? Na ziemi klasy IV farma inwestora wymaga MPZP.',
        '**MPZP:** czy plan dopuszcza OZE, czy jest to „czysty” teren rolniczy? Bez planu farma inwestora może powstać na podstawie WZ tylko poza użytkami rolnymi klas I–IV i gruntami leśnymi (np. na ziemi klasy V–VI) i przy mocy do 1000 kW, a nową WZ (z wniosku złożonego od 1 września 2026 r.) wydaje się tylko w gminie, w której wszedł w życie plan ogólny.',
        '**Dostęp do drogi:** farma musi mieć dojazd dla ciężkiego sprzętu.',
        '**Linie energetyczne:** czy w pobliżu przebiega linia średniego napięcia (SN)? To zwiększa szansę na przyłączenie.',
      ]],
      ['h3', 'Masz wątpliwości? Nie podpisuj w ciemno.'],
      ['p', 'Rynek nieruchomości pod OZE jest drapieżny. Firmy przedstawiają gotowe wzory umów, które zabezpieczają głównie ich interesy. Jako adwokat specjalizujący się w nieruchomościach, pomagam właścicielom gruntów ocenić realne szanse inwestycji i negocjować bezpieczne umowy dzierżawy.'],
      ['p', '**Opisz sprawę w formularzu poniżej i podaj numer działki.** W ciągu 24 h roboczych odpiszę, co trzeba zrobić — np. sprawdzić klasę gruntu i przeznaczenie w planie, przejrzeć umowę dzierżawy czy wynegocjować jej zmiany — i od razu prześlę ofertę z ceną i terminem. Do akceptacji oferty nic nie płacisz.'],
    ],
  },
  {
    slug: 'ile-kosztuje-sluzebnosc-drogi-koniecznej',
    title: 'Ile kosztuje ustanowienie służebności drogi koniecznej w 2025 roku?',
    metaTitle: 'Ile kosztuje ustanowienie służebności drogi koniecznej?',
    excerpt: 'Kupiłeś działkę w atrakcyjnej cenie, ale okazuje się, że nie ma ona bezpośredniego dostępu do drogi publicznej? A może odziedziczyłeś ziemię, do której dojeżdża się „przez pole sąsiada” na podstawie ustnej umowy sprzed lat? W obu przypadkach, aby legalnie budować lub sprzedać nieruchomość, potrzebujesz uregulowanego dostępu do drogi – czyli służebności drogi koniecznej.',
    date: '19 grudnia 2025', iso: '2025-12-19', readTime: '3 min',
    category: 'Służebności', tags: ['Droga konieczna', 'Koszty', 'Biegły'],
    cover: '/assets/blog-koszt-drogi-koniecznej.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/ile-kosztuje-ustanowienie-służebności-drogi-koniecznej-w-2025-roku',
    related: ['droga-konieczna', 'audyt-stanu-prawnego-nieruchomosci'],
    body: [
      ['lead', 'Kupiłeś działkę w atrakcyjnej cenie, ale okazuje się, że nie ma ona bezpośredniego dostępu do drogi publicznej? A może odziedziczyłeś ziemię, do której dojeżdża się „przez pole sąsiada” na podstawie ustnej umowy sprzed lat? W obu przypadkach, aby legalnie budować lub sprzedać nieruchomość, potrzebujesz uregulowanego dostępu do drogi – czyli służebności drogi koniecznej. Podstawowe pytanie, jakie słyszę w kancelarii, brzmi: „Panie Mecenasie, ile to będzie kosztować?”. W 2025 roku odpowiedź na to pytanie jest złożona, ale w tym artykule rozłożymy te koszty na czynniki pierwsze.'],
      ['h2', 'Dwie drogi do celu: umowa lub sąd'],
      ['p', 'Zanim zaczniemy liczyć złotówki, musisz wiedzieć, że koszt zależy głównie od tego, czy Twój sąsiad jest ugodowy, czy też sprawa musi trafić na wokandę. Mamy więc dwa scenariusze:'],
      ['ol', [
        '**Ścieżka polubowna (Notariusz)** – szybsza, zazwyczaj tańsza operacyjnie, ale wymagająca zgody sąsiada.',
        '**Ścieżka sądowa** – dłuższa, generująca koszty biegłych, konieczna, gdy sąsiad mówi „nie”.',
      ]],
      ['h2', 'Scenariusz 1: Koszty u notariusza (gdy jest zgoda)'],
      ['p', 'Jeśli sąsiad zgadza się na ustanowienie służebności, gratuluję! To oszczędza mnóstwo czasu i nerwów. Tutaj koszty są przewidywalne i składają się na nie:'],
      ['ul', [
        '**Taksa notarialna:** Jej wysokość zależy od wartości służebności (którą określacie sami lub z rzeczoznawcą). Zazwyczaj jest to koszt rzędu **kilkuset do 1000 zł + VAT**.',
        '**Opłata sądowa za wpis w Księdze Wieczystej:** Stała opłata wynosząca **200 zł** za wpis prawa w dziale III KW nieruchomości obciążonej (sąsiada) i ewentualnie w dziale I-Sp Twojej księgi.',
        '**Wypisy aktu notarialnego:** Ok. **150-250 zł**.',
        '**Wynagrodzenie dla sąsiada:** To najważniejszy punkt. Prawo mówi, że służebność ustanawia się za wynagrodzeniem (chyba że sąsiad zrzeknie się go dobrowolnie, co zdarza się rzadko). Wysokość tej kwoty to kwestia Waszych negocjacji.',
      ]],
      ['h2', 'Scenariusz 2: Koszty w sądzie (gdy jest konflikt)'],
      ['p', 'Jeżeli sąsiad odmawia, musisz złożyć wniosek do sądu. W 2025 roku koszty postępowania sądowego wzrosły głównie ze względu na rosnące stawki biegłych. Oto co Cię czeka:'],
      ['h3', '1. Opłata od wniosku'],
      ['p', 'Na start płacisz stałą opłatę sądową w wysokości **200 zł**. To najmniejszy wydatek w całej sprawie.'],
      ['h3', '2. Opinia biegłego geodety (największa zmienna)'],
      ['p', 'Sąd nie wytyczy drogi „na oko”. Musi powołać biegłego geodetę, który sporządzi mapę do celów prawnych i zaprojektuje przebieg drogi (często w kilku wariantach).'],
      ['ul', ['**Koszt:** W 2025 roku, w zależności od stopnia skomplikowania sprawy i regionu Polski, zaliczka na biegłego to zazwyczaj **od 2 000 zł do nawet 5 000 zł**.']],
      ['h3', '3. Opinia biegłego rzeczoznawcy'],
      ['p', 'Jeśli sąd ustanowi drogę, musi też ustalić wysokość wynagrodzenia dla sąsiada (jeśli nie dogadacie się w tej kwestii w trakcie procesu). Biegły rzeczoznawca wyceni wartość zajętego gruntu.'],
      ['ul', ['**Koszt:** Kolejna zaliczka, zazwyczaj w granicach **1 500 – 3 000 zł**.']],
      ['h3', '4. Wynagrodzenie za ustanowienie służebności (odszkodowanie)'],
      ['p', 'To nie jest koszt procesowy, ale kwota, którą będziesz musiał przelać sąsiadowi po wyroku. Zgodnie z Kodeksem cywilnym (art. 145 § 1), właścicielowi gruntu, przez który droga ma prowadzić, należy się wynagrodzenie.'],
      ['ul', ['**Ile?** Zależy to od cen ziemi w Twojej okolicy i tego, jak bardzo droga „psuje” działkę sąsiada. Może to być **kilka tysięcy złotych**, a w prestiżowych lokalizacjach – nawet **kilkadziesiąt tysięcy**.']],
      ['h2', 'Przykład z życia: historia Pana Marka'],
      ['p', 'Pan Marek kupił okazyjnie działkę pod miastem. Sprzedający zapewniał: „Sąsiedzi są mili, pozwalają jeździć”. Niestety, gdy Pan Marek wjechał koparką, „miły sąsiad” postawił płot. Sprawa trafiła do sądu.'],
      ['p', 'Koszty, jakie poniósł Pan Marek (stan na 2025 r.):'],
      ['ul', [
        'Opłata sądowa: 200 zł',
        'Biegły geodeta (skomplikowany przebieg): 3 500 zł',
        'Biegły rzeczoznawca: 2 000 zł',
        'Reprezentacja prawna: (ustalana indywidualnie)',
        'Wynagrodzenie dla sąsiada (zasądzone): 18 000 zł (ponieważ droga „przecięła” działkę sąsiada, obniżając jej wartość).',
      ]],
      ['p', '**Łącznie:** Dostęp do drogi kosztował Pana Marka blisko 25 000 zł (nie licząc kosztów adwokata). Gdyby wiedział o tym przed zakupem, negocjowałby niższą cenę działki.'],
      ['h2', 'Czy da się te koszty przerzucić na sąsiada?'],
      ['p', 'W postępowaniu nieprocesowym (a takim jest sprawa o drogę konieczną) co do zasady każdy uczestnik ponosi koszty związane ze swoim udziałem w sprawie. Oznacza to, że jako wnioskodawca, to Ty – któremu zależy na drodze – zazwyczaj musisz pokryć koszty biegłych. Sąd rzadko obciąża nimi sąsiada, chyba że ten postępuje w sposób rażąco niewłaściwy.'],
      ['h2', 'Podsumowanie'],
      ['p', 'Ustanowienie drogi koniecznej to inwestycja, która podnosi wartość Twojej nieruchomości, ale wymaga budżetu.'],
      ['ul', [
        '**Wariant optymistyczny (Notariusz):** ok. 1 500 – 2 000 zł + wynagrodzenie dla sąsiada.',
        '**Wariant realistyczny (Sąd):** ok. 4 000 – 8 000 zł (koszty proceduralne) + wynagrodzenie dla sąsiada.',
      ]],
      ['h3', 'Masz problem z dojazdem do działki?'],
      ['p', 'Każda działka jest inna, a mapy geodezyjne potrafią kryć niespodzianki. Zanim wydasz tysiące złotych na biegłych lub wdasz się w konflikt z sąsiadem, warto sprawdzić, czy prawo stoi po Twojej stronie.'],
      ['p', 'Opisz sprawę w formularzu poniżej. **W ciągu 24 h roboczych** odpiszę, co trzeba zrobić — np. negocjacje z sąsiadem, umowa u notariusza czy wniosek do sądu o ustanowienie drogi koniecznej — i od razu prześlę ofertę z ceną i terminem. Do akceptacji oferty nic nie płacisz.'],
    ],
  },
  {
    slug: '5-nielegalnych-sposobow-na-wyrzucenie-lokatora',
    title: '5 nielegalnych sposobów na wyrzucenie niechcianego lokatora – jak działają „czyściciele” i dlaczego to pułapka?',
    metaTitle: '5 nielegalnych sposobów na wyrzucenie lokatora',
    excerpt: 'Masz w swoim mieszkaniu lokatora, który nie płaci, nie chce się wyprowadzić i czuje się bezkarny? W Internecie aż roi się od „skutecznych porad” i ofert firm, które obiecują szybkie rozwiązanie problemu w kilka dni. Jako adwokat muszę Cię jednak ostrzec: to, co wydaje się drogą na skróty, zazwyczaj kończy się sprawą karną dla właściciela.',
    date: '22 grudnia 2025', iso: '2025-12-22', readTime: '3 min',
    category: 'Najem', tags: ['Eksmisja', 'Czyściciele', 'Art. 191 KK'],
    cover: '/assets/blog-nielegalna-eksmisja.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/5-nielegalnych-sposobów-na-wyrzucenie-niechcianego-lokatora-jak-działają-czyściciele-i-dlaczego-to',
    related: ['eksmisja', 'windykacja-czynszu', 'bezpieczny-najem'],
    body: [
      ['lead', 'Masz w swoim mieszkaniu lokatora, który nie płaci, nie chce się wyprowadzić i czuje się bezkarny? To sytuacja, która potrafi wyprowadzić z równowagi nawet najspokojniejszego właściciela. W Internecie aż roi się od „skutecznych porad” i ofert firm, które obiecują szybkie rozwiązanie problemu w kilka dni.'],
      ['p', 'Jako adwokat muszę Cię jednak ostrzec: **to, co wydaje się drogą na skróty, zazwyczaj kończy się sprawą karną dla właściciela.** Tak zwani „czyściciele” stosują metody, które polski kodeks karny wprost penalizuje. **Zamiast odzyskać nieruchomość, możesz zyskać wyrok karny i obowiązek zapłaty wysokiego odszkodowania.**'],
      ['p', 'Oto 5 najczęstszych nielegalnych metod, przed którymi przestrzegam każdego klienta:'],
      ['h2', '1. Odcinanie mediów (prądu, wody, gazu)'],
      ['p', 'To najczęstsza metoda stosowana przez osoby mieniące się „skutecznymi negocjatorami”. Argumentacja jest prosta: skoro lokator nie płaci, właściciel nie ma obowiązku finansować mu mediów.'],
      ['ul', [
        '**rzeczywistość prawna:** zgodnie z art. 191 § 1a kodeksu karnego, kto w celu zmuszenia innej osoby do określonego działania (np. opuszczenia lokalu) stosuje przemoc innego rodzaju, która istotnie utrudnia korzystanie z zajmowanego lokalu mieszkalnego, podlega karze pozbawienia wolności do lat 3;',
        '**ryzyko:** lokator może złożyć zawiadomienie na policję, a Ty jako właściciel ryzykujesz nie tylko sprawę karną, ale też pozew o przywrócenie posiadania.',
      ]],
      ['h2', '2. Wymiana zamków pod nieobecność lokatora'],
      ['p', 'Wydaje się to najprostszym rozwiązaniem: poczekać, aż lokator wyjdzie po zakupy, wejść do środka i zmienić wkładki w drzwiach.'],
      ['ul', [
        '**rzeczywistość prawna:** w Polsce prawo chroni tzw. posiadanie, a nie tylko własność; nawet jeśli lokator zajmuje mieszkanie bezumownie, nie możesz uniemożliwić mu wejścia do miejsca, w którym aktualnie żyje;',
        '**ryzyko:** lokator ma prawo wezwać służby, które mogą nakazać Ci natychmiastowe wpuszczenie go do środka; dodatkowo grozi Ci sprawa o naruszenie miru domowego.',
      ]],
      ['h2', '3. „Dokwaterowanie” uciążliwych współlokatorów'],
      ['p', 'Firmy zajmujące się „czyszczeniem” oferują czasem wprowadzenie do mieszkania osób, które mają za zadanie uprzykrzyć życie lokatorowi tak bardzo, by sam zdecydował się na wyprowadzkę.'],
      ['ul', [
        '**rzeczywistość prawna:** takie działanie jest uznawane za uporczywe nękanie i próbę obejścia przepisów o eksmisji;',
        '**ryzyko:** sądy bardzo surowo oceniają takie próby, często nakładając na właścicieli wysokie zadośćuczynienia na rzecz nękanego lokatora.',
      ]],
      ['h2', '4. Wynoszenie mebli i rzeczy osobistych'],
      ['p', 'Wystawienie ubrań czy sprzętów lokatora na klatkę schodową to prosty przepis na poważne kłopoty.'],
      ['ul', [
        '**rzeczywistość prawna:** właściciel nie ma prawa dysponować mieniem lokatora, nawet jeśli ten jest dłużnikiem;',
        '**ryzyko:** lokator może oskarżyć Cię o kradzież lub zniszczenie mienia, a udowodnienie przed sądem, że w wyrzuconych workach nie było np. drogiej elektroniki lub gotówki, będzie niemal niemożliwe.',
      ]],
      ['h2', '5. Przymusowa „wizyta” i zastraszanie'],
      ['p', 'Nachodzenie lokatora w nocy, krzyki czy fizyczne blokowanie wyjścia z mieszkania to metody niedopuszczalne.'],
      ['ul', [
        '**rzeczywistość prawna:** to bezpośrednie naruszenie nietykalności cielesnej lub groźba karalna;',
        '**ryzyko:** służby porządkowe w takich przypadkach reagują błyskawicznie, a lokator zyskuje status ofiary, co stawia Cię w bardzo złym świetle w przyszłym procesie cywilnym.',
      ]],
      ['h2', 'Przykład z życia wzięty'],
      ['p', 'Pani Anna, właścicielka mieszkania w Warszawie, zdecydowała się na odcięcie prądu lokatorowi, który nie płacił od ośmiu miesięcy. Najemca nie tylko nie wyprowadził się, ale zgłosił sprawę do prokuratury. Efekt był opłakany: Pani Anna usłyszała wyrok skazujący za utrudnianie korzystania z lokalu oraz musiała zapłacić 5000 zł zadośćuczynienia swojemu dłużnikowi. Mieszkanie odzyskała dopiero rok później, korzystając z pomocy komornika, ale z ogromnym obciążeniem finansowym i emocjonalnym.'],
      ['h2', 'Podsumowanie: jak zrobić to legalnie?'],
      ['p', 'Jedyną bezpieczną drogą jest uzyskanie **tytułu wykonawczego** (wyroku eksmisyjnego sądu z klauzulą wykonalności) i przekazanie sprawy **komornikowi**. Tylko komornik sądowy ma uprawnienia do przymusowego usunięcia osób z lokalu.'],
      ['p', 'Rozumiem Twoją frustrację, ale jako Twój pełnomocnik pomogę Ci przejść przez tę procedurę zgodnie z literą prawa, dbając o to, byś odzyskał nieruchomość bez narażania się na odpowiedzialność karną.'],
      ['h3', 'Skorzystaj z pomocy specjalisty'],
      ['p', 'Masz problem z uciążliwym lokatorem i nie wiesz, od czego zacząć? Nie ryzykuj działań na własną rękę, które mogą obrócić się przeciwko Tobie.'],
      ['p', 'Opisz sprawę w formularzu poniżej — **bezpłatna wstępna analiza w ciągu 24 h roboczych**. W odpowiedzi:'],
      ['ul', [
        'przeczytam Twój opis i dokumenty;',
        'powiem, co trzeba zrobić: wypowiedzenie najmu, pozew o eksmisję czy wniosek do komornika;',
        'od razu prześlę ofertę z ceną i terminem.',
      ]],
      ['p', 'Do akceptacji oferty nic nie płacisz.'],
    ],
  },
  {
    slug: 'dzierzawa-pod-fotowoltaike-a-vat',
    title: 'Kiedy słońce zarabia, a fiskus zaciera ręce – czy dzierżawa pod fotowoltaikę jest zwolniona z VAT?',
    metaTitle: 'Dzierżawa pod fotowoltaikę a VAT – czy jest zwolniona?',
    excerpt: '„Prowadzę własną firmę (jestem czynnym vatowcem), ale mam też kawałek ziemi, na której jestem rolnikiem ryczałtowym. Zgłosił się do mnie inwestor, który chce na moim polu postawić farmę fotowoltaiczną. Moja księgowa zapytała, czy wystawię fakturę z VAT-em, czy bez. Przecież to moja ziemia rolna, a dzierżawa gruntów rolnych jest zwolniona z podatku, prawda?”',
    date: '30 grudnia 2025', iso: '2025-12-30', readTime: '2 min',
    category: 'Grunty rolne i OZE', tags: ['Fotowoltaika', 'VAT', 'Dzierżawa'],
    cover: '/assets/blog-dzierzawa-pv-vat.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/kiedy-słońce-zarabia-a-fiskus-zaciera-ręce-czy-dzierżawa-pod-fotowoltaikę-jest-zwolniona-z-vat',
    related: ['dzierzawa-oze', 'dzierzawa-rolna'],
    body: [
      ['h2', 'Pytanie klienta'],
      ['lead', '„Panie Mecenasie, mam taką zagwozdkę. Prowadzę własną firmę (jestem czynnym „vatowcem”), ale mam też kawałek ziemi, na której jestem rolnikiem ryczałtowym. Zgłosił się do mnie inwestor, który chce na moim polu postawić farmę fotowoltaiczną. Warunki są świetne, stały czynsz przez lata, nic tylko podpisywać.'],
      ['p', 'Ale moja księgowa zasiała we mnie ziarno niepewności. Zapytała, czy wystawię fakturę z VAT-em, czy bez. Przecież to moja ziemia rolna, a dzierżawa gruntów rolnych jest zwolniona z podatku, prawda? Czy fakt, że jestem vatowcem w innej firmie, coś tu zmienia? Nie chciałbym na starcie wpaść w kłopoty z Urzędem Skarbowym”.'],
      ['h2', 'Mecenas odpowiada'],
      ['p', 'Rozumiem Twój dylemat. To klasyczny przypadek zderzenia dwóch światów: rolniczego (zazwyczaj preferencyjnego podatkowo) i twardego biznesu energetycznego. Wielu właścicieli gruntów wpada w tę pułapkę, zakładając, że skoro ziemia jest rolna, to zwolnienie z VAT należy się „z automatu”. Niestety, w przypadku farm fotowoltaicznych sprawa wygląda inaczej.'],
      ['p', 'Musimy spojrzeć na to oczami fiskusa. Dla Urzędu Skarbowego kluczowe nie jest to, co jest napisane w ewidencji gruntów, ale to, co faktycznie będzie się na tej ziemi działo. Przepisy mówią jasno: zwolnienie z podatku VAT przysługuje tylko wtedy, gdy dzierżawca wykorzystuje grunty na **cele rolnicze**.'],
      ['p', 'Tutaj dochodzimy do sedna problemu, ponieważ:'],
      ['ul', [
        'dzierżawa gruntu pod farmę fotowoltaiczną nie jest traktowana jako działalność rolnicza;',
        'produkcja prądu ze słońca to cel przemysłowy lub usługowy, a nie rolniczy, więc nie obejmuje go zwolnienie przedmiotowe przewidziane dla rolników;',
        'usługi dzierżawy i najmu, ze względu na swój ciągły charakter, wypełniają definicję działalności gospodarczej;',
        'jeżeli wydzierżawiasz grunt na cele inne niż rolnicze (a takimi jest fotowoltaika), czynność ta jest obciążona stawką 23% VAT.',
      ]],
      ['p', 'Skoro prowadzisz już działalność gospodarczą i jesteś czynnym podatnikiem VAT, to ta transakcja zostanie „wchłonięta” przez Twój status przedsiębiorcy. Występujesz w obrocie jako profesjonalista, a nie rolnik ryczałtowy sprzedający marchewkę.'],
      ['p', 'Mówiąc najprościej: Twoja faktura za czynsz dzierżawny musi zawierać 23% VAT.'],
      ['h2', 'Co to oznacza dla Ciebie w praktyce?'],
      ['p', 'Musisz skalkulować opłacalność inwestycji, pamiętając o podatku. Kwota, którą wynegocjowałeś z inwestorem, powinna być dla Ciebie kwotą netto, do której doliczysz podatek należny Skarbowi Państwa.'],
      ['p', 'Brak świadomości tego mechanizmu to ryzyko, że:'],
      ['ul', [
        'wystawisz fakturę „zwolnioną z VAT”, a po kontroli będziesz musiał oddać 23% z własnej kieszeni wraz z odsetkami;',
        'źle skonstruujesz umowę dzierżawy, nie zabezpieczając kwestii podatkowych.',
      ]],
      ['p', 'Nie ryzykuj błędów na starcie wieloletniej umowy. Jeśli chcesz mieć pewność, że Twoja umowa dzierżawy zabezpiecza Twoje interesy, a nie tylko interesy inwestora – sprawdźmy to wspólnie.'],
    ],
  },
  {
    slug: 'plan-ogolny-a-wniosek-o-wz-w-toku',
    title: 'Panika w urzędzie? Czy „Plan Ogólny” wysadzi Twój wniosek o WZ w powietrze?',
    metaTitle: 'Plan ogólny a wniosek o WZ w toku – co się zmienia?',
    excerpt: '„Dwa miesiące temu złożyłem wniosek o Warunki Zabudowy dla mojej działki pod miastem. Wczoraj sąsiad postraszył mnie, że gmina lada chwila uchwali nowy plan ogólny. Podobno jak on wejdzie w życie, to stare przepisy idą do kosza, a mój wniosek przepadnie. Czy to prawda?”',
    date: '31 grudnia 2025', iso: '2025-12-31', updated: '7 października 2026', updatedIso: '2026-10-07', readTime: '4 min',
    category: 'Warunki zabudowy', tags: ['WZ', 'Plan ogólny', 'Przepisy przejściowe'],
    cover: '/assets/blog-plan-ogolny-wniosek-wz.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/panika-w-urzędzie-czy-plan-ogólny-wysadzi-twój-wniosek-o-wz-w-powietrze',
    related: ['warunki-zabudowy', 'plan-ogolny'],
    body: [
      ['h2', 'Pytanie Klienta'],
      ['lead', '„Panie Mecenasie, mam stan przedzawałowy! Dwa miesiące temu złożyłem wniosek o Warunki Zabudowy (WZ) dla mojej działki pod miastem. Wszystko szło gładko, ale wczoraj sąsiad postraszył mnie, że gmina lada chwila uchwali ten nowy »plan ogólny«. Podobno jak on wejdzie w życie, to stare przepisy idą do kosza, a mój wniosek przepadnie albo będą go oceniać według nowych, surowszych zasad. Czy to prawda, że moja procedura wyląduje w śmietniku, bo urzędnicy nie zdążą wydać decyzji przed zmianą prawa?”'],
      ['note', 'Aktualizacja 7.10.2026: Tekst uwzględnia stan prawny na 7 października 2026 r. Dodałem nowe daty (studium obowiązywało najdłużej do 31 sierpnia 2026 r., a przy wnioskach złożonych od 1 września 2026 r. WZ można wydać tylko w gminie z planem ogólnym) i rozwinąłem opis przepisów przejściowych. Dopisałem też, jak na sprawę w toku wpływa plan miejscowy i które WZ wygasają po 5 latach.'],
      ['h2', 'Mecenas odpowiada'],
      ['p', 'Spokojnie, proszę odłożyć leki na serce i zaparzyć sobie melisę. Sąsiad, choć pewnie miał dobre intencje, nieco minął się z prawdą. Prawo w Polsce bywa skomplikowane, ale w tym konkretnym przypadku ustawodawca zadbał o to, by nie zmieniać reguł gry w trakcie meczu.'],
      ['p', 'Kluczem do zrozumienia Twojej sytuacji są tak zwane przepisy przejściowe. Mówiąc najprościej: to instrukcja obsługi dla urzędników, która tłumaczy im, co robić ze „starymi” sprawami, gdy wchodzą „nowe” przepisy.'],
      ['p', 'Sytuacja wygląda następująco: **jeżeli Twój wniosek o Warunki Zabudowy wpłynął do urzędu, zanim w Twojej gminie wszedł w życie plan ogólny, a najpóźniej 31 sierpnia 2026 r., to jesteś bezpieczny.** Był to ostatni dzień, w którym mogło jeszcze obowiązywać stare studium (czyli dotychczasowy dokument o kierunkach zagospodarowania gminy). Przy wniosku złożonym od 1 września 2026 r. WZ można wydać tylko w gminie, w której wszedł w życie plan ogólny (art. 59 ust. 3 ustawy z 7 lipca 2023 r. o zmianie ustawy o planowaniu i zagospodarowaniu przestrzennym oraz niektórych innych ustaw).'],
      ['p', 'Urzędnicy mają obowiązek rozpatrzyć Twoją sprawę według przepisów przejściowych, które opisuję niżej. Część reguł się zmieniła, ale to nie wywraca procedury do góry nogami.'],
      ['p', 'Co to oznacza? Że wejście w życie planu ogólnego w trakcie, gdy Ty czekasz na pieczątkę, nie ma wpływu na Twoją sprawę. Choć w międzyczasie stare „studium” straciło moc, Twój wniosek jest procedowany tak, jakby planu ogólnego w ogóle nie było. Nowy plan ogólny nie będzie stosowany do postępowań, które już trwają.'],
      ['p', 'Możemy wyróżnić tu dwie grupy spraw, w zależności od tego, kiedy złożyłeś wniosek:'],
      ['ul', [
        'jeśli postępowanie ruszyło **przed 24 września 2023 r.**, to stosuje się „stare” przepisy w czystej postaci, bez żadnych zmian wprowadzonych nową ustawą;',
        'jeśli postępowanie ruszyło **24 września 2023 r. lub później** (czyli tak jak w Twoim przypadku), ale przed wejściem w życie planu ogólnego i najpóźniej 31 sierpnia 2026 r., stosuje się nowe przepisy z kilkoma wyjątkami. Przede wszystkim tzw. dobre sąsiedztwo ocenia się według przepisów w dawnym brzmieniu. Chodzi o wymóg, by co najmniej jedna działka sąsiednia, dostępna z tej samej drogi publicznej, była zabudowana w sposób, który pozwala określić wymagania dla nowej zabudowy. Nie stosuje się też nowego wymogu, by działka leżała w obszarze uzupełnienia zabudowy, czyli w wyznaczonej w planie ogólnym części gminy, poza którą co do zasady nie dostaniesz WZ na nowy budynek (art. 59 ust. 2 ustawy z 7 lipca 2023 r.);',
        '**w obu przypadkach fakt uchwalenia planu ogólnego w toku sprawy jest dla Ciebie neutralny.**',
      ]],
      ['p', '**Co to oznacza dla Ciebie w praktyce?**'],
      ['ul', [
        'Złożenie wniosku o WZ jest jak „zaklepanie kolejki” – liczy się data startu, a późniejsze wejście w życie planu ogólnego nie może Ci zaszkodzić w toczącym się postępowaniu. Inaczej jest z planem miejscowym (czyli szczegółowym planem dla Twojej okolicy). Na czas jego sporządzania urząd może zawiesić (czyli wstrzymać) Twoją sprawę, co do zasady najwyżej na 18 miesięcy od dnia złożenia wniosku. Jeżeli w tym czasie gmina zacznie zbierać uwagi do projektu planu (w ramach konsultacji społecznych albo wyłożenia projektu do publicznego wglądu), urząd może przedłużyć zawieszenie o najwyżej 6 miesięcy. Jeżeli rada gminy uchwali plan w okresie zawieszenia, WZ nie dostaniesz, a o tym, co zbudujesz, zdecyduje plan (art. 4 ust. 2 oraz art. 62 ust. 1 i 3 ustawy o planowaniu i zagospodarowaniu przestrzennym, dalej: u.p.z.p.);',
        'nie musisz się martwić, że urzędnik odrzuci wniosek tylko dlatego, że w międzyczasie radni uchwalili plan ogólny;',
        'Jeżeli w trakcie sprawy rada gminy nie uchwali planu miejscowego, najważniejsze warunki Twojej inwestycji (m.in. dobre sąsiedztwo) urząd oceni według zasad znanych Ci w momencie składania dokumentów. Jedna zmiana dotyczy jednak samej decyzji. Od 1 stycznia 2026 r. obowiązuje art. 64c u.p.z.p.: WZ wygasa po 5 latach od dnia, w którym stała się prawomocna (czyli nie można jej już zaskarżyć ani odwołaniem, ani skargą do sądu). Terminu ważności nie mają tylko WZ prawomocne przed 1 stycznia 2026 r. oraz WZ wydane na wniosek, który wpłynął do urzędu przed 16 października 2025 r. (art. 62 ustawy z 7 lipca 2023 r.). Jeżeli Twoja WZ ma 5-letni termin, wniosek o pozwolenie na budowę musi dotrzeć do urzędu przed jego upływem (art. 32 ust. 4 pkt 1 Prawa budowlanego).',
      ]],
      ['p', 'Pamiętaj jednak, że każda gmina interpretuje przepisy w swoim tempie, a diabeł tkwi w szczegółach Twojego konkretnego wniosku.'],
      ['p', 'Jeżeli masz wniosek o WZ w toku, **opisz sprawę w formularzu poniżej.** W ciągu 24 h roboczych odpiszę, co trzeba sprawdzić w dokumentacji, i prześlę ofertę z ceną i terminem. Do akceptacji oferty nic nie płacisz.'],
    ],
  }
);
window.BLOG.sort((a, b) => (b.iso || '').localeCompare(a.iso || ''));
