/* blog-data-6.jsx — nowe poradniki z planu treści 300 tematów (IX 2026). Dołącza do window.BLOG.
   Pole metaTitle (do 60 znaków) trafia do <title> zamiast pełnego tytułu (app.jsx, setMetaForView). Pole faq szablon pomija (pytania są w treści wpisu). */
window.BLOG.push(
  {
    slug: 'ile-trwa-eksmisja-lokatora',
    title: 'Ile trwa eksmisja lokatora bez tytułu prawnego? Kalendarz 2026',
    metaTitle: 'Ile trwa eksmisja lokatora? Kalendarz i koszty 2026',
    excerpt: 'Eksmisja lokatora bez tytułu prawnego trwa od kilkunastu miesięcy do kilku lat. Pokazuję kalendarz, błędy, które cofają sprawę, i jak odzyskać pieniądze.',
    date: '26 września 2026', iso: '2026-09-26', readTime: '10 min',
    updated: '27 września 2026', updatedIso: '2026-09-27',
    category: 'Najem', tags: ['Eksmisja', 'Lokal socjalny', 'Odszkodowanie od gminy'],
    cover: '/assets/blog-ile-trwa-eksmisja.jpg',
    related: ['eksmisja', 'windykacja-czynszu', 'bezpieczny-najem'],
    faq: [
      { q: 'Ile trwa eksmisja z mieszkania, gdy lokator nie płaci?', a: 'Zwykle od kilkunastu miesięcy do kilku lat. Od pierwszej nieopłaconej raty do końca najmu mija około 5 miesięcy, potem proces (zwykle od kilku do kilkunastu miesięcy) i egzekucja. Jeżeli sąd przyzna lokal socjalny albo gmina nie wskaże pomieszczenia tymczasowego, całość może trwać kilka lat.' },
      { q: 'Co zrobić, gdy lokator nie płaci i nie chce się wyprowadzić?', a: 'Gdy zaległość obejmie 3 pełne okresy płatności, uprzedź lokatora na piśmie o zamiarze wypowiedzenia i daj mu miesiąc na zapłatę. Potem wypowiedz najem na piśmie z podaniem przyczyny (art. 11). Jeżeli się nie wyprowadzi, złóż pozew o eksmisję i o odszkodowanie za zajmowanie lokalu. Nie wymieniaj zamków i nie odcinaj mediów.' },
      { q: 'Ile trwa eksmisja komornicza?', a: 'Zależy głównie od gminy. Jeżeli sąd przyznał lokal socjalny, eksmisję wstrzymuje się, aż gmina złoży ofertę (art. 14 ust. 6). Jeżeli nie przyznał, a lokator nie ma dokąd się wyprowadzić, komornik czeka, aż gmina wskaże pomieszczenie tymczasowe, bez limitu czasu (art. 1046 § 4 k.p.c.). Skrócisz to, zapewniając takie pomieszczenie samodzielnie (art. 1046 § 5).' },
      { q: 'Czy mogę wymienić zamki, gdy lokator nie płaci?', a: 'Nie. Lokator może żądać przywrócenia posiadania (art. 344 k.c.), a zmuszanie do wyprowadzki przez utrudnianie korzystania z mieszkania może być przestępstwem (art. 191 § 1a k.k.).' },
      { q: 'Czy lokatora można eksmitować zimą?', a: 'Od 1 listopada do 31 marca nie, jeżeli nie wskazano mu lokalu lub pomieszczenia, do którego ma się przenieść (art. 16). Wyjątki z art. 17 dotyczą m.in. przemocy w rodzinie i samowolnego zajęcia lokalu.' },
      { q: 'Czy można eksmitować matkę z dzieckiem z prywatnego mieszkania?', a: 'Tak. Przy mieszkaniu prywatnym sąd nie musi przyznać lokalu socjalnego nawet rodzinie z dzieckiem, bo obowiązkowy katalog z art. 14 ust. 4 nie działa (art. 14 ust. 7). Może go jednak przyznać, oceniając sytuację rodziny. Wtedy eksmisja czeka, aż gmina złoży ofertę lokalu (art. 14 ust. 6).' },
      { q: 'Czy komornik czeka na gminę tylko 6 miesięcy?', a: 'Nie. Obecny art. 1046 § 4 k.p.c. nie przewiduje limitu czasu. Czekanie możesz skrócić, zapewniając pomieszczenie tymczasowe samodzielnie (art. 1046 § 5).' },
      { q: 'Czy gmina zapłaci mi za to, że lokator dalej mieszka?', a: 'Możesz tego żądać, jeżeli sąd przyznał lokatorowi lokal socjalny, a gmina go nie dostarcza (art. 18 ust. 5). Szkodę trzeba wykazać, np. czynszem najmu, którego nie dostajesz. Termin przedawnienia jest w orzecznictwie sporny (3 albo 6 lat) i biegnie osobno za każdy miesiąc – nie czekaj z pozwem do końca eksmisji.' },
      { q: 'Ile kosztuje eksmisja?', a: 'Opłata od pozwu o eksmisję wynosi 200 zł, a opłata komornicza od wniosku o eksmisję z mieszkania 1500 zł. Do tego zaliczki na wydatki komornika (np. ślusarz, transport i przechowanie rzeczy lokatora) i wynagrodzenie pełnomocnika. Jeżeli wygrasz, sąd co do zasady obciąży lokatora kosztami procesu. Moje wynagrodzenie podaję w ofercie razem z bezpłatną wstępną analizą.' },
    ],
    body: [
      ['lead', 'Lokator nie płaci, a Ty dalej płacisz czynsz do wspólnoty? Eksmisja lokatora bez tytułu prawnego (czyli po zakończeniu najmu) może potrwać od kilkunastu miesięcy do kilku lat. Zanim w ogóle złożysz pozew, przy zaległościach w czynszu mija około 5 miesięcy. Przy czynszu najmu 2 500 zł każdy rok czekania to 30 000 zł, których nie dostajesz. Najwięcej czasu zabierają błędy w wypowiedzeniu i czekanie na gminę. Poniżej kalendarz, pułapki i to, co możesz zrobić, żeby odzyskać mieszkanie szybciej, oraz od kogo możesz żądać pieniędzy za ten czas.'],
      ['note', 'Stan prawny na 26.09.2026. Tekst dotyczy mieszkania prywatnego (właściciel to osoba fizyczna) i zwykłej umowy najmu. Najem okazjonalny opisuję na końcu.'],
      ['h2', 'Ile trwa eksmisja lokatora? Kalendarz krok po kroku'],
      ['ol', [
        '**Zaległość za 3 pełne okresy płatności.** Wypowiedzieć najem z powodu długu możesz dopiero, gdy zaległość sięga co najmniej 3 pełnych okresów płatności (art. 11 ust. 2 pkt 2 ustawy o ochronie praw lokatorów). Liczy się kwota, a nie sam upływ miesięcy.',
        '**Pisemne uprzedzenie i dodatkowy miesiąc.** Najpierw na piśmie uprzedzasz o zamiarze wypowiedzenia i dajesz miesiąc na zapłatę zaległych i bieżących należności.',
        '**Wypowiedzenie.** Dopiero potem wypowiadasz najem na piśmie, z podaniem przyczyny, na miesiąc naprzód, na koniec miesiąca kalendarzowego (art. 11 ust. 1 i 2). Od pierwszej nieopłaconej raty do końca najmu mija więc zwykle około 5 miesięcy (nawet przy najszybszym tempie nie mniej niż około 4), a przy doręczeniach przez awizo dłużej.',
        '**Pozew o eksmisję i wyrok.** Opłata od pozwu wynosi 200 zł (art. 27 pkt 11 ustawy o kosztach sądowych w sprawach cywilnych). Ile potrwa proces, zależy od sądu i od tego, czy lokator się broni. Z mojego doświadczenia: od kilku do kilkunastu miesięcy, dłużej przy apelacji.',
        '**Komornik.** Z wyrokiem z klauzulą wykonalności składasz wniosek o eksmisję. Opłata od wniosku wynosi 1500 zł (art. 34 ustawy o kosztach komorniczych) i płacisz ją z góry. Lokator ma obowiązek zwrócić ją jako koszt egzekucji (art. 770 Kodeksu postępowania cywilnego), ale od niewypłacalnego lokatora trudno ją odzyskać. Jeżeli lokator wyprowadzi się sam najpóźniej 3 dni przed wyznaczoną eksmisją, komornik zwróci Ci połowę opłaty (art. 39 ustawy o kosztach komorniczych).',
        '**Czekanie na gminę.** To najdłuższy i najmniej przewidywalny etap. Opisuję go niżej.',
      ]],
      ['h2', 'Dlaczego eksmisja z mieszkania trwa tak długo?'],
      ['h3', 'Błąd w wypowiedzeniu cofa sprawę do zera'],
      ['p', 'Sądy oddalają pozwy o eksmisję, gdy wypowiedzenie było wadliwe. Wtedy cały kalendarz zaczyna się od nowa. Typowe błędy, przez które sądy oddalały pozwy:'],
      ['ul', [
        '**Brak pisemnego uprzedzenia z miesięcznym terminem.** Wypowiedzenie jest bezskuteczne (czyli najem trwa dalej), a samego pozwu sąd nie uzna za uprzedzenie (wyrok SR dla Łodzi-Widzewa w Łodzi z 28.11.2017 r., II C 390/17).',
        '**Uprzedzenie wysłane za wcześnie**, zanim zaległość sięgnęła 3 pełnych okresów. Sąd uznał je za wadliwe, a wypowiedzenie za bezskuteczne (wyrok SR dla Łodzi-Widzewa w Łodzi z 30.04.2018 r., II C 663/17).',
        '**Inna przyczyna w wypowiedzeniu niż w pozwie.** Przyczyna podana w wypowiedzeniu wiąże wynajmującego (II C 390/17).',
        '**Zapisy umowy „na skróty”**, np. wypowiedzenie bez przyczyny albo rozwiązanie umowy przy 2 miesiącach zaległości. Są nieważne, bo art. 11 można zmienić umową tylko na korzyść lokatora (wyrok zaoczny SR w Toruniu z 6.09.2018 r., I C 534/18).',
      ]],
      ['h3', 'Samowolna eksmisja wydłuża sprawę'],
      ['p', 'Wymiana zamków, odcięcie mediów czy wyniesienie rzeczy lokatora nie skracają eksmisji. Lokator może wytoczyć powództwo o przywrócenie naruszonego posiadania (art. 344 Kodeksu cywilnego). Takie działania, stosowane uporczywie albo tak, że istotnie utrudniają korzystanie z mieszkania, żeby zmusić lokatora do wyprowadzki, są przestępstwem (art. 191 § 1a Kodeksu karnego). Może nim być nawet jednorazowa wymiana zamków, jeśli odcina lokatorowi dostęp do mieszkania. Więcej o tym piszę w poradniku „5 nielegalnych sposobów na wyrzucenie niechcianego lokatora”.'],
      ['h3', 'Czy można eksmitować matkę z dzieckiem? Sąd bada lokal socjalny'],
      ['p', 'W wyroku eksmisyjnym sąd z urzędu orzeka, czy lokatorowi przysługuje prawo do lokalu socjalnego (art. 14 ust. 1 i 3). Przy mieszkaniu prywatnym nie musi go przyznać nawet rodzinie z dzieckiem, bo obowiązkowy katalog z art. 14 ust. 4 tu nie działa (art. 14 ust. 7). Może jednak go przyznać, biorąc pod uwagę sytuację materialną i rodzinną lokatora oraz to, jak dotąd korzystał z lokalu.'],
      ['p', 'Jeżeli sąd przyzna lokal socjalny, eksmisję wstrzymuje się do czasu, aż gmina złoży lokatorowi ofertę (art. 14 ust. 6). Na to można czekać latami.'],
      ['h3', 'Komornik czeka na gminę bez limitu czasu'],
      ['p', 'Jeżeli sąd nie przyznał lokalu socjalnego, a lokator nie ma gdzie się wyprowadzić, komornik wstrzymuje eksmisję, dopóki gmina nie wskaże pomieszczenia tymczasowego (art. 1046 § 4 Kodeksu postępowania cywilnego). Przepis nie przewiduje limitu czasu. W internecie wciąż można przeczytać o 6 miesiącach, ale takiego limitu w obecnym brzmieniu przepisu nie ma.'],
      ['h3', 'Eksmisja zimą: od 1 listopada do 31 marca'],
      ['p', 'Od 1 listopada do 31 marca wyroków eksmisyjnych nie wykonuje się, jeżeli lokatorowi nie wskazano lokalu, do którego ma się przenieść (art. 16). Ten zakaz dotyczy także byłego najemcy po wypowiedzeniu. Wyjątki z art. 17 obejmują m.in. przemoc w rodzinie, rażące naruszanie porządku domowego i samowolne zajęcie lokalu.'],
      ['h2', 'Jak skrócić eksmisję i odzyskać pieniądze'],
      ['ol', [
        '**Pisma bez błędów od pierwszego dnia.** Uprzedzenie, wypowiedzenie i pozew w kolejności z art. 11. To jedyny etap, który w całości zależy od Ciebie. Błąd kosztuje cały czas procesu i co najmniej 2 miesiące na nowe uprzedzenie i wypowiedzenie.',
        '**Odszkodowanie od lokatora za każdy miesiąc.** Osoba, która zajmuje lokal bez tytułu prawnego, płaci co miesiąc odszkodowanie w wysokości czynszu, jaki mógłbyś dostać z najmu, a jeśli to nie pokrywa strat, także odszkodowanie uzupełniające (art. 18 ust. 1 i 2). Przykład: przy czynszu rynkowym 2 500 zł rok zajmowania mieszkania to 30 000 zł, których możesz żądać. Jeżeli jednak sąd przyzna lokatorowi lokal socjalny i wstrzyma eksmisję, od tej chwili lokator płaci tylko tyle, ile wynosiłby czynsz socjalny, a różnicę do dotychczasowego czynszu pokrywa gmina (art. 18 ust. 3a). Wyrok to jeszcze nie pieniądze: odzyskasz je, jeśli lokator ma z czego zapłacić.',
        '**Zapewnij pomieszczenie tymczasowe sam.** Działa to tylko wtedy, gdy sąd nie przyznał lokatorowi lokalu socjalnego. Jeżeli wskażesz pomieszczenie spełniające wymogi ustawy (m.in. co najmniej 5 m² na osobę, dostęp do wody i ustępu, możliwość ogrzewania, art. 2 ust. 1 pkt 5a) i zapewnisz lokatorowi prawo do zamieszkania w nim, np. wynajmując je na jego rzecz, komornik nie może wstrzymać eksmisji (art. 1046 § 5 k.p.c.). Moja ocena: bywa to tańsze niż czekanie na gminę. Przykład: jeśli pokój kosztuje 1 000 zł miesięcznie, a odzyskane mieszkanie wynajmiesz za 2 500 zł, zyskujesz 1 500 zł co miesiąc.',
        '**Odszkodowanie od gminy.** Jeżeli sąd przyznał lokatorowi lokal socjalny, a gmina go nie dostarcza, możesz żądać od gminy odszkodowania (art. 18 ust. 5 ustawy i art. 417 Kodeksu cywilnego; tak Sąd Najwyższy w wyroku z 29.10.2021 r., I CSKP 168/21). Trybunał Konstytucyjny uznał ten przepis za zgodny z Konstytucją (wyrok z 8.04.2010 r., P 1/08). Sąd Najwyższy przyjmuje, że sam fakt niedostarczenia lokalu przesądza o bezprawności zaniechania gminy, ale szkodę i jej związek z tym zaniechaniem trzeba wykazać (wyrok z 30.06.2022 r., II CSKP 381/22), i że gmina odpowiada niezależnie od tego, dlaczego brakuje jej lokali (wyrok z 14.11.2024 r., II CNPP 44/22). Przykład: sąd zasądził od gminy rynkowy czynsz za ponad 3 lata oczekiwania na lokal socjalny, wyliczony przez biegłego, a Sąd Apelacyjny w Krakowie utrzymał to rozstrzygnięcie, korygując jedynie omyłkę rachunkową (wyrok z 4.06.2024 r., I ACa 3007/23). Termin przedawnienia jest w orzecznictwie sporny (sądy przyjmują 3 albo 6 lat) i biegnie osobno za każdy miesiąc szkody, więc najstarsze miesiące przepadają pierwsze. Z pozwem nie warto czekać do końca eksmisji.',
      ]],
      ['h2', 'Ile trwa eksmisja przy najmie okazjonalnym?'],
      ['p', 'Moja ocena: zwykle kilka miesięcy, bo nie ma procesu o eksmisję. Jeżeli chcesz wypowiedzieć umowę przed terminem z powodu zaległości, nadal obowiązują 3 pełne okresy, pisemne uprzedzenie i miesiąc na zapłatę (art. 19e w zw. z art. 11 ust. 2 pkt 2). Po wygaśnięciu lub rozwiązaniu umowy doręczasz żądanie opróżnienia lokalu z urzędowo poświadczonym podpisem i terminem co najmniej 7 dni, a potem składasz wniosek o nadanie klauzuli wykonalności aktowi notarialnemu, w którym najemca poddał się egzekucji (art. 19d). Nie stosuje się przepisów o lokalu socjalnym i okresie ochronnym (art. 19e), a najemcy nie przysługuje pomieszczenie tymczasowe (art. 25d pkt 2).'],
      ['p', 'Warunki: wynajmujesz jako osoba fizyczna bez działalności w zakresie najmu, do umowy dołączasz akt notarialny o poddaniu się egzekucji, wskazanie lokalu, do którego najemca się wyprowadzi, i zgodę właściciela tego lokalu (art. 19a), a umowę zgłaszasz naczelnikowi urzędu skarbowego w 14 dni od rozpoczęcia najmu (art. 19b). Jak przygotować umowę najmu okazjonalnego, żeby zadziałała w razie problemów, opisałem w poradniku „Jak bezpiecznie wynająć mieszkanie?”.'],
      ['h2', 'Co mogę dla Ciebie zrobić'],
      ['ul', [
        'Przygotować uprzedzenie i wypowiedzenie tak, żeby sąd nie oddalił pozwu z powodu formy.',
        'Złożyć pozew o eksmisję i o odszkodowanie za zajmowanie lokalu.',
        'Poprowadzić egzekucję, także z zapewnieniem pomieszczenia tymczasowego.',
        'Pozwać gminę o odszkodowanie, jeżeli nie dostarcza lokalu socjalnego.',
        'Na przyszłość: przygotować umowę najmu okazjonalnego.',
      ]],
      ['p', 'Nie obiecuję wyniku. Opisz sprawę w formularzu: w ciągu 24 h roboczych odpiszę, na którym etapie jesteś i co trzeba zrobić — wypowiedzenie, pozew czy wniosek do komornika — i od razu prześlę ofertę z ceną i terminem. Do akceptacji oferty nic nie płacisz.'],
      ['h2', 'Najczęstsze pytania'],
      ['h3', 'Ile trwa eksmisja z mieszkania, gdy lokator nie płaci?'],
      ['p', 'Zwykle od kilkunastu miesięcy do kilku lat. Od pierwszej nieopłaconej raty do końca najmu mija około 5 miesięcy, potem proces (zwykle od kilku do kilkunastu miesięcy) i egzekucja. Jeżeli sąd przyzna lokal socjalny albo gmina nie wskaże pomieszczenia tymczasowego, całość może trwać kilka lat.'],
      ['h3', 'Co zrobić, gdy lokator nie płaci i nie chce się wyprowadzić?'],
      ['p', 'Gdy zaległość obejmie 3 pełne okresy płatności, uprzedź lokatora na piśmie o zamiarze wypowiedzenia i daj mu miesiąc na zapłatę. Potem wypowiedz najem na piśmie z podaniem przyczyny (art. 11). Jeżeli się nie wyprowadzi, złóż pozew o eksmisję i o odszkodowanie za zajmowanie lokalu. Nie wymieniaj zamków i nie odcinaj mediów.'],
      ['h3', 'Ile trwa eksmisja komornicza?'],
      ['p', 'Zależy głównie od gminy. Jeżeli sąd przyznał lokal socjalny, eksmisję wstrzymuje się, aż gmina złoży ofertę (art. 14 ust. 6). Jeżeli nie przyznał, a lokator nie ma dokąd się wyprowadzić, komornik czeka, aż gmina wskaże pomieszczenie tymczasowe, bez limitu czasu (art. 1046 § 4 k.p.c.). Skrócisz to, zapewniając takie pomieszczenie samodzielnie (art. 1046 § 5).'],
      ['h3', 'Czy mogę wymienić zamki, gdy lokator nie płaci?'],
      ['p', 'Nie. Lokator może żądać przywrócenia posiadania (art. 344 k.c.), a zmuszanie do wyprowadzki przez utrudnianie korzystania z mieszkania może być przestępstwem (art. 191 § 1a k.k.).'],
      ['h3', 'Czy lokatora można eksmitować zimą?'],
      ['p', 'Od 1 listopada do 31 marca nie, jeżeli nie wskazano mu lokalu lub pomieszczenia, do którego ma się przenieść (art. 16). Wyjątki z art. 17 dotyczą m.in. przemocy w rodzinie i samowolnego zajęcia lokalu.'],
      ['h3', 'Czy można eksmitować matkę z dzieckiem z prywatnego mieszkania?'],
      ['p', 'Tak. Przy mieszkaniu prywatnym sąd nie musi przyznać lokalu socjalnego nawet rodzinie z dzieckiem, bo obowiązkowy katalog z art. 14 ust. 4 nie działa (art. 14 ust. 7). Może go jednak przyznać, oceniając sytuację rodziny. Wtedy eksmisja czeka, aż gmina złoży ofertę lokalu (art. 14 ust. 6).'],
      ['h3', 'Czy komornik czeka na gminę tylko 6 miesięcy?'],
      ['p', 'Nie. Obecny art. 1046 § 4 k.p.c. nie przewiduje limitu czasu. Czekanie możesz skrócić, zapewniając pomieszczenie tymczasowe samodzielnie (art. 1046 § 5).'],
      ['h3', 'Czy gmina zapłaci mi za to, że lokator dalej mieszka?'],
      ['p', 'Możesz tego żądać, jeżeli sąd przyznał lokatorowi lokal socjalny, a gmina go nie dostarcza (art. 18 ust. 5). Szkodę trzeba wykazać, np. czynszem najmu, którego nie dostajesz. Termin przedawnienia jest w orzecznictwie sporny (3 albo 6 lat) i biegnie osobno za każdy miesiąc – nie czekaj z pozwem do końca eksmisji.'],
      ['h3', 'Ile kosztuje eksmisja?'],
      ['p', 'Opłata od pozwu o eksmisję wynosi 200 zł, a opłata komornicza od wniosku o eksmisję z mieszkania 1500 zł. Do tego zaliczki na wydatki komornika (np. ślusarz, transport i przechowanie rzeczy lokatora) i wynagrodzenie pełnomocnika. Jeżeli wygrasz, sąd co do zasady obciąży lokatora kosztami procesu. Moje wynagrodzenie podaję w ofercie razem z bezpłatną wstępną analizą.'],
      ['h2', 'Źródła'],
      ['ul', [
        'Ustawa z 21.06.2001 o ochronie praw lokatorów, mieszkaniowym zasobie gminy i o zmianie Kodeksu cywilnego (t.j. Dz.U. 2023 poz. 725): art. 2 ust. 1 pkt 5a, 11, 14, 16–18, 19a, 19b, 19d, 19e, 25d.',
        'Kodeks postępowania cywilnego (t.j. Dz.U. 2026 poz. 468): art. 770, 1046.',
        'Kodeks cywilny: art. 344, 417; Kodeks karny: art. 191 § 1a.',
        'Ustawa o kosztach sądowych w sprawach cywilnych (t.j. Dz.U. 2025 poz. 1228): art. 27 pkt 11.',
        'Ustawa z 28.02.2018 o kosztach komorniczych (t.j. Dz.U. 2024 poz. 377): art. 34, 39.',
        'Wyrok TK z 8.04.2010 r., P 1/08.',
        'Wyroki SN: z 29.10.2021 r., I CSKP 168/21; z 30.06.2022 r., II CSKP 381/22; z 14.11.2024 r., II CNPP 44/22 (skarga o stwierdzenie niezgodności z prawem prawomocnego wyroku).',
        'Wyrok SA w Krakowie z 4.06.2024 r., I ACa 3007/23.',
        'Wyroki SR dla Łodzi-Widzewa w Łodzi: z 28.11.2017 r., II C 390/17; z 30.04.2018 r., II C 663/17. Wyrok zaoczny SR w Toruniu z 6.09.2018 r., I C 534/18.',
      ]],
      ['quote', 'Masz podobną sytuację? Napisz do mnie – zobaczę, jak mogę Ci pomóc, i prześlę ofertę współpracy.'],
    ],
  },
  {
    slug: 'warunki-zabudowy-ile-wazne',
    title: 'Warunki zabudowy – ile są ważne? Policz ostatni dzień swojej WZ',
    metaTitle: 'Warunki zabudowy – ile ważne? 5 lat czy bezterminowo',
    metaDesc: 'Warunki zabudowy z wniosków, które wpłynęły od 16.10.2025 r., prawomocne w 2026 r. lub później, są ważne 5 lat. Pozostałe nie mają terminu ważności.',
    excerpt: 'Nowa WZ wygasa po 5 latach od uprawomocnienia. Pokazuję, jak w 3 krokach policzyć ostatni dzień ważności i jak nie stracić decyzji przed budową.',
    date: '6 października 2026', iso: '2026-10-06', readTime: '14 min',
    category: 'Planowanie przestrzenne', tags: ['WZ', 'Ważność WZ', 'Pozwolenie na budowę'],
    cover: '/assets/blog-warunki-zabudowy-ile-wazne.jpg',
    related: ['warunki-zabudowy', 'pozwolenie-na-budowe', 'audyt-stanu-prawnego-nieruchomosci'],
    faq: [
      { q: 'Ile są ważne warunki zabudowy?', a: 'Warunki zabudowy (WZ) z wniosku, który wpłynął do urzędu 16 października 2025 r. lub później, wygasają po 5 latach od dnia, w którym stały się prawomocne, jeżeli stało się to 1 stycznia 2026 r. lub później (art. 64c u.p.z.p.). Pozostałe WZ nie mają terminu ważności, ale każda WZ może wygasnąć wcześniej, np. po uchwaleniu planu miejscowego z innymi ustaleniami.' },
      { q: 'Do kiedy warunki zabudowy były bezterminowe?', a: 'Bez terminu ważności są warunki zabudowy z wniosków, które wpłynęły do urzędu najpóźniej 15 października 2025 r., oraz wszystkie WZ, które stały się prawomocne najpóźniej 31 grudnia 2025 r. (art. 62 ustawy z 7 lipca 2023 r.). Wystarczy jeden z tych warunków. Takie WZ mogą jednak wygasnąć po uchwaleniu planu miejscowego z innymi ustaleniami (art. 65 u.p.z.p.).' },
      { q: 'Czy moje warunki zabudowy z 2020 r. są nadal ważne?', a: 'Tak, jeżeli nie wygasły z innego powodu. Decyzje prawomocne przed 1 stycznia 2026 r. nie mają terminu ważności (art. 62 ustawy z 7 lipca 2023 r.). Mogą jednak wygasnąć, gdy gmina uchwali plan miejscowy z innymi ustaleniami albo gdy pozwolenie na budowę uzyska inny wnioskodawca (art. 65 u.p.z.p.).' },
      { q: 'Od kiedy liczy się 5 lat ważności WZ?', a: 'Od dnia, w którym decyzja stała się prawomocna, a nie od dnia jej wydania ani doręczenia. Zwykle jest to kilka tygodni po dacie na decyzji. Ostatni dzień ważności to dzień z tą samą datą 5 lat później, np. WZ prawomocna od 17 marca 2026 r. jest ważna do 17 marca 2031 r. włącznie.' },
      { q: 'Mam WZ z 2026 r., a budować chcę za 3 lata. Zdążę?', a: 'Jeżeli Twoja WZ ma 5-letni termin, wniosek o pozwolenie na budowę z projektem musi dotrzeć do urzędu przed jego końcem. Tylko wtedy pozwolenie można wydać na podstawie tej WZ (art. 32 ust. 4 pkt 1 Prawa budowlanego; dla nowych WZ to wykładnia, wyroków jeszcze nie ma). Wcześniej WZ może wygasić plan miejscowy z innymi ustaleniami, dopóki nie masz ostatecznego pozwolenia. Ostateczne pozwolenie ma potem własny, 3-letni termin na rozpoczęcie budowy.' },
      { q: 'Czy można przedłużyć warunki zabudowy?', a: 'Nie, warunków zabudowy nie można przedłużyć – ustawa tego nie przewiduje. Po wygaśnięciu, jeżeli dla działki nadal nie ma planu miejscowego, trzeba złożyć nowy wniosek. Urząd oceni go według przepisów z dnia złożenia (plan ogólny, obszar uzupełnienia zabudowy, a przy wnioskach od 1 stycznia 2027 r. prawo do działki).' },
      { q: 'Czy plan ogólny unieważnia warunki zabudowy?', a: 'Nie. Plan ogólny nie powoduje wygaśnięcia WZ. Wygaśnięcie może spowodować dopiero uchwalenie planu miejscowego z innymi ustaleniami (art. 65 ust. 1 pkt 2 u.p.z.p.).' },
      { q: 'Co, jeśli WZ wygaśnie w trakcie sprawy o pozwolenie na budowę?', a: 'Jeżeli wniosek o pozwolenie złożyłeś, gdy WZ była jeszcze ważna, urząd może wydać pozwolenie na jej podstawie (art. 32 ust. 4 pkt 1 Prawa budowlanego). Przy art. 64c nie ma jeszcze wyroków, więc nie zostawiaj wniosku na ostatnie dni.' },
      { q: 'Kupuję działkę z warunkami zabudowy. Czy dostanę nowy termin?', a: 'Nie. Przeniesienie decyzji na nabywcę (art. 63 ust. 5 u.p.z.p.) nie zmienia dnia prawomocności, od którego liczy się 5 lat. Tak wynika z brzmienia art. 64c, ale orzeczeń na ten temat jeszcze nie ma. Termin policz przed podpisaniem umowy.' },
    ],
    body: [
      ['lead', 'Masz warunki zabudowy i budowę planujesz „za kilka lat”? Sprawdź, czy Twoja „wuzetka” ma datę ważności. Decyzja o warunkach zabudowy (WZ) wydana na nowych zasadach wygasa po 5 latach od dnia, w którym stała się prawomocna (art. 64c ustawy o planowaniu i zagospodarowaniu przestrzennym). Prawomocna to taka, której nie można już zaskarżyć ani odwołaniem, ani skargą do sądu. Dotyczy to WZ, które stały się prawomocne w 2026 r. lub później, jeżeli wniosek wpłynął do urzędu 16 października 2025 r. lub później. Po wygaśnięciu nowej WZ możesz już nie dostać, bo od 1 września 2026 r. WZ wydaje się tylko w gminie z planem ogólnym. Poniżej pokazuję, jak w 3 krokach policzyć ostatni dzień ważności Twojej WZ i co zrobić, żeby jej nie stracić.'],
      ['note', 'Stan prawny na 5.10.2026. Tekst dotyczy decyzji o warunkach zabudowy. Pierwsze WZ wygasną z powodu upływu 5 lat najwcześniej w 2031 r., dlatego nie ma jeszcze wyroków o liczeniu tego terminu. Opieram się na przepisach, komentarzach i orzecznictwie dotyczącym podobnych terminów.'],
      ['h2', 'Ile są ważne warunki zabudowy?'],
      ['p', 'To zależy od dwóch dat: kiedy wniosek wpłynął do urzędu i kiedy decyzja stała się prawomocna.'],
      ['ul', [
        '**Bez terminu ważności** są WZ, które stały się prawomocne przed 1 stycznia 2026 r., oraz WZ wydane w sprawach wszczętych (czyli gdy wniosek wpłynął do urzędu) przed 16 października 2025 r., nawet jeśli uprawomocniły się później. Wystarczy jeden z tych warunków (art. 62 ustawy z 7 lipca 2023 r. o zmianie ustawy o planowaniu i zagospodarowaniu przestrzennym).',
        '**5 lat od prawomocności** obowiązują wszystkie pozostałe WZ (art. 64c u.p.z.p.). Po upływie 5 lat decyzja wygasa z mocy prawa, bez osobnej decyzji urzędu (tak wynika z brzmienia art. 64c; orzeczeń jeszcze nie ma). Ustawa nie przewiduje jej przedłużenia.',
        '**Każda WZ, także bezterminowa, może wygasnąć wcześniej**, np. gdy rada gminy uchwali dla tego terenu plan miejscowy z innymi ustaleniami (art. 65 u.p.z.p.). Opisuję to niżej.',
      ]],
      ['h2', 'Jak policzyć termin ważności warunków zabudowy? 3 kroki'],
      ['ol', [
        '**Sprawdź datę wniosku.** Jeżeli wniosek o WZ wpłynął do urzędu przed 16 października 2025 r., Twoja decyzja nie ma terminu ważności. Liczy się dzień, w którym wniosek dotarł do urzędu, a nie dzień nadania na poczcie (art. 61 § 3 k.p.a.). Znajdziesz go na pieczątce wpływu na Twojej kopii wniosku, w potwierdzeniu odbioru (UPO) przy wniosku elektronicznym albo w aktach sprawy. Data „na wniosek z dnia…” w decyzji bywa datą z wniosku, a nie datą wpływu. Jeżeli wniosek wpłynął przed 16 października 2025 r., przejdź od razu do części o planie miejscowym.',
        '**Ustal dzień, w którym WZ stała się prawomocna.** Jeżeli było to przed 1 stycznia 2026 r., decyzja też nie ma terminu. Jak ustalić ten dzień, piszę niżej.',
        '**Dodaj 5 lat.** Ostatni dzień ważności to dzień z tą samą datą 5 lat później (art. 112 Kodeksu cywilnego; tak samo art. 57 § 3a Kodeksu postępowania administracyjnego). Następnego dnia decyzja już nie obowiązuje.',
      ]],
      ['p', '**Przykład.** Urząd doręczył WZ ostatniej stronie (u nas sąsiadowi; Ty odebrałeś ją wcześniej) w poniedziałek 2 marca 2026 r. Termin 14 dni na odwołanie liczy się od następnego dnia (dnia doręczenia nie liczysz), więc minął 16 marca. Nikt się nie odwołał. Decyzja jest prawomocna od 17 marca 2026 r. (tak przyjmuje praktyka przy podobnym terminie z Prawa budowlanego), więc jest ważna do 17 marca 2031 r. włącznie, a 18 marca 2031 r. już wygasła. Bezpieczniej przyjmij jednak, że ostatnim dniem jest 16 marca 2031 r.'],
      ['p', '**Budujesz za kilka lat?** Przy tej WZ wniosek o pozwolenie na budowę musi dotrzeć do urzędu najpóźniej 16 marca 2031 r., a bezpieczniej do końca 2030 r. Do wniosku potrzebny jest projekt budowlany, więc architekta zamów z kilkumiesięcznym wyprzedzeniem. Przed końcem 5 lat WZ może też wygasić plan miejscowy (opisuję to niżej).'],
      ['p', 'Trzy uwagi do liczenia:'],
      ['ul', [
        'WZ prawomocna 29 lutego (np. w 2028 r.) jest ważna do 28 lutego, 5 lat później.',
        'Gdy ostatni dzień ważności wypada w sobotę albo w święto, nie przesuwa się na dzień roboczy. To termin obowiązywania decyzji, a nie termin na złożenie pisma (tak komentarz do art. 57 k.p.a. o terminach prawa materialnego; orzeczeń do art. 64c jeszcze nie ma). Jeśli WZ jest ważna do soboty, wniosek o pozwolenie złóż najpóźniej w piątek.',
        'Inaczej jest z 14 dniami na odwołanie i 30 dniami na skargę. Gdy ich ostatni dzień wypada w sobotę albo w święto, termin kończy się w najbliższym dniu roboczym (art. 57 § 4 k.p.a., art. 83 § 2 p.p.s.a.). Razem z nim przesuwa się dzień prawomocności.',
      ]],
      ['h3', 'Kiedy WZ staje się prawomocna?'],
      ['p', 'Decyzja jest prawomocna, gdy jest ostateczna (czyli nie można się już od niej odwołać do samorządowego kolegium odwoławczego) i nie można jej już zaskarżyć do sądu (art. 16 § 3 k.p.a.). W praktyce:'],
      ['ul', [
        '**Nikt się nie odwołał:** od dnia następującego po upływie 14 dni na odwołanie, liczonych od doręczenia decyzji ostatniej stronie (art. 129 § 2 k.p.a.). Stronami bywają też właściciele działek sąsiednich, gdy inwestycja wpływa na ich nieruchomość (art. 28 k.p.a.; NSA z 8.09.2021 r., II OSK 1604/21). Jeśli strona nie odebrała listu, decyzję uważa się za doręczoną z upływem 14 dni od pierwszego awiza (art. 44 § 4 k.p.a.). Gdy urząd doręcza przez obwieszczenie (np. przy nieznanym adresie właściciela sąsiedniej działki), doręczenie następuje po 14 dniach od obwieszczenia (art. 49 § 2 k.p.a.; art. 64 ust. 1 w zw. z art. 53 ust. 1c u.p.z.p.). Dlatego WZ uprawomocnia się często dopiero 4–5 tygodni po dacie na decyzji.',
        '**Samorządowe kolegium odwoławcze (SKO) utrzymało decyzję i nikt nie złożył skargi:** od dnia następującego po upływie 30 dni na skargę do sądu administracyjnego, liczonych od doręczenia decyzji SKO ostatniej stronie (art. 53 § 1 Prawa o postępowaniu przed sądami administracyjnymi).',
        '**Sąd oddalił skargę:** od dnia, w którym wyrok stał się prawomocny.',
        '**Wszystkie strony zrzekły się odwołania:** od dnia, w którym urząd otrzymał oświadczenie ostatniej z nich (art. 127a k.p.a.).',
        '**SKO przekazało sprawę do ponownego rozpatrzenia albo sąd uchylił decyzję:** liczy się nowa decyzja.',
      ]],
      ['h3', 'Jak sprawdzić datę prawomocności?'],
      ['ul', [
        '**Klauzula prawomocności (pieczątka „prawomocna z dniem…”) na Twoim egzemplarzu decyzji** to dobry punkt wyjścia, ale tylko potwierdzenie. Gdy urząd się pomyli, liczy się data wynikająca z doręczeń (tak NSA w wyroku z 10.03.2020 r., II OSK 1311/18, o klauzuli ostateczności pozwolenia na budowę). Nie masz klauzuli albo chcesz ją sprawdzić? Skorzystaj z jednego z dwóch sposobów poniżej.',
        '**Wgląd w akta** (art. 73 k.p.a.): w aktach są daty doręczeń wszystkim stronom (zwrotki, potwierdzenia elektroniczne).',
        '**Zaświadczenie z urzędu** (art. 217 k.p.a.): wystarczy krótki wniosek o zaświadczenie o dniu, w którym decyzja stała się prawomocna, z jej numerem i datą. Urząd wydaje je najpóźniej w 7 dni. Zaświadczenie też tylko potwierdza datę, więc porównaj je z datami doręczeń.',
      ]],
      ['p', 'Liczysz sam i nie znasz dat doręczeń sąsiadom? Przyjmij bezpieczny wariant: do daty wydania decyzji (z jej nagłówka) dodaj 14 dni, a potem 5 lat. Przykład: dla decyzji z 12 lutego 2026 r. przyjmij, że WZ jest ważna do 26 lutego 2031 r. Prawdziwy termin nie będzie wcześniejszy, chyba że wszystkie strony zrzekły się odwołania (wtedy licz od dnia, w którym urząd dostał ostatnie oświadczenie). Gdy decyzja dotyczy wielu stron albo była zaskarżana, łatwo o pomyłkę o kilka dni.'],
      ['h2', 'Kiedy WZ wygaśnie wcześniej?'],
      ['h3', 'Plan miejscowy z innymi ustaleniami'],
      ['p', 'Gdy rada gminy uchwali dla Twojego terenu plan miejscowy z innymi ustaleniami niż w WZ (czyli plan przewiduje dla działki coś innego, np. inne przeznaczenie), urząd stwierdzi wygaśnięcie decyzji osobną decyzją (art. 65 ust. 1 pkt 2 i ust. 3 u.p.z.p.). Dotyczy to także WZ bezterminowych. Chroni Cię tylko:'],
      ['ul', [
        'ostateczne pozwolenie na budowę,',
        'upływ terminu na sprzeciw wobec zgłoszenia budowy (czyli urząd nie wniósł sprzeciwu w terminie, zwykle 21 dni od doręczenia zgłoszenia),',
        'zgłoszenie budowy domu jednorodzinnego o powierzchni zabudowy do 70 m² (art. 65 ust. 2 u.p.z.p., art. 29 ust. 1 pkt 1a Prawa budowlanego).',
      ]],
      ['p', 'Przy planie miejscowym, inaczej niż przy 5-letnim terminie, sam złożony wniosek o pozwolenie nie wystarcza. Po wygaszeniu WZ urząd ocenia projekt według obowiązującego planu, a nie według WZ (NSA z 21.01.2011 r., II OSK 152/10). Czy rada gminy podjęła uchwałę o przystąpieniu do sporządzania planu miejscowego dla Twojej okolicy, sprawdzisz w BIP gminy albo w urzędzie. Jeśli tak, nie zwlekaj z projektem.'],
      ['h3', 'Pozwolenie na budowę dla innej osoby'],
      ['p', 'WZ dla tej samej działki może dostać więcej niż jedna osoba. Gdy pozwolenie na budowę albo skuteczne zgłoszenie uzyska inny wnioskodawca, urząd stwierdzi wygaśnięcie pozostałych WZ (art. 65 ust. 1 pkt 1–1b). To ważne przy zakupie działki „z wuzetką” wydaną na sprzedającego.'],
      ['h3', 'Plan ogólny nie kasuje WZ'],
      ['p', 'Wejście w życie planu ogólnego gminy nie powoduje wygaśnięcia WZ. Przepis o wygaśnięciu mówi tylko o planie miejscowym, a plan ogólny nie jest podstawą oceny projektu przy pozwoleniu na budowę (art. 65 ust. 1 i art. 13a ust. 6 u.p.z.p.).'],
      ['h2', 'Jak nie stracić WZ przed budową?'],
      ['ol', [
        '**Złóż wniosek o pozwolenie na budowę tak, żeby dotarł do urzędu przed ostatnim dniem ważności WZ.** Pozwolenie można wydać tylko temu, kto złożył wniosek w okresie ważności WZ (art. 32 ust. 4 pkt 1 Prawa budowlanego). Nie licz na datę stempla pocztowego: sprawę wszczyna dzień, w którym wniosek dotarł do urzędu (art. 61 § 3 k.p.a.). Przy WZ wydawanych według ustawy o zagospodarowaniu przestrzennym z 1994 r. (obowiązywała do 2003 r.), które też miały termin ważności, NSA uznał, że późniejszy upływ ważności nie przekreśla wtedy sprawy (wyrok z 7.03.2007 r., II OSK 1465/05). Przy art. 64c to na razie wykładnia, bez wyroków.',
        '**Zgłoszenie budowy rób z zapasem.** Przy zgłoszeniu nie ma takiej furtki. Złóż je tak, żeby 21 dni na sprzeciw urzędu, liczone od dnia, w którym zgłoszenie do niego dotarło (art. 30 ust. 5 Prawa budowlanego), minęło przed końcem ważności WZ. Wezwanie do uzupełnienia zgłoszenia przerywa ten termin (art. 30 ust. 5d), dlatego złóż zgłoszenie co najmniej miesiąc przed końcem ważności WZ. Przy domu jednorodzinnym o powierzchni zabudowy do 70 m² urząd nie wnosi sprzeciwu, a budowę można zacząć po doręczeniu zgłoszenia (art. 30 ust. 5j–5k). Takie zgłoszenie też złóż z zapasem.',
        '**Pamiętaj o terminie pozwolenia.** Ostateczne pozwolenie na budowę wygasa, jeżeli nie zaczniesz budowy w ciągu 3 lat od dnia, w którym stało się ostateczne, albo przerwiesz ją na ponad 3 lata (art. 37 ust. 1 Prawa budowlanego). Nowe pozwolenie wymaga wtedy ważnej WZ albo planu miejscowego. Samo pozwolenie nie wygasa razem z WZ: jeśli 5 lat od WZ minie w trakcie budowy, możesz budować dalej (to wykładnia przepisów, orzeczeń jeszcze nie ma). Kłopot pojawi się, gdy w trakcie budowy trzeba zmienić projekt w sposób, który wymaga zmiany WZ.',
        '**Kupujesz działkę z WZ? Policz termin przed umową.** Gdy urząd przeniesie WZ sprzedającego na Ciebie (art. 63 ust. 5 u.p.z.p.), nie dostajesz nowych 5 lat. Liczysz od tego samego dnia prawomocności co sprzedający (tak wynika z brzmienia art. 64c; orzeczeń jeszcze nie ma).',
      ]],
      ['h2', 'Co z warunkami zabudowy po 5 latach?'],
      ['p', 'Po 5 latach WZ wygasa i nie da się jej przedłużyć. Pozwolenie na budowę można na jej podstawie wydać tylko wtedy, gdy wniosek o nie złożyłeś w okresie ważności WZ (art. 32 ust. 4 pkt 1 Prawa budowlanego). Jeżeli dla działki obowiązuje plan miejscowy, nowej WZ się nie wydaje. O tym, czy i co zbudujesz, decyduje plan (art. 4 ust. 2 u.p.z.p.). Jeżeli planu miejscowego nie ma, możesz złożyć nowy wniosek o warunki zabudowy. Urząd oceni go według przepisów z dnia złożenia, a dziś są to nowe zasady:'],
      ['ul', [
        'od 1 września 2026 r. WZ wydaje się tylko w gminie, w której wszedł w życie plan ogólny (art. 59 ust. 3 ustawy z 7 lipca 2023 r.);',
        'przy budowie nowego budynku działka musi co do zasady leżeć w obszarze uzupełnienia zabudowy wyznaczonym w planie ogólnym (czyli tam, gdzie gmina jeszcze pozwoli postawić dom; art. 61 ust. 1 pkt 1a u.p.z.p.), z wyjątkami m.in. dla rozbudowy, nadbudowy i odbudowy;',
        'przy wnioskach złożonych od 1 stycznia 2027 r. WZ dostanie tylko ten, kto ma prawo do dysponowania działką na cele budowlane (czyli np. jest właścicielem albo ma z właścicielem umowę, która pozwala budować; art. 63 ust. 1a u.p.z.p.).',
      ]],
      ['p', 'Działka, na której dziś możesz budować na podstawie WZ, po jej wygaśnięciu może zostać bez tej możliwości do czasu uchwalenia planu miejscowego. Czy można wtedy żądać pieniędzy od gminy, wyjaśniam w tekście Odszkodowanie za plan ogólny. Czy Twoja gmina ma plan ogólny i czy działka leży w obszarze uzupełnienia zabudowy, sprawdzisz w BIP gminy albo w urzędzie.'],
      ['h2', 'Co mogę dla Ciebie zrobić'],
      ['ul', [
        'Policzyć ostatni dzień ważności Twojej WZ na podstawie akt sprawy. Dostaniesz datę, do której wniosek o pozwolenie na budowę musi dotrzeć do urzędu.',
        'Sprawdzić, czy gmina nie przygotowuje planu miejscowego, który może wygasić decyzję.',
        'Przed zakupem działki z WZ zrobić audyt stanu prawnego: WZ, plan ogólny, obszar uzupełnienia zabudowy, księga wieczysta. Przed zapłatą ceny dowiesz się, czy i do kiedy możesz tam budować.',
        'Przygotować i złożyć wniosek o pozwolenie na budowę albo zgłoszenie we współpracy z Twoim architektem.',
      ]],
      ['p', 'Nie obiecuję wyniku. Opisz sprawę w formularzu – to bezpłatna wstępna analiza. Dołącz skan albo zdjęcie decyzji o WZ (z klauzulą prawomocności, jeśli ją masz). W ciągu 24 h roboczych odpiszę, co trzeba zrobić, i prześlę ofertę z ceną i terminem. Do akceptacji oferty nic nie płacisz.'],
      ['h2', 'Najczęstsze pytania'],
      ['h3', 'Ile są ważne warunki zabudowy?'],
      ['p', 'Warunki zabudowy (WZ) z wniosku, który wpłynął do urzędu 16 października 2025 r. lub później, wygasają po 5 latach od dnia, w którym stały się prawomocne, jeżeli stało się to 1 stycznia 2026 r. lub później (art. 64c u.p.z.p.). Pozostałe WZ nie mają terminu ważności, ale każda WZ może wygasnąć wcześniej, np. po uchwaleniu planu miejscowego z innymi ustaleniami.'],
      ['h3', 'Do kiedy warunki zabudowy były bezterminowe?'],
      ['p', 'Bez terminu ważności są warunki zabudowy z wniosków, które wpłynęły do urzędu najpóźniej 15 października 2025 r., oraz wszystkie WZ, które stały się prawomocne najpóźniej 31 grudnia 2025 r. (art. 62 ustawy z 7 lipca 2023 r.). Wystarczy jeden z tych warunków. Takie WZ mogą jednak wygasnąć po uchwaleniu planu miejscowego z innymi ustaleniami (art. 65 u.p.z.p.).'],
      ['h3', 'Czy moje warunki zabudowy z 2020 r. są nadal ważne?'],
      ['p', 'Tak, jeżeli nie wygasły z innego powodu. Decyzje prawomocne przed 1 stycznia 2026 r. nie mają terminu ważności (art. 62 ustawy z 7 lipca 2023 r.). Mogą jednak wygasnąć, gdy gmina uchwali plan miejscowy z innymi ustaleniami albo gdy pozwolenie na budowę uzyska inny wnioskodawca (art. 65 u.p.z.p.).'],
      ['h3', 'Od kiedy liczy się 5 lat ważności WZ?'],
      ['p', 'Od dnia, w którym decyzja stała się prawomocna, a nie od dnia jej wydania ani doręczenia. Zwykle jest to kilka tygodni po dacie na decyzji. Ostatni dzień ważności to dzień z tą samą datą 5 lat później, np. WZ prawomocna od 17 marca 2026 r. jest ważna do 17 marca 2031 r. włącznie.'],
      ['h3', 'Mam WZ z 2026 r., a budować chcę za 3 lata. Zdążę?'],
      ['p', 'Jeżeli Twoja WZ ma 5-letni termin, wniosek o pozwolenie na budowę z projektem musi dotrzeć do urzędu przed jego końcem. Tylko wtedy pozwolenie można wydać na podstawie tej WZ (art. 32 ust. 4 pkt 1 Prawa budowlanego; dla nowych WZ to wykładnia, wyroków jeszcze nie ma). Wcześniej WZ może wygasić plan miejscowy z innymi ustaleniami, dopóki nie masz ostatecznego pozwolenia. Ostateczne pozwolenie ma potem własny, 3-letni termin na rozpoczęcie budowy.'],
      ['h3', 'Czy można przedłużyć warunki zabudowy?'],
      ['p', 'Nie, warunków zabudowy nie można przedłużyć – ustawa tego nie przewiduje. Po wygaśnięciu, jeżeli dla działki nadal nie ma planu miejscowego, trzeba złożyć nowy wniosek. Urząd oceni go według przepisów z dnia złożenia (plan ogólny, obszar uzupełnienia zabudowy, a przy wnioskach od 1 stycznia 2027 r. prawo do działki).'],
      ['h3', 'Czy plan ogólny unieważnia warunki zabudowy?'],
      ['p', 'Nie. Plan ogólny nie powoduje wygaśnięcia WZ. Wygaśnięcie może spowodować dopiero uchwalenie planu miejscowego z innymi ustaleniami (art. 65 ust. 1 pkt 2 u.p.z.p.).'],
      ['h3', 'Co, jeśli WZ wygaśnie w trakcie sprawy o pozwolenie na budowę?'],
      ['p', 'Jeżeli wniosek o pozwolenie złożyłeś, gdy WZ była jeszcze ważna, urząd może wydać pozwolenie na jej podstawie (art. 32 ust. 4 pkt 1 Prawa budowlanego). Przy art. 64c nie ma jeszcze wyroków, więc nie zostawiaj wniosku na ostatnie dni.'],
      ['h3', 'Kupuję działkę z warunkami zabudowy. Czy dostanę nowy termin?'],
      ['p', 'Nie. Przeniesienie decyzji na nabywcę (art. 63 ust. 5 u.p.z.p.) nie zmienia dnia prawomocności, od którego liczy się 5 lat. Tak wynika z brzmienia art. 64c, ale orzeczeń na ten temat jeszcze nie ma. Termin policz przed podpisaniem umowy.'],
      ['h2', 'Źródła'],
      ['ul', [
        'Ustawa z 27.03.2003 o planowaniu i zagospodarowaniu przestrzennym (t.j. Dz.U. 2026 poz. 538 ze zm.): art. 4 ust. 2, 13a ust. 5–6, 53 ust. 1c, 61 ust. 1 pkt 1a, 63 ust. 1a (od 1.01.2027) i ust. 5, 64 ust. 1, 64c, 65.',
        'Ustawa z 7.07.2023 o zmianie ustawy o planowaniu i zagospodarowaniu przestrzennym oraz niektórych innych ustaw (Dz.U. 2023 poz. 1688 ze zm.): art. 59 ust. 3, art. 62 w brzmieniu ustawy z 5.11.2025 (Dz.U. 2025 poz. 1668).',
        'Prawo budowlane (t.j. Dz.U. 2026 poz. 524): art. 29 ust. 1 pkt 1a, 30 ust. 5, 5d i 5j–5k, 32 ust. 4 pkt 1, 37 ust. 1.',
        'Kodeks postępowania administracyjnego (t.j. Dz.U. 2025 poz. 1691): art. 16 § 3, 28, 44, 49, 57 § 3a i § 4, 61 § 3, 73, 127a, 129 § 2, 217.',
        'Prawo o postępowaniu przed sądami administracyjnymi (t.j. Dz.U. 2026 poz. 143): art. 53 § 1, 83 § 2.',
        'Kodeks cywilny (t.j. Dz.U. 2026 poz. 795): art. 110, 112.',
        'Wyroki NSA: z 7.03.2007 r., II OSK 1465/05; z 10.03.2020 r., II OSK 1311/18; z 21.01.2011 r., II OSK 152/10; z 8.09.2021 r., II OSK 1604/21.',
      ]],
      ['quote', 'Masz podobną sytuację? Napisz do mnie – zobaczę, jak mogę Ci pomóc, i prześlę ofertę współpracy.'],
    ],
  },
);
window.BLOG.sort((a, b) => (b.iso || '').localeCompare(a.iso || ''));
