/* blog-data-6.jsx — nowe poradniki z planu treści 300 tematów (IX 2026). Dołącza do window.BLOG.
   Pola metaTitle i faq są dodatkowe: obecny szablon je pomija, gałąź P0 może ich użyć (setMeta, FAQPage). */
window.BLOG.push(
  {
    slug: 'ile-trwa-eksmisja-lokatora',
    title: 'Ile trwa eksmisja lokatora bez tytułu prawnego? Kalendarz 2026',
    metaTitle: 'Ile trwa eksmisja lokatora? Kalendarz i koszty 2026',
    excerpt: 'Eksmisja lokatora bez tytułu prawnego trwa od kilkunastu miesięcy do kilku lat. Pokazuję kalendarz, błędy, które cofają sprawę, i jak odzyskać pieniądze.',
    date: '26 września 2026', iso: '2026-09-26', readTime: '10 min',
    category: 'Najem', tags: ['Eksmisja', 'Lokal socjalny', 'Odszkodowanie od gminy'],
    cover: '/assets/blog-ile-trwa-eksmisja.jpg',
    related: ['eksmisja', 'windykacja-czynszu', 'bezpieczny-najem'],
    faq: [
      { q: 'Ile trwa eksmisja z mieszkania, gdy lokator nie płaci?', a: 'Zwykle od kilkunastu miesięcy do kilku lat. Od pierwszej nieopłaconej raty do końca najmu mija około 5 miesięcy, potem proces (zwykle od kilku do kilkunastu miesięcy) i egzekucja. Jeżeli sąd przyzna lokal socjalny albo gmina nie wskaże pomieszczenia tymczasowego, całość może trwać kilka lat.' },
      { q: 'Co zrobić, gdy lokator nie płaci i nie chce się wyprowadzić?', a: 'Gdy zaległość obejmie 3 pełne okresy płatności, uprzedź lokatora na piśmie o zamiarze wypowiedzenia i daj mu miesiąc na zapłatę. Potem wypowiedz najem na piśmie z podaniem przyczyny (art. 11). Jeżeli się nie wyprowadzi, złóż pozew o eksmisję i o odszkodowanie za zajmowanie lokalu. Nie wymieniaj zamków i nie odcinaj mediów.' },
      { q: 'Ile trwa eksmisja komornicza?', a: 'Zależy głównie od gminy. Jeżeli sąd przyznał lokal socjalny, eksmisję wstrzymuje się, aż gmina złoży ofertę (art. 14 ust. 6). Jeżeli nie przyznał, a lokator nie ma dokąd się wyprowadzić, komornik czeka, aż gmina wskaże pomieszczenie tymczasowe, bez limitu czasu (art. 1046 § 4 k.p.c.). Skrócisz to, zapewniając takie pomieszczenie samodzielnie (art. 1046 § 5).' },
      { q: 'Czy mogę wymienić zamki, gdy lokator nie płaci?', a: 'Nie. Lokator może żądać przywrócenia posiadania (art. 344 k.c.), a zmuszanie do wyprowadzki przez utrudnianie korzystania z mieszkania może być przestępstwem (art. 191 § 1a k.k.).' },
      { q: 'Czy lokatora można eksmitować zimą?', a: 'Od 1 listopada do 31 marca nie, jeżeli nie wskazano mu lokalu lub pomieszczenia, do którego ma się przenieść (art. 16). Wyjątki z art. 17 dotyczą m.in. przemocy w rodzinie i samowolnego zajęcia lokalu.' },
      { q: 'Czy można eksmitować matkę z dzieckiem z prywatnego mieszkania?', a: 'Tak. Przy mieszkaniu prywatnym sąd nie musi przyznać lokalu socjalnego nawet rodzinie z dzieckiem, bo obowiązkowy katalog z art. 14 ust. 4 nie działa (art. 14 ust. 7). Może go jednak przyznać, oceniając sytuację rodziny. Wtedy eksmisja czeka, aż gmina złoży ofertę lokalu (art. 14 ust. 6).' },
      { q: 'Czy komornik czeka na gminę tylko 6 miesięcy?', a: 'Nie. Obecny art. 1046 § 4 k.p.c. nie przewiduje limitu czasu. Czekanie możesz skrócić, zapewniając pomieszczenie tymczasowe samodzielnie (art. 1046 § 5).' },
      { q: 'Czy gmina zapłaci mi za to, że lokator dalej mieszka?', a: 'Możesz tego żądać, jeżeli sąd przyznał lokatorowi lokal socjalny, a gmina go nie dostarcza (art. 18 ust. 5). Szkodę trzeba wykazać, np. czynszem najmu, którego nie dostajesz. Roszczenie przedawnia się po 6 latach, liczonych osobno za każdy miesiąc.' },
      { q: 'Ile kosztuje eksmisja?', a: 'Opłata od pozwu o eksmisję wynosi 200 zł, a opłata komornicza od wniosku o eksmisję z mieszkania 1500 zł. Do tego zaliczki na wydatki komornika (np. ślusarz, transport i przechowanie rzeczy lokatora) i wynagrodzenie pełnomocnika. Jeżeli wygrasz, sąd co do zasady obciąży lokatora kosztami procesu. Wycenę Twojej sprawy prześlę mailem po opisie w formularzu, bez opłat.' },
    ],
    body: [
      ['lead', 'Lokator nie płaci, a Ty dalej płacisz czynsz do wspólnoty? Eksmisja lokatora bez tytułu prawnego (czyli po zakończeniu najmu) może potrwać od kilkunastu miesięcy do kilku lat. Zanim w ogóle złożysz pozew, przy zaległościach w czynszu mija około 5 miesięcy. Przy czynszu najmu 2 500 zł każdy rok czekania to 30 000 zł, których nie dostajesz. Najwięcej czasu zabierają błędy w wypowiedzeniu i czekanie na gminę. Poniżej kalendarz, pułapki i to, co możesz zrobić, żeby odzyskać mieszkanie szybciej, oraz od kogo możesz żądać pieniędzy za ten czas.'],
      ['note', 'Stan prawny na 26.09.2026. Tekst dotyczy mieszkania prywatnego (właściciel to osoba fizyczna) i zwykłej umowy najmu. Najem okazjonalny opisuję na końcu.'],
      ['h2', 'Ile trwa eksmisja lokatora? Kalendarz krok po kroku'],
      ['ol', [
        '**Zaległość za 3 pełne okresy płatności.** Wypowiedzieć najem z powodu długu możesz dopiero, gdy zaległość sięga co najmniej 3 pełnych okresów płatności (art. 11 ust. 2 pkt 2 ustawy o ochronie praw lokatorów). Liczy się kwota, a nie sam upływ miesięcy.',
        '**Pisemne uprzedzenie i dodatkowy miesiąc.** Najpierw na piśmie uprzedzasz o zamiarze wypowiedzenia i dajesz miesiąc na zapłatę zaległych i bieżących należności.',
        '**Wypowiedzenie.** Dopiero potem wypowiadasz najem na piśmie, z podaniem przyczyny, na miesiąc naprzód, na koniec miesiąca kalendarzowego (art. 11 ust. 1 i 2). Od pierwszej nieopłaconej raty do końca najmu mija więc zwykle około 5 miesięcy (nawet przy najszybszym tempie nie mniej niż około 4), a przy doręczeniach przez awizo dłużej.',
        '**Pozew o eksmisję i wyrok.** Opłata od pozwu wynosi 200 zł (art. 27 pkt 11 ustawy o kosztach sądowych w sprawach cywilnych). Ile potrwa proces, zależy od sądu i od tego, czy lokator się broni. Z mojego doświadczenia: od kilku do kilkunastu miesięcy, dłużej przy apelacji.',
        '**Komornik.** Z wyrokiem z klauzulą wykonalności składasz wniosek o eksmisję. Opłata od wniosku wynosi 1500 zł (art. 34 ustawy o kosztach komorniczych) i płacisz ją z góry. Lokator ma obowiązek zwrócić ją jako koszt egzekucji (art. 770 Kodeksu postępowania cywilnego), ale od niewypłacalnego lokatora trudno ją odzyskać. Jeżeli lokator wyprowadzi się sam najpóźniej 3 dni przed wyznaczoną eksmisją, komornik zwróci Ci połowę opłaty (art. 39 ustawy o kosztach komorniczych).',
        '**Czekanie na gminę.** To najdłuższy i najmniej przewidywalny etap. Opisuję go niżej.',
      ]],
      ['h2', 'Dlaczego eksmisja z mieszkania trwa tak długo?'],
      ['h3', 'Błąd w wypowiedzeniu cofa sprawę do zera'],
      ['p', 'Sądy oddalają pozwy o eksmisję, gdy wypowiedzenie było wadliwe. Wtedy cały kalendarz zaczyna się od nowa. Typowe błędy, przez które sądy oddalały pozwy:'],
      ['ul', [
        '**Brak pisemnego uprzedzenia z miesięcznym terminem.** Wypowiedzenie jest bezskuteczne (czyli najem trwa dalej), a samego pozwu sąd nie uzna za uprzedzenie (wyrok SR dla Łodzi-Widzewa w Łodzi z 28.11.2017 r., II C 390/17).',
        '**Uprzedzenie wysłane za wcześnie**, zanim zaległość sięgnęła 3 pełnych okresów. Sąd uznał je za wadliwe, a wypowiedzenie za bezskuteczne (wyrok SR dla Łodzi-Widzewa w Łodzi z 30.04.2018 r., II C 663/17).',
        '**Inna przyczyna w wypowiedzeniu niż w pozwie.** Przyczyna podana w wypowiedzeniu wiąże wynajmującego (II C 390/17).',
        '**Zapisy umowy „na skróty”**, np. wypowiedzenie bez przyczyny albo rozwiązanie umowy przy 2 miesiącach zaległości. Są nieważne, bo art. 11 można zmienić umową tylko na korzyść lokatora (wyrok zaoczny SR w Toruniu z 6.09.2018 r., I C 534/18).',
      ]],
      ['h3', 'Samowolna eksmisja wydłuża sprawę'],
      ['p', 'Wymiana zamków, odcięcie mediów czy wyniesienie rzeczy lokatora nie skracają eksmisji. Lokator może wytoczyć powództwo o przywrócenie naruszonego posiadania (art. 344 Kodeksu cywilnego). Takie działania, stosowane uporczywie albo tak, że istotnie utrudniają korzystanie z mieszkania, żeby zmusić lokatora do wyprowadzki, są przestępstwem (art. 191 § 1a Kodeksu karnego). Może nim być nawet jednorazowa wymiana zamków, jeśli odcina lokatorowi dostęp do mieszkania. Więcej o tym piszę w poradniku „5 nielegalnych sposobów na wyrzucenie niechcianego lokatora”.'],
      ['h3', 'Czy można eksmitować matkę z dzieckiem? Sąd bada lokal socjalny'],
      ['p', 'W wyroku eksmisyjnym sąd z urzędu orzeka, czy lokatorowi przysługuje prawo do lokalu socjalnego (art. 14 ust. 1 i 3). Przy mieszkaniu prywatnym nie musi go przyznać nawet rodzinie z dzieckiem, bo obowiązkowy katalog z art. 14 ust. 4 tu nie działa (art. 14 ust. 7). Może jednak go przyznać, biorąc pod uwagę sytuację materialną i rodzinną lokatora oraz to, jak dotąd korzystał z lokalu.'],
      ['p', 'Jeżeli sąd przyzna lokal socjalny, eksmisję wstrzymuje się do czasu, aż gmina złoży lokatorowi ofertę (art. 14 ust. 6). Na to można czekać latami.'],
      ['h3', 'Komornik czeka na gminę bez limitu czasu'],
      ['p', 'Jeżeli sąd nie przyznał lokalu socjalnego, a lokator nie ma gdzie się wyprowadzić, komornik wstrzymuje eksmisję, dopóki gmina nie wskaże pomieszczenia tymczasowego (art. 1046 § 4 Kodeksu postępowania cywilnego). Przepis nie przewiduje limitu czasu. W internecie wciąż można przeczytać o 6 miesiącach, ale takiego limitu w obecnym brzmieniu przepisu nie ma.'],
      ['h3', 'Eksmisja zimą: od 1 listopada do 31 marca'],
      ['p', 'Od 1 listopada do 31 marca wyroków eksmisyjnych nie wykonuje się, jeżeli lokatorowi nie wskazano lokalu, do którego ma się przenieść (art. 16). Ten zakaz dotyczy także byłego najemcy po wypowiedzeniu. Wyjątki z art. 17 obejmują m.in. przemoc w rodzinie, rażące naruszanie porządku domowego i samowolne zajęcie lokalu.'],
      ['h2', 'Jak skrócić eksmisję i odzyskać pieniądze'],
      ['ol', [
        '**Pisma bez błędów od pierwszego dnia.** Uprzedzenie, wypowiedzenie i pozew w kolejności z art. 11. To jedyny etap, który w całości zależy od Ciebie. Błąd kosztuje cały czas procesu i co najmniej 2 miesiące na nowe uprzedzenie i wypowiedzenie.',
        '**Odszkodowanie od lokatora za każdy miesiąc.** Osoba, która zajmuje lokal bez tytułu prawnego, płaci co miesiąc odszkodowanie w wysokości czynszu, jaki mógłbyś dostać z najmu, a jeśli to nie pokrywa strat, także odszkodowanie uzupełniające (art. 18 ust. 1 i 2). Przykład: przy czynszu rynkowym 2 500 zł rok zajmowania mieszkania to 30 000 zł, których możesz żądać. Jeżeli jednak sąd przyzna lokatorowi lokal socjalny i wstrzyma eksmisję, od tej chwili lokator płaci tylko tyle, ile wynosiłby czynsz socjalny, a różnicę do dotychczasowego czynszu pokrywa gmina (art. 18 ust. 3a). Wyrok to jeszcze nie pieniądze: odzyskasz je, jeśli lokator ma z czego zapłacić.',
        '**Zapewnij pomieszczenie tymczasowe sam.** Działa to tylko wtedy, gdy sąd nie przyznał lokatorowi lokalu socjalnego. Jeżeli wskażesz pomieszczenie spełniające wymogi ustawy (m.in. co najmniej 5 m² na osobę, dostęp do wody i ustępu, możliwość ogrzewania, art. 2 ust. 1 pkt 5a) i zapewnisz lokatorowi prawo do zamieszkania w nim, np. wynajmując je na jego rzecz, komornik nie może wstrzymać eksmisji (art. 1046 § 5 k.p.c.). Moja ocena: bywa to tańsze niż czekanie na gminę. Przykład: jeśli pokój kosztuje 1 000 zł miesięcznie, a odzyskane mieszkanie wynajmiesz za 2 500 zł, zyskujesz 1 500 zł co miesiąc.',
        '**Odszkodowanie od gminy.** Jeżeli sąd przyznał lokatorowi lokal socjalny, a gmina go nie dostarcza, możesz żądać od gminy odszkodowania (art. 18 ust. 5 ustawy i art. 417 Kodeksu cywilnego; tak Sąd Najwyższy w wyroku z 29.10.2021 r., I CSKP 168/21). Trybunał Konstytucyjny uznał ten przepis za zgodny z Konstytucją (wyrok z 8.04.2010 r., P 1/08). Sąd Najwyższy przyjmuje, że sam fakt niedostarczenia lokalu przesądza o bezprawności zaniechania gminy, ale szkodę i jej związek z tym zaniechaniem trzeba wykazać (wyrok z 30.06.2022 r., II CSKP 381/22), i że gmina odpowiada niezależnie od tego, dlaczego brakuje jej lokali (wyrok z 14.11.2024 r., II CNPP 44/22). Przykład: sąd zasądził od gminy rynkowy czynsz za ponad 3 lata oczekiwania na lokal socjalny, wyliczony przez biegłego, a Sąd Apelacyjny w Krakowie utrzymał to rozstrzygnięcie, korygując jedynie omyłkę rachunkową (wyrok z 4.06.2024 r., I ACa 3007/23). Roszczenie przedawnia się po 6 latach, ale termin biegnie osobno za każdy miesiąc szkody, więc najstarsze miesiące przepadają pierwsze. Z pozwem nie warto czekać do końca eksmisji.',
      ]],
      ['h2', 'Ile trwa eksmisja przy najmie okazjonalnym?'],
      ['p', 'Moja ocena: zwykle kilka miesięcy, bo nie ma procesu o eksmisję. Jeżeli chcesz wypowiedzieć umowę przed terminem z powodu zaległości, nadal obowiązują 3 pełne okresy, pisemne uprzedzenie i miesiąc na zapłatę (art. 19e w zw. z art. 11 ust. 2 pkt 2). Po wygaśnięciu lub rozwiązaniu umowy doręczasz żądanie opróżnienia lokalu z urzędowo poświadczonym podpisem i terminem co najmniej 7 dni, a potem składasz wniosek o nadanie klauzuli wykonalności aktowi notarialnemu, w którym najemca poddał się egzekucji (art. 19d). Nie stosuje się przepisów o lokalu socjalnym i okresie ochronnym (art. 19e), a najemcy nie przysługuje pomieszczenie tymczasowe (art. 25d pkt 2).'],
      ['p', 'Warunki: wynajmujesz jako osoba fizyczna bez działalności w zakresie najmu, do umowy dołączasz akt notarialny o poddaniu się egzekucji, wskazanie lokalu, do którego najemca się wyprowadzi, i zgodę właściciela tego lokalu (art. 19a), a umowę zgłaszasz naczelnikowi urzędu skarbowego w 14 dni od rozpoczęcia najmu (art. 19b). Jak przygotować umowę najmu okazjonalnego, żeby zadziałała w razie problemów, opisałem w poradniku „Jak bezpiecznie wynająć mieszkanie?”.'],
      ['h2', 'Co mogę dla Ciebie zrobić'],
      ['ul', [
        'Przygotować uprzedzenie i wypowiedzenie tak, żeby sąd nie oddalił pozwu z powodu formy.',
        'Złożyć pozew o eksmisję i o odszkodowanie za zajmowanie lokalu.',
        'Poprowadzić egzekucję, także z zapewnieniem pomieszczenia tymczasowego.',
        'Pozwać gminę o odszkodowanie, jeżeli nie dostarcza lokalu socjalnego.',
        'Na przyszłość: przygotować umowę najmu okazjonalnego.',
      ]],
      ['p', 'Nie obiecuję wyniku. Mogę za to powiedzieć, na którym etapie jesteś, co możesz jeszcze zrobić i ile to kosztuje. Po opisie sprawy w formularzu odpiszę mailem z oceną, planem i ceną. Ta wycena jest bezpłatna.'],
      ['h2', 'Najczęstsze pytania'],
      ['h3', 'Ile trwa eksmisja z mieszkania, gdy lokator nie płaci?'],
      ['p', 'Zwykle od kilkunastu miesięcy do kilku lat. Od pierwszej nieopłaconej raty do końca najmu mija około 5 miesięcy, potem proces (zwykle od kilku do kilkunastu miesięcy) i egzekucja. Jeżeli sąd przyzna lokal socjalny albo gmina nie wskaże pomieszczenia tymczasowego, całość może trwać kilka lat.'],
      ['h3', 'Co zrobić, gdy lokator nie płaci i nie chce się wyprowadzić?'],
      ['p', 'Gdy zaległość obejmie 3 pełne okresy płatności, uprzedź lokatora na piśmie o zamiarze wypowiedzenia i daj mu miesiąc na zapłatę. Potem wypowiedz najem na piśmie z podaniem przyczyny (art. 11). Jeżeli się nie wyprowadzi, złóż pozew o eksmisję i o odszkodowanie za zajmowanie lokalu. Nie wymieniaj zamków i nie odcinaj mediów.'],
      ['h3', 'Ile trwa eksmisja komornicza?'],
      ['p', 'Zależy głównie od gminy. Jeżeli sąd przyznał lokal socjalny, eksmisję wstrzymuje się, aż gmina złoży ofertę (art. 14 ust. 6). Jeżeli nie przyznał, a lokator nie ma dokąd się wyprowadzić, komornik czeka, aż gmina wskaże pomieszczenie tymczasowe, bez limitu czasu (art. 1046 § 4 k.p.c.). Skrócisz to, zapewniając takie pomieszczenie samodzielnie (art. 1046 § 5).'],
      ['h3', 'Czy mogę wymienić zamki, gdy lokator nie płaci?'],
      ['p', 'Nie. Lokator może żądać przywrócenia posiadania (art. 344 k.c.), a zmuszanie do wyprowadzki przez utrudnianie korzystania z mieszkania może być przestępstwem (art. 191 § 1a k.k.).'],
      ['h3', 'Czy lokatora można eksmitować zimą?'],
      ['p', 'Od 1 listopada do 31 marca nie, jeżeli nie wskazano mu lokalu lub pomieszczenia, do którego ma się przenieść (art. 16). Wyjątki z art. 17 dotyczą m.in. przemocy w rodzinie i samowolnego zajęcia lokalu.'],
      ['h3', 'Czy można eksmitować matkę z dzieckiem z prywatnego mieszkania?'],
      ['p', 'Tak. Przy mieszkaniu prywatnym sąd nie musi przyznać lokalu socjalnego nawet rodzinie z dzieckiem, bo obowiązkowy katalog z art. 14 ust. 4 nie działa (art. 14 ust. 7). Może go jednak przyznać, oceniając sytuację rodziny. Wtedy eksmisja czeka, aż gmina złoży ofertę lokalu (art. 14 ust. 6).'],
      ['h3', 'Czy komornik czeka na gminę tylko 6 miesięcy?'],
      ['p', 'Nie. Obecny art. 1046 § 4 k.p.c. nie przewiduje limitu czasu. Czekanie możesz skrócić, zapewniając pomieszczenie tymczasowe samodzielnie (art. 1046 § 5).'],
      ['h3', 'Czy gmina zapłaci mi za to, że lokator dalej mieszka?'],
      ['p', 'Możesz tego żądać, jeżeli sąd przyznał lokatorowi lokal socjalny, a gmina go nie dostarcza (art. 18 ust. 5). Szkodę trzeba wykazać, np. czynszem najmu, którego nie dostajesz. Roszczenie przedawnia się po 6 latach, liczonych osobno za każdy miesiąc.'],
      ['h3', 'Ile kosztuje eksmisja?'],
      ['p', 'Opłata od pozwu o eksmisję wynosi 200 zł, a opłata komornicza od wniosku o eksmisję z mieszkania 1500 zł. Do tego zaliczki na wydatki komornika (np. ślusarz, transport i przechowanie rzeczy lokatora) i wynagrodzenie pełnomocnika. Jeżeli wygrasz, sąd co do zasady obciąży lokatora kosztami procesu. Wycenę Twojej sprawy prześlę mailem po opisie w formularzu, bez opłat.'],
      ['h2', 'Źródła'],
      ['ul', [
        'Ustawa z 21.06.2001 o ochronie praw lokatorów, mieszkaniowym zasobie gminy i o zmianie Kodeksu cywilnego (t.j. Dz.U. 2023 poz. 725): art. 2 ust. 1 pkt 5a, 11, 14, 16–18, 19a, 19b, 19d, 19e, 25d.',
        'Kodeks postępowania cywilnego (t.j. Dz.U. 2026 poz. 468): art. 770, 1046.',
        'Kodeks cywilny: art. 344, 417; Kodeks karny: art. 191 § 1a.',
        'Ustawa o kosztach sądowych w sprawach cywilnych (t.j. Dz.U. 2025 poz. 1228): art. 27 pkt 11.',
        'Ustawa z 28.02.2018 o kosztach komorniczych (t.j. Dz.U. 2024 poz. 377): art. 34, 39.',
        'Wyrok TK z 8.04.2010 r., P 1/08.',
        'Wyroki SN: z 29.10.2021 r., I CSKP 168/21; z 30.06.2022 r., II CSKP 381/22; z 14.11.2024 r., II CNPP 44/22 (skarga o stwierdzenie niezgodności z prawem prawomocnego wyroku).',
        'Wyrok SA w Krakowie z 4.06.2024 r., I ACa 3007/23.',
        'Wyroki SR dla Łodzi-Widzewa w Łodzi: z 28.11.2017 r., II C 390/17; z 30.04.2018 r., II C 663/17. Wyrok zaoczny SR w Toruniu z 6.09.2018 r., I C 534/18.',
      ]],
      ['quote', 'Masz podobną sytuację? Napisz do mnie – zobaczę, jak mogę Ci pomóc, i prześlę ofertę współpracy.'],
    ],
  },
);
window.BLOG.sort((a, b) => (b.iso || '').localeCompare(a.iso || ''));
