/* blog-data.jsx — wpisy przeniesione 1:1 z www.mecenasodnieruchomosci.pl/blog (Wix).
   body = lista bloków: ['lead'|'p'|'h2'|'h3', tekst] | ['ul'|'ol', [pozycje]].
   W tekście **pogrubienie** renderuje się jako <strong>. Okładki pobrane z Wix do assets/. */

const BLOG = [
  {
    slug: 'warunki-zabudowy-2026-lublin',
    metaDesc: 'Od 1 września 2026 r. obowiązują nowe zasady wydawania decyzji o warunkach zabudowy. Co z działkami pod Lublinem, co z wydaną już WZ i jak się zabezpieczyć.',
    title: 'Warunki zabudowy 2026 w Lublinie i okolicy — czy stracisz prawo do budowy na działce?',
    metaTitle: 'Warunki zabudowy 2026 w Lublinie – co się zmienia?',
    excerpt: 'Od kilku miesięcy w mojej kancelarii powtarza się jedno pytanie: „Panie mecenasie, mam działkę pod Lublinem, budowę planowałem za rok, może dwa — czy zdążę?”. Niepokój jest uzasadniony. Od 1 września 2026 roku obowiązują nowe zasady wydawania decyzji o warunkach zabudowy. Dla części działek może to oznaczać, że budowa jest — przynajmniej na jakiś czas — po prostu niemożliwa.',
    date: '15 czerwca 2026', iso: '2026-06-15', updated: '7 października 2026', updatedIso: '2026-10-07', readTime: '10 min',
    category: 'Warunki zabudowy', tags: ['WZ', 'Plan ogólny', 'Lublin'],
    cover: '/assets/blog-wz-2026-lublin.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/warunki-zabudowy-2026-lublin',
    related: ['warunki-zabudowy', 'plan-ogolny', 'analiza-umowy-przedwstepnej'],
    body: [
      ['lead', 'Od kilku miesięcy w mojej kancelarii powtarza się jedno pytanie: „Panie mecenasie, mam działkę pod Lublinem, budowę planowałem za rok, może dwa — czy zdążę?”. Niepokój jest uzasadniony. Od 1 września 2026 roku obowiązują nowe zasady wydawania decyzji o warunkach zabudowy. Dla części działek może to oznaczać, że budowa jest — przynajmniej na jakiś czas — po prostu niemożliwa.'],
      ['note', 'Aktualizacja 7.10.2026 (stan prawny na ten dzień): tekst opisuje zasady obowiązujące po 1 września 2026 r., gdy WZ na wniosek złożony od tego dnia wydaje się tylko w gminie, w której wszedł w życie plan ogólny. Dopisałem zasady wygasania WZ (5-letni termin nowych decyzji, plan miejscowy z innymi ustaleniami) i dane o rozstrzygnięciach nadzorczych wojewody lubelskiego. Poprawiłem opis wymogu prawa do działki: dotyczy wniosków, które wpłyną do urzędu od 1 stycznia 2027 r., i nie tylko właścicieli.'],
      ['p', 'Najkrótsza odpowiedź jest taka: jeśli masz już prawomocną decyzję o warunkach zabudowy (czyli taką, której nie można już zaskarżyć ani odwołaniem, ani skargą do sądu), plan ogólny gminy (nowy dokument planistyczny, opisuję go niżej) Ci jej nie odbierze. Sprawdź jednak, czy decyzja ma termin ważności i czy gmina nie szykuje dla Twojego terenu miejscowego planu zagospodarowania przestrzennego, który mógłby doprowadzić do jej wygaśnięcia. Jeśli takiej decyzji nie masz, a Twoja działka leży poza terenem, który gmina wyznaczyła albo dopiero wyznaczy pod nową zabudowę, sprawa robi się poważna. Niżej tłumaczę, o co dokładnie chodzi i co zrobić, żeby się zabezpieczyć — niezależnie od tego, czy działka jest w Lublinie, w Konopnicy, Niemcach, Głusku, czy w gminie na drugim końcu Polski.'],
      ['h2', 'Na czym polega zmiana'],
      ['p', 'Przez lata regułą było, że dla działki bez miejscowego planu zagospodarowania przestrzennego dało się uzyskać decyzję o warunkach zabudowy (w skrócie: WZ) na zasadzie tzw. dobrego sąsiedztwa — w uproszczeniu: jeśli w pobliżu coś już stało, można było budować i u siebie. To podejście już nie wystarcza. Dobre sąsiedztwo nadal jest wymagane, ale przy nowych wnioskach dochodzą do niego kolejne warunki.'],
      ['p', 'Po reformie o tym, czy na działce w ogóle wolno coś postawić, przesądza nowy dokument — plan ogólny gminy. Decyzje WZ na nowe wnioski są wydawane co do zasady tylko dla działek leżących w wyznaczonym przez gminę **obszarze uzupełnienia zabudowy** (art. 61 ust. 1 pkt 1a ustawy o planowaniu i zagospodarowaniu przestrzennym, w skrócie: u.p.z.p.). Wyjątki dotyczą m.in. rozbudowy, nadbudowy i odbudowy. Jeżeli Twoja działka leży poza tym obszarem, uzyskanie WZ dla nowej zabudowy nie jest możliwe — pozostaje czekać, aż gmina uchwali dla tego terenu miejscowy plan. Jeśli plan ogólny nie przewiduje tam zabudowy, gmina musiałaby najpierw zmienić plan ogólny, bo plan miejscowy musi być z nim zgodny (art. 20 ust. 1 u.p.z.p.). Wniosek o sporządzenie albo zmianę planu możesz złożyć, ale decyzję podejmuje rada gminy i może to potrwać.'],
      ['p', 'Podstawą tych zmian jest ustawa z 27 marca 2003 r. o planowaniu i zagospodarowaniu przestrzennym, gruntownie znowelizowana ustawą z 7 lipca 2023 r. w ramach tzw. reformy planistycznej. Najważniejsze terminy reformy przesuwano potem dwukrotnie, ostatnio ustawą z 30 kwietnia 2026 r.'],
      ['h2', 'Plan ogólny — dokument, który przejmuje stery'],
      ['p', 'Plan ogólny zastępuje znane dotąd studium uwarunkowań i kierunków zagospodarowania przestrzennego. To nie jest kosmetyka. Studium było wewnętrznym dokumentem gminy, a plan ogólny staje się aktem prawa miejscowego, czyli wiąże tak samo urząd, jak i Ciebie. Nowe plany miejscowe i decyzje WZ wydawane na nowe wnioski muszą być z nim co do zasady zgodne (art. 13a ust. 5 i art. 20 ust. 1 u.p.z.p.).'],
      ['p', 'Plan dzieli całą gminę na strefy (mieszkaniowe, usługowe, rolnicze i inne), ustala dla nich parametry zabudowy — maksymalną wysokość, intensywność, procent powierzchni biologicznie czynnej — i to właśnie w nim gmina może (ale nie musi) wskazać obszary uzupełnienia zabudowy.'],
      ['h2', 'Obszar uzupełnienia zabudowy — tu jest pies pogrzebany'],
      ['p', 'To pojęcie warto zapamiętać, bo od niego zależy los inwestycji. Obszar uzupełnienia zabudowy to teren wyznaczony w planie ogólnym, przeznaczony do „dogęszczania” tego, co już istnieje.'],
      ['p', 'Problem w tym, że wyznaczenie takiego obszaru jest dla gminy dobrowolne, a zasady jego rysowania są dość rygorystyczne. W praktyce część działek, które jeszcze niedawno bez trudu można było zabudować na podstawie WZ, tę możliwość straciła. Przyczyny są trzy: działka znalazła się w planie ogólnym poza obszarem uzupełnienia zabudowy, gmina takich obszarów w ogóle nie wyznaczyła albo plan ogólny w gminie jeszcze nie wszedł w życie. To jest właśnie powód, dla którego odkładanie tematu „na potem” bywa kosztownym błędem.'],
      ['h2', 'Co z działkami pod Lublinem?'],
      ['p', 'Tu dochodzimy do sedna dla mieszkańców regionu. Gminy wokół Lublina są na bardzo różnych etapach prac nad planem ogólnym. Wojewoda lubelski do 30 września 2026 r. stwierdził też nieważność planów ogólnych w 18 rozstrzygnięciach nadzorczych: 12 razy w całości i 6 razy w części. Jeżeli w Twojej gminie wojewoda stwierdził nieważność całego planu, urząd nie wyda WZ — także na rozbudowę czy nadbudowę — dopóki plan ogólny nie wejdzie w życie. Dotyczy to wniosków złożonych od 1 września 2026 r. To oznacza, że sytuacja właściciela działki w Konopnicy może wyglądać zupełnie inaczej niż jego znajomego z Niemiec, Jastkowa, Wólki, Głuska czy Niedrzwicy Dużej, choć dzieli ich kilkanaście kilometrów.'],
      ['p', 'Granicą był **31 sierpnia 2026 roku** — najdłużej do tego dnia mogły obowiązywać stare studia (art. 65 ust. 1 ustawy z 7 lipca 2023 r.). Pierwotnie był to 31 grudnia 2025 r., potem 30 czerwca 2026 r. Jeśli w Twojej gminie plan ogólny jeszcze nie wszedł w życie (samo uchwalenie przez radę gminy nie wystarczy), urząd nie wyda WZ na wniosek złożony od 1 września 2026 r. (art. 59 ust. 3 tej ustawy). Dla kogoś, kto planował budowę domu pod Lublinem w przyszłym sezonie, to realny przestój.'],
      ['p', 'Status swojej gminy najpewniej sprawdzisz w jej Biuletynie Informacji Publicznej oraz w wydziale planowania przestrzennego. Można też podejrzeć strefy i obszary uzupełnienia zabudowy w serwisach mapowych — ale przy konkretnej parceli i tak zwykle trzeba sięgnąć po wypis z planu albo analizę pod WZ. Jeśli nie masz pewności, jak czytać te dane, to dobry moment, żeby ktoś zrobił to za Ciebie, zanim złożysz wniosek o WZ albo kupisz działkę.'],
      ['h2', 'Mam już decyzję WZ — czy coś tracę?'],
      ['p', 'Z powodu planu ogólnego — nie. Jego wejście w życie nie powoduje wygaśnięcia WZ (art. 65 ust. 1 i art. 13a ust. 6 u.p.z.p.). Bez terminu ważności są WZ, które stały się prawomocne przed 1 stycznia 2026 r. Bez terminu są też WZ z wniosków, które wpłynęły do urzędu przed 16 października 2025 r., nawet jeśli uprawomocniły się później (art. 62 ustawy z 7 lipca 2023 r.). Jeśli masz taką WZ, nie musisz robić nic, żeby ją „uratować”. Pozostałe WZ wygasają po 5 latach od dnia, w którym stały się prawomocne (art. 64c u.p.z.p.). Przy takiej WZ wniosek o pozwolenie na budowę musi dotrzeć do urzędu przed końcem tych 5 lat (art. 32 ust. 4 pkt 1 Prawa budowlanego).'],
      ['p', 'Są jednak dwie sytuacje, w których każda WZ, także bezterminowa, może wygasnąć. Pierwsza: rada gminy uchwala dla Twojego terenu miejscowy plan zagospodarowania przestrzennego z innymi ustaleniami niż w WZ (czyli plan przewiduje dla działki coś innego, np. inne przeznaczenie). Urząd stwierdza wtedy wygaśnięcie WZ osobną decyzją (art. 65 ust. 1 pkt 2 i ust. 3 u.p.z.p.). Chroni Cię przed tym tylko ostateczne pozwolenie na budowę (czyli takie, od którego nie można się już odwołać), upływ terminu na sprzeciw wobec zgłoszenia budowy albo zgłoszenie budowy domu jednorodzinnego o powierzchni zabudowy do 70 m² (art. 65 ust. 2). Sam złożony wniosek o pozwolenie nie wystarczy. Druga: pozwolenie na budowę albo skuteczne zgłoszenie uzyskuje inny wnioskodawca, bo WZ dla tej samej działki może mieć kilka osób. Wtedy urząd stwierdza wygaśnięcie Twojej WZ (art. 65 ust. 1 pkt 1–1b).'],
      ['h2', 'Daty, które warto sobie zapisać'],
      ['ul', [
        '**1 stycznia 2026 r.** — nowe decyzje WZ przestają być bezterminowe: wygasają po 5 latach od dnia, w którym stały się prawomocne (art. 64c u.p.z.p.). Nie dotyczy to WZ prawomocnych przed tym dniem ani WZ z wniosków, które wpłynęły do urzędu przed 16 października 2025 r.',
        '**1 lipca 2026 r.** — wchodzi w życie większość przepisów ustawy z 30 kwietnia 2026 r., która przesunęła terminy reformy.',
        '**31 sierpnia 2026 r.** — koniec obowiązywania starych studiów: od 1 września 2026 r. nie obowiązuje już żadne studium (art. 65 ust. 1 ustawy z 7 lipca 2023 r.). Wnioski o WZ, które wpłynęły do urzędu najpóźniej 31 sierpnia 2026 r., urząd rozpatruje według dawnych zasad, bez wymogu obszaru uzupełnienia zabudowy (art. 59 ust. 2 tej ustawy). W gminie, w której plan ogólny wszedł w życie wcześniej, wniosek musiał wpłynąć przed dniem jego wejścia w życie.',
        '**1 września 2026 r.** — nowe zasady działają w pełni. Na wniosek złożony od tego dnia WZ można wydać tylko w gminie, w której wszedł w życie plan ogólny (art. 59 ust. 3 ustawy z 7 lipca 2023 r.). Decyzja musi być zgodna z tym planem. Przy budowie nowego budynku działka musi też co do zasady leżeć w obszarze uzupełnienia zabudowy (art. 61 ust. 1 pkt 1a u.p.z.p.). Kolejna ważna data to **1 stycznia 2027 r.**: przy wnioskach, które wpłyną do urzędu od tego dnia, WZ dostanie tylko ten, kto ma prawo do działki (piszę o tym niżej).',
      ]],
      ['h2', 'Nowość od 2027 r.: warunki zabudowy tylko dla tego, kto ma prawo do działki'],
      ['p', 'To zmiana, którą szczególnie powinni odnotować kupujący i inwestorzy. Dotąd wniosek o WZ mógł złożyć każdy — i wielu inwestorów korzystało z tego, żeby przed zakupem sprawdzić, czy na danej działce w ogóle da się budować. Przy wnioskach, które wpłyną do urzędu od 1 stycznia 2027 r., decyzję uzyska wyłącznie osoba, która ma prawo do dysponowania nieruchomością na cele budowlane (czyli np. jest właścicielem albo ma z właścicielem umowę, która pozwala budować). Trzeba będzie też złożyć o tym oświadczenie pod rygorem odpowiedzialności karnej (art. 63 ust. 1a–1b u.p.z.p.). Jeżeli wniosek wpłynie do urzędu najpóźniej 31 grudnia 2026 r., prawo do działki nie będzie wymagane (art. 12 ustawy z 30 kwietnia 2026 r.). Liczy się dzień, w którym wniosek dotarł do urzędu, a nie data nadania na poczcie (art. 61 § 3 Kodeksu postępowania administracyjnego).'],
      ['p', 'Skutek jest praktyczny i nieoczywisty: od 2027 r. nie zbadasz już „na próbę” cudzej działki, zanim ją kupisz. Rośnie więc znaczenie dobrze napisanej umowy przedwstępnej — takiej, w której zakup uzależniasz od uzyskania korzystnej WZ. Widziałem już transakcje, w których brak takiego zastrzeżenia kończył się zakupem gruntu, na którym ostatecznie nie dało się postawić tego, co kupujący planował. Przy wnioskach o WZ od 2027 r. zwykła umowa przedwstępna sprzedaży nie wystarczy jednak, żeby decyzję wydano Tobie. Umowa musi wtedy przewidywać Twoje uprawnienie do wykonywania robót budowlanych na działce (art. 3 pkt 11 Prawa budowlanego). Inaczej o WZ musi wystąpić sprzedający.'],
      ['h2', 'Co zrobić teraz — konkretnie'],
      ['p', 'Jeśli masz działkę bez planu miejscowego i bez decyzji WZ, a myślisz o budowie, warto rozważyć kilka kroków:'],
      ['ul', [
        'sprawdź stan działki — czy obejmuje ją plan miejscowy i czy w Twojej gminie wszedł już w życie plan ogólny (a jeśli nie — na jakim etapie są prace nad nim);',
        'ustal, czy działka leży w obszarze uzupełnienia zabudowy albo ma szansę do niego trafić — przy budowie nowego budynku to przesądza o WZ;',
        'jeśli w Twojej gminie wszedł już w życie plan ogólny, a działka leży w obszarze uzupełnienia zabudowy, rozważ złożenie wniosku o WZ. Nowa WZ wygasa jednak po 5 latach od dnia, w którym stała się prawomocna (art. 64c u.p.z.p.), więc w tym czasie wniosek o pozwolenie na budowę musi dotrzeć do urzędu;',
        'śledź projekt planu ogólnego i złóż uwagi, gdy jego zapisy ograniczają zabudowę Twojej działki — w czasie konsultacji społecznych wciąż można na niego wpłynąć;',
        'kupując działkę budowlaną, zabezpiecz się umownie, zamiast liczyć na to, że „jakoś się ułoży”.',
      ]],
      ['h2', 'Prowadzę te sprawy także online — w całej Polsce'],
      ['p', 'Kancelarię prowadzę w Lublinie i większość moich klientów to właściciele działek z miasta i okolicznych gmin. Ale analiza planistyczna nie wymaga już osobistej wizyty. Status działki, jej położenie względem obszaru uzupełnienia zabudowy czy treść planu miejscowego potrafię ocenić zdalnie — na podstawie numeru ewidencyjnego działki, danych z geoportalu i dokumentów, które prześlesz. Wstępną analizę sprawy robię bezpłatnie i zdalnie, a sprawy o warunki zabudowy czy uwagi do planu ogólnego można poprowadzić korespondencyjnie niezależnie od tego, w którym województwie leży nieruchomość. Jeśli więc trafiłeś tu z Warszawy, Rzeszowa czy Trójmiasta — to też do Ciebie.'],
      ['h2', 'Najczęstsze pytania'],
      ['p', '**Czy stracę ważność decyzji WZ, którą dostałem np. w 2022 roku?** Z powodu upływu czasu — nie. WZ, która stała się prawomocna przed 1 stycznia 2026 r., nie ma terminu ważności (art. 62 ustawy z 7 lipca 2023 r.). Urząd stwierdzi jednak jej wygaśnięcie w dwóch sytuacjach. Pierwsza: rada gminy uchwali dla tego terenu plan miejscowy z innymi ustaleniami, a Ty nie masz jeszcze ostatecznego pozwolenia na budowę ani skutecznego zgłoszenia budowy. Druga: pozwolenie na budowę lub skuteczne zgłoszenie uzyska na tym terenie inny wnioskodawca (art. 65 u.p.z.p.).'],
      ['p', '**Co to jest obszar uzupełnienia zabudowy?** To teren wskazany w planie ogólnym gminy, przeznaczony do uzupełniania istniejącej zabudowy. Przy wnioskach złożonych od 1 września 2026 r. WZ na budowę nowego budynku wydaje się co do zasady tylko w jego granicach (art. 61 ust. 1 pkt 1a u.p.z.p.). Wyjątki dotyczą m.in. rozbudowy, nadbudowy i odbudowy.'],
      ['p', '**Co, jeśli moja gmina pod Lublinem nie ma jeszcze planu ogólnego?** Na wniosek złożony od 1 września 2026 r. urząd nie wyda WZ, dopóki w gminie nie wejdzie w życie plan ogólny (art. 59 ust. 3 ustawy z 7 lipca 2023 r.). Liczy się wejście planu w życie, a nie samo uchwalenie. Wnioski, które wpłynęły do urzędu najpóźniej 31 sierpnia 2026 r., urząd rozpatruje według dawnych zasad (art. 59 ust. 2 tej ustawy). Jeżeli dla działki obowiązuje plan miejscowy, WZ się nie wydaje — o zabudowie decyduje plan (art. 4 ust. 2 u.p.z.p.).'],
      ['p', '**Gdzie sprawdzę status planu ogólnego mojej gminy?** W Biuletynie Informacji Publicznej gminy oraz w wydziale planowania przestrzennego urzędu. Strefy i obszary uzupełnienia zabudowy bywają też widoczne w serwisach mapowych, ale dla konkretnej działki najlepiej potwierdzić to wypisem lub analizą.'],
      ['p', '**Czy mogę jeszcze zdążyć ze złożeniem wniosku o WZ?** Na dawnych zasadach już nie. Według nich rozpatruje się tylko wnioski, które wpłynęły do urzędu najpóźniej 31 sierpnia 2026 r. W gminie, w której plan ogólny wszedł w życie wcześniej, wniosek musiał wpłynąć przed dniem jego wejścia w życie (art. 59 ust. 2–3 ustawy z 7 lipca 2023 r.). Dziś WZ dostaniesz tylko w gminie, w której wszedł w życie plan ogólny, a na nowy budynek co do zasady tylko w obszarze uzupełnienia zabudowy. Przy wnioskach, które wpłyną do urzędu od 1 stycznia 2027 r., potrzebne będzie też prawo do dysponowania działką na cele budowlane (art. 63 ust. 1a u.p.z.p.). Nowa WZ wygasa po 5 latach od dnia, w którym stała się prawomocna (art. 64c u.p.z.p.).'],
      ['h2', 'Sprawdźmy, co nowe przepisy oznaczają dla Twojej działki'],
      ['p', 'Reforma sprawia, że stan prawny i planistyczny działki trzeba dziś czytać dokładniej niż kiedykolwiek, a zwłoka potrafi kosztować utratę możliwości zabudowy. Jeśli chcesz wiedzieć, na czym stoisz, pomogę Ci przeanalizować sytuację działki, przygotować i poprowadzić wniosek o warunki zabudowy, złożyć uwagi do projektu planu ogólnego albo bezpiecznie skonstruować umowę kupna.'],
    ],
  },
  {
    slug: 'warunki-zabudowy-dla-czesci-dzialki',
    metaDesc: 'Urząd żąda warunków zabudowy dla całej działki? Zasadą jest, że WZ dotyczy działki jako całości. Kiedy orzecznictwo dopuszcza WZ tylko dla jej części.',
    title: 'Ustalenie warunków zabudowy dla części działki – czy to w ogóle możliwe?',
    metaTitle: 'Warunki zabudowy dla części działki – czy to możliwe?',
    excerpt: 'Kupiłeś lub odziedziczyłeś dużą działkę. Chcesz wybudować dom, ale interesuje Cię zagospodarowanie tylko jednego, niewielkiego narożnika nieruchomości, na przykład tego z dostępem do drogi. Składasz wniosek o ustalenie warunków zabudowy (tzw. „wuzetkę”) i... zderzasz się ze ścianą. Urząd twierdzi, że musisz ustalić warunki dla całej działki. Czy urzędnicy mają rację? A może prawo zostawia nam furtkę?',
    date: '2 marca 2026', iso: '2026-03-02', updated: '9 kwietnia 2026', readTime: '3 min',
    category: 'Warunki zabudowy', tags: ['WZ', 'Orzecznictwo', 'Podział działki'],
    cover: '/assets/blog-wz-czesc-dzialki.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/ustalenie-warunków-zabudowy-dla-części-działki-czy-to-w-ogóle-możliwe',
    related: ['warunki-zabudowy'],
    body: [
      ['lead', 'Kupiłeś lub odziedziczyłeś dużą działkę. Chcesz wybudować dom, ale interesuje Cię zagospodarowanie tylko jednego, niewielkiego narożnika nieruchomości, na przykład tego z dostępem do drogi. Składasz wniosek o ustalenie warunków zabudowy (tzw. „wuzetkę”) i... zderzasz się ze ścianą. Urząd twierdzi, że musisz ustalić warunki dla całej działki. Czy urzędnicy mają rację? A może prawo zostawia nam furtkę?'],
      ['p', 'Jako adwokat często spotykam się z frustracją klientów, którzy nie rozumieją, dlaczego urząd ingeruje w ich plany inwestycyjne dotyczące ułamka ich własności. Sprawa nie jest prosta, a orzecznictwo bywa bezlitosne. Warto jednak wiedzieć, że w sądach pojawiło się „światełko w tunelu”.'],
      ['h2', 'Twarda zasada: WZ-tka dotyczy całości'],
      ['p', 'Niestety, muszę zacząć od mniej przyjemnych wiadomości. Jeśli urząd odmawia wydania decyzji dla fragmentu Twojego gruntu, opiera się na bardzo silnej linii orzeczniczej sądów administracyjnych.'],
      ['p', 'Wedle dominującego stanowiska ustalenie warunków zabudowy dotyczy działki objętej wnioskiem jako całości nie zaś tylko tej jej części, która na skutek realizacji inwestycji będzie faktycznie zabudowana lub w inny sposób zagospodarowana. Takie podejście potwierdził Naczelny Sąd Administracyjny m.in. w wyroku z dnia 10 stycznia 2008 r. (sygn. akt II OSK 1826/06). Ustalenie warunków zabudowy odnosi się do działki objętej wnioskiem jako całości - stanowisko to ma na celu zapobieganie sytuacji, w której na jednej działce geodezyjnej istniałyby nadmiernie zróżnicowane zasady zagospodarowania przestrzennego.'],
      ['p', 'Innymi słowy: dla urzędu najmniejszą jednostką, o której można rozmawiać w kontekście decyzji WZ, jest cała działka w jej granicach geodezyjnych.'],
      ['h2', 'Światełko w tunelu – wyłom w orzecznictwie!'],
      ['p', 'W prawie rzadko kiedy wszystko jest czarno-białe. W ostatnich latach można zauważyć, że w jednolitym stanowisku składów sądów administracyjnych w zakresie dopuszczalności ustalania warunków zabudowy dla części działki pojawił się wyłom.'],
      ['p', 'Przełomowe okazało się podejście Wojewódzkiego Sądu Administracyjnego w Poznaniu - Wojewódzki Sąd Administracyjny w Poznaniu dopuścił możliwość ustalenia warunków zabudowy dla części działki, uzależniając taką możliwość od konkretnego stanu faktycznego sprawy, tj. charakterystycznych parametrów konkretnej nieruchomości. Sąd ten, w wyroku z 16 września 2015 r. (sygn. akt IV SA/Po 332/15) orzekł, że charakterystyczne parametry konkretnej nieruchomości pozwalają na ustalenie warunków zabudowy dla części działki. To drugie stanowisko jest dużo bardziej elastyczne i bierze pod uwagę realny stan terenu planowanej inwestycji. Takie stanowisko zasługuje na aprobatę, ponieważ chroni inwestorów przed automatycznym wykluczeniem możliwości budowy, gdy tylko specyfika nieruchomości na to pozwala.'],
      ['p', '**Co to oznacza dla Ciebie?** Jeśli Twoja działka jest specyficzna (np. jest bardzo długa, w połowie przecięta rowem melioracyjnym, albo część stanowi nieużytek, a część świetny teren pod budowę), masz argumenty do walki z urzędem.'],
      ['h2', 'Przykład z życia wzięty'],
      ['p', 'Pan Tomasz odziedziczył 3-hektarową działkę na obrzeżach miasta. Działka to długi, wąski pas ziemi. Pan Tomasz chciał wybudować dom jednorodzinny wyłącznie na samym jej początku, przy drodze asfaltowej. Reszta miała pozostać dziką łąką. Urząd odmówił wydania WZ dla fragmentu działki. Gdy Pan Tomasz wystąpił o WZ dla całości – ponownie dostał odmowę, bo na samym końcu jego 3-hektarowego pola nie było sąsiedniej zabudowy, co złamało tzw. „zasadę dobrego sąsiedztwa”. W takiej sytuacji, powołanie się na elastyczne orzecznictwo dopuszczające WZ dla części działki mogłoby uratować plany budowlane Pana Tomasza. Alternatywą jest zawsze geodezyjny podział działki przed złożeniem wniosku – co jednak kosztuje czas i pieniądze.'],
      ['h2', 'Podsumowanie'],
      ['p', 'Walka o warunki zabudowy bywa wyczerpująca. Zasadą jest, że urząd patrzy na Twoją działkę jako całość. Prawo nie jest jednak w 100% zabetonowane i istnieją już argumenty prawne pozwalające ubiegać się o decyzję WZ tylko dla interesującego nas fragmentu gruntu. Wszystko zależy od indywidualnych cech Twojej nieruchomości.'],
      ['p', '**Utknąłeś w martwym punkcie ze swoim urzędem?** Złożenie wniosku o WZ to często gra w szachy. Zanim wydasz pieniądze na podziały geodezyjne lub zrezygnujesz z inwestycji, sprawdźmy Twoją sytuację.'],
    ],
  },
  {
    slug: 'wydruki-ksiag-wieczystych-i-alerty-krs-2026',
    metaDesc: 'Samodzielnie wydrukowany elektroniczny odpis z księgi wieczystej z mocą dokumentu z sądu i alerty KRS w aplikacji mObywatel. Co zmieniają nowe przepisy.',
    title: 'Rewolucja w urzędach 2026: Wydruki Ksiąg Wieczystych z mocą urzędową i Alerty KRS w Twoim telefonie',
    metaTitle: 'Wydruki ksiąg wieczystych i alerty KRS w 2026 roku',
    excerpt: 'Koniec z wizytami w sądach i czekaniem na papierowe dokumenty z pieczątką. Ustawa z 9 stycznia 2026 r. wprowadza potężne zmiany, które odczuje każdy inwestor, przedsiębiorca i nabywca nieruchomości. Cyfryzacja przyspiesza – już niedługo samodzielnie wydrukowany odpis z Księgi Wieczystej zastąpi ten urzędowy, a o każdym nowym wpisie w KRS Twojej spółki dowiesz się ze swojej aplikacji mObywatel.',
    date: '1 marca 2026', iso: '2026-03-01', updated: '9 kwietnia 2026', readTime: '2 min',
    category: 'Księgi wieczyste', tags: ['Księgi wieczyste', 'KRS', 'mObywatel'],
    cover: '/assets/blog-kw-krs-2026.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/rewolucja-w-urzędach-2026-wydruki-ksiąg-wieczystych-z-mocą-urzędową-i-alerty-krs-w-twoim-telefonie',
    related: ['audyt-stanu-prawnego-nieruchomosci', 'obsluga-zakupu'],
    body: [
      ['lead', 'Koniec z wizytami w sądach i czekaniem na papierowe dokumenty z pieczątką. Ustawa z 9 stycznia 2026 r. wprowadza potężne zmiany, które odczuje każdy inwestor, przedsiębiorca i nabywca nieruchomości. Cyfryzacja przyspiesza – już niedługo samodzielnie wydrukowany odpis z Księgi Wieczystej zastąpi ten urzędowy, a o każdym nowym wpisie w KRS Twojej spółki dowiesz się ze swojej aplikacji mObywatel. Zobacz, jak nowe prawo ułatwi Ci życie i zabezpieczy Twoje interesy.'],
      ['h2', 'Księgi Wieczyste bez wychodzenia z domu'],
      ['p', 'Do tej pory, aby uzyskać oficjalny dokument potwierdzający stan prawny nieruchomości, wielu z nas musiało pofatygować się do sądu. Nowelizacja ustawy o księgach wieczystych i hipotece znacząco to upraszcza, zrównując moc dokumentu elektronicznego i jego wydruku z dokumentem sądowym.'],
      ['p', 'Oto najważniejsze zasady, które musisz znać:'],
      ['ul', [
        'pobrane z systemu i samodzielnie wydrukowane elektroniczne odpisy, wyciągi oraz zaświadczenia o zamknięciu ksiąg wieczystych mają moc dokumentów wydawanych przez sąd;',
        'podstawowym warunkiem jest to, aby dokument posiadał cechy umożliwiające jego weryfikację z centralną bazą danych;',
        'jeśli pobrałeś takie dokumenty jeszcze przed wejściem w życie nowych przepisów, zachowają one swoją moc urzędową, o ile da się je technicznie zweryfikować z bazą danych.',
      ]],
      ['p', 'To ogromna oszczędność czasu przed wizytą u notariusza czy podczas załatwiania kredytu hipotecznego. Pamiętaj jednak, że Ministerstwo Sprawiedliwości wyda jeszcze nowe rozporządzenia regulujące dokładne cechy tych dokumentów oraz wysokość opłat za ich pobranie.'],
      ['h2', 'Alerty z KRS prosto na Twój telefon (mObywatel)'],
      ['p', 'Drugim kluczowym elementem nowelizacji jest integracja Krajowego Rejestru Sądowego z popularną aplikacją mObywatel. To świetne narzędzie do monitorowania bezpieczeństwa własnego biznesu oraz weryfikacji kontrahentów.'],
      ['p', 'Jak to będzie działać w praktyce?'],
      ['ul', [
        'informacje o rejestracji nowej sprawy lub dokonaniu wpisu (z numerem KRS, sygnaturą i datą) będą przesyłane automatycznie na Twój telefon;',
        'aby uruchomić usługę, musisz być powiązany z danym podmiotem swoim numerem PESEL i wskazać jego numer KRS;',
        'alerty obejmują nie tylko przedsiębiorców, ale też fundacje, stowarzyszenia czy publiczne zakłady opieki zdrowotnej;',
        'możesz włączyć śledzenie dla maksymalnie 50 podmiotów bezpośrednio w aplikacji mObywatel;',
        'subskrypcja na alerty jest ważna przez rok, ale jako użytkownik masz prawo ją przedłużyć.',
      ]],
      ['h3', 'Przykład z życia wzięty: Uratowana transakcja'],
      ['p', 'Wyobraźmy sobie Pana Tomasza, inwestora, który w poniedziałek rano ma sfinalizować u notariusza bardzo opłacalny zakup działki. W piątek wieczorem przypomina sobie, że notariusz prosił o najświeższy, oficjalny odpis z Księgi Wieczystej, potwierdzający wykreślenie starej hipoteki. Sądy są już zamknięte. W starym stanie prawnym transakcja musiałaby zostać przesunięta, co groziło utratą zadatku. Dzięki nowym przepisom, Pan Tomasz po prostu loguje się do systemu, pobiera dokument, drukuje go w domu i w poniedziałek rano kładzie na biurku notariusza pełnoprawny, urzędowy odpis.'],
      ['h3', 'Kiedy zmiany wchodzą w życie?'],
      ['p', 'Ustawodawca przewidział dwa różne terminy wdrożenia nowości, co ma dać czas na techniczne przygotowanie systemów:'],
      ['ul', [
        '**31 marca 2026 r.** – wejdą w życie ułatwienia dotyczące Ksiąg Wieczystych.',
        '**31 maja 2026 r.** – zaczną działać powiadomienia KRS w aplikacji mObywatel.',
      ]],
      ['p', '**Czujesz, że przepisy dotyczące nieruchomości spędzają Ci sen z powiek?** A może planujesz skomplikowaną transakcję i chcesz mieć pewność, że Twoje interesy są w pełni zabezpieczone?'],
      ['p', 'Opisz sprawę w formularzu poniżej. **W ciągu 24 h roboczych** odpiszę, co trzeba w niej zrobić — np. sprawdzić księgę wieczystą przed transakcją, przygotować umowę czy wniosek o wpis — i od razu prześlę ofertę z ceną i terminem. Do akceptacji oferty nic nie płacisz.'],
    ],
  },
  {
    slug: 'zawyzony-podatek-od-nieruchomosci-blad-w-ewidencji',
    title: 'Zawyżony podatek od nieruchomości przez błąd w ewidencji? Zobacz, z kim tak naprawdę musisz walczyć',
    metaTitle: 'Zawyżony podatek od nieruchomości przez błąd w ewidencji',
    excerpt: 'Dostajesz decyzję z urzędu miasta lub gminy o wysokości podatku od nieruchomości na dany rok. Otwierasz kopertę i przecierasz oczy ze zdumienia. Kwota jest znacznie wyższa niż zazwyczaj, a w uzasadnieniu widzisz, że urząd doliczył Ci kilkadziesiąt metrów kwadratowych powierzchni użytkowej, których w rzeczywistości nie masz.',
    date: '28 lutego 2026', iso: '2026-02-28', readTime: '2 min',
    category: 'Podatek od nieruchomości', tags: ['Ewidencja gruntów', 'Podatek', 'Starosta'],
    cover: '/assets/blog-podatek-ewidencja.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/zawyżony-podatek-od-nieruchomości-przez-błąd-w-ewidencji-zobacz-z-kim-tak-naprawdę-musisz-walczyć',
    related: ['uregulowanie-stanu-prawnego'],
    body: [
      ['lead', 'Dostajesz decyzję z urzędu miasta lub gminy o wysokości podatku od nieruchomości na dany rok. Otwierasz kopertę i przecierasz oczy ze zdumienia. Kwota jest znacznie wyższa niż zazwyczaj, a w uzasadnieniu widzisz, że urząd doliczył Ci kilkadziesiąt metrów kwadratowych powierzchni użytkowej, których w rzeczywistości nie masz.'],
      ['p', 'Myślisz: „To prosty błąd, napiszę odwołanie, przyjdzie urzędnik, zmierzy i po sprawie”. Niestety, prawo podatkowe potrafi być bezlitosne, a walka z błędnym metrażem wcale nie zaczyna się w wydziale podatków. Dlaczego? Wyjaśniam poniżej.'],
      ['h2', 'Papier przyjmie wszystko, a urząd w to uwierzy'],
      ['p', 'Większość z nas zakłada, że skoro stan faktyczny (to, jak dom wygląda w rzeczywistości) różni się od stanu prawnego (tego, co jest w dokumentach), to wystarczy ten fakt udowodnić. Nic bardziej mylnego w przypadku podatków lokalnych.'],
      ['p', 'Zgodnie z polskim prawem, **ewidencja gruntów i budynków stanowi wyłączne i wiążące źródło danych dla wymiaru podatków**. Oznacza to, że dla urzędnika naliczającego opłatę liczy się tylko to, co widnieje w oficjalnym rejestrze geodezyjnym. Co więcej, organy podatkowe nie są uprawnione do samodzielnego badania zgodności tych danych ze stanem faktycznym ani do ich korygowania w toku postępowania podatkowego.'],
      ['p', 'Mówiąc po ludzku: urzędnik skarbowy nie ma prawa wziąć miarki, przyjechać do Twojego domu i stwierdzić: „Rzeczywiście, w rejestrze jest błąd, zmniejszamy podatek”. Jego ręce są związane.'],
      ['h2', 'Przykład z życia wzięty'],
      ['p', 'Wyobraź sobie sytuację, w której współwłaściciele nieruchomości otrzymują decyzję ustalającą podatek od nieruchomości na kwotę 1757 zł. Urząd wyliczył to m.in. na podstawie powierzchni działki i budynków widniejących w ewidencji. Jeden ze współwłaścicieli wnosi odwołanie, bo zauważa potężny błąd – według niego powierzchnia użytkowa budynków mieszkalnych została w papierach zawyżona o kilkaset metrów kwadratowych.'],
      ['p', 'Sprawa trafia do organu odwoławczego, a ostatecznie do Wojewódzkiego Sądu Administracyjnego. Finał? Sąd oddala skargę i przypomina twardą zasadę: podstawą opodatkowania podatkiem od nieruchomości jest stan ujawniony w rejestrach publicznych, a nie faktyczny stan nieruchomości. Co więcej, dane z ewidencji korzystają z domniemania prawdziwości do czasu ich zmiany we właściwym trybie.'],
      ['h2', 'Co z błędnymi dokumentami spadkowymi?'],
      ['p', 'Czasami zawyżony podatek to nie tylko kwestia metrów, ale tego, na kogo nałożono obowiązek zapłaty. Zdarza się, że klienci kwestionują same postanowienia o stwierdzeniu nabycia spadku. Tutaj zasada jest podobna. Prawomocne orzeczenia sądów powszechnych wiążą organy administracji publicznej i sądy administracyjne. Dopóki taki wyrok nie zostanie oficjalnie wzruszony (np. uchylony w innym trybie), musi być respektowany przy rozstrzyganiu spraw podatkowych.'],
      ['h2', 'Jak realnie rozwiązać ten problem?'],
      ['p', 'Jeśli znalazłeś się w podobnej sytuacji, pamiętaj o jednej kluczowej zasadzie: **nie walcz ze skutkiem, walcz z przyczyną**. Podważenie lub zmiana zapisów ewidencji może nastąpić wyłącznie w odrębnym postępowaniu przed właściwymi organami administracji geodezyjnej.'],
      ['ul', [
        '**Krok 1:** zamiast skupiać się wyłącznie na odwołaniach od decyzji podatkowej, musisz natychmiast zainicjować postępowanie o aktualizację operatu ewidencji gruntów i budynków u Starosty.',
        '**Krok 2:** dopiero po wyprostowaniu dokumentów geodezyjnych możesz skutecznie domagać się zmiany decyzji podatkowej, a nawet zwrotu nadpłaty.',
      ]],
      ['p', 'Szanse na wygraną są duże, o ile wiesz, do których drzwi zapukać. Jeśli uderzasz do złego urzędu, stracisz tylko czas i nerwy, a na końcu i tak zapłacisz zawyżony podatek.'],
    ],
  },
  {
    slug: 'przebudowa-czy-nowy-zjazd-nsa',
    title: 'Przebudowa czy nowy zjazd? NSA o granicach kompetencji zarządcy drogi',
    metaTitle: 'Przebudowa czy nowy zjazd? NSA o zarządcy drogi',
    excerpt: 'Planujesz budowę pawilonu handlowego lub biurowca na działce, która od lat ma swój zjazd z drogi publicznej. Chcesz go jedynie odświeżyć i dostosować do obecnych standardów, ale w odpowiedzi od zarządcy drogi słyszysz, że zjazdu w ogóle nie powinno tam być, bo jest za blisko skrzyżowania. Brzmi znajomo? To częsta pułapka urzędnicza, w której organy mylą lokalizację nowego zjazdu z przebudową już istniejącego.',
    date: '27 lutego 2026', iso: '2026-02-27', readTime: '2 min',
    category: 'Proces budowlany', tags: ['Zjazd z drogi', 'NSA', 'Zarządca drogi'],
    cover: '/assets/blog-zjazd-nsa.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/przebudowa-czy-nowy-zjazd-nsa-o-granicach-kompetencji-zarządcy-drogi',
    related: ['pozwolenie-na-budowe', 'nadzor-budowlany-pinb'],
    body: [
      ['h2', 'Masz już zjazd, ale zarządca drogi mówi „nie” jego modernizacji?'],
      ['lead', 'Planujesz budowę pawilonu handlowego lub biurowca na działce, która od lat ma swój zjazd z drogi publicznej. Chcesz go jedynie odświeżyć i dostosować do obecnych standardów, ale w odpowiedzi od zarządcy drogi słyszysz, że zjazdu w ogóle nie powinno tam być, bo jest za blisko skrzyżowania. Brzmi znajomo? To częsta pułapka urzędnicza, w której organy mylą lokalizację nowego zjazdu z przebudową już istniejącego. Najnowszy wyrok Naczelnego Sądu Administracyjnego rzuca nowe światło na tę kwestię, stając po stronie inwestorów i właścicieli nieruchomości.'],
      ['h2', 'Dwa różne światy, czyli lokalizacja a przebudowa'],
      ['p', 'Zgodnie z ustawą o drogach publicznych, mamy do czynienia z dwoma odrębnymi procedurami. Zezwolenie na lokalizację zjazdu dotyczy sytuacji, gdy zjazdu fizycznie nie ma i organ ocenia możliwość włączenia ruchu drogowego spowodowanego nową inwestycją. Z kolei zezwolenie na przebudowę zjazdu dotyczy modernizacji zjazdu, który już istnieje i funkcjonuje w przestrzeni. To rozróżnienie jest kluczowe, ponieważ przy przebudowie zarządca drogi nie może oceniać, czy zjazd w ogóle powinien w danym miejscu istnieć. Ta kwestia została rozstrzygnięta w przeszłości, gdy zjazd powstawał zgodnie z prawem.'],
      ['h2', 'Granice kompetencji zarządcy drogi'],
      ['p', 'Zarządca drogi ma prawo odmówić zgody na przebudowę tylko w ściśle określonych przypadkach prawnych:'],
      ['ul', [
        'gdy planowane prace spowodują, że legalny dotychczas zjazd przestanie odpowiadać wymogom przepisów prawa;',
        'jeśli nowe parametry zjazdu będą generować którąś z prawnych przeszkód przebudowy;',
        'kiedy poziom bezpiecznego korzystania z niego spadnie poniżej dolnego ekstremum akceptowanego przez regulacje.',
      ]],
      ['p', 'Jeśli twoim celem jest na przykład dostosowanie parametrów do nowoczesnych wymogów prawa, to twoje działanie z definicji zmierza do poprawy bezpieczeństwa. Zasada praworządności zakłada, że istniejący, legalny zjazd jest bezpieczny. Organ powinien zatem badać tylko nowe parametry zjazdu, a nie negować sam fakt jego istnienia w danej lokalizacji. Choć decyzja zarządcy ma charakter uznaniowy, nie oznacza to, że urzędnik może zdecydować o wszystkim dowolnie, gdyż musi opierać się na wyczerpująco przedstawionych realiach i zagrożeniach, które wywołałaby sama przebudowa.'],
      ['h2', 'Przykład z życia pana Marka'],
      ['p', 'Pan Marek kupił działkę z dawnym budynkiem biurowym, do którego prowadził żwirowy zjazd z drogi krajowej, legalnie wzniesiony przed 1985 rokiem. Chciał wybudować tam mały market i złożył wniosek o przebudowę zjazdu, deklarując wolę dostosowania jego parametrów do współczesnych wymogów. Zarządca drogi odmówił, twierdząc, że zjazd jest zbyt blisko przejścia dla pieszych i skrzyżowania, co wygeneruje dodatkowy punkt kolizyjny. Finał w sądzie administracyjnym pokazał jednak, że skoro zjazd już istnieje i ma status zjazdu publicznego, zarządca nie może go traktować jak inwestycji nowo lokowanej. Pan Marek nie chciał tworzyć nowego punktu dostępu, lecz naprawić stary, co w rezultacie miało korzystnie wpłynąć na bezpieczeństwo uczestników ruchu.'],
      ['h2', 'Zadbaj o profesjonalną analizę swojej sytuacji'],
      ['p', 'Nie pozwól, by błędna urzędnicza interpretacja przepisów zablokowała twoją inwestycję. Jeśli twój wniosek o przebudowę zjazdu został odrzucony argumentami dotyczącymi złej lokalizacji, istnieje bardzo duże prawdopodobieństwo, że decyzja ta narusza prawo i można ją skutecznie podważyć. Zarządca drogi nie może arbitralnie zakazać prac modernizacyjnych przy funkcjonującym zjeździe publicznym, omijając rzetelną ocenę projektowanych zmian.'],
    ],
  },
  {
    slug: 'warunki-zabudowy-a-plan-ogolny-przepisy-przejsciowe',
    title: 'Na jakiej podstawie należy wydać warunki zabudowy, jeśli w trakcie postępowania wejdzie w życie plan ogólny?',
    metaTitle: 'Warunki zabudowy a plan ogólny – przepisy przejściowe',
    excerpt: 'Reforma planowania przestrzennego wprowadziła sporo zamieszania w kalendarzach inwestorów. Wielu moich klientów pyta z niepokojem: „Panie Mecenasie, co jeśli złożę wniosek o WZ, a gmina w międzyczasie uchwali plan ogólny? Czy moje starania pójdą na marne?”. Odpowiedź jest optymistyczna, ale diabeł tkwi w szczegółach.',
    date: '30 stycznia 2026', iso: '2026-01-30', updated: '6 października 2026', updatedIso: '2026-10-06', readTime: '4 min',
    category: 'Planowanie przestrzenne', tags: ['WZ', 'Plan ogólny', 'Przepisy przejściowe'],
    cover: '/assets/blog-wz-plan-ogolny.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/na-jakiej-podstawie-należy-wydać-warunki-zabudowy-jeśli-w-trakcie-postępowania-wejdzie-w-życie-plan',
    related: ['warunki-zabudowy', 'plan-ogolny'],
    body: [
      ['lead', 'Reforma planowania przestrzennego wprowadziła sporo zamieszania w kalendarzach inwestorów. Wielu moich klientów pyta z niepokojem: „Panie Mecenasie, co jeśli złożę wniosek o WZ, a gmina w międzyczasie uchwali plan ogólny? Czy moje starania pójdą na marne?”. Odpowiedź jest optymistyczna, ale diabeł tkwi w szczegółach.'],
      ['note', 'Aktualizacja 6.10.2026: studia uwarunkowań obowiązywały najdłużej do 31 sierpnia 2026 r. (ustawa z 30 kwietnia 2026 r. przesunęła ten termin z 30 czerwca). Opisana niżej ochrona dotyczy więc wniosków, które wpłynęły do urzędu przed wejściem w życie planu ogólnego w gminie i najpóźniej 31 sierpnia 2026 r. Na wniosek złożony od 1 września 2026 r. WZ można wydać tylko w gminie, w której wszedł w życie plan ogólny. Dopisałem też, że WZ z wniosku, który wpłynął do urzędu 16 października 2025 r. lub później, wygasa po 5 latach od dnia, w którym stała się prawomocna, jeżeli stało się to 1 stycznia 2026 r. lub później (szczegóły we wpisie „Warunki zabudowy – ile są ważne?”).'],
      ['h2', 'Kluczowy moment: Data złożenia wniosku'],
      ['p', 'W prawie administracyjnym często obowiązuje zasada, że „prawo nie działa wstecz”, ale w urbanistyce kluczowe są tzw. **przepisy przejściowe**. To one decydują, czy Twój wniosek będzie rozpatrywany na starych, łagodniejszych zasadach, czy na nowych, często surowszych warunkach wynikających z planu ogólnego.'],
      ['p', 'Zgodnie ze stanem prawnym na 6 października 2026 r. najważniejszą datą jest moment wszczęcia postępowania. To dzień, w którym wniosek dotarł do urzędu, a nie dzień nadania go na poczcie (art. 61 § 3 Kodeksu postępowania administracyjnego, dalej: k.p.a.).'],
      ['h3', 'Zasada kontynuacji (art. 59 ust. 2 ustawy z 7 lipca 2023 r.)'],
      ['p', 'Jeżeli Twój wniosek o wydanie decyzji o warunkach zabudowy (WZ) dotarł do urzędu **przed dniem wejścia w życie planu ogólnego** w gminie (i najpóźniej 31 sierpnia 2026 r.), to Twoja sprawa powinna być prowadzona na „starych” zasadach.'],
      ['p', 'Oznacza to, że:'],
      ['ul', [
        '**plan ogólny nie jest podstawą Twojej decyzji**, nawet jeśli zaczął już obowiązywać w trakcie trwania procedury;',
        'urząd **nie może** odmówić wydania WZ tylko dlatego, że teren nie znajduje się w „obszarze uzupełnienia zabudowy” wyznaczonym w nowym planie (czyli tam, gdzie gmina jeszcze pozwoli postawić dom);',
        'stosuje się dawne zasady oceny wniosku, m.in. tzw. zasadę dobrego sąsiedztwa (czyli nawiązanie do zabudowy na działkach sąsiednich) w brzmieniu sprzed reformy, co chroni interesy inwestora, który zapoczątkował proces wcześniej. „Stare” zasady nie dotyczą jednak terminu ważności decyzji. Jeżeli wniosek wpłynął do urzędu 16 października 2025 r. lub później, a WZ stała się prawomocna (czyli nie można jej już zaskarżyć ani odwołaniem, ani skargą do sądu) 1 stycznia 2026 r. lub później, to WZ wygasa po 5 latach od uprawomocnienia (art. 64c ustawy o planowaniu i zagospodarowaniu przestrzennym).',
      ]],
      ['h2', 'Co to oznacza w praktyce?'],
      ['p', 'Wiele osób obawia się, że wejście w życie planu ogólnego „kasuje” dotychczasowe starania. Nic bardziej mylnego. Ustawa z 7 lipca 2023 r. o zmianie ustawy o planowaniu i zagospodarowaniu przestrzennym oraz niektórych innych ustaw (u.z.u.p.z.p.) w art. 59 ust. 2 jasno wskazuje, że dla spraw wszczętych przed utratą mocy dotychczasowych studiów uwarunkowań, przy ocenie wniosku stosujemy dawne reguły gry, a nie ograniczenia z planu ogólnego.'],
      ['p', 'Studia te zachowywały moc do dnia wejścia w życie planu ogólnego w danej gminie, ale nie dłużej niż do **31 sierpnia 2026 roku** (art. 65 ust. 1 u.z.u.p.z.p.). Od 1 września 2026 r. nie obowiązuje już żadne studium.'],
      ['h3', 'Przykład z życia wzięty'],
      ['p', 'Wyobraźmy sobie pana Marka, który 20 marca 2026 r. złożył w urzędzie gminy wniosek o warunki zabudowy dla domu jednorodzinnego. Trzy dni później, 23 marca, w jego gminie wszedł w życie nowoczesny plan ogólny, który umieszcza jego działkę w strefie zieleni i rekreacji, poza obszarem uzupełnienia zabudowy.'],
      ['p', 'Czy pan Marek stracił szansę na budowę? **Nie.** Ponieważ wszczął postępowanie przed wejściem w życie planu, organ musi rozpatrzyć jego wniosek bez uwzględniania ograniczeń wynikających z tego planu. Jeżeli urząd wyda panu Markowi WZ, to będzie ona jednak ważna 5 lat od dnia, w którym stanie się prawomocna, bo wniosek wpłynął do urzędu po 15 października 2025 r. Wniosek o pozwolenie na budowę musi więc dotrzeć do urzędu, zanim te 5 lat minie (art. 32 ust. 4 pkt 1 Prawa budowlanego).'],
      ['h2', 'Na co musisz uważać?'],
      ['p', 'Choć przepisy chronią „stare” wnioski, musisz pamiętać o dwóch kwestiach:'],
      ['ol', [
        '**termin 31 sierpnia 2026 r.:** to graniczna data, po której stare studia uwarunkowań definitywnie straciły moc. Na wniosek złożony od 1 września 2026 r. WZ można wydać tylko w gminie, w której wszedł w życie plan ogólny (art. 59 ust. 3 u.z.u.p.z.p.). Przy budowie nowego budynku działka musi też co do zasady leżeć w obszarze uzupełnienia zabudowy (art. 61 ust. 1 pkt 1a ustawy o planowaniu i zagospodarowaniu przestrzennym).',
        '**precyzja wniosku:** jeżeli urząd wezwie Cię do uzupełnienia braków, uzupełnij je w wyznaczonym terminie (nie krótszym niż 7 dni). Wniosek z nieusuniętymi brakami urząd pozostawi bez rozpoznania (czyli w ogóle go nie rozpatrzy; art. 64 § 2 k.p.a.). Nowy wniosek złożony od 1 września 2026 r. urząd oceni już według nowych zasad, a w gminie, w której nie wszedł w życie plan ogólny, WZ nie wyda.',
      ]],
      ['h3', 'Masz wniosek o WZ w toku?'],
      ['p', 'Procesy inwestycyjne bywają stresujące, zwłaszcza gdy przepisy zmieniają się z miesiąca na miesiąc. Nie musisz zgadywać, czy Twój wniosek jest bezpieczny.'],
      ['p', 'Opisz sprawę w formularzu poniżej. **W ciągu 24 h roboczych** odpiszę, co trzeba zrobić z Twoim wnioskiem — np. uzupełnić braki, ponaglić urząd czy złożyć skargę na bezczynność — i od razu prześlę ofertę z ceną i terminem. Do akceptacji oferty nic nie płacisz.'],
    ],
  },
];

Object.assign(window, { BLOG });
