/* blog-data-2.jsx — wpisy przeniesione z Wix, partia 2 (X–XII 2025). Dołącza do window.BLOG. */
window.BLOG.push(
  {
    slug: 'podzial-nieruchomosci-po-rozwodzie-komu-sad-przyzna-mieszkanie',
    title: 'Podział nieruchomości po rozwodzie: komu sąd przyzna mieszkanie lub dom?',
    excerpt: 'Gdy małżeństwo się kończy, wspólny dom lub mieszkanie staje się centralnym punktem sporu. To nie tylko budynek, ale centrum życiowe, inwestycja i symbol stabilizacji. Pytanie „kto to dostanie?” pada niemal zawsze jako pierwsze. Odpowiedź jest złożona, ale opiera się na twardej logice, którą sąd stosuje w każdej sprawie.',
    date: '10 października 2025', iso: '2025-10-10', updated: '11 października 2025', readTime: '6 min',
    category: 'Podział majątku', tags: ['Rozwód', 'Podział majątku', 'Kredyt hipoteczny'],
    cover: 'assets/blog-podzial-majatku-rozwod.png',
    source: 'https://www.mecenasodnieruchomosci.pl/post/podział-majątku-w-lublinie-kto-dostanie-mieszkanie-po-rozwodzie-kluczowe-kryteria-sądu',
    related: ['podzial-majatku-po-rozwodzie', 'zniesienie-wspolwlasnosci'],
    body: [
      ['lead', 'Gdy małżeństwo się kończy, wspólny dom lub mieszkanie staje się centralnym punktem sporu. To nie tylko budynek, ale centrum życiowe, inwestycja i symbol stabilizacji. W mojej praktyce jako adwokata od spraw o podział majątku, zarówno w Lublinie, jak i w Warszawie, pytanie „kto to dostanie?” pada niemal zawsze jako pierwsze. Odpowiedź jest złożona, ale opiera się na twardej logice, którą sąd stosuje w każdej sprawie.'],
      ['h3', 'Co musisz wiedzieć, zanim zaczniesz walkę o nieruchomość?'],
      ['ul', [
        '**Zdolność do spłaty to warunek numer jeden.** Sąd nie przyzna Ci nieruchomości, jeśli nie udowodnisz, że stać Cię na spłatę drugiego małżonka. To absolutna podstawa.',
        '**Dobro dzieci jest ważniejsze niż Twoje preferencje.** Jeśli masz dzieci, sąd przyzna nieruchomość temu rodzicowi, z którym one mieszkają, aby zapewnić im stabilizację.',
        '**Kredyt hipoteczny nie znika po podziale.** Sąd podzieli wartość rynkową nieruchomości, ignorując dług. Dla banku nadal oboje jesteście dłużnikami, nawet jeśli mieszkanie przypadnie tylko jednemu z Was.',
      ]],
      ['h2', 'Jak sąd w ogóle może podzielić nieruchomość?'],
      ['p', 'Przepisy Kodeksu cywilnego narzucają sądowi trzyetapową ścieżkę podziału nieruchomości:'],
      ['ol', [
        '**Podział fizyczny (w naturze):** Czy da się z jednego domu zrobić dwa osobne mieszkania? Albo podzielić dużą działkę? W przypadku większości mieszkań i domów jednorodzinnych, które trafiają na wokandę jest to opcja czysto teoretyczna.',
        '**Przyznanie nieruchomości jednemu z małżonków:** To najczęstszy scenariusz. Jedna osoba staje się wyłącznym właścicielem i musi spłacić drugą.',
        '**Sprzedaż licytacyjna:** Ostateczność, gdy podział jest niemożliwy, a byli małżonkowie nie mogą się porozumieć lub żadnego nie stać na spłatę.',
      ]],
      ['p', 'W praktyce 9 na 10 spraw dotyczących jednego mieszkania lub domu od razu przechodzi do etapu drugiego. Cała energia i strategia procesowa od początku skupiają się na jednym pytaniu: **które z Was ma lepsze argumenty, by przejąć nieruchomość?**'],
      ['h2', 'Kluczowe kryteria decyzyjne sądu – moja analiza z sali sądowej'],
      ['p', 'Decyzja sądu nie jest loterią. Opiera się na konkretnych, hierarchicznie ułożonych przesłankach. Oto one, w kolejności, w jakiej analizuje je sędzia.'],
      ['h3', '1. Zdolność do spłaty – Twój bilet wstępu do gry'],
      ['p', 'To jest absolutny fundament i pierwszy filtr. Zanim sąd zacznie rozważać, kto jest bardziej związany z mieszkaniem, sprawdzi, **czy kogoś w ogóle stać na jego przejęcie.**'],
      ['p', 'Orzeczenie sądu musi być realne do wykonania. Zasądzenie spłaty w wysokości 300 000 zł od osoby zarabiającej pensję minimalną i bez oszczędności jest prawną fikcją. Prowadziłoby to wprost do egzekucji komorniczej i sprzedaży licytacyjnej – czyli scenariusza, którego sąd chciał uniknąć.'],
      ['p', '**Jak udowodnić zdolność do spłaty?**'],
      ['ul', [
        'promesa kredytowa z banku - najmocniejszy dowód;',
        'zaświadczenie o zarobkach, umowa o pracę, wyciągi z konta;',
        'dowody posiadania oszczędności, akcji, innych nieruchomości;',
        'wiarygodne oświadczenie rodziny o gotowości udzielenia pożyczki (tzw. darowizna celowa).',
      ]],
      ['p', 'Jeśli tylko Ty wykażesz realną zdolność do spłaty, Twoja pozycja w sporze staje się dominująca.'],
      ['h3', '2. Dobro małoletnich dzieci – argument koronny'],
      ['p', 'Gdy oboje macie zdolność finansową, decydujący głos zyskują dzieci. Sąd, kierując się nadrzędną zasadą ochrony ich dobra, zrobi wszystko, by zminimalizować chaos w ich życiu.'],
      ['p', 'W praktyce oznacza to, że **nieruchomość niemal zawsze zostanie przyznana temu rodzicowi, przy którym ustalono miejsce pobytu dzieci i który sprawuje nad nimi codzienną pieczę.** Chodzi o to, by dzieci nie musiały zmieniać szkoły, przedszkola, otoczenia i znajomych w i tak trudnym dla nich okresie. Argument ten ma ogromną siłę przebicia i często przesądza o wyniku sprawy.'],
      ['h3', '3. Pozostałe, wspierające argumenty'],
      ['p', 'Gdy zdolność spłaty jest po obu stronach, a małżonkowie nie mają dzieci, sąd analizuje dodatkowe okoliczności:'],
      ['ul', [
        '**Kto faktycznie mieszka w nieruchomości?** Jeśli po rozstaniu jeden z małżonków dobrowolnie się wyprowadził i założył nowe centrum życiowe gdzie indziej, sąd przychylniej spojrzy na tego, kto pozostał.',
        '**Kto poczynił znaczne nakłady z majątku osobistego?** Jeśli np. mieszkanie na warszawskim Ursynowie zostało wykończone za pieniądze z darowizny, którą otrzymałeś od swoich rodziców, jest to istotny argument świadczący o Twoim silniejszym związku z tą nieruchomością.',
        '**Kto daje lepszą gwarancję dbania o nieruchomość?** Dotyczy to zwłaszcza starszych domów wymagających remontów i inwestycji.',
        '**Czy w nieruchomości prowadzona jest działalność gospodarcza?** Jeśli np. w mieszkaniu na Starym Mieście w Lublinie prowadzisz gabinet lekarski, który jest Twoim głównym źródłem dochodu (i źródłem środków na spłatę oraz alimenty), sąd będzie dążył do ochrony bytu tego przedsiębiorstwa.',
      ]],
      ['h3', 'Case study z mojej praktyki (historie zanonimizowane)'],
      ['p', '**Przypadek 1: Sprawa w Warszawie (Mokotów)**'],
      ['ul', [
        '**Sytuacja:** Małżeństwo z dwójką dzieci w wieku szkolnym, mieszkanie o wartości 900 000 zł, obciążone kredytem na 300 000 zł. Oboje rodzice chcieli przejąć mieszkanie. Ojciec zarabiał znacznie więcej i przedstawił promesę kredytową na spłatę. Matka miała niższe dochody, ale to przy niej sąd ustalił miejsce pobytu dzieci.',
        '**Rozstrzygnięcie:** Sąd przyznał mieszkanie matce. Uzasadnienie: zapewnienie stabilizacji dzieciom było ważniejsze niż lepsza sytuacja finansowa ojca. Sąd uznał, że dochody matki (plus alimenty) wystarczą do utrzymania nieruchomości i stopniowej spłaty, którą rozłożył na raty.',
      ]],
      ['p', '**Przypadek 2: Sprawa w Lublinie (Węglin)**'],
      ['ul', [
        '**Sytuacja:** Bezdzietne małżeństwo, dom o wartości 1 200 000 zł. Mąż prowadził w garażu warsztat samochodowy, który był jego jedynym źródłem utrzymania. Żona po rozstaniu wróciła do rodziców. Oboje mieli zdolność kredytową.',
        '**Rozstrzygnięcie:** Sąd przyznał dom mężowi. Kluczowe było społeczno-gospodarcze przeznaczenie nieruchomości. Pozbawienie męża warsztatu oznaczałoby zniszczenie jego firmy i utratę zdolności do dokonania spłaty.',
      ]],
      ['h2', 'Największa pułapka: co się dzieje ze wspólnym kredytem hipotecznym?'],
      ['p', 'To najczęściej niezrozumiana kwestia. Sąd, dokonując podziału majątku, **dzieli tylko aktywa (wartość nieruchomości), a nie pasywa (długi).**'],
      ['p', '**Co to oznacza w praktyce?**'],
      ['ol', [
        'Sąd powołuje biegłego, który ustala **aktualną wartość rynkową** nieruchomości (np. 800 000 zł).',
        'Sąd **nie odejmuje od tej wartości kwoty kredytu** pozostałego do spłaty (np. 300 000 zł).',
        'Małżonek, który przejmuje mieszkanie, musi spłacić drugiemu połowę pełnej wartości, czyli 400 000 zł.',
        '**Dla banku nic się nie zmienia!** Oboje nadal jesteście solidarnymi dłużnikami. Jeśli Twój były małżonek przestanie spłacać raty za mieszkanie, które przejął, bank może legalnie ściągnąć cały dług od Ciebie.',
      ]],
      ['p', 'Dlatego, choć prowadzę sprawy o podział majątku w całej Polsce, zawsze podkreślam klientom – czy to w Lublinie, Warszawie, czy w ramach konsultacji online dla kogoś z Krakowa – że orzeczenie sądu to dopiero połowa sukcesu. Drugą połową jest uregulowanie sprawy z bankiem, np. poprzez umowne przejęcie długu przez jednego z kredytobiorców.'],
      ['h2', 'Checklista: przygotuj się do sprawy o podział nieruchomości'],
      ['ol', [
        '**Zbierz dokumenty finansowe:** Umowy o pracę, PIT-y za ostatnie 2 lata, wyciągi z kont bankowych (6 miesięcy wstecz).',
        '**Uzyskaj promesę kredytową:** Skontaktuj się z bankiem lub doradcą kredytowym i zdobądź pisemne potwierdzenie zdolności do zaciągnięcia kredytu na spłatę.',
        '**Zgromadź dowody na nakłady:** Faktury, rachunki, potwierdzenia przelewów za remonty czy wyposażenie finansowane z Twojego majątku osobistego (np. darowizny, spadku).',
        '**Ustal numer księgi wieczystej nieruchomości.**',
        '**Przygotuj świadków:** Jeśli członkowie rodziny mają poświadczyć, że pomogą Ci finansowo, uprzedź ich o tym.',
        '**Spisz argumenty dotyczące Twojego związku z nieruchomością:** Dlaczego to Tobie powinno na niej bardziej zależeć? (dzieci, praca, wkład osobisty).',
        '**Skonsultuj się z adwokatem:** Zanim złożysz jakikolwiek wniosek, omów swoją strategię ze specjalistą.',
      ]],
      ['h2', 'FAQ – najczęstsze pytania o podział nieruchomości'],
      ['p', '**1. Czy sąd może zmusić mnie do wzięcia nieruchomości i spłaty, jeśli tego nie chcę?** Nie. Sąd Najwyższy wielokrotnie potwierdzał, że przyznanie nieruchomości na własność wymaga zgody tej osoby. Sąd nie może nikogo zmusić do zadłużenia się z tytułu spłaty wbrew jego woli.'],
      ['p', '**2. Jak długo sąd daje na dokonanie spłaty?** Standardowo jest to od kilku do kilkunastu miesięcy od uprawomocnienia się orzeczenia. W wyjątkowych sytuacjach, na wniosek zobowiązanego, sąd może rozłożyć spłatę na raty, maksymalnie na okres 10 lat.'],
      ['p', '**3. Co jeśli nie zgadzamy się co do wartości mieszkania?** Jeśli nie ma zgody, sąd obligatoryjnie powoła biegłego rzeczoznawcę majątkowego. Jego operat szacunkowy jest dla sądu kluczowym dowodem i rzadko bywa kwestionowany.'],
      ['p', '**4. Czy wina za rozpad małżeństwa ma wpływ na to, kto dostanie mieszkanie?** Wina co do zasady nie ma bezpośredniego wpływu na sam sposób podziału majątku. Może mieć znaczenie przy ewentualnym ustalaniu nierównych udziałów, ale to zupełnie inna i znacznie trudniejsza do udowodnienia kwestia.'],
      ['p', '**5. Prowadzę sprawy w Lublinie i Warszawie, ale czy mogę liczyć na pomoc w innym mieście?** Oczywiście. Choć większość spraw prowadzę w sądach w Lublinie i Warszawie, regularnie reprezentuję klientów z całej Polski. Wiele czynności, w tym konsultacje i przygotowanie pism procesowych, można z powodzeniem realizować online.'],
      ['h3', 'Potrzebujesz wsparcia w sprawie o podział majątku?'],
      ['p', 'Sprawy o podział nieruchomości są skomplikowane i obarczone ogromnymi emocjami. Błędna strategia na starcie może kosztować Cię setki tysięcy złotych i poczucie bezpieczeństwa. Jako adwokat prowadzący sprawy o podział majątku wiem, że to właśnie wspólna nieruchomość jest źródłem największych sporów i niepewności.'],
      ['note', 'Niniejszy artykuł ma charakter wyłącznie informacyjny i nie stanowi porady prawnej. Każda sytuacja wymaga indywidualnej analizy. W celu uzyskania wiążącej porady prawnej skontaktuj się z profesjonalnym pełnomocnikiem.'],
    ],
  },
  {
    slug: 'jak-bezpiecznie-wynajac-mieszkanie-poradnik',
    title: 'Jak bezpiecznie wynająć mieszkanie? Kompletny poradnik prawnika od nieruchomości',
    excerpt: 'Jako adwokat specjalizujący się w prawie nieruchomości, widziałem już wszystko: od drobnych nieporozumień po kosztowne batalie sądowe. Ten artykuł to esencja moich doświadczeń, która pomoże Ci wynająć mieszkanie bezpiecznie i z zyskiem.',
    date: '11 października 2025', iso: '2025-10-11', readTime: '5 min',
    category: 'Najem', tags: ['Najem okazjonalny', 'Kaucja', 'Wynajmujący'],
    cover: 'assets/blog-bezpieczny-najem.png',
    source: 'https://www.mecenasodnieruchomosci.pl/post/jak-bezpiecznie-wynająć-mieszkanie-kompletny-poradnik-prawnika-od-nieruchomości',
    related: ['bezpieczny-najem', 'eksmisja', 'kaucja-najem'],
    body: [
      ['lead', 'Jako adwokat specjalizujący się w prawie nieruchomości, widziałem już wszystko: od drobnych nieporozumień po kosztowne batalie sądowe. Ten artykuł to esencja moich doświadczeń, która pomoże Ci wynająć mieszkanie bezpiecznie i z zyskiem.'],
      ['h3', 'TL;DR – Wynajem w 3 krokach:'],
      ['ul', [
        '**Weryfikuj najemcę:** Zawsze sprawdzaj tożsamość, źródło dochodu i historię poprzednich najmów. To Twoja pierwsza linia obrony.',
        '**Stwórz żelazną umowę:** Nie polegaj na darmowych wzorach z internetu. Zainwestuj w umowę najmu okazjonalnego, która realnie chroni Twoje interesy.',
        '**Dokumentuj wszystko:** Protokół zdawczo-odbiorczy ze szczegółową dokumentacją fotograficzną to absolutna podstawa, by uniknąć sporów o kaucję.',
      ]],
      ['h2', 'Krok 1: Weryfikacja najemcy – fundament Twojego spokoju'],
      ['p', 'W mojej praktyce często powtarzam, że najlepsze umowy nie ratują relacji ze złym najemcą. Dlatego prewencja jest kluczowa. Na dynamicznych rynkach, takich jak **Warszawa**, gdzie rotacja jest ogromna, czy **Lublin**, zdominowany przez najem studencki, dokładna weryfikacja to nie opcja, a konieczność.'],
      ['h3', 'Dlaczego to tak ważne?'],
      ['p', 'Złe decyzje na tym etapie prowadzą do problemów z płatnościami, zniszczeń lokalu, a nawet trudności z eksmisją. Postępowania przed sądami, takimi jak Sąd Rejonowy dla m.st. Warszawy czy Sąd Rejonowy Lublin-Zachód, potrafią ciągnąć się miesiącami, generując koszty i stres.'],
      ['h3', 'Co i jak sprawdzić? Praktyczna checklista:'],
      ['ul', [
        '**Dokument tożsamości:** Poproś o okazanie dowodu osobistego lub paszportu. Sprawdź zgodność danych.',
        '**Źródło dochodu:** Zapytaj o miejsce pracy i formę zatrudnienia. Poproś o zaświadczenie o zarobkach lub inny dokument potwierdzający stabilność finansową. To standardowa procedura, nie obawiaj się pytać.',
        '**Referencje (opcjonalnie):** Zapytaj o kontakt do poprzedniego wynajmującego. To coraz popularniejsza praktyka, szczególnie przy wynajmie droższych nieruchomości w dzielnicach takich jak warszawski Mokotów czy Śródmieście.',
        '**Bazy dłużników:** Możesz zapytać, czy potencjalny najemca wyrazi zgodę na sprawdzenie go w BIG InfoMonitor czy KRD. Jego reakcja sama w sobie będzie cenną informacją.',
      ]],
      ['p', 'Pamiętaj, że wszystkie te działania muszą odbywać się z poszanowaniem RODO. Możesz pytać tylko o dane niezbędne do oceny wiarygodności płatniczej i zawarcia umowy.'],
      ['h2', 'Krok 2: Umowa najmu – Twoja tarcza prawna'],
      ['p', 'Darmowy wzór umowy z internetu to prosta droga do kłopotów. Dlaczego? Ponieważ większość z nich zawiera klauzule niedozwolone (abuzywne) lub po prostu nie chroni właściciela w wystarczającym stopniu.'],
      ['h3', 'Umowa na czas określony czy nieokreślony?'],
      ['ul', [
        '**Czas określony:** Daje Ci większą pewność co do długości najmu i przychodów. Jest trudniejsza do wypowiedzenia przez najemcę, ale również przez Ciebie (chyba że umowa przewiduje konkretne przypadki).',
        '**Czas nieokreślony:** Daje obu stronom większą elastyczność. Najemca może ją wypowiedzieć z zachowaniem terminów ustawowych (zazwyczaj 3 miesiące), a Ty – tylko w sytuacjach ściśle określonych w ustawie o ochronie praw lokatorów.',
      ]],
      ['p', '**Z mojego doświadczenia wynika, że dla właściciela niemal zawsze korzystniejsza jest umowa na czas określony, najlepiej na 12 miesięcy.**'],
      ['h3', 'Najem okazjonalny – najlepszy przyjaciel właściciela'],
      ['p', 'Jeśli wynajmujesz mieszkanie jako osoba fizyczna, **umowa najmu okazjonalnego** to absolutna podstawa. To jedyne rozwiązanie, które znacząco upraszcza i przyspiesza ewentualną eksmisję problematycznego lokatora, omijając wiele restrykcyjnych przepisów ustawy o ochronie praw lokatorów.'],
      ['p', '**Kluczowe elementy najmu okazjonalnego:**'],
      ['ol', [
        '**Oświadczenie najemcy o dobrowolnym poddaniu się egzekucji** (w formie aktu notarialnego).',
        '**Wskazanie innego lokalu**, w którym najemca będzie mógł zamieszkać po eksmisji.',
        '**Oświadczenie właściciela tego lokalu** o wyrażeniu zgody na zamieszkanie najemcy.',
      ]],
      ['p', 'Koszt notariusza (ok. 300-400 zł) to niewielka cena za ogromne bezpieczeństwo, jakie daje ta forma umowy.'],
      ['p', '**Case study z mojej praktyki (Warszawa):** Pani Anna z warszawskiego Mokotowa wynajęła swoje dwupokojowe mieszkanie młodemu małżeństwu. Po trzech miesiącach przestali płacić czynsz. Standardowa umowa oznaczałaby wielomiesięczną batalię sądową. Na szczęście, przekonałem ją wcześniej do zawarcia umowy najmu okazjonalnego. Dzięki oświadczeniu o poddaniu się egzekucji, po uzyskaniu klauzuli wykonalności, mogliśmy niemal natychmiast skierować sprawę do komornika. Cały proces odzyskania lokalu skrócił się z potencjalnego roku do niecałych trzech miesięcy.'],
      ['h2', 'Krok 3: Przekazanie lokalu i kaucja – diabeł tkwi w szczegółach'],
      ['p', 'Umowa podpisana? Świetnie. Ale to nie koniec. Równie ważne jest prawidłowe przekazanie mieszkania.'],
      ['h3', 'Protokół zdawczo-odbiorczy – Twoja polisa ubezpieczeniowa'],
      ['p', 'To dokument, w którym opisujesz stan techniczny mieszkania i jego wyposażenia w dniu przekazania kluczy. Im bardziej szczegółowy, tym lepiej.'],
      ['p', '**Co musi zawierać protokół?**'],
      ['ul', [
        'Dokładny opis stanu ścian, podłóg, okien.',
        'Listę wszystkich mebli i sprzętów AGD wraz z ich stanem (np. „lodówka marki X, działa, widoczne zarysowanie na drzwiach”).',
        'Stany liczników (prąd, woda, gaz, ogrzewanie).',
        'Liczbę przekazanych kompletów kluczy.',
        '**Dokumentację fotograficzną!** Zrób szczegółowe zdjęcia całego mieszkania, a zwłaszcza istniejących już usterek. To niepodważalny dowód w razie sporu.',
      ]],
      ['h3', 'Kaucja – jak ją prawidłowo rozliczyć?'],
      ['p', 'Kaucja zabezpiecza Twoje roszczenia z tytułu ewentualnych zniszczeń lub niezapłaconego czynszu. Pamiętaj, że:'],
      ['ul', [
        'Maksymalna wysokość kaucji to 12-krotność miesięcznego czynszu (w praktyce standardem jest 1- lub 2-krotność).',
        'Masz 30 dni od dnia opróżnienia lokalu na jej zwrot lub rozliczenie.',
        'Możesz z niej potrącić jedynie koszty naprawy zniszczeń ponad normalne zużycie oraz niezapłacone należności. Nie możesz jej zatrzymać na „odświeżenie mieszkania”.',
      ]],
      ['p', '**Case study z mojej praktyki (Klient online z Lublina)** Pan Krzysztof, mieszkający na stałe w Wielkiej Brytanii, odziedziczył mieszkanie na lubelskim Czechowie. Chciał je wynająć, ale obawiał się problemów, zarządzając nieruchomością na odległość. Skontaktował się ze mną online. Przygotowałem dla niego kompletną dokumentację – umowę najmu okazjonalnego oraz wzór bardzo szczegółowego protokołu zdawczo-odbiorczego. Dzięki konsultacjom online, Pan Krzysztof był w stanie samodzielnie i bezpiecznie przeprowadzić cały proces, mając pewność, że jego interesy są chronione.'],
      ['h2', 'Kiedy sprawy idą źle – wypowiedzenie umowy'],
      ['p', 'Nawet najlepsze przygotowanie nie daje 100% gwarancji. Jeśli najemca przestaje płacić, musisz działać szybko i zgodnie z prawem.'],
      ['ol', [
        '**Wezwanie do zapłaty:** Wyślij oficjalne pismo (listem poleconym za potwierdzeniem odbioru), wzywające do uregulowania zaległości i wyznaczające dodatkowy, miesięczny termin na zapłatę.',
        '**Oświadczenie o wypowiedzeniu:** Dopiero po bezskutecznym upływie tego terminu możesz złożyć oświadczenie o wypowiedzeniu umowy.',
        '**Postępowanie sądowe:** Jeśli najemca nie opuści lokalu dobrowolnie, kolejnym krokiem jest pozew o eksmisję.',
      ]],
      ['p', '**Choć większość spraw prowadzę w Lublinie i Warszawie, reprezentuję klientów z całej Polski – również online.** Proces windykacji i eksmisji jest skomplikowany, dlatego na tym etapie wsparcie adwokata od nieruchomości jest nieocenione.'],
      ['h2', 'FAQ – najczęstsze pytania właścicieli'],
      ['p', '**1. Czy mogę wejść do wynajmowanego mieszkania bez zgody najemcy?** Absolutnie nie. Wejście do lokalu bez zgody i obecności najemcy (poza sytuacjami awarii zagrażającej bezpieczeństwu) jest naruszeniem miru domowego i stanowi przestępstwo.'],
      ['p', '**2. Kto płaci za drobne naprawy w mieszkaniu?** Zgodnie z prawem, najemcę obciążają drobne naprawy i konserwacja (np. wymiana żarówek, uszczelki w kranie, naprawa zamków). Poważne awarie (np. instalacji elektrycznej, pieca gazowego) są obowiązkiem właściciela. Warto te kwestie doprecyzować w umowie.'],
      ['p', '**3. Czy mogę podnieść czynsz w trakcie trwania umowy na czas określony?** Tylko jeśli umowa zawiera tzw. klauzulę waloryzacyjną, która precyzyjnie określa warunki podwyżki (np. o wskaźnik inflacji GUS). W innym przypadku podniesienie czynszu wymaga zgody najemcy i podpisania aneksu do umowy.'],
      ['p', '**4. Co zrobić, gdy najemca nie chce odebrać korespondencji?** Jeśli wysyłasz ważne pisma (jak wezwanie do zapłaty) listem poleconym za potwierdzeniem odbioru, a najemca go nie odbierze, pismo uważa się za skutecznie doręczone, jeżeli adresat mógł się z nim realnie zapoznać (a w postępowaniu sądowym kiedy przesyłka była podwójnie awizowana). Zachowaj dowód nadania i zwrotkę.'],
      ['h2', 'Potrzebujesz pewności? Porozmawiajmy'],
      ['p', 'Zarządzanie najmem nie musi być polem minowym. Dobrze przygotowana strategia i solidne dokumenty to klucz do spokoju i ochrony Twojej inwestycji.'],
      ['p', 'Jeśli planujesz wynająć mieszkanie w **Lublinie, Warszawie** lub gdziekolwiek indziej w Polsce i chcesz mieć pewność, że Twoja umowa jest kuloodporna, opisz swoją sprawę w formularzu poniżej — bezpłatnie ocenię ją w ciągu 24 h.'],
      ['note', 'Niniejszy artykuł ma charakter wyłącznie informacyjny i nie stanowi porady prawnej. Każda sytuacja prawna jest inna i wymaga indywidualnej analizy. W celu uzyskania wiążącej porady prawnej, skontaktuj się z profesjonalnym pełnomocnikiem.'],
    ],
  },
  {
    slug: 'nielegalne-wydobycie-piachu-z-dzialki-konsekwencje',
    title: 'Twoja działka, Twoja odpowiedzialność? Nielegalne wydobycie piachu – konsekwencje',
    excerpt: 'Posiadanie własnego kawałka ziemi – czy to działki rolnej odziedziczonej po dziadkach, czy gruntu inwestycyjnego pod miastem – kojarzy się z bezpieczeństwem i wolnością. Niestety, w mojej praktyce adwokackiej zbyt często widzę, jak ta sielanka zamienia się w koszmar. Właściciele, często nieświadomi zagrożeń, stają przed widmem gigantycznych kar i wieloletnich postępowań.',
    date: '11 października 2025', iso: '2025-10-11', readTime: '6 min',
    category: 'Odpowiedzialność właściciela', tags: ['Prawo geologiczne', 'Opłata podwyższona', 'Działka rolna'],
    cover: 'assets/blog-wydobycie-piachu.png',
    source: 'https://www.mecenasodnieruchomosci.pl/post/twoja-działka-twoja-odpowiedzialność-nielegalne-wydobycie-piachu-konsekwencje',
    related: ['dzierzawa-rolna', 'uregulowanie-stanu-prawnego'],
    body: [
      ['lead', 'Posiadanie własnego kawałka ziemi – czy to działki rolnej odziedziczonej po dziadkach, czy gruntu inwestycyjnego pod miastem – kojarzy się z bezpieczeństwem i wolnością. Niestety, w mojej praktyce adwokackiej zbyt często widzę, jak ta sielanka zamienia się w koszmar. Właściciele, często nieświadomi zagrożeń, stają przed widmem gigantycznych kar i wieloletnich postępowań.'],
      ['p', '**TL;DR – Co musisz wiedzieć?**'],
      ['ul', [
        '**Twoja zgoda ma znaczenie:** Nawet ustna zgoda na wykorzystanie Twojej działki przez kogoś innego może obarczyć Cię odpowiedzialnością za jego nielegalne działania.',
        '**Konsekwencje są potrójne:** Nielegalne działania na Twoim gruncie (np. wydobycie piasku) mogą uruchomić lawinę postępowań: administracyjnego (opłata karna), karnego (grzywna, a nawet więzienie) i karno-skarbowego (zaległy podatek z odsetkami).',
        '**Bierność to najgorsza strategia:** Ignorowanie sygnałów ostrzegawczych i brak zabezpieczeń prawnych to prosta droga do problemów. Kluczem jest proaktywne działanie.',
      ]],
      ['h2', 'Pułapka nieświadomości: kiedy Twój grunt staje się źródłem problemów?'],
      ['p', 'Wyobraź sobie sytuację: masz działkę rolną na obrzeżach Lublina lub rekreacyjną pod Warszawą, która od lat leży odłogiem. Pewnego dnia zgłasza się do Ciebie lokalny przedsiębiorca lub sąsiad z propozycją: „Pan pozwoli, że wezmę sobie trochę piasku na budowę, a w zamian wyrównam teren / zapłacę parę groszy”. Brzmi jak układ, w którym wszyscy wygrywają. Ty masz uporządkowaną działkę i dodatkowy dochód, on – tani materiał.'],
      ['p', 'Niestety, polskie prawo, w szczególności Prawo geologiczne i górnicze, jest w tej kwestii bezwzględne. Wydobycie kopaliny, nawet tak pospolitej jak piasek, w celach komercyjnych wymaga **koncesji**. Bez niej taka działalność jest nielegalna, a odpowiedzialność może spaść na Ciebie jako właściciela gruntu.'],
      ['p', 'Z mojego doświadczenia, jako **adwokata od nieruchomości w Lublinie i Warszawie**, wynika, że problemy najczęściej biorą się z:'],
      ['ul', [
        '**Ustnych umów:** Brak pisemnego śladu i jasno określonych zasad.',
        '**Niskiej świadomości prawnej:** Przekonania, że „na swoim mogę robić, co chcę”.',
        '**Zaufania do „znajomych”:** Przymykania oka na działania osób trzecich na naszej ziemi.',
      ]],
      ['h2', 'Z życia kancelarii: historia, która mogła zrujnować moją klientkę'],
      ['p', 'Niedawno zgłosiła się do mnie córka starszej Pani, właścicielki 1,5-hektarowej działki rolnej w okolicach Tarnobrzega. Jej matka, przez trzy lata, na podstawie ustnej umowy z sąsiadem, pozwalała firmie zewnętrznej pobierać piasek ze swojej ziemi. W zamian otrzymywała niewielkie kwoty, które traktowała jako dodatek do emerytury. Nie miała pojęcia, że powinna to zgłaszać do urzędu skarbowego, a tym bardziej, że taka działalność wymaga jakichkolwiek pozwoleń.'],
      ['p', 'Sprawa wyszła na jaw, gdy na sąsiednią działkę wkroczyła Policja. Funkcjonariusze zaczęli zadawać pytania również o nieruchomość matki mojej klientki. Sąsiad, który pośredniczył w umowie, umył ręce. Nagle starsza, schorowana kobieta stanęła przed perspektywą utraty dorobku całego życia.'],
      ['h2', 'Trzy fronty, jedna bitwa: jakie kary grożą za nielegalne wykorzystanie działki?'],
      ['p', 'Analiza tej sprawy pokazała, że nieświadome udostępnienie gruntu uruchomiło mechanizm zapadkowy, otwierając aż trzy potencjalne fronty walki z państwowymi organami. Co ważne, postępowania te mogą toczyć się niezależnie i równolegle.'],
      ['h3', 'Cios w portfel: opłata podwyższona – kara administracyjna'],
      ['p', 'To najpoważniejsze zagrożenie finansowe. Jeśli organ nadzoru górniczego (najczęściej starosta) stwierdzi wydobycie kopaliny bez koncesji, nakłada tzw. **opłatę podwyższoną**. Jest to sankcja administracyjna, której wysokość stanowi **40-krotność** standardowej opłaty eksploatacyjnej.'],
      ['p', 'W przypadku mojej klientki, z działki o powierzchni 0,4 ha wybrano piasek na głębokość około 2 metrów. Prosta symulacja pokazała, że groziła jej kara w wysokości **ponad 400 000 zł**. Co kluczowe, orzecznictwo sądów administracyjnych (w tym Naczelnego Sądu Administracyjnego) potwierdza, że jeśli ustalenie bezpośredniego sprawcy jest trudne, opłatą może zostać obciążony właściciel nieruchomości, który na proceder się godził i czerpał z niego korzyści.'],
      ['h3', 'Od świadka do oskarżonego: odpowiedzialność karna'],
      ['p', 'Ten sam czyn jest również ścigany na gruncie prawa karnego.'],
      ['ul', [
        '**Wykroczenie (art. 177 Prawa geologicznego i górniczego):** Za wydobycie kopaliny bez koncesji grozi kara aresztu albo grzywny.',
        '**Przestępstwo (art. 176 Prawa geologicznego i górniczego):** Jeśli wydobycie wyrządziło znaczną szkodę w mieniu lub środowisku (a degradacja 0,4 ha gruntu rolnego może być tak zakwalifikowana), kara może sięgnąć **do 3 lat pozbawienia wolności**.',
      ]],
      ['p', 'W przypadku mojej klientki istniało realne ryzyko, że z osoby wezwanej na przesłuchanie w charakterze świadka, szybko stanie się podejrzaną. Reprezentowałem ją podczas czynności w komendzie, gdzie kluczowe było skorzystanie z prawa do odmowy odpowiedzi na pytania, które mogłyby ją obciążyć (art. 183 Kodeksu postępowania karnego).'],
      ['h3', 'Fiskus nie zapomina: konsekwencje podatkowe'],
      ['p', 'Każdy przychód, nawet ten z nielegalnego źródła, podlega opodatkowaniu. Kwoty otrzymywane przez matkę mojej klientki powinny być co roku wykazywane w zeznaniu PIT jako „przychody z innych źródeł”. Niezrobienie tego skutkuje:'],
      ['ul', [
        '**Powstaniem zaległości podatkowej**, od której naliczane są odsetki (w ostatnich latach sięgające nawet 16,5% rocznie).',
        '**Odpowiedzialnością karno-skarbową** za uszczuplenie podatku (art. 54 Kodeksu karnego skarbowego). W tym przypadku było to wykroczenie skarbowe zagrożone grzywną.',
      ]],
      ['p', 'Choć w porównaniu do opłaty podwyższonej kwota zaległego podatku (kilka tysięcy złotych) wydawała się niewielka, to właśnie ona często jako pierwsza zwraca uwagę urzędów.'],
      ['h2', 'Jak się chronić? Twoja checklista bezpiecznego właściciela'],
      ['p', 'Problemy mojej klientki wynikały z braku wiedzy i działania w zaufaniu. Aby uniknąć podobnego scenariusza, każdy właściciel gruntu powinien przeprowadzić mały audyt bezpieczeństwa.'],
      ['ol', [
        '**Umowy tylko na piśmie:** Czy każdą zgodę na korzystanie z mojej działki (dzierżawa, użyczenie) mam potwierdzoną pisemną umową, precyzującą cel i zakres wykorzystania?',
        '**Monitoring nieruchomości:** Czy regularnie (przynajmniej raz na kwartał) odwiedzam swoją działkę, aby sprawdzić, czy nie dzieje się na niej nic niepokojącego?',
        '**Dokumentacja fotograficzna:** Czy mam zdjęcia dokumentujące stan działki, które mogą posłużyć jako dowód w razie jej zniszczenia lub nielegalnego wykorzystania?',
        '**Znajomość sąsiadów:** Czy mam kontakt do sąsiadów, którzy mogliby mnie poinformować o podejrzanej aktywności na moim terenie?',
        '**Weryfikacja kontrahenta:** Zanim zgodzę się na jakąkolwiek współpracę, czy sprawdziłem wiarygodność osoby lub firmy (np. w CEIDG/KRS)?',
        '**Konsultacja prawna:** Czy w przypadku jakichkolwiek wątpliwości dotyczących umowy lub planowanej działalności na mojej działce, skonsultowałem się z prawnikiem?',
        '**Uregulowany stan prawny:** Czy mam pewność, że księga wieczysta mojej nieruchomości jest aktualna i nie ma w niej niepokojących wpisów?',
      ]],
      ['h2', 'Lokalny problem, globalne rozwiązania: pomoc prawna w Lublinie, Warszawie i całej Polsce'],
      ['p', 'Choć opisany przypadek dotyczył województwa świętokrzyskiego, z podobnymi problemami spotykam się, reprezentując klientów przed sądami i urzędami w całej Polsce. Niezależnie od tego, czy chodzi o działkę na warszawskim Mokotowie, której sąsiad używa jako parkingu, czy o grunt rolny pod Krakowem, na którym ktoś urządził nielegalne wysypisko – mechanizmy prawne są podobne.'],
      ['p', 'Współczesna technologia pozwala na skuteczne prowadzenie spraw na odległość. Choć większość spraw prowadzę stacjonarnie w **Lublinie (gdzie sprawy często trafiają do Sądu Rejonowego Lublin-Zachód) i Warszawie (np. przed Sądem Rejonowym dla m.st. Warszawy)**, z powodzeniem reprezentuję klientów z całej Polski, korzystając z konsultacji online i elektronicznego obiegu dokumentów. **Prawnik nieruchomości online** to dziś standard, który pozwala na szybki dostęp do profesjonalnej pomocy, niezależnie od miejsca zamieszkania.'],
      ['h2', 'Najczęściej zadawane pytania (FAQ)'],
      ['p', '**1. Czy mogę wydobywać piasek na własne potrzeby bez żadnych pozwoleń?** Tak, ale pod rygorystycznymi warunkami. Prawo geologiczne i górnicze (art. 4) pozwala na to osobie fizycznej, jeśli łącznie spełni ona następujące warunki: wydobycie jest na jej własne potrzeby (nie na sprzedaż), nie przekracza 10 m³ w roku kalendarzowym, odbywa się bez użycia materiałów wybuchowych i jest zgodne z przeznaczeniem nieruchomości. Zamiar takiego wydobycia należy zgłosić do organu nadzoru górniczego na 7 dni przed rozpoczęciem prac.'],
      ['p', '**2. Sąsiad bez mojej wiedzy zaczął składować na mojej działce odpady. Co robić?** Należy działać natychmiast. Po pierwsze, wezwać go pisemnie do natychmiastowego usunięcia odpadów i przywrócenia działki do stanu poprzedniego. Po drugie, udokumentować sytuację (zdjęcia, notatki). Jeśli wezwanie nie poskutkuje, należy zgłosić sprawę na Policję lub do straży miejskiej oraz do wójta/burmistrza/prezydenta miasta, który może nakazać usunięcie odpadów w drodze decyzji administracyjnej.'],
      ['p', '**3. Dostałem wezwanie na przesłuchanie w charakterze świadka w sprawie mojej działki. Czy potrzebuję adwokata?** Absolutnie tak. Jak pokazuje opisana historia, status świadka w takich sprawach jest bardzo niestabilny i łatwo można stać się podejrzanym. Adwokat (lub radca prawny) jako pełnomocnik świadka zadba o prawidłowy przebieg przesłuchania, doradzi, kiedy można legalnie odmówić odpowiedzi na pytanie (art. 183 KPK), i będzie chronił Twoje interesy na każdym etapie.'],
      ['p', '**4. Czy umowa dzierżawy chroni mnie przed odpowiedzialnością za działania dzierżawcy?** Dobrze skonstruowana umowa dzierżawy znacząco zwiększa Twoje bezpieczeństwo, ale nie daje 100% gwarancji. Kluczowe jest, aby umowa precyzyjnie określała cel dzierżawy i zakazywała prowadzenia na gruncie działalności bez wymaganych prawem pozwoleń. W umowie warto zawrzeć wysokie kary umowne za naruszenie tych zasad oraz klauzulę o natychmiastowym rozwiązaniu umowy.'],
      ['h2', 'Zabezpiecz swoją przyszłość – opisz swoją sprawę'],
      ['p', 'Jeśli masz wątpliwości co do bezpieczeństwa prawnego swojej nieruchomości lub znalazłeś się w sytuacji podobnej do opisanej, nie czekaj, aż problem eskaluje. Czas działa na Twoją niekorzyść.'],
      ['note', 'Powyższy artykuł ma charakter wyłącznie informacyjny i edukacyjny, nie stanowi porady prawnej. Każdy stan faktyczny wymaga indywidualnej analizy. W celu uzyskania wiążącej porady prawnej, skontaktuj się z profesjonalnym pełnomocnikiem.'],
    ],
  },
  {
    slug: 'jak-przygotowac-sie-na-zmiany-w-planowaniu-przestrzennym',
    title: 'Prawnik od nieruchomości radzi: jak przygotować się na zmiany w planowaniu przestrzennym?',
    excerpt: 'Reforma planowania przestrzennego przynosi rewolucję w lokalnych procedurach planistycznych. Pojawia się plan ogólny gminy, zmieniają się zasady wydawania decyzji o warunkach zabudowy (WZ) oraz uchwalania miejscowych planów. Wyjaśniam najważniejsze zmiany i podpowiadam, jakie działania podjąć, by zabezpieczyć swoje interesy.',
    date: '28 października 2025', iso: '2025-10-28', readTime: '13 min',
    category: 'Planowanie przestrzenne', tags: ['Plan ogólny', 'WZ', 'MPZP', 'Konsultacje społeczne'],
    cover: 'assets/blog-reforma-planowania.png',
    source: 'https://www.mecenasodnieruchomosci.pl/post/prawnik-od-nieruchomości-radzi-jak-przygotować-się-na-zmiany-w-planowaniu-przestrzennym',
    related: ['plan-ogolny', 'warunki-zabudowy', 'skarga-na-plan-miejscowy'],
    body: [
      ['lead', 'Jako prawnik od nieruchomości widzę na co dzień, jak zmiany w prawie planowania wpływają na właścicieli gruntów. Niedawna reforma planowania przestrzennego (wprowadzona ustawą z 7 lipca 2023 r.) przynosi rewolucję w lokalnych procedurach planistycznych. Pojawia się plan ogólny gminy, zmieniają się zasady wydawania decyzji o warunkach zabudowy (WZ) oraz uchwalania miejscowych planów zagospodarowania przestrzennego (MPZP). Wprowadzono też bardziej rozbudowane konsultacje społeczne przy tworzeniu planów, aby mieszkańcy – w tym właściciele nieruchomości – mieli większy wpływ na ustalenia planistyczne.'],
      ['p', 'Ten artykuł wyjaśnia w przystępny sposób najważniejsze zmiany oraz podpowiada, jakie działania podjąć, by odpowiednio zabezpieczyć swoje interesy. Niezależnie od tego czy posiadasz działkę na lubelskim Czechowie, LSM czy Węglinie, czy też w warszawskiej dzielnicy Mokotów, Ursynów albo Wola – reformy dotkną wszystkich. Poniżej przedstawiam praktyczne porady z perspektywy adwokata nieruchomości. Dowiesz się, kiedy warto złożyć wnioski o WZ, jak reagować na nowe plany ogólne i miejscowe, jak sprawdzić klasę gruntu, a także jak skorzystać z pomocy prawnej, by przejść przez te zmiany bez stresu.'],
      ['h2', 'Najważniejsze zmiany w procedurze planistycznej'],
      ['h3', 'Plan ogólny gminy – nowy obowiązkowy dokument'],
      ['p', 'Do połowy 2026 r. każda gmina musi uchwalić plan ogólny dla całego swojego obszaru. Plan ogólny zastąpi dotychczasowe studium uwarunkowań i będzie aktem prawa miejscowego wyznaczającym ogólne zasady zagospodarowania przestrzennego. To kluczowy element reformy – od 1 lipca 2026 r. gmina bez planu ogólnego nie będzie mogła uchwalić nowego MPZP ani wydać decyzji WZ. Termin sporządzenia planów ogólnych wydłużono do 30 czerwca 2026 (pierwotnie gminy miały czas do końca 2025 roku), aby uniknąć paraliżu inwestycyjnego. Plan ogólny będzie w całości sporządzany cyfrowo i obejmie cały teren gminy, wytyczając tzw. strefy planistyczne oraz obszary uzupełnienia zabudowy (OUZ).'],
      ['p', '**Co to oznacza dla właściciela działki?** Jeśli Twoja nieruchomość znajduje się w gminie, która nie zdąży z planem ogólnym na czas, od połowy 2026 r. do momentu uchwalenia planu możesz mieć zamrożoną możliwość inwestycji – urząd nie wyda WZ ani nie uchwali lokalnego planu dla Twojego terenu. W skali kraju na początku 2025 r. ok. 25% gmin nawet nie rozpoczęło prac nad planem ogólnym, co pokazuje skalę ryzyka. Warto zatem monitorować, czy gmina pracuje nad planem ogólnym i zgłaszać wnioski, by uwzględniła Twój interes (np. ujęcie terenu w obszarze zabudowy).'],
      ['h3', 'Warunki zabudowy (WZ) – koniec „wuzetki” bez ograniczeń'],
      ['p', 'Decyzje o warunkach zabudowy przechodzą duże zmiany:'],
      ['ul', [
        '**Ograniczenie terytorialne:** Od 1 lipca 2026 r. WZ będą wydawane tylko dla działek położonych w obszarach uzupełnienia zabudowy (OUZ), wyznaczonych w planie ogólnym. Na terenach poza OUZ nie postawisz domu ani innej zabudowy na podstawie WZ – zniknie dotychczasowa zasada „dobrego sąsiedztwa” pozwalająca budować w luźno zabudowanych okolicach. Krótko mówiąc, poza wyznaczonymi obszarami zabudowy nowe inwestycje będą wymagały miejscowego planu.',
        '**Limit czasowy:** Obecnie WZ są bezterminowe, ale to się kończy. Od 2026 r. każde nowe WZ będzie ważne maksymalnie 5 lat. Po upływie tego czasu decyzja wygaśnie, jeśli inwestor nie uzyska pozwolenia na budowę. Co ważne, WZ wydane przed końcem 2025 r. zachowają bezterminowy charakter – będą wciąż ważne bez ograniczeń czasowych. To zachęca wielu inwestorów i właścicieli do zabezpieczenia się zawczasu.',
        '**Okres przejściowy – do 30.06.2026:** Mamy jeszcze kilkanaście miesięcy, by korzystać ze „starych” zasad. Do 30 czerwca 2026 r. można składać wnioski o WZ nawet w gminach bez planu ogólnego (dopóki nie uchwalą planu). Decyzje uzyskane w tym okresie (i które staną się ostateczne najpóźniej 31.12.2025) będą bezterminowe. Natomiast WZ wydane już w 2026 r. (jeśli uprawomocnią się po 1.01.2026) będą miały narzucony 5-letni termin ważności. W praktyce oznacza to, że końcówka 2025 to ostatni dzwonek, by uzyskać WZ na starych zasadach. Wiele osób już teraz składa wnioski, co spowodowało wzmożony ruch w urzędach i niestety wydłużenie kolejek.',
      ]],
      ['p', '**Co ta zmiana oznacza w praktyce?** Jeśli masz działkę bez miejscowego planu (a tak bywa np. na obrzeżach miasta, jak Węglin w Lublinie czy części Ursynowa w Warszawie), to do połowy 2026 możesz starać się o WZ na dotychczasowych zasadach. Po tym terminie, jeżeli Twój teren nie będzie w OUZ, nie dostaniesz WZ w ogóle dopóki gmina nie uchwali MPZP dla tego obszaru. W rezultacie warto już teraz rozważyć złożenie wniosku o WZ, by „zaklepać” sobie prawa do zabudowy. Pamiętaj też o ograniczeniu czasowym – od 2026 r. nawet uzyskane WZ będą wygasać, więc planuj inwestycję z uwzględnieniem tego 5-letniego terminu.'],
      ['h3', 'Miejscowe plany zagospodarowania (MPZP) – kontynuacja czy wstrzymanie?'],
      ['p', 'Lokalne plany pozostają kluczowym narzędziem planowania, ale reforma wpływa na ich procedurę:'],
      ['ul', [
        '**Brak planu ogólnego = brak nowych MPZP:** Jak wspomniano, gminy bez uchwalonego planu ogólnego od lipca 2026 nie będą mogły uchwalać ani zmieniać miejscowych planów. To oznacza możliwy przestój w planowaniu miejscowym, jeśli gmina się spóźni z planem ogólnym. Dla właścicieli działek skutkiem może być np. zablokowanie korzystnej zmiany planu lub uchwalenia planu umożliwiającego zabudowę terenów do tej pory rolnych.',
        '**Większa spójność z planem ogólnym:** Nowe i zmieniane MPZP będą musiały być zgodne z ustaleniami planu ogólnego. Plan ogólny będzie narzucał pewne ramy (np. strefy funkcjonalne, limity intensywności zabudowy, standardy urbanistyczne), które plan miejscowy doprecyzuje lokalnie. W praktyce może to ograniczyć dowolność gmin w uchwalaniu planów sprzecznych z wcześniejszym studium – teraz plan ogólny będzie wiążący. Dla Ciebie jako właściciela to ważny sygnał: sprawdź, co plan ogólny przewiduje dla Twojej okolicy, bo miejscowy plan będzie musiał się w to wpisać.',
        '**Kontrola społeczna i nadzorcza:** Reforma kładzie nacisk na partycypację społeczną (o czym za chwilę), ale też na nadzór wojewody nad planami. Już pierwsze uchwalone plany ogólne były weryfikowane – zdarzyło się, że wojewoda unieważnił plan ogólny miasta, jeśli dopatrzył się uchybienia (np. błędne ustalenie parametrów w jednej strefie). Samorządy naciskają, by złagodzić rygory (bo unieważnienie całego planu ogólnego to dla gminy duży problem), ale na razie przepisy wymagają wysokiej jakości dokumentów. Dla właściciela działki efekt może być taki, że proces uchwalania planów się wydłuży – warto śledzić ogłoszenia gminy, bo np. plan ogólny może być ponownie wykładany do wglądu, gdy coś trzeba poprawić.',
      ]],
      ['h3', 'Konsultacje społeczne – nowy standard w planowaniu'],
      ['p', 'Reforma znacząco rozszerza wymagania co do udziału społeczeństwa w procedurze planistycznej. Dawniej konsultacje często sprowadzały się do wyłożenia projektu planu i dyskusji publicznej w urzędzie. Teraz jest inaczej:'],
      ['ul', [
        '**Więcej form konsultacji:** Gmina musi zastosować co najmniej trzy różne formy konsultacji, w tym: zbieranie uwag na piśmie, otwarte spotkania z mieszkańcami lub warsztaty planistyczne, a także np. ankiety lub geoankiety internetowe, spacery studyjne czy punkty konsultacyjne. Katalog form jest szeroki, aby aktywnie zaangażować mieszkańców (np. warsztaty dla chętnych, spacery po terenie planu, ankiety online). Co ważne, zapewniono też możliwość udziału zdalnego w niektórych formach, co ułatwia uczestnictwo osobom zapracowanym czy mieszkającym daleko.',
        '**Dostępność czasowa i powszechność:** Ustawowo konsultacje mają odbywać się po godzinach pracy urzędów, w łatwo dostępnych miejscach – tak, by każdy mógł wziąć udział. Udział mogą brać wszyscy zainteresowani, w tym osoby nieletnie (np. młodzież również może wyrazić swoje zdanie). To podkreśla, że planowanie przestrzenne dotyczy całej lokalnej społeczności.',
        '**Newsletter i informowanie mieszkańców:** Nowe przepisy zachęcają gminy do lepszego informowania o planach – np. możliwość zapisu na newsletter planistyczny, gdzie dostaniemy e-mail o każdej inicjatywie planistycznej czy wniosku inwestycyjnym w okolicy. Warto sprawdzić, czy Twój urząd oferuje takie powiadomienia.',
        '**Konsekwencje prawne:** Niespełnienie nowych wymogów konsultacji może skutkować unieważnieniem uchwalonego planu. Wojewodowie już uchylali plany miejscowe, jeśli gmina nie dopełniła nowych obowiązków partycypacyjnych w procedurze rozpoczętej po 24 września 2023 r. To dla właścicieli ważny sygnał: masz realny wpływ na plan, a jednocześnie jeśli plan został uchwalony z naruszeniem Twoich praw udziału – możesz go z pomocą prawnika podważyć.',
      ]],
      ['p', '**Co robić jako właściciel?** Aktywnie uczestnicz w konsultacjach! Śledź ogłoszenia o przystąpieniu do sporządzania planu ogólnego czy miejscowego dla Twojej okolicy (np. osiedla Czechów w Lublinie czy dzielnicy Wola w Warszawie). Zgłaszaj wnioski na początku procesu – możesz np. wnioskować o przeznaczenie Twojego terenu pod zabudowę mieszkaniową, jeśli dziś jest rolny. Chodź na spotkania i warsztaty – tam możesz dowiedzieć się o planowanych ustaleniach z pierwszej ręki i zgłosić swoje uwagi ustnie. Wypełnij ankietę lub geoankietę, jeśli gmina ją udostępnia, aby wskazać swoje potrzeby. Pamiętaj: konsultacje odbywają się często po godzinach pracy, w pobliżu (np. w domu kultury na osiedlu), więc starają się być przyjazne mieszkańcom. Każda uwaga musi być rozpatrzona przez gminę – Twój głos może wpłynąć na kształt planu, który zadecyduje o warunkach zabudowy Twojej działki i okolicy.'],
      ['h2', 'Praktyczne porady dla właścicieli działek – jak reagować na zmiany?'],
      ['ol', [
        '**Sprawdź stan planistyczny swojej nieruchomości:** Na początek dowiedz się, czy Twoja działka ma obowiązujący miejscowy plan. Jeśli tak – zapoznaj się z jego ustaleniami (przeznaczenie terenu, wysokość zabudowy, itp.). Plan miejscowy daje Ci pewność co do możliwości zabudowy, ale upewnij się, czy gmina nie planuje go zmieniać. Jeśli nie masz MPZP, zobacz czy wydano decyzję o warunkach zabudowy dla tego terenu (na Ciebie lub poprzedniego właściciela). Brak planu i WZ oznacza, że teren jest niezaplanowany – tu reforma ma największy wpływ. Informacje sprawdzisz w urzędzie gminy lub często online na geoportalu czy w BIP.',
        '**Śledź prace nad planem ogólnym i zgłaszaj wnioski:** Gminy publikują uchwały o przystąpieniu do planu ogólnego – od tego momentu możesz w określonym terminie zgłaszać wnioski do planu. Warto to zrobić, jeśli np. Twoja działka nie jest zabudowana – wnioskuj o objęcie jej obszarem uzupełnienia zabudowy (OUZ). To ważne, bo jeśli znajdziesz się poza OUZ, po 2026 r. nie dostaniesz WZ na budowę. Przykład z praktyki: w jednej z gmin klienci mojej kancelarii mieli dużą działkę rolną na skraju miasta. Dzięki złożonym wnioskom teren ten uwzględniono w OUZ planu ogólnego – zabezpieczyli tym samym przyszłą możliwość zabudowy. Jeśli plan ogólny jest na etapie wyłożenia projektu, sprawdź koniecznie projekt planu (dostępny w urzędzie lub w internecie) i złóż ewentualne uwagi. To samo dotyczy nowych miejscowych planów dla Twojego rejonu – reaguj już na etapie projektu.',
        '**Złóż wniosek o WZ przed „deadlinem”, jeśli planujesz budowę:** Gdy Twoja działka nie ma planu miejscowego, a myślisz o budowie w najbliższych latach, rozważ złożenie wniosku o decyzję WZ przed 30 czerwca 2026 r. Po tej dacie może to być niemożliwe (jeśli gmina uchwali plan ogólny, Twój teren może być poza OUZ). Nawet jeśli nie planujesz budowy od razu, warto mieć WZ w ręku – szczególnie że decyzje wydane i ostateczne do końca 2025 r. będą bezterminowe. Uwaga: wniosek o WZ powinien być dobrze przygotowany (określ, co chcesz budować), aby urząd nie odrzucił go z błahych powodów. Prawnik nieruchomości może tu pomóc sporządzić solidny wniosek. Pamiętaj, że gmina nie może odmówić przyjęcia wniosku WZ ani zawiesić postępowania tylko dlatego, że pracuje nad planem ogólnym – przepisy na to nie pozwalają.',
        '**Sprawdź klasę i przeznaczenie gruntu:** Jeżeli Twoja działka leży na terenie nominalnie rolnym (często na obrzeżach miast, np. Węglin Północny w Lublinie, czy peryferyjne części Ursynowa), sprawdź jej klasę bonitacyjną. Klasę gruntu (I-VI) znajdziesz w ewidencji gruntów (wydział geodezji) lub na geoportalu. To ważne, bo grunty rolne klas I–III podlegają ochronie – przed zabudową trzeba je odrolnić (uzyskać zgodę na zmianę przeznaczenia). Miejscowy plan może automatycznie odrolnić grunt, ale decyzja WZ już wymaga odrolnienia osobną decyzją przy pozwoleniu na budowę. Jeśli planujesz budowę na działce rolnej, upewnij się, że w planie miejscowym projektowanym dla Twojego terenu gmina przewiduje zmianę przeznaczenia. W razie wątpliwości skonsultuj się z prawnikiem – oceni, czy Twoja działka ma ograniczenia (np. wysoką klasę gleby, obszar chroniony) i jak to wpływa na możliwość zabudowy. Pro tip: działki budowlane w granicach miasta często mają klasy IV–VI, co ułatwia sprawę, ale lepiej to zawczasu zweryfikować.',
        '**Uważaj na zmiany planów miejscowych:** Jeśli Twoja działka jest objęta MPZP – śpij spokojniej, bo masz jasno określone warunki zabudowy. Ale… plany miejscowe też mogą być zmieniane. Jeżeli słyszysz, że gmina szykuje zmianę planu dla Twojej okolicy (np. żeby obniżyć intensywność zabudowy, wyznaczyć park, drogę itp.), zareaguj. Masz prawo składać uwagi do projektu zmiany planu – i warto z tego skorzystać, by bronić swojego interesu (np. zachować możliwość zabudowy wielorodzinnej zamiast nowych ograniczeń). Dla przykładu, mieszkańcy osiedla LSM w Lublinie pilnują, by nowe plany nie dopuściły uciążliwych usług wśród bloków, a właściciele gruntów na Czechowie walczyli o korzystne dla nich zapisy przy planowaniu tzw. Górek Czechowskich. Pamiętaj, że plan miejscowy to akt prawa – po uchwaleniu jest wiążący. Więc lepiej zapobiegać niekorzystnym zapisom na etapie projektu, niż później walczyć z uchwalonym planem (choć i to możliwe, ale wymaga skargi do sądu administracyjnego).',
        '**Skorzystaj z profesjonalnej pomocy, gdy robi się skomplikowanie:** Reforma jest złożona i może rodzić wiele pytań. Adwokat nieruchomości specjalizujący się w prawie budowlanym i planistycznym pomoże Ci ocenić sytuację Twojej nieruchomości. Przykładowo, moja Kancelaria analizuje dla klientów stan planistyczny działki (czy jest plan, studium, projekt planu, WZ, decyzje o inwestycjach celu publicznego itp.), a następnie doradza strategię działania. Czasem najlepszym ruchem jest szybki wniosek o WZ, innym razem – inicjatywa uchwalenia planu miejscowego (zdarza się, że inwestor finansuje sporządzenie planu dla swojego terenu). Niekiedy warto też wystąpić o zmianę przeznaczenia działki w studium/planie – prawnicy mogą pomóc przygotować wnioski i argumentację. Jeśli czujesz się niepewnie wobec urzędowych procedur, skorzystaj z bezpłatnej wstępnej analizy sprawy (formularz poniżej – odpowiadam w 24 h, dla klientów w całej Polsce), w której uzyskasz odpowiedzi na nurtujące pytania.',
        '**Reprezentacja w postępowaniach planistycznych:** Warto wiedzieć, że możesz działać przez pełnomocnika. Kancelaria specjalizująca się w nieruchomościach może reprezentować Cię w kontaktach z urzędem – np. składać wnioski i uwagi w Twoim imieniu, negocjować z planistami podczas spotkań, a nawet formalnie zaskarżyć niekorzystne ustalenia planu. Przykład z praktyki: reprezentowałem klientów z Mazur, których działki rekreacyjne w projekcie planu miejscowego miały zostać przeznaczone pod zalesienie. Po interwencji i przedstawieniu argumentacji prawnej część terenu utrzymała funkcję budowlaną. Podobnie w jednej ze spraw w Małopolsce – właściciel działki rolnej planował agroturystykę; dzięki naszym uwagom do planu włączono jego teren do obszaru zabudowy zagrodowej. Pomoc prawnika z całej Polski (również online) jest dostępna – nie musisz ograniczać się do lokalnych specjalistów, jeśli gdzie indziej znajdziesz odpowiednie doświadczenie. Ważne, by Twój pełnomocnik znał realia prawa planistycznego po reformie 2023.',
      ]],
      ['h2', 'Usługi kancelarii nieruchomości w kontekście reformy planowania'],
      ['p', 'Reforma zwiększa zapotrzebowanie na specjalistyczną pomoc prawną. Moja kancelaria (działająca w Warszawie, Lublinie oraz zdalnie - w całej Polsce) oferuje kompleksowe wsparcie w sprawach planistycznych – zarówno dla właścicieli indywidualnych, jak i dla inwestorów. Oto, jak mogę Ci pomóc:'],
      ['ul', [
        '**Analiza planistyczna działki:** Sprawdzę wszystkie dokumenty dotyczące Twojego gruntu – miejscowy plan (lub jego brak), zapisy planu ogólnego (jeśli jest uchwalony lub projektowany), decyzje WZ, studium, rejestr zabytków, obszary chronione, klasa gruntu itp. Otrzymasz raport, jakie masz możliwości zabudowy i jakie ograniczenia wynikają z obecnych i przyszłych regulacji.',
        '**Doradztwo strategiczne i konsultacje WZ/MPZP:** Podpowiem, jakie kroki podjąć w związku z reformą. Np. czy lepiej starać się o WZ teraz, czy czekać na plan miejscowy; czy zgłaszać uwagi do planu ogólnego; jak zwiększyć szanse na korzystne ustalenia dla Twojej działki. Omawiamy to podczas indywidualnych konsultacji (również online – obsługuję klientów z całej Polski). Moim celem jest zabezpieczenie Twojego prawa do zabudowy i maksymalizacja wartości nieruchomości w nowych realiach.',
        '**Pomoc w procedurze WZ:** Przygotowuję i składam wnioski o warunki zabudowy tak, aby były kompletne i zgodne z przepisami. Pilnuję terminów i reprezentuję klienta przed urzędem. Jeśli gmina nie wydaje decyzji w ustawowym terminie, wiem jak skutecznie ponaglić urząd lub wnieść skargę na bezczynność. Po uzyskaniu WZ analizuję jej treść – czy na pewno daje to, o co wnioskowałeś, i czy nie warto się odwołać, by uzyskać lepsze warunki.',
        '**Reprezentacja w procedurze planu miejscowego/ogólnego:** Gdy gmina przystąpi do sporządzenia planu (ogłasza to publicznie), pomagam klientom złożyć formalne wnioski na etapie początkowym. Gdy jest projekt planu – przygotowuję uwagi w imieniu klientów, bazując na wiedzy urbanistycznej i prawnej. Moje argumenty są merytoryczne, często poparte orzecznictwem, co zwiększa szanse ich uwzględnienia. Jeżeli plan zostanie uchwalony niekorzystnie, reprezentuję klienta przed wojewodą (wnioski o stwierdzenie nieważności aktu) oraz przed sądem administracyjnym (skarga na plan). Takie sprawy prowadziłem m.in. dla klientów z Pomorza (plan ograniczający zabudowę w strefie nadmorskiej) czy z okolic Krakowa (plan zmieniający przeznaczenie gruntów inwestycyjnych).',
        '**Bieżące doradztwo i informacje:** Utrzymuję kontakt z klientem na każdym etapie. Ponieważ prawo planistyczne jest w trakcie wdrażania reformy, informuję o kolejnych zmianach, np. nowych rozporządzeniach wykonawczych (choćby standardy urbanistyczne dla OUZ) czy o wydłużeniu terminów. Świadczę też usługę monitoringu planistycznego – na życzenie klienta obserwuję, czy w danej gminie nie rozpoczyna się proces planistyczny dotyczący jego terenu i od razu go o tym powiadamiam.',
      ]],
      ['h2', 'FAQ – najczęstsze pytania o reformę planowania i prawa właścicieli'],
      ['p', '**Q: Co to jest plan ogólny gminy i czy zastępuje miejscowe plany?**'],
      ['p', 'A: Plan ogólny gminy to nowy dokument planistyczny obowiązkowy dla każdej gminy do połowy 2026 r. Określa ogólne ramy zagospodarowania przestrzennego na obszarze całej gminy (m.in. strefy funkcjonalne i obszary uzupełnienia zabudowy). Nie zastępuje on miejscowych planów, ale warunkuje ich tworzenie – nowe MPZP muszą być zgodne z ustaleniami planu ogólnego. Plan ogólny zastępuje dawne studium uwarunkowań. W praktyce: najpierw gmina uchwala plan ogólny, a potem na jego podstawie może uchwalać lub zmieniać miejscowe plany dla poszczególnych obszarów.'],
      ['p', '**Q: Do kiedy można uzyskać decyzję o warunkach zabudowy (WZ) na starych zasadach?**'],
      ['p', 'A: Do 30 czerwca 2026 r. – do tego dnia można składać wnioski o WZ według dotychczasowych zasad, o ile dla danego terenu nie uchwalono jeszcze planu ogólnego. Jeśli gmina nie ma planu ogólnego, wnioski WZ będą rozpatrywane jak dotąd (wymagana zgodność z sąsiedztwem). Uwaga: kluczowa jest data uzyskania decyzji. Jeżeli decyzja WZ stanie się ostateczna do 31 grudnia 2025 r., będzie bezterminowa. WZ uzyskane później (w 2026 r.) będą miały już termin ważności 5 lat. Dlatego wiele osób stara się o WZ wcześniej, by zdążyć przed zmianami.'],
      ['p', '**Q: Moja działka nie ma miejscowego planu. Co się zmieni po 2026 roku?**'],
      ['p', 'A: Po 2026 r. zmienią się dwie kluczowe kwestie: 1) Jeżeli Twoja gmina nie uchwali planu ogólnego, nie dostaniesz WZ ani nie powstanie plan miejscowy dla Twojej działki aż do uchwalenia planu ogólnego. Inwestycje mogą zostać wstrzymane. 2) Jeśli gmina uchwali plan ogólny, a Twoja działka nie znajdzie się w obszarze uzupełnienia zabudowy (OUZ) – również nie uzyskasz WZ, dopóki gmina nie uchwali MPZP dla tego terenu. Mówiąc prościej: dla terenów bez planu wzrosło ryzyko blokady inwestycji. Dlatego zalecam zdobycie WZ wcześniej lub nacisk na gminę, by ujęła Twój teren w OUZ planu ogólnego albo sporządziła miejscowy plan.'],
      ['p', '**Q: Jak mogę sprawdzić, czy moja działka będzie w obszarze uzupełnienia zabudowy (OUZ)?**'],
      ['p', 'A: Informacja o OUZ będzie wynikać z uchwalonego planu ogólnego gminy. Jeśli plan ogólny jest już uchwalony – zajrzyj do jego dokumentacji (powinna być dostępna na stronie urzędu gminy lub w Biuletynie Informacji Publicznej). Będą tam mapy lub dane przestrzenne pokazujące granice OUZ. Jeśli plan ogólny jest dopiero tworzony, możesz: 1) sprawdzić projekt planu ogólnego (jeśli jest na etapie wyłożenia do wglądu publicznego) – tam będą proponowane OUZ, 2) zapytać w urzędzie lub u gminnego urbanisty, czy w przewidywaniach Twój obszar będzie OUZ, 3) zgłosić wniosek o włączenie Twojej działki do OUZ (to sygnał dla planistów, że ktoś planuje tam zabudowę). Warto również monitorować strony społecznościowe lub lokalne media – często samorządy publikują wstępne informacje o koncepcji planu ogólnego.'],
      ['p', '**Q: Czym różnią się konsultacje społeczne od dawnej „dyskusji publicznej”?**'],
      ['p', 'A: Dawniej, przy planach miejscowych, po wyłożeniu projektu planu do publicznego wglądu odbywała się jednorazowa dyskusja publiczna – spotkanie w urzędzie, często w godzinach pracy, gdzie projektant prezentował plan i można było zadawać pytania. Reformowane przepisy wprowadziły szersze konsultacje społeczne już na wcześniejszym etapie – przed formalnym wyłożeniem planu. Teraz gmina musi zorganizować różnorodne formy spotkań i zbierania opinii (np. warsztaty, spacery, ankiety), zwykle popołudniami i bliżej mieszkańców. Konsultacje mają charakter aktywny i wieloetapowy – ich celem jest zebranie pomysłów i uwag jeszcze zanim plan nabierze ostatecznego kształtu. Oczywiście nadal będzie formalne wyłożenie planu i możliwość składania uwag pisemnych, ale rola mieszkańców jest wzmocniona na wczesnym etapie. Dzięki temu plan ma lepiej odpowiadać na lokalne potrzeby, a ewentualne konflikty (np. protesty) mogą zostać wychwycone wcześniej. Dla Ciebie to okazja, by wcześniej dowiedzieć się o planie i wpłynąć na niego, zamiast dopiero reagować na gotowy projekt.'],
      ['p', '**Q: Czy potrzebuję prawnika, aby złożyć uwagi lub wnioski do planu?**'],
      ['p', 'A: Formalnie nie ma takiego obowiązku – każdy może samodzielnie złożyć wniosek czy uwagę. W praktyce jednak pomoc prawnika nieruchomości lub urbanisty bywa bardzo cenna. Profesjonalista: 1) Sprawdzi procedurę – czy urząd dochował terminów ogłoszeń, czy poprawnie Cię powiadomił (jeśli jesteś „osobą, której interes prawny jest objęty planem”, masz prawo indywidualnego zawiadomienia). 2) Sformułuje precyzyjnie wniosek/uwagę – powołując się na konkretne przepisy i wykazując interes prawny, co zwiększa wagę Twojego głosu. 3) Doradzi, jakie argumenty podnieść – np. że plan drastycznie obniży wartość Twojej działki, albo że narusza zasady planistyczne. 4) W razie potrzeby przygotuje odwołanie/skargę – jeśli plan zostanie uchwalony niekorzystnie, prawnik przygotuje skargę do sądu administracyjnego lub wniosek do wojewody. Podsumowując: nie jest to konieczne, ale jeśli stawka jest wysoka (np. duża nieruchomość inwestycyjna) lub sprawa skomplikowana, wsparcie prawnika może zadecydować o powodzeniu.'],
      ['p', 'Czy potrzebujesz pomocy w sprawach planistycznych? Moja kancelaria nieruchomości (Lublin, Warszawa, cała Polska online) służy wsparciem.'],
      ['p', 'Opisz swoją sprawę w formularzu poniżej – bezpłatnie, w ciągu 24 h przeanalizuję Twoją sytuację i podpowiem najlepsze rozwiązania. Skontaktuj się już dziś, aby chronić swoje prawa i inwestycje!'],
      ['note', 'Powyższy artykuł ma charakter informacyjny i nie stanowi porady prawnej. Przepisy mogą ulegać zmianom, a każdy stan faktyczny wymaga indywidualnej analizy. Skonsultuj się z prawnikiem przed podjęciem działań prawnych dotyczących Twojej nieruchomości.'],
    ],
  },
  {
    slug: 'wyrok-tk-zasiedzenie-sluzebnosci-przesylu',
    title: 'Rewolucyjny wyrok TK: koniec z „darmowym” zasiedzeniem służebności przesyłu?',
    excerpt: 'Jeśli jesteś właścicielem działki, przez którą biegną „stare” rury, kable lub linie energetyczne, a przedsiębiorstwo przesyłowe odmawiało Ci zapłaty, powołując się na zasiedzenie – ten artykuł jest dla Ciebie. 2 grudnia 2025 roku Trybunał Konstytucyjny wydał orzeczenie (sygn. P 10/16), które wywraca do góry nogami dotychczasową linię obrony gigantów energetycznych.',
    date: '15 grudnia 2025', iso: '2025-12-15', readTime: '3 min',
    category: 'Służebność przesyłu', tags: ['Trybunał Konstytucyjny', 'Słupy na działce', 'Zasiedzenie'],
    cover: 'assets/blog-wyrok-tk-przesyl.png',
    source: 'https://www.mecenasodnieruchomosci.pl/post/rewolucyjny-wyrok-tk-koniec-z-darmowym-zasiedzeniem-służebności-przesyłu',
    related: ['odszkodowanie-sluzebnosc-przesylu', 'bezumowne-korzystanie'],
    body: [
      ['lead', 'Jeśli jesteś właścicielem działki, przez którą biegną „stare” rury, kable lub linie energetyczne, a przedsiębiorstwo przesyłowe odmawiało Ci zapłaty, powołując się na zasiedzenie – ten artykuł jest dla Ciebie. 2 grudnia 2025 roku Trybunał Konstytucyjny wydał orzeczenie (sygn. P 10/16), które wywraca do góry nogami dotychczasową linię obrony gigantów energetycznych.'],
      ['p', 'Jako adwokat od lat obserwuję nierówną walkę właścicieli gruntów z operatorami sieci. Do tej pory sądy często stawały po stronie firm, uznając, że mogły one zasiedzieć prawo do korzystania z Twojej ziemi, nawet jeśli urządzenia postawiono w PRL-u bez żadnej umowy. Najnowszy wyrok TK mówi temu „stop”. Co to oznacza w praktyce?'],
      ['h2', 'Co się zmieniło? „NIE” dla fikcji prawnej'],
      ['p', 'Aby zrozumieć wagę tej zmiany, musimy cofnąć się w czasie. Instytucja **służebności przesyłu** została wprowadzona do Kodeksu cywilnego dopiero **3 sierpnia 2008 roku**.'],
      ['p', 'Co działo się wcześniej? Przez lata sądy stosowały tzw. wykładnię rozszerzającą. Przyjmowano, że przedsiębiorstwa mogły nabyć przez zasiedzenie tzw. „służebność gruntową o treści odpowiadającej służebności przesyłu” na podstawie okresów posiadania sprzed 2008 roku (np. z lat 70. czy 80.).'],
      ['p', 'Co orzekł Trybunał Konstytucyjny w wyroku **P 10/16**?'],
      ['p', 'Trybunał uznał, że przepisy Kodeksu cywilnego rozumiane w ten sposób, że pozwalają na zasiedzenie służebności przesyłu przed jej formalnym wprowadzeniem do prawa (przed 3 sierpnia 2008 r.), są niezgodne z Konstytucją.'],
      ['h3', 'Najważniejsze wnioski z wyroku to:'],
      ['ul', [
        'brak podstawy prawnej: nie można nabyć przez zasiedzenie prawa, które w danym czasie nie istniało w systemie prawnym;',
        'ochrona własności: przyjmowanie fikcji prawnej (że „stare” zasiedzenie jest ważne) narusza konstytucyjne prawo własności i zaufanie obywatela do państwa;',
        'koniec automatyzmu: firmy przesyłowe tracą swój najpotężniejszy argument w sporach o zapłatę („nie zapłacimy, bo już to zasiedzieliśmy za darmo”).',
      ]],
      ['h2', 'Kogo dotyczą te zmiany?'],
      ['p', 'Zmiana ta jest **ogromną szansą** dla właścicieli nieruchomości, na których znajdują się urządzenia przesyłowe (słupy, gazociągi, wodociągi), zwłaszcza te wybudowane przed 2008 rokiem.'],
      ['p', 'Dotyczy to Ciebie, jeśli:'],
      ['ol', [
        'masz na działce infrastrukturę, za którą nie otrzymujesz wynagrodzenia;',
        'przedsiębiorstwo przesyłowe odmówiło zawarcia umowy, twierdząc, że nabyło służebność przez zasiedzenie;',
        'przegrałeś sprawę sądową o wynagrodzenie w oparciu o argument zasiedzenia (w takim przypadku otwiera się krótka droga do wznowienia postępowania!).',
      ]],
      ['h2', 'Co to zmienia w praktyce?'],
      ['p', 'Wyobraźmy sobie Pana Jana Kowalskiego. Na jego działce w 1985 roku postawiono linię energetyczną. Pan Jan nigdy nie wyraził na to zgody, nie było też decyzji wywłaszczeniowej.'],
      ['ul', [
        '**Scenariusz PRZED wyrokiem:** pan Jan idzie do sądu po wynagrodzenie za bezumowne korzystanie z gruntu, a Zakład Energetyczny odpowiada: „Korzystamy z tej linii od 30 lat. W 2015 roku zasiedzieliśmy służebność. Dziękujemy, nic się Panu nie należy”. Sądy masowo akceptowały taką argumentację, więc Pan Jan przegrywał.',
        '**Scenariusz PO wyroku (teraz):** adwokat Pana Jana podnosi argument z wyroku TK P 10/16. Wskazuje, że Zakład Energetyczny nie mógł doliczać okresu sprzed 2008 roku do czasu potrzebnego na zasiedzenie specyficznej „służebności przesyłu”, bo takiej instytucji wtedy nie było.',
        'Efekt: zarzut zasiedzenia upada, a **Zakład Energetyczny musi zapłacić Panu Janowi wynagrodzenie za bezumowne korzystanie (do 10 lat wstecz) oraz zacząć płacić za bieżącą służebność lub przesunąć infrastrukturę.**',
      ]],
      ['h2', 'Szansa, ale nie bez pułapek'],
      ['p', 'Choć wyrok jest przełomowy, nie oznacza on, że pieniądze wpłyną na Twoje konto automatycznie. Należy pamiętać o kilku kwestiach:'],
      ['ol', [
        'indywidualna analiza: każda sprawa jest inna i trzeba sprawdzić, czy przedsiębiorstwo nie dysponuje np. starą decyzją administracyjną (tzw. decyzją wywłaszczeniową), która nadal może być skuteczną podstawą do zajęcia gruntu;',
        'wznowienie postępowań: jeśli przegrałeś już prawomocnie sprawę w sądzie z powodu zasiedzenia, masz **bardzo mało czasu** (zazwyczaj 3 miesiące od publikacji wyroku TK w Dzienniku Ustaw) na złożenie skargi o wznowienie postępowania;',
        'postawa sądów: choć wyroki TK są ostateczne, w obecnej, skomplikowanej sytuacji prawnej w Polsce, przedsiębiorstwa będą szukały innych „furtek”, dlatego profesjonalna reprezentacja jest kluczowa.',
      ]],
      ['h3', 'Nie pozwól, by Twoje roszczenia się przedawniły'],
      ['p', 'Wyrok Trybunału Konstytucyjnego to potężny oręż, który wręczyliśmy właścicielom nieruchomości. Jednak, jak każda broń, wymaga umiejętnego użycia. Operatorzy sieci mają całe działy prawne, które już analizują, jak zminimalizować straty. Ty też nie powinieneś działać sam.'],
      ['p', 'Jeśli masz na działce „niechciane” urządzenia i chcesz sprawdzić, czy po tym wyroku należą Ci się pieniądze – opisz sprawę w formularzu poniżej. Bezpłatnie, w ciągu 24 h przeanalizuję Twoją sytuację i powiem Ci szczerze, czy warto walczyć o odszkodowanie.'],
    ],
  },
  {
    slug: 'zasiedzenie-sluzebnosci-drogi-po-30-latach',
    title: 'Zasiedzenie służebności drogi: czy można przejąć prawo przejazdu po 30 latach?',
    excerpt: 'Wyobraź sobie sytuację: od dekad dojeżdżasz do swojego domu tą samą, utartą ścieżką biegnącą przez działkę sąsiada. Tak robił Twój ojciec, a może i dziadek. Nikt nigdy nie protestował. Aż do dzisiaj. Nowy właściciel sąsiedniej działki stawia płot i mówi: „To mój teren, proszę tędy nie jeździć”.',
    date: '16 grudnia 2025', iso: '2025-12-16', readTime: '3 min',
    category: 'Służebności', tags: ['Zasiedzenie', 'Droga dojazdowa', 'Art. 292 KC'],
    cover: 'assets/blog-zasiedzenie-drogi.png',
    source: 'https://www.mecenasodnieruchomosci.pl/post/zasiedzenie-służebności-drogi-czy-można-przejąć-prawo-przejazdu-po-30-latach',
    related: ['droga-konieczna', 'zasiedzenie-nieruchomosci'],
    body: [
      ['lead', 'Wyobraź sobie sytuację: od dekad dojeżdżasz do swojego domu tą samą, utartą ścieżką biegnącą przez działkę sąsiada. Tak robił Twój ojciec, a może i dziadek. Nikt nigdy nie protestował. Aż do dzisiaj. Nowy właściciel sąsiedniej działki stawia płot i mówi: „To mój teren, proszę tędy nie jeździć”.'],
      ['p', 'Czy ma do tego prawo? A może Tobie przysługuje już **zasiedzenie służebności drogi**? Wiele osób myśli, że sam upływ czasu wystarczy, by „przejąć” prawo przejazdu. Jako adwokat od nieruchomości muszę ostudzić te emocje – przepisy są tutaj bardziej wymagające, niż podpowiada „chłopski rozum”.'],
      ['p', 'W dzisiejszym wpisie wyjaśnię, kiedy faktycznie dochodzi do zasiedzenia służebności i o co chodzi z tajemniczym „trwałym i widocznym urządzeniem”.'],
      ['h2', 'Czym jest zasiedzenie służebności gruntowej?'],
      ['p', 'Zasiedzenie kojarzy nam się zazwyczaj z przejęciem prawa własności całej działki (np. gdy uprawiamy kawałek ziemi sąsiada jak swój własny). Jednak **służebność gruntowa** (czyli np. prawo przechodu i przejazdu) to ograniczone prawo rzeczowe.'],
      ['p', 'Zasiedzenie takiej służebności oznacza, że po upływie określonego czasu, prawo (sąd) uznaje, iż możesz legalnie korzystać z cudzej działki w określonym zakresie, mimo że nigdy nie podpisałeś z sąsiadem aktu notarialnego.'],
      ['p', 'Podstawa prawna to **art. 292 kodeksu cywilnego**, który mówi jasno:'],
      ['quote', '„Służebność gruntowa może być nabyta przez zasiedzenie tylko w wypadku, gdy polega na korzystaniu z trwałego i widocznego urządzenia.”'],
      ['p', 'Tu dochodzimy do sedna problemu.'],
      ['h2', 'Kluczowy warunek: trwałe i widoczne urządzenie'],
      ['p', 'To właśnie na tym punkcie „wykłada się” 90% spraw sądowych o zasiedzenie drogi. Aby sąd stwierdził, że nabyłeś prawo przejazdu, nie wystarczy udowodnić, że jeździłeś tamtędy przez 30 lat. Musisz udowodnić, że korzystałeś z **trwałego i widocznego urządzenia**.'],
      ['p', '**Co to oznacza w praktyce?**'],
      ['ul', [
        '**Samo wyjeżdżenie kolein na trawie to zazwyczaj za mało.** Sądy wielokrotnie orzekały, że zwykła polna droga, powstała jedynie na skutek przejeżdżania kół, nie jest „urządzeniem”.',
        '**Urządzenie musi być efektem celowego działania człowieka.** Musi to być np. utwardzona droga (szuter, płyty betonowe, kostka brukowa), mostek, przepust czy nasyp.',
        '**Kto musiał to zbudować?** To punkt często sporny, ale linia orzecznicza Sądu Najwyższego skłania się ku temu, że urządzenie to powinno być wykonane przez **posiadacza służebności** (czyli Ciebie lub Twoich poprzedników prawnych), a nie przez właściciela gruntu, po którym jeździsz. Jeśli korzystasz z asfaltowej drogi, którą wylał sąsiad dla siebie – szanse na zasiedzenie drastycznie maleją.',
      ]],
      ['h2', 'Ile lat trzeba czekać? Dobra i zła wiara'],
      ['p', 'Jeśli spełniasz warunek „trwałego urządzenia”, pozostaje kwestia czasu. Kodeks cywilny przewiduje dwa terminy:'],
      ['ol', [
        '**20 lat** – jeśli uzyskałeś posiadanie w **dobrej wierze**. W sprawach o służebność zdarza się to niezwykle rzadko (np. gdybyś miał błędnie sporządzony akt notarialny, który dawał Ci mylne przekonanie, że masz prawo).',
        '**30 lat** – jeśli uzyskałeś posiadanie w **złej wierze**. To standardowa sytuacja: wiesz, że grunt nie jest Twój i nie masz na piśmie prawa przejazdu, ale i tak z niego korzystasz.',
      ]],
      ['p', 'Termin ten musi być **nieprzerwany**.'],
      ['h2', 'Przykład z życia wzięty'],
      ['p', 'Aby lepiej to zobrazować, posłużę się historią z mojej kancelarii (dane zmienione).'],
      ['p', 'Pan Stanisław kupił działkę w 1990 roku. Aby dojechać do domu, musiał przejeżdżać przez pas ziemi należący do sąsiada. Sąsiad ustnie pozwolił, mówiąc: „A jeździj pan, mi to nie szkodzi”. Pan Stanisław, chcąc mieć wygodnie, w 1991 roku na własny koszt zakupił i ułożył na tym pasie płyty betonowe (tzw. jumbo) oraz wykonał drenaż, aby droga nie zamakała. W 2023 roku sąsiad zmarł, a jego spadkobiercy zażądali od Pana Stanisława opłat za przejazd lub usunięcia drogi. Wynik: Pan Stanisław ma bardzo duże szanse na stwierdzenie zasiedzenia służebności w sądzie. Minęło ponad 30 lat (od 1991 r.), a on korzystał z drogi, którą sam utwardził (trwałe i widoczne urządzenie).'],
      ['p', 'Gdyby Pan Stanisław tylko jeździł po błocie przez 30 lat – sprawę by przegrał.'],
      ['h2', 'Co zrobić, gdy masz wątpliwości?'],
      ['p', 'Sprawy o zasiedzenie służebności są skomplikowane dowodowo. Sąd będzie badał mapy geodezyjne, zdjęcia lotnicze z przeszłości, przesłuchiwał świadków i oceniał, kto i kiedy utwardził drogę.'],
      ['p', 'Jeśli sąsiad grozi Ci zamknięciem przejazdu lub sam jesteś właścicielem gruntu i chcesz uregulować sytuację prawną, nie działaj pod wpływem emocji. Jeden zły ruch (np. podpisanie umowy najmu drogi) może przerwać bieg zasiedzenia i zniweczyć lata „stażu”.'],
      ['h3', 'Nie jesteś pewien, czy spełniasz warunki zasiedzenia?'],
      ['p', 'Prawo nieruchomości bywa labiryntem, ale ja pomagam znaleźć z niego wyjście. Zamiast martwić się po nocach, porozmawiajmy o faktach.'],
      ['p', 'Opisz swoją sprawę w formularzu poniżej — bezpłatna wstępna analiza w ciągu 24 h. To nic nie kosztuje i do niczego nie zobowiązuje, a w odpowiedzi:'],
      ['ul', [
        'Przeczytam Twoją historię.',
        'Wstępnie ocenię, czy w Twoim przypadku istnieją przesłanki do zasiedzenia.',
        'Podpowiem, jakie kroki warto podjąć w pierwszej kolejności.',
      ]],
    ],
  }
);
window.BLOG.sort((a, b) => (b.iso || '').localeCompare(a.iso || ''));
