/* blog-data.jsx — wpisy przeniesione 1:1 z www.mecenasodnieruchomosci.pl/blog (Wix).
   body = lista bloków: ['lead'|'p'|'h2'|'h3', tekst] | ['ul'|'ol', [pozycje]].
   W tekście **pogrubienie** renderuje się jako <strong>. Okładki pobrane z Wix do assets/. */

const BLOG = [
  {
    slug: 'warunki-zabudowy-2026-lublin',
    title: 'Warunki zabudowy 2026 w Lublinie i okolicy — czy stracisz prawo do budowy na działce?',
    excerpt: 'Od kilku miesięcy w mojej kancelarii powtarza się jedno pytanie: „Panie mecenasie, mam działkę pod Lublinem, budowę planowałem za rok, może dwa — czy zdążę?”. Niepokój jest uzasadniony. Od 1 września 2026 roku zmieniają się zasady wydawania decyzji o warunkach zabudowy i dla części działek może to oznaczać, że budowa stanie się — przynajmniej na jakiś czas — po prostu niemożliwa.',
    date: '15 czerwca 2026', iso: '2026-06-15', readTime: '6 min',
    category: 'Warunki zabudowy', tags: ['WZ', 'Plan ogólny', 'Lublin'],
    cover: 'assets/blog-wz-2026-lublin.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/warunki-zabudowy-2026-lublin',
    related: ['warunki-zabudowy', 'plan-ogolny', 'analiza-umowy-przedwstepnej'],
    body: [
      ['lead', 'Od kilku miesięcy w mojej kancelarii powtarza się jedno pytanie: „Panie mecenasie, mam działkę pod Lublinem, budowę planowałem za rok, może dwa — czy zdążę?”. Niepokój jest uzasadniony. Od 1 września 2026 roku zmieniają się zasady wydawania decyzji o warunkach zabudowy i dla części działek może to oznaczać, że budowa stanie się — przynajmniej na jakiś czas — po prostu niemożliwa.'],
      ['p', 'Najkrótsza odpowiedź jest taka: jeśli masz już prawomocną decyzję o warunkach zabudowy, możesz spać spokojnie. Jeśli jej nie masz, a Twoja działka leży poza terenem, który gmina wyznaczy pod nową zabudowę, sprawa robi się poważna. Niżej tłumaczę, o co dokładnie chodzi i co zrobić, żeby się zabezpieczyć — niezależnie od tego, czy działka jest w Lublinie, w Konopnicy, Niemcach, Głusku, czy w gminie na drugim końcu Polski.'],
      ['h2', 'Na czym polega zmiana'],
      ['p', 'Do tej pory regułą było, że dla działki bez miejscowego planu zagospodarowania przestrzennego dało się uzyskać decyzję o warunkach zabudowy (w skrócie: WZ) na zasadzie tzw. dobrego sąsiedztwa — w uproszczeniu: jeśli w pobliżu coś już stało, można było budować i u siebie. To podejście odchodzi do historii.'],
      ['p', 'Po reformie o tym, czy na działce w ogóle wolno coś postawić, przesądza nowy dokument — plan ogólny gminy. Nowe decyzje WZ będą wydawane co do zasady tylko dla działek leżących w wyznaczonym przez gminę **obszarze uzupełnienia zabudowy**, a w miastach dodatkowo w obszarach śródmiejskich. Jeżeli Twoja działka się w nim nie znajdzie, uzyskanie WZ dla nowej zabudowy przestanie być możliwe — pozostanie czekać, aż gmina uchwali dla tego terenu miejscowy plan. A na to nie masz wpływu i może to potrwać.'],
      ['p', 'Podstawą tych zmian jest ustawa z 27 marca 2003 r. o planowaniu i zagospodarowaniu przestrzennym, gruntownie znowelizowana w ramach tzw. reformy planistycznej.'],
      ['h2', 'Plan ogólny — dokument, który przejmuje stery'],
      ['p', 'Plan ogólny zastępuje znane dotąd studium uwarunkowań i kierunków zagospodarowania przestrzennego. To nie jest kosmetyka. Studium było wewnętrznym dokumentem gminy, a plan ogólny staje się aktem prawa miejscowego, czyli wiąże tak samo urząd, jak i Ciebie. Każda nowa decyzja WZ i każdy nowy plan miejscowy muszą być z nim zgodne.'],
      ['p', 'Plan dzieli całą gminę na strefy (mieszkaniowe, usługowe, rolnicze i inne), ustala dla nich parametry zabudowy — maksymalną wysokość, intensywność, procent powierzchni biologicznie czynnej — i to właśnie w nim gmina może (ale nie musi) wskazać obszary uzupełnienia zabudowy.'],
      ['h2', 'Obszar uzupełnienia zabudowy — tu jest pies pogrzebany'],
      ['p', 'To pojęcie warto zapamiętać, bo od niego zależy los inwestycji. Obszar uzupełnienia zabudowy to teren wyznaczony w planie ogólnym, przeznaczony do „dogęszczania” tego, co już istnieje.'],
      ['p', 'Problem w tym, że wyznaczenie takiego obszaru jest dla gminy dobrowolne, a zasady jego rysowania są dość rygorystyczne. W praktyce część działek, które dziś bez trudu można zabudować, po wejściu planu ogólnego tę możliwość straci — albo dlatego, że znajdą się poza obszarem uzupełnienia zabudowy, albo dlatego, że gmina takich obszarów u siebie nie wyznaczy w ogóle. To jest właśnie powód, dla którego odkładanie tematu „na potem” bywa kosztownym błędem.'],
      ['h2', 'Co z działkami pod Lublinem?'],
      ['p', 'Tu dochodzimy do sedna dla mieszkańców regionu. Gminy wokół Lublina są na bardzo różnych etapach. W powiecie lubelskim zaawansowane prace nad planem ogólnym prowadzi mniej więcej co trzecia gmina — część ma już wyłożony projekt, a kilka nie ruszyło z procedurą w ogóle. To oznacza, że sytuacja właściciela działki w Konopnicy może wyglądać zupełnie inaczej niż jego znajomego z Niemiec, Jastkowa, Wólki, Głuska czy Niedrzwicy Dużej, choć dzieli ich kilkanaście kilometrów.'],
      ['p', 'Granicą jest **31 sierpnia 2026 roku** — do tego dnia gminy powinny uchwalić plany ogólne (termin przesunięto o dwa miesiące względem pierwotnego 30 czerwca). Jeśli Twoja gmina nie zdąży, od 1 września wydawanie nowych decyzji WZ zostanie u niej wstrzymane do czasu uchwalenia planu ogólnego albo planu miejscowego. Dla kogoś, kto planował budowę domu pod Lublinem w przyszłym sezonie, to realny przestój.'],
      ['p', 'Status swojej gminy najpewniej sprawdzisz w jej Biuletynie Informacji Publicznej oraz w wydziale planowania przestrzennego. Można też podejrzeć strefy i obszary uzupełnienia zabudowy w serwisach mapowych — ale przy konkretnej parceli i tak zwykle trzeba sięgnąć po wypis z planu albo analizę pod WZ. Jeśli nie masz pewności, jak czytać te dane, to dobry moment, żeby ktoś zrobił to za Ciebie, zanim termin minie.'],
      ['h2', 'Mam już decyzję WZ — czy coś tracę?'],
      ['p', 'Nie. Decyzje o warunkach zabudowy wydane przed reformą — a jest ich w skali kraju około czterech milionów — zostają w mocy i są bezterminowe. Jako właściciel z prawomocną WZ nie musisz robić nic, żeby ją „uratować”.'],
      ['p', 'Jest jeden wyjątek, o którym warto wiedzieć: jeśli gmina uchwali dla Twojego terenu miejscowy plan zagospodarowania przestrzennego, wcześniejsza WZ przestaje obowiązywać. Plan miejscowy jest nadrzędny wobec decyzji o warunkach zabudowy.'],
      ['h2', 'Daty, które warto sobie zapisać'],
      ['ul', [
        '**1 stycznia 2026 r.** — nowe decyzje WZ przestają być bezterminowe i są ważne 5 lat od dnia, w którym staną się ostateczne. Wyjątek: bezterminowo ważne pozostają decyzje wydane z wniosków złożonych jeszcze przed 16 października 2025 r.',
        '**1 lipca 2026 r.** — wchodzi w życie większość przepisów ustawy przesuwającej terminy reformy.',
        '**31 sierpnia 2026 r.** — graniczny termin obowiązywania starych studiów; do tego dnia gminy powinny mieć uchwalone plany ogólne.',
        '**1 września 2026 r.** — nowe zasady działają w pełni. WZ tylko zgodnie z planem ogólnym i co do zasady tylko w obszarze uzupełnienia zabudowy.',
      ]],
      ['h2', 'Nowość: o warunki zabudowy poprosi tylko właściciel'],
      ['p', 'To zmiana, którą szczególnie powinni odnotować kupujący i inwestorzy. Dotąd wniosek o WZ mógł złożyć każdy — i wielu inwestorów korzystało z tego, żeby przed zakupem sprawdzić, czy na danej działce w ogóle da się budować. Po zmianach decyzję uzyska wyłącznie osoba mająca tytuł prawny do nieruchomości na cele budowlane.'],
      ['p', 'Skutek jest praktyczny i nieoczywisty: nie zbadasz już „na próbę” cudzej działki, zanim ją kupisz. Rośnie więc znaczenie dobrze napisanej umowy przedwstępnej — takiej, w której zakup uzależniasz od uzyskania korzystnej WZ. Widziałem już transakcje, w których brak takiego zastrzeżenia kończył się zakupem gruntu, na którym ostatecznie nie dało się postawić tego, co kupujący planował.'],
      ['h2', 'Co zrobić teraz — konkretnie'],
      ['p', 'Jeśli masz działkę bez planu miejscowego i bez decyzji WZ, a myślisz o budowie, warto rozważyć kilka kroków:'],
      ['ul', [
        'sprawdź stan działki — czy obejmuje ją plan miejscowy, czy obowiązuje studium i na jakim etapie jest plan ogólny w Twojej gminie;',
        'ustal, czy działka ma szansę trafić do obszaru uzupełnienia zabudowy — to przesądza o WZ po 1 września 2026 r.;',
        'jeśli masz tytuł prawny i realne plany, rozważ złożenie wniosku o WZ jeszcze przed tą datą;',
        'śledź projekt planu ogólnego i złóż uwagi, gdy jego zapisy ograniczają zabudowę Twojej działki — na etapie wyłożenia projektu wciąż można na niego wpłynąć;',
        'kupując działkę budowlaną, zabezpiecz się umownie, zamiast liczyć na to, że „jakoś się ułoży”.',
      ]],
      ['h2', 'Prowadzę te sprawy także online — w całej Polsce'],
      ['p', 'Kancelarię prowadzę w Lublinie i większość moich klientów to właściciele działek z miasta i okolicznych gmin. Ale analiza planistyczna nie wymaga już osobistej wizyty. Status działki, jej położenie względem przyszłego obszaru uzupełnienia zabudowy czy treść planu miejscowego potrafię ocenić zdalnie — na podstawie numeru ewidencyjnego działki, danych z geoportalu i dokumentów, które prześlesz. Wstępną analizę sprawy robię bezpłatnie i zdalnie, a sprawy o warunki zabudowy czy uwagi do planu ogólnego można poprowadzić korespondencyjnie niezależnie od tego, w którym województwie leży nieruchomość. Jeśli więc trafiłeś tu z Warszawy, Rzeszowa czy Trójmiasta — to też do Ciebie.'],
      ['h2', 'Najczęstsze pytania'],
      ['p', '**Czy stracę ważność decyzji WZ, którą dostałem np. w 2022 roku?** Nie. Wcześniejsze decyzje zostają w mocy i są bezterminowe. Wyjątkiem jest sytuacja, w której gmina uchwali dla tego terenu plan miejscowy — wtedy stara WZ przestaje obowiązywać.'],
      ['p', '**Co to jest obszar uzupełnienia zabudowy?** To teren wskazany w planie ogólnym gminy, przeznaczony do uzupełniania istniejącej zabudowy. Po 1 września 2026 r. nowe WZ będą wydawane co do zasady tylko w jego granicach (a w miastach także w obszarze śródmiejskim).'],
      ['p', '**Co, jeśli moja gmina pod Lublinem nie uchwali planu ogólnego na czas?** Po 1 września 2026 r. wydawanie nowych decyzji WZ zostanie u niej wstrzymane — do czasu uchwalenia planu ogólnego albo planu miejscowego dla danego terenu.'],
      ['p', '**Gdzie sprawdzę status planu ogólnego mojej gminy?** W Biuletynie Informacji Publicznej gminy oraz w wydziale planowania przestrzennego urzędu. Strefy i obszary uzupełnienia zabudowy bywają też widoczne w serwisach mapowych, ale dla konkretnej działki najlepiej potwierdzić to wypisem lub analizą.'],
      ['p', '**Czy mogę jeszcze zdążyć ze złożeniem wniosku o WZ?** Tak, jeśli masz tytuł prawny do działki. Uzyskanie decyzji przed wejściem nowych zasad zabezpiecza możliwość zabudowy na dotychczasowych regułach.'],
      ['h2', 'Sprawdźmy Twoją działkę, zanim zmienią się przepisy'],
      ['p', 'Reforma sprawia, że stan prawny i planistyczny działki trzeba dziś czytać dokładniej niż kiedykolwiek, a zwłoka potrafi kosztować utratę możliwości zabudowy. Jeśli chcesz wiedzieć, na czym stoisz, pomogę Ci przeanalizować sytuację działki, przygotować i poprowadzić wniosek o warunki zabudowy, złożyć uwagi do projektu planu ogólnego albo bezpiecznie skonstruować umowę kupna.'],
    ],
  },
  {
    slug: 'warunki-zabudowy-dla-czesci-dzialki',
    title: 'Ustalenie warunków zabudowy dla części działki – czy to w ogóle możliwe?',
    excerpt: 'Kupiłeś lub odziedziczyłeś dużą działkę. Chcesz wybudować dom, ale interesuje Cię zagospodarowanie tylko jednego, niewielkiego narożnika nieruchomości, na przykład tego z dostępem do drogi. Składasz wniosek o ustalenie warunków zabudowy (tzw. „wuzetkę”) i... zderzasz się ze ścianą. Urząd twierdzi, że musisz ustalić warunki dla całej działki. Czy urzędnicy mają rację? A może prawo zostawia nam furtkę?',
    date: '2 marca 2026', iso: '2026-03-02', updated: '9 kwietnia 2026', readTime: '3 min',
    category: 'Warunki zabudowy', tags: ['WZ', 'Orzecznictwo', 'Podział działki'],
    cover: 'assets/blog-wz-czesc-dzialki.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/ustalenie-warunków-zabudowy-dla-części-działki-czy-to-w-ogóle-możliwe',
    related: ['warunki-zabudowy'],
    body: [
      ['lead', 'Kupiłeś lub odziedziczyłeś dużą działkę. Chcesz wybudować dom, ale interesuje Cię zagospodarowanie tylko jednego, niewielkiego narożnika nieruchomości, na przykład tego z dostępem do drogi. Składasz wniosek o ustalenie warunków zabudowy (tzw. „wuzetkę”) i... zderzasz się ze ścianą. Urząd twierdzi, że musisz ustalić warunki dla całej działki. Czy urzędnicy mają rację? A może prawo zostawia nam furtkę?'],
      ['p', 'Jako adwokat często spotykam się z frustracją klientów, którzy nie rozumieją, dlaczego urząd ingeruje w ich plany inwestycyjne dotyczące ułamka ich własności. Sprawa nie jest prosta, a orzecznictwo bywa bezlitosne. Warto jednak wiedzieć, że w sądach pojawiło się „światełko w tunelu”.'],
      ['h2', 'Twarda zasada: WZ-tka dotyczy całości'],
      ['p', 'Niestety, muszę zacząć od mniej przyjemnych wiadomości. Jeśli urząd odmawia wydania decyzji dla fragmentu Twojego gruntu, opiera się na bardzo silnej linii orzeczniczej sądów administracyjnych.'],
      ['p', 'Wedle dominującego stanowiska ustalenie warunków zabudowy dotyczy działki objętej wnioskiem jako całości nie zaś tylko tej jej części, która na skutek realizacji inwestycji będzie faktycznie zabudowana lub w inny sposób zagospodarowana. Takie podejście potwierdził Naczelny Sąd Administracyjny m.in. w wyroku z dnia 10 stycznia 2008 r. (sygn. akt II OSK 1826/06). Ustalenie warunków zabudowy odnosi się do działki objętej wnioskiem jako całości - stanowisko to ma na celu zapobieganie sytuacji, w której na jednej działce geodezyjnej istniałyby nadmiernie zróżnicowane zasady zagospodarowania przestrzennego.'],
      ['p', 'Innymi słowy: dla urzędu najmniejszą jednostką, o której można rozmawiać w kontekście decyzji WZ, jest cała działka w jej granicach geodezyjnych.'],
      ['h2', 'Światełko w tunelu – wyłom w orzecznictwie!'],
      ['p', 'W prawie rzadko kiedy wszystko jest czarno-białe. W ostatnich latach można zauważyć, że w jednolitym stanowisku składów sądów administracyjnych w zakresie dopuszczalności ustalania warunków zabudowy dla części działki pojawił się wyłom.'],
      ['p', 'Przełomowe okazało się podejście Wojewódzkiego Sądu Administracyjnego w Poznaniu - Wojewódzki Sąd Administracyjny w Poznaniu dopuścił możliwość ustalenia warunków zabudowy dla części działki, uzależniając taką możliwość od konkretnego stanu faktycznego sprawy, tj. charakterystycznych parametrów konkretnej nieruchomości. Sąd ten, w wyroku z 16 września 2015 r. (sygn. akt IV SA/Po 332/15) orzekł, że charakterystyczne parametry konkretnej nieruchomości pozwalają na ustalenie warunków zabudowy dla części działki. To drugie stanowisko jest dużo bardziej elastyczne i bierze pod uwagę realny stan terenu planowanej inwestycji. Takie stanowisko zasługuje na aprobatę, ponieważ chroni inwestorów przed automatycznym wykluczeniem możliwości budowy, gdy tylko specyfika nieruchomości na to pozwala.'],
      ['p', '**Co to oznacza dla Ciebie?** Jeśli Twoja działka jest specyficzna (np. jest bardzo długa, w połowie przecięta rowem melioracyjnym, albo część stanowi nieużytek, a część świetny teren pod budowę), masz argumenty do walki z urzędem.'],
      ['h2', 'Przykład z życia wzięty'],
      ['p', 'Pan Tomasz odziedziczył 3-hektarową działkę na obrzeżach miasta. Działka to długi, wąski pas ziemi. Pan Tomasz chciał wybudować dom jednorodzinny wyłącznie na samym jej początku, przy drodze asfaltowej. Reszta miała pozostać dziką łąką. Urząd odmówił wydania WZ dla fragmentu działki. Gdy Pan Tomasz wystąpił o WZ dla całości – ponownie dostał odmowę, bo na samym końcu jego 3-hektarowego pola nie było sąsiedniej zabudowy, co złamało tzw. „zasadę dobrego sąsiedztwa”. W takiej sytuacji, powołanie się na elastyczne orzecznictwo dopuszczające WZ dla części działki mogłoby uratować plany budowlane Pana Tomasza. Alternatywą jest zawsze geodezyjny podział działki przed złożeniem wniosku – co jednak kosztuje czas i pieniądze.'],
      ['h2', 'Podsumowanie'],
      ['p', 'Walka o warunki zabudowy bywa wyczerpująca. Zasadą jest, że urząd patrzy na Twoją działkę jako całość. Prawo nie jest jednak w 100% zabetonowane i istnieją już argumenty prawne pozwalające ubiegać się o decyzję WZ tylko dla interesującego nas fragmentu gruntu. Wszystko zależy od indywidualnych cech Twojej nieruchomości.'],
      ['p', '**Utknąłeś w martwym punkcie ze swoim urzędem?** Złożenie wniosku o WZ to często gra w szachy. Zanim wydasz pieniądze na podziały geodezyjne lub zrezygnujesz z inwestycji, sprawdźmy Twoją sytuację.'],
    ],
  },
  {
    slug: 'wydruki-ksiag-wieczystych-i-alerty-krs-2026',
    title: 'Rewolucja w urzędach 2026: Wydruki Ksiąg Wieczystych z mocą urzędową i Alerty KRS w Twoim telefonie',
    excerpt: 'Koniec z wizytami w sądach i czekaniem na papierowe dokumenty z pieczątką. Ustawa z 9 stycznia 2026 r. wprowadza potężne zmiany, które odczuje każdy inwestor, przedsiębiorca i nabywca nieruchomości. Cyfryzacja przyspiesza – już niedługo samodzielnie wydrukowany odpis z Księgi Wieczystej zastąpi ten urzędowy, a o każdym nowym wpisie w KRS Twojej spółki dowiesz się ze swojej aplikacji mObywatel.',
    date: '1 marca 2026', iso: '2026-03-01', updated: '9 kwietnia 2026', readTime: '2 min',
    category: 'Księgi wieczyste', tags: ['Księgi wieczyste', 'KRS', 'mObywatel'],
    cover: 'assets/blog-kw-krs-2026.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/rewolucja-w-urzędach-2026-wydruki-ksiąg-wieczystych-z-mocą-urzędową-i-alerty-krs-w-twoim-telefonie',
    related: ['audyt-stanu-prawnego-nieruchomosci', 'obsluga-zakupu'],
    body: [
      ['lead', 'Koniec z wizytami w sądach i czekaniem na papierowe dokumenty z pieczątką. Ustawa z 9 stycznia 2026 r. wprowadza potężne zmiany, które odczuje każdy inwestor, przedsiębiorca i nabywca nieruchomości. Cyfryzacja przyspiesza – już niedługo samodzielnie wydrukowany odpis z Księgi Wieczystej zastąpi ten urzędowy, a o każdym nowym wpisie w KRS Twojej spółki dowiesz się ze swojej aplikacji mObywatel. Zobacz, jak nowe prawo ułatwi Ci życie i zabezpieczy Twoje interesy.'],
      ['h2', 'Księgi Wieczyste bez wychodzenia z domu'],
      ['p', 'Do tej pory, aby uzyskać oficjalny dokument potwierdzający stan prawny nieruchomości, wielu z nas musiało pofatygować się do sądu. Nowelizacja ustawy o księgach wieczystych i hipotece znacząco to upraszcza, zrównując moc dokumentu elektronicznego i jego wydruku z dokumentem sądowym.'],
      ['p', 'Oto najważniejsze zasady, które musisz znać:'],
      ['ul', [
        'pobrane z systemu i samodzielnie wydrukowane elektroniczne odpisy, wyciągi oraz zaświadczenia o zamknięciu ksiąg wieczystych mają moc dokumentów wydawanych przez sąd;',
        'podstawowym warunkiem jest to, aby dokument posiadał cechy umożliwiające jego weryfikację z centralną bazą danych;',
        'jeśli pobrałeś takie dokumenty jeszcze przed wejściem w życie nowych przepisów, zachowają one swoją moc urzędową, o ile da się je technicznie zweryfikować z bazą danych.',
      ]],
      ['p', 'To ogromna oszczędność czasu przed wizytą u notariusza czy podczas załatwiania kredytu hipotecznego. Pamiętaj jednak, że Ministerstwo Sprawiedliwości wyda jeszcze nowe rozporządzenia regulujące dokładne cechy tych dokumentów oraz wysokość opłat za ich pobranie.'],
      ['h2', 'Alerty z KRS prosto na Twój telefon (mObywatel)'],
      ['p', 'Drugim kluczowym elementem nowelizacji jest integracja Krajowego Rejestru Sądowego z popularną aplikacją mObywatel. To świetne narzędzie do monitorowania bezpieczeństwa własnego biznesu oraz weryfikacji kontrahentów.'],
      ['p', 'Jak to będzie działać w praktyce?'],
      ['ul', [
        'informacje o rejestracji nowej sprawy lub dokonaniu wpisu (z numerem KRS, sygnaturą i datą) będą przesyłane automatycznie na Twój telefon;',
        'aby uruchomić usługę, musisz być powiązany z danym podmiotem swoim numerem PESEL i wskazać jego numer KRS;',
        'alerty obejmują nie tylko przedsiębiorców, ale też fundacje, stowarzyszenia czy publiczne zakłady opieki zdrowotnej;',
        'możesz włączyć śledzenie dla maksymalnie 50 podmiotów bezpośrednio w aplikacji mObywatel;',
        'subskrypcja na alerty jest ważna przez rok, ale jako użytkownik masz prawo ją przedłużyć.',
      ]],
      ['h3', 'Przykład z życia wzięty: Uratowana transakcja'],
      ['p', 'Wyobraźmy sobie Pana Tomasza, inwestora, który w poniedziałek rano ma sfinalizować u notariusza bardzo opłacalny zakup działki. W piątek wieczorem przypomina sobie, że notariusz prosił o najświeższy, oficjalny odpis z Księgi Wieczystej, potwierdzający wykreślenie starej hipoteki. Sądy są już zamknięte. W starym stanie prawnym transakcja musiałaby zostać przesunięta, co groziło utratą zadatku. Dzięki nowym przepisom, Pan Tomasz po prostu loguje się do systemu, pobiera dokument, drukuje go w domu i w poniedziałek rano kładzie na biurku notariusza pełnoprawny, urzędowy odpis.'],
      ['h3', 'Kiedy zmiany wchodzą w życie?'],
      ['p', 'Ustawodawca przewidział dwa różne terminy wdrożenia nowości, co ma dać czas na techniczne przygotowanie systemów:'],
      ['ul', [
        '**31 marca 2026 r.** – wejdą w życie ułatwienia dotyczące Ksiąg Wieczystych.',
        '**31 maja 2026 r.** – zaczną działać powiadomienia KRS w aplikacji mObywatel.',
      ]],
      ['p', '**Czujesz, że przepisy dotyczące nieruchomości spędzają Ci sen z powiek?** A może planujesz skomplikowaną transakcję i chcesz mieć pewność, że Twoje interesy są w pełni zabezpieczone?'],
      ['p', 'Opisz swoją sprawę w formularzu poniżej — **bezpłatnie, w ciągu 24 h** ocenię Twoją sytuację prawną i powiem Ci, jak mogę pomóc.'],
    ],
  },
  {
    slug: 'zawyzony-podatek-od-nieruchomosci-blad-w-ewidencji',
    title: 'Zawyżony podatek od nieruchomości przez błąd w ewidencji? Zobacz, z kim tak naprawdę musisz walczyć',
    excerpt: 'Dostajesz decyzję z urzędu miasta lub gminy o wysokości podatku od nieruchomości na dany rok. Otwierasz kopertę i przecierasz oczy ze zdumienia. Kwota jest znacznie wyższa niż zazwyczaj, a w uzasadnieniu widzisz, że urząd doliczył Ci kilkadziesiąt metrów kwadratowych powierzchni użytkowej, których w rzeczywistości nie masz.',
    date: '28 lutego 2026', iso: '2026-02-28', readTime: '2 min',
    category: 'Podatek od nieruchomości', tags: ['Ewidencja gruntów', 'Podatek', 'Starosta'],
    cover: 'assets/blog-podatek-ewidencja.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/zawyżony-podatek-od-nieruchomości-przez-błąd-w-ewidencji-zobacz-z-kim-tak-naprawdę-musisz-walczyć',
    related: ['uregulowanie-stanu-prawnego'],
    body: [
      ['lead', 'Dostajesz decyzję z urzędu miasta lub gminy o wysokości podatku od nieruchomości na dany rok. Otwierasz kopertę i przecierasz oczy ze zdumienia. Kwota jest znacznie wyższa niż zazwyczaj, a w uzasadnieniu widzisz, że urząd doliczył Ci kilkadziesiąt metrów kwadratowych powierzchni użytkowej, których w rzeczywistości nie masz.'],
      ['p', 'Myślisz: „To prosty błąd, napiszę odwołanie, przyjdzie urzędnik, zmierzy i po sprawie”. Niestety, prawo podatkowe potrafi być bezlitosne, a walka z błędnym metrażem wcale nie zaczyna się w wydziale podatków. Dlaczego? Wyjaśniam poniżej.'],
      ['h2', 'Papier przyjmie wszystko, a urząd w to uwierzy'],
      ['p', 'Większość z nas zakłada, że skoro stan faktyczny (to, jak dom wygląda w rzeczywistości) różni się od stanu prawnego (tego, co jest w dokumentach), to wystarczy ten fakt udowodnić. Nic bardziej mylnego w przypadku podatków lokalnych.'],
      ['p', 'Zgodnie z polskim prawem, **ewidencja gruntów i budynków stanowi wyłączne i wiążące źródło danych dla wymiaru podatków**. Oznacza to, że dla urzędnika naliczającego opłatę liczy się tylko to, co widnieje w oficjalnym rejestrze geodezyjnym. Co więcej, organy podatkowe nie są uprawnione do samodzielnego badania zgodności tych danych ze stanem faktycznym ani do ich korygowania w toku postępowania podatkowego.'],
      ['p', 'Mówiąc po ludzku: urzędnik skarbowy nie ma prawa wziąć miarki, przyjechać do Twojego domu i stwierdzić: „Rzeczywiście, w rejestrze jest błąd, zmniejszamy podatek”. Jego ręce są związane.'],
      ['h2', 'Przykład z życia wzięty'],
      ['p', 'Wyobraź sobie sytuację, w której współwłaściciele nieruchomości otrzymują decyzję ustalającą podatek od nieruchomości na kwotę 1757 zł. Urząd wyliczył to m.in. na podstawie powierzchni działki i budynków widniejących w ewidencji. Jeden ze współwłaścicieli wnosi odwołanie, bo zauważa potężny błąd – według niego powierzchnia użytkowa budynków mieszkalnych została w papierach zawyżona o kilkaset metrów kwadratowych.'],
      ['p', 'Sprawa trafia do organu odwoławczego, a ostatecznie do Wojewódzkiego Sądu Administracyjnego. Finał? Sąd oddala skargę i przypomina twardą zasadę: podstawą opodatkowania podatkiem od nieruchomości jest stan ujawniony w rejestrach publicznych, a nie faktyczny stan nieruchomości. Co więcej, dane z ewidencji korzystają z domniemania prawdziwości do czasu ich zmiany we właściwym trybie.'],
      ['h2', 'Co z błędnymi dokumentami spadkowymi?'],
      ['p', 'Czasami zawyżony podatek to nie tylko kwestia metrów, ale tego, na kogo nałożono obowiązek zapłaty. Zdarza się, że klienci kwestionują same postanowienia o stwierdzeniu nabycia spadku. Tutaj zasada jest podobna. Prawomocne orzeczenia sądów powszechnych wiążą organy administracji publicznej i sądy administracyjne. Dopóki taki wyrok nie zostanie oficjalnie wzruszony (np. uchylony w innym trybie), musi być respektowany przy rozstrzyganiu spraw podatkowych.'],
      ['h2', 'Jak realnie rozwiązać ten problem?'],
      ['p', 'Jeśli znalazłeś się w podobnej sytuacji, pamiętaj o jednej kluczowej zasadzie: **nie walcz ze skutkiem, walcz z przyczyną**. Podważenie lub zmiana zapisów ewidencji może nastąpić wyłącznie w odrębnym postępowaniu przed właściwymi organami administracji geodezyjnej.'],
      ['ul', [
        '**Krok 1:** zamiast skupiać się wyłącznie na odwołaniach od decyzji podatkowej, musisz natychmiast zainicjować postępowanie o aktualizację operatu ewidencji gruntów i budynków u Starosty.',
        '**Krok 2:** dopiero po wyprostowaniu dokumentów geodezyjnych możesz skutecznie domagać się zmiany decyzji podatkowej, a nawet zwrotu nadpłaty.',
      ]],
      ['p', 'Szanse na wygraną są duże, o ile wiesz, do których drzwi zapukać. Jeśli uderzasz do złego urzędu, stracisz tylko czas i nerwy, a na końcu i tak zapłacisz zawyżony podatek.'],
    ],
  },
  {
    slug: 'przebudowa-czy-nowy-zjazd-nsa',
    title: 'Przebudowa czy nowy zjazd? NSA o granicach kompetencji zarządcy drogi',
    excerpt: 'Planujesz budowę pawilonu handlowego lub biurowca na działce, która od lat ma swój zjazd z drogi publicznej. Chcesz go jedynie odświeżyć i dostosować do obecnych standardów, ale w odpowiedzi od zarządcy drogi słyszysz, że zjazdu w ogóle nie powinno tam być, bo jest za blisko skrzyżowania. Brzmi znajomo? To częsta pułapka urzędnicza, w której organy mylą lokalizację nowego zjazdu z przebudową już istniejącego.',
    date: '27 lutego 2026', iso: '2026-02-27', readTime: '2 min',
    category: 'Proces budowlany', tags: ['Zjazd z drogi', 'NSA', 'Zarządca drogi'],
    cover: 'assets/blog-zjazd-nsa.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/przebudowa-czy-nowy-zjazd-nsa-o-granicach-kompetencji-zarządcy-drogi',
    related: ['pozwolenie-na-budowe', 'nadzor-budowlany-pinb'],
    body: [
      ['h2', 'Masz już zjazd, ale zarządca drogi mówi „nie” jego modernizacji?'],
      ['lead', 'Planujesz budowę pawilonu handlowego lub biurowca na działce, która od lat ma swój zjazd z drogi publicznej. Chcesz go jedynie odświeżyć i dostosować do obecnych standardów, ale w odpowiedzi od zarządcy drogi słyszysz, że zjazdu w ogóle nie powinno tam być, bo jest za blisko skrzyżowania. Brzmi znajomo? To częsta pułapka urzędnicza, w której organy mylą lokalizację nowego zjazdu z przebudową już istniejącego. Najnowszy wyrok Naczelnego Sądu Administracyjnego rzuca nowe światło na tę kwestię, stając po stronie inwestorów i właścicieli nieruchomości.'],
      ['h2', 'Dwa różne światy, czyli lokalizacja a przebudowa'],
      ['p', 'Zgodnie z ustawą o drogach publicznych, mamy do czynienia z dwoma odrębnymi procedurami. Zezwolenie na lokalizację zjazdu dotyczy sytuacji, gdy zjazdu fizycznie nie ma i organ ocenia możliwość włączenia ruchu drogowego spowodowanego nową inwestycją. Z kolei zezwolenie na przebudowę zjazdu dotyczy modernizacji zjazdu, który już istnieje i funkcjonuje w przestrzeni. To rozróżnienie jest kluczowe, ponieważ przy przebudowie zarządca drogi nie może oceniać, czy zjazd w ogóle powinien w danym miejscu istnieć. Ta kwestia została rozstrzygnięta w przeszłości, gdy zjazd powstawał zgodnie z prawem.'],
      ['h2', 'Granice kompetencji zarządcy drogi'],
      ['p', 'Zarządca drogi ma prawo odmówić zgody na przebudowę tylko w ściśle określonych przypadkach prawnych:'],
      ['ul', [
        'gdy planowane prace spowodują, że legalny dotychczas zjazd przestanie odpowiadać wymogom przepisów prawa;',
        'jeśli nowe parametry zjazdu będą generować którąś z prawnych przeszkód przebudowy;',
        'kiedy poziom bezpiecznego korzystania z niego spadnie poniżej dolnego ekstremum akceptowanego przez regulacje.',
      ]],
      ['p', 'Jeśli twoim celem jest na przykład dostosowanie parametrów do nowoczesnych wymogów prawa, to twoje działanie z definicji zmierza do poprawy bezpieczeństwa. Zasada praworządności zakłada, że istniejący, legalny zjazd jest bezpieczny. Organ powinien zatem badać tylko nowe parametry zjazdu, a nie negować sam fakt jego istnienia w danej lokalizacji. Choć decyzja zarządcy ma charakter uznaniowy, nie oznacza to, że urzędnik może zdecydować o wszystkim dowolnie, gdyż musi opierać się na wyczerpująco przedstawionych realiach i zagrożeniach, które wywołałaby sama przebudowa.'],
      ['h2', 'Przykład z życia pana Marka'],
      ['p', 'Pan Marek kupił działkę z dawnym budynkiem biurowym, do którego prowadził żwirowy zjazd z drogi krajowej, legalnie wzniesiony przed 1985 rokiem. Chciał wybudować tam mały market i złożył wniosek o przebudowę zjazdu, deklarując wolę dostosowania jego parametrów do współczesnych wymogów. Zarządca drogi odmówił, twierdząc, że zjazd jest zbyt blisko przejścia dla pieszych i skrzyżowania, co wygeneruje dodatkowy punkt kolizyjny. Finał w sądzie administracyjnym pokazał jednak, że skoro zjazd już istnieje i ma status zjazdu publicznego, zarządca nie może go traktować jak inwestycji nowo lokowanej. Pan Marek nie chciał tworzyć nowego punktu dostępu, lecz naprawić stary, co w rezultacie miało korzystnie wpłynąć na bezpieczeństwo uczestników ruchu.'],
      ['h2', 'Zadbaj o profesjonalną analizę swojej sytuacji'],
      ['p', 'Nie pozwól, by błędna urzędnicza interpretacja przepisów zablokowała twoją inwestycję. Jeśli twój wniosek o przebudowę zjazdu został odrzucony argumentami dotyczącymi złej lokalizacji, istnieje bardzo duże prawdopodobieństwo, że decyzja ta narusza prawo i można ją skutecznie podważyć. Zarządca drogi nie może arbitralnie zakazać prac modernizacyjnych przy funkcjonującym zjeździe publicznym, omijając rzetelną ocenę projektowanych zmian.'],
    ],
  },
  {
    slug: 'warunki-zabudowy-a-plan-ogolny-przepisy-przejsciowe',
    title: 'Na jakiej podstawie należy wydać warunki zabudowy, jeśli w trakcie postępowania wejdzie w życie plan ogólny?',
    excerpt: 'Reforma planowania przestrzennego wprowadziła sporo zamieszania w kalendarzach inwestorów. Wielu moich klientów pyta z niepokojem: „Panie Mecenasie, co jeśli złożę wniosek o WZ, a gmina w międzyczasie uchwali plan ogólny? Czy moje starania pójdą na marne?”. Odpowiedź jest optymistyczna, ale diabeł tkwi w szczegółach.',
    date: '30 stycznia 2026', iso: '2026-01-30', readTime: '2 min',
    category: 'Planowanie przestrzenne', tags: ['WZ', 'Plan ogólny', 'Przepisy przejściowe'],
    cover: 'assets/blog-wz-plan-ogolny.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/na-jakiej-podstawie-należy-wydać-warunki-zabudowy-jeśli-w-trakcie-postępowania-wejdzie-w-życie-plan',
    related: ['warunki-zabudowy', 'plan-ogolny'],
    body: [
      ['lead', 'Reforma planowania przestrzennego wprowadziła sporo zamieszania w kalendarzach inwestorów. Wielu moich klientów pyta z niepokojem: „Panie Mecenasie, co jeśli złożę wniosek o WZ, a gmina w międzyczasie uchwali plan ogólny? Czy moje starania pójdą na marne?”. Odpowiedź jest optymistyczna, ale diabeł tkwi w szczegółach.'],
      ['h2', 'Kluczowy moment: Data złożenia wniosku'],
      ['p', 'W prawie administracyjnym często obowiązuje zasada, że „prawo nie działa wstecz”, ale w urbanistyce kluczowe są tzw. **przepisy przejściowe**. To one decydują, czy Twój wniosek będzie rozpatrywany na starych, łagodniejszych zasadach, czy na nowych, często surowszych warunkach wynikających z planu ogólnego.'],
      ['p', 'Zgodnie z aktualnym stanem prawnym na styczeń 2026 r., najważniejszą datą jest moment wszczęcia postępowania.'],
      ['h3', 'Zasada kontynuacji (Art. 59 ust. 2 ustawy nowelizującej)'],
      ['p', 'Jeśli złożyłeś wniosek o wydanie decyzji o warunkach zabudowy (WZ) **przed dniem wejścia w życie planu ogólnego** (i przed 1 lipca 2026 r.), to Twoja sprawa powinna być prowadzona na „starych” zasadach.'],
      ['p', 'Oznacza to, że:'],
      ['ul', [
        '**plan ogólny nie jest podstawą Twojej decyzji**, nawet jeśli zaczął już obowiązywać w trakcie trwania procedury;',
        'urząd **nie może** odrzucić Twojego wniosku tylko dlatego, że teren nie znajduje się w „obszarze uzupełnienia zabudowy” wyznaczonym w nowym planie;',
        'stosuje się przepisy w brzmieniu dotychczasowym, co chroni interesy inwestora, który zapoczątkował proces wcześniej.',
      ]],
      ['h2', 'Co to oznacza w praktyce?'],
      ['p', 'Wiele osób obawia się, że wejście w życie planu ogólnego „kasuje” dotychczasowe starania. Nic bardziej mylnego. Ustawa o zmianie ustawy o planowaniu i zagospodarowaniu przestrzennym (u.z.u.p.z.p.) w art. 59 ust. 2 jasno wskazuje, że dla spraw wszczętych przed utratą mocy dotychczasowych studiów uwarunkowań, stosujemy reguły gry obowiązujące w dniu złożenia wniosku.'],
      ['p', 'Studia te zachowują moc do czasu uchwalenia planu ogólnego, ale nie dłużej niż do **30 czerwca 2026 roku**.'],
      ['h3', 'Przykład z życia wzięty'],
      ['p', 'Wyobraźmy sobie pana Marka, który 20 marca 2026 r. złożył wniosek o warunki zabudowy dla domu jednorodzinnego. Trzy dni później, 23 marca, w jego gminie wszedł w życie nowoczesny plan ogólny, który w miejscu jego działki przewiduje jedynie tereny zielone.'],
      ['p', 'Czy pan Marek stracił szansę na budowę? **Nie.** Ponieważ wszczął postępowanie przed wejściem w życie planu, organ musi rozpatrzyć jego wniosek bez uwzględniania ograniczeń wynikających z tego planu.'],
      ['h2', 'Na co musisz uważać?'],
      ['p', 'Choć przepisy chronią „stare” wnioski, musisz pamiętać o dwóch kwestiach:'],
      ['ol', [
        '**termin 30 czerwca 2026 r.:** to graniczna data, po której stare studia uwarunkowań definitywnie tracą moc.',
        '**precyzja wniosku:** błędy formalne mogą spowodować, że wniosek zostanie uznany za złożony skutecznie dopiero po uzupełnieniu braków – co może przesunąć datę wszczęcia na moment, w którym plan ogólny już obowiązuje.',
      ]],
      ['h3', 'Potrzebujesz pewności? Skonsultuj swój wniosek!'],
      ['p', 'Procesy inwestycyjne bywają stresujące, zwłaszcza gdy przepisy zmieniają się z miesiąca na miesiąc. Nie musisz zgadywać, czy Twój wniosek jest bezpieczny.'],
      ['p', 'Opisz swoją sprawę w formularzu poniżej — **bezpłatna wstępna analiza w ciągu 24 h**, bez zobowiązań. Przeanalizuję Twoją sytuację i podpowiem, czy Twój projekt jest chroniony przez przepisy przejściowe.'],
    ],
  },
];

Object.assign(window, { BLOG });
