/* blog-data-5.jsx — wpisy przeniesione z Wix, partia 5 (I 2026: służebności, drogi konieczne). Dołącza do window.BLOG. */
window.BLOG.push(
  {
    slug: 'wycena-sluzebnosci-przesylu-rzeczoznawca',
    title: 'Wycena służebności przesyłu – jak robi to rzeczoznawca majątkowy?',
    excerpt: 'Dostałeś pismo od zakładu energetycznego lub gazowniczego z propozycją zapłaty za ustanowienie służebności przesyłu? Kluczowe pytanie brzmi: „ILE?”. Wyjaśniam, jak rzeczoznawcy majątkowi wyliczają te kwoty i dlaczego pierwsza propozycja od przedsiębiorcy to zazwyczaj tylko ułamek tego, co Ci się należy.',
    date: '12 stycznia 2026', iso: '2026-01-12', readTime: '3 min',
    category: 'Służebność przesyłu', tags: ['Operat szacunkowy', 'Współczynnik K', 'Rzeczoznawca'],
    cover: 'assets/blog-wycena-przesyl.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/wycena-służebności-przesyłu-jak-robi-to-rzeczoznawca-majątkowy',
    related: ['odszkodowanie-sluzebnosc-przesylu', 'bezumowne-korzystanie'],
    body: [
      ['lead', 'Dostałeś pismo od zakładu energetycznego lub gazowniczego z propozycją zapłaty za ustanowienie służebności przesyłu? A może planujesz dochodzić odszkodowania za „rurę”, która od lat blokuje Twoje plany budowlane? W obu przypadkach kluczowe pytanie brzmi: „ILE?”. Dziś wyjaśnię Ci, jak rzeczoznawcy majątkowi wyliczają te kwoty i dlaczego pierwsza propozycja od przedsiębiorcy to zazwyczaj tylko ułamek tego, co Ci się należy.'],
      ['p', 'Jako adwokat zajmujący się prawem nieruchomości często słyszę od Klientów, że operaty szacunkowe przypominają czarną magię. Wzory, współczynniki, strefy... Czy da się to zrozumieć bez doktoratu z matematyki? Tak. I warto to zrobić, zanim cokolwiek podpiszesz.'],
      ['h2', 'Służebność przesyłu – za co właściwie płacą?'],
      ['p', 'Zanim przejdziemy do cyfr, musimy ustalić jedną rzecz. Kiedy przedsiębiorstwo przesyłowe chce korzystać z Twojej ziemi (postawić słup, zakopać kabel), ogranicza Twoje prawo własności. Zgodnie z **Kodeksem cywilnym**, za to ograniczenie należy Ci się **odpowiednie wynagrodzenie**.'],
      ['p', 'Pamiętaj: to nie jest cena sprzedaży działki. To zapłata za to, że:'],
      ['ol', [
        'Musisz znosić obecność urządzeń na swoim terenie.',
        'Pracownicy firmy mogą wchodzić na Twój teren w celu napraw i konserwacji.',
        'Nie możesz swobodnie zabudować części swojej działki (strefa ochronna).',
      ]],
      ['h2', 'Rzeczoznawca majątkowy – jedyny, który może wycenić szkodę'],
      ['p', 'Jako adwokat mogę wywalczyć dla Ciebie prawo do zapłaty, ocenić czy umowa jest bezpieczna i reprezentować Cię w sądzie. Jednak ani ja, ani sędzia nie możemy sami ustalić kwoty.'],
      ['p', 'Do tego potrzebny jest **rzeczoznawca majątkowy**, który sporządza dokument zwany **operatem szacunkowym**. To na jego podstawie sądy orzekają wysokość wynagrodzenia.'],
      ['h2', 'Jak wygląda wzór na wycenę? (uproszczony schemat)'],
      ['p', 'Choć każda sprawa jest inna, rzeczoznawcy najczęściej posługują się pewnym ogólnym schematem wyliczeń. Żebyś wiedział, na co patrzeć w dokumentach, rozbijmy to na czynniki pierwsze. Wycena służebności zależy głównie od trzech elementów:'],
      ['h3', '1. Powierzchnia pasa służebności'],
      ['p', 'To nie jest tylko powierzchnia, którą zajmuje sam słup czy rura. To cały pas terenu niezbędny do obsługi urządzenia oraz strefa, w której nie możesz się budować.'],
      ['ul', ['**Problem:** Przedsiębiorstwa często zaniżają tę powierzchnię, przyjmując tylko obrys urządzenia. Walczymy o to, by pas obejmował całą strefę ochronną.']],
      ['h3', '2. Wartość rynkowa 1 m² Twojego gruntu'],
      ['p', 'Rzeczoznawca sprawdza, po ile sprzedają się podobne działki w Twojej okolicy.'],
      ['ul', ['**Ważne:** Jeśli Twoja działka jest budowlana, stawka będzie wysoka. Jeśli w ewidencji widnieje jako rola – stawka będzie drastycznie niższa.']],
      ['h3', '3. Współczynnik współkorzystania (tzw. współczynnik K)'],
      ['p', 'To najbardziej kontrowersyjny element. Określa on, w jakim stopniu Ty (właściciel) i przedsiębiorstwo przesyłowe dzielicie się korzystaniem z tego pasa gruntu.'],
      ['ul', [
        'Jeśli rura biegnie głęboko pod ziemią i możesz na niej posadzić trawę – współczynnik będzie niższy (np. 0,3).',
        'Jeśli stoi tam wielki słup wysokiego napięcia, pod którym nic nie zrobisz – współczynnik powinien dążyć do 1,0 (czyli tak, jakbyś ten kawałek ziemi sprzedał).',
      ]],
      ['quote', 'Równanie w uproszczeniu: Wynagrodzenie = powierzchnia pasa × wartość 1 m² gruntu × współczynnik „K”'],
      ['h2', 'Dodatkowy element: obniżenie wartości całej nieruchomości'],
      ['p', 'To nie wszystko. Czasem samo istnienie urządzenia sprawia, że **cała Twoja działka traci na wartości**.'],
      ['p', 'Wyobraź sobie piękną działkę pod miastem. Przez jej środek puszczono linię wysokiego napięcia. Nawet jeśli linia zajmuje wąski pas, to nikt nie chce kupić takiej działki pod budowę domu, bo „szpeci widok” i ludzie boją się pola magnetycznego. Rzeczoznawca powinien uwzględnić tę utratę wartości rynkowej w wycenie!'],
      ['h2', 'Przykład z życia wzięty: sprawa Pani Janiny'],
      ['p', 'Pani Janina odziedziczyła działkę budowlaną pod Wrocławiem. Przez róg działki przebiega gazociąg. Firma gazownicza zaproponowała jej jednorazowo **2 500 zł** za ustanowienie służebności.'],
      ['p', 'Pani Janina przyszła do mnie z pytaniem, czy to dobra oferta. Sprawdziliśmy dokumenty. Okazało się, że strefa kontrolowana gazociągu wyłącza z zabudowy aż 400 m² jej działki (w najlepszym miejscu, od frontu). Powołaliśmy niezależnego rzeczoznawcę. Co się okazało?'],
      ['ol', [
        'Wartość gruntu w tej okolicy wzrosła.',
        'Współczynnik współkorzystania był znacznie wyższy, bo gazociąg uniemożliwiał zrobienie wjazdu na posesję w planowanym miejscu.',
        'Doliczyliśmy odszkodowanie za obniżenie wartości reszty działki.',
      ]],
      ['p', '**Efekt?** Realna wartość służebności i odszkodowania wyniosła **28 000 zł**. To ponad 10 razy więcej niż pierwsza propozycja!'],
      ['h2', 'Dlaczego nie warto wierzyć na słowo wycenie od przedsiębiorstwa?'],
      ['p', 'Operaty szacunkowe zlecane przez przedsiębiorstwa przesyłowe są często robione masowo i... „oszczędnie”. Rzeczoznawca działający na zlecenie giganta energetycznego może (świadomie lub nie) przyjmować najniższe możliwe współczynniki. Dlatego w sprawach sądowych zawsze walczymy o powołanie **biegłego sądowego**, który jest bezstronny.'],
      ['h3', 'Nie podpisuj ugody w ciemno – skonsultuj to'],
      ['p', 'Sprawy o służebność przesyłu to gra na liczbach i przepisach. Błąd na etapie negocjacji może kosztować Cię dziesiątki tysięcy złotych, których już nie odzyskasz, bo służebność ustanawia się zazwyczaj „na zawsze”.'],
      ['p', 'Jeśli otrzymałeś wycenę lub propozycję umowy i czujesz, że kwota jest zaniżona – nie zgaduj. **Prześlij ją w formularzu poniżej — bezpłatna wstępna analiza w ciągu 24 h.** W odpowiedzi:'],
      ['ul', [
        'spojrzę na Twoją sytuację okiem praktyka;',
        'ocenię, czy propozycja przedsiębiorstwa mieści się w rynkowych standardach;',
        'powiem Ci, czy warto walczyć o wyższą kwotę.',
      ]],
    ],
  },
  {
    slug: 'zniesienie-sluzebnosci-przesylu-nieistniejaca-linia',
    title: 'Czy można znieść służebność przesyłu, jeśli linia już nie istnieje?',
    excerpt: 'Przeglądasz księgę wieczystą i w dziale III widzisz wpis: służebność przesyłu na rzecz zakładu energetycznego. Problem w tym, że na działce nic nie ma — stare słupy zniknęły dekadę temu, a rury dawno wykopano. Czy taki „wirtualny” wpis jest groźny? Czy można się go pozbyć?',
    date: '13 stycznia 2026', iso: '2026-01-13', readTime: '3 min',
    category: 'Księgi wieczyste', tags: ['Wykreślenie służebności', 'Art. 293 KC', 'Dział III KW'],
    cover: 'assets/blog-zniesienie-sluzebnosci.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/zniesienie-sluzebnosci-nieistniejaca-linia',
    related: ['uregulowanie-stanu-prawnego', 'audyt-stanu-prawnego-nieruchomosci'],
    body: [
      ['lead', 'Wyobraź sobie taką sytuację: przeglądasz Księgę Wieczystą swojej nieruchomości i w dziale III widzisz wpis. Służebność przesyłu na rzecz zakładu energetycznego lub gazowni. Problem w tym, że patrzysz za okno na swoją działkę i... nic tam nie ma. Stare słupy zniknęły dekadę temu, a rury dawno wykopano.'],
      ['p', 'Czy taki „wirtualny” wpis jest groźny? Czy można się go pozbyć? A może on wygasa samoczynnie? W dzisiejszym wpisie wyjaśnię, jak posprzątać w dokumentach, gdy infrastruktura fizycznie przestała istnieć.'],
      ['h2', 'Fizycznie czysto, a w papierach bałagan'],
      ['p', 'To jeden z częstszych problemów, z jakimi trafiają do mnie klienci chcący sprzedać działkę lub rozpocząć budowę domu. Warto wiedzieć, że **fizyczne usunięcie urządzeń (słupów, rur) nie powoduje automatycznego zniknięcia wpisu z Księgi Wieczystej.**'],
      ['p', 'Sąd wieczystoksięgowy nie prowadzi wizji lokalnych. Sędzia nie wie, że zakład energetyczny zdemontował linię. Dopóki nie złożysz odpowiedniego wniosku popartego dokumentami, obciążenie będzie wisieć w Twojej KW w nieskończoność. Dlaczego to problem?'],
      ['ul', [
        'Obniża to wartość nieruchomości w oczach potencjalnego kupca.',
        'Banki mogą kręcić nosem przy udzielaniu kredytu hipotecznego.',
        'Teoretycznie przedsiębiorstwo przesyłowe wciąż ma prawo wstępu na Twój grunt (skoro służebność istnieje w dokumentach).',
      ]],
      ['h2', 'Kiedy służebność można wykreślić? Dwie główne ścieżki'],
      ['p', 'Jako właściciel nieruchomości masz w ręku silne argumenty prawne. Kodeks cywilny przewiduje sytuacje, w których służebność przestaje być potrzebna lub wygasa.'],
      ['h3', '1. Wygaśnięcie przez niewykonywanie (art. 293 k.c.)'],
      ['p', 'To najmocniejszy argument, jeśli linia zniknęła dawno temu. Zgodnie z prawem, służebność przesyłu wygasa, jeżeli nie jest wykonywana przez **lat 10**.'],
      ['p', 'Co to oznacza w praktyce? Jeśli przedsiębiorstwo usunęło rurę w 2010 roku i od tego czasu nie korzysta z Twojego gruntu, służebność wygasła z mocy prawa w 2020 roku. Twoim zadaniem jest jedynie (i aż) potwierdzenie tego faktu dokumentem, który pozwoli wykreślić wpis z KW.'],
      ['h3', '2. Zniesienie służebności z powodu utraty znaczenia (art. 295 k.c.)'],
      ['p', 'Jeśli okres 10 lat jeszcze nie minął, ale urządzenia zostały trwale usunięte i przedsiębiorstwo nie planuje ich odtwarzać, służebność utraciła dla nich wszelkie znaczenie gospodarcze. W takiej sytuacji możesz żądać zniesienia służebności **bez wynagrodzenia**. Nie ma rury = nie ma potrzeby obciążania Twojej działki.'],
      ['h2', 'Jak wykreślić „ducha” z Księgi Wieczystej? Krok po kroku'],
      ['p', 'Wielu moich klientów obawia się, że od razu muszą iść do sądu. Na szczęście często udaje się to załatwić polubownie, choć wymaga to cierpliwości i odpowiedniej taktyki.'],
      ['ol', [
        '**Wezwanie do przedsiębiorstwa.** Wysyłamy pismo do gestora sieci (np. Tauron, PGE, PSG) z żądaniem wydania zgody na wykreślenie służebności w formie pisemnej z podpisem notarialnie poświadczonym. W piśmie wskazujemy, że urządzenia nie istnieją.',
        '**Reakcja przedsiębiorstwa.** Duże firmy często mają bałagan w dokumentacji. Może się okazać, że oni sami nie wiedzą, że tej linii już u Ciebie nie ma. Jeśli przyznają nam rację – udajemy się do notariusza po stosowny dokument (zgodę).',
        '**Droga sądowa (jeśli odmówią).** Jeśli przedsiębiorstwo milczy lub twierdzi, że „może kiedyś coś tam zbudujemy”, musimy złożyć pozew o stwierdzenie wygaśnięcia służebności lub o jej zniesienie. W przypadku braku infrastruktury, sądy zazwyczaj stają po stronie właścicieli gruntów.',
      ]],
      ['h2', 'Historia z życia wzięta: przypadek Pana Tomasza'],
      ['p', 'Pan Tomasz odziedziczył działkę pod miastem. W latach 90. biegła przez nią napowietrzna linia telefoniczna. Słupy usunięto w 2005 roku, kiedy wieś skanalizowano teletechnicznie (kable w ziemi, ale w drodze gminnej, nie na działce Pana Tomasza).'],
      ['p', 'W 2024 roku Pan Tomasz znalazł kupca na działkę. Kupiec, po sprawdzeniu KW, wycofał się, bojąc się wpisu o służebności. Pan Tomasz myślał, że sprawa jest przegrana.'],
      ['p', 'Skontaktowaliśmy się z operatorem telekomunikacyjnym. Okazało się, że w ich mapach linia widniała jako „nieczynna/zlikwidowana”. Po wymianie dwóch pism oficjalnych i wskazaniu, że służebność wygasła przez niewykonywanie (minęło ponad 10 lat), operator wydał zgodę na wykreślenie wpisu. Koszt? Opłata notarialna i opłata sądowa za wniosek w KW. Zysk? Działka sprzedana po cenie rynkowej, bez „skazy” prawnej.'],
      ['h2', 'Nie czekaj, aż kupiec ucieknie'],
      ['p', 'Masz w Księdze Wieczystej wpisy, które nie mają pokrycia w rzeczywistości? Nieistniejące rury, kable czy słupy to problem, który da się rozwiązać, ale wymaga to podjęcia konkretnych działań prawnych. Sam wpis nie zniknie.'],
      ['p', 'Jeśli nie wiesz, czy w Twoim przypadku doszło do wygaśnięcia służebności, lub przedsiębiorstwo przesyłowe odmawia współpracy — **podaj numer księgi wieczystej w formularzu poniżej. Bezpłatnie, w ciągu 24 h:**'],
      ['ul', [
        'spojrzę na Twoją Księgę Wieczystą;',
        'ocenię szanse na szybkie wykreślenie wpisu;',
        'podpowiem, od czego zacząć rozmowy z przedsiębiorstwem.',
      ]],
      ['p', 'Nie pozwól, aby stare papiery blokowały Twoje plany inwestycyjne.'],
    ],
  },
  {
    slug: 'wynagrodzenie-za-sluzebnosc-drogi-koniecznej',
    title: 'Jak obliczyć wynagrodzenie za służebność drogi koniecznej?',
    excerpt: 'Brak dostępu do drogi publicznej to dla właściciela działki prawdziwy dramat. Rozwiązaniem jest ustanowienie służebności drogi koniecznej. Ale tu pojawia się pytanie, które słyszę niemal codziennie: „Ile to będzie kosztować?” lub „Ile mogę zażądać od sąsiada?”.',
    date: '14 stycznia 2026', iso: '2026-01-14', readTime: '3 min',
    category: 'Służebności', tags: ['Droga konieczna', 'Wynagrodzenie', 'Art. 145 KC'],
    cover: 'assets/blog-wynagrodzenie-droga-konieczna.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/wynagrodzenie-za-sluzebnosc-drogi-koniecznej',
    related: ['droga-konieczna'],
    body: [
      ['lead', 'Brak dostępu do drogi publicznej to dla właściciela działki prawdziwy dramat. Budowa domu, sprzedaż gruntu, czy nawet zwykły dojazd na posesję stają się niemożliwe. Rozwiązaniem jest ustanowienie służebności drogi koniecznej. Ale tu pojawia się kluczowe pytanie, które słyszę w mojej kancelarii niemal codziennie: „Mecenasie, ile to będzie kosztować?” lub „Ile mogę zażądać od sąsiada?”.'],
      ['p', 'Dzisiaj wyjaśnię Ci, jak w praktyce wygląda wyliczanie wynagrodzenia za służebność i co wpływa na ostateczną kwotę.'],
      ['h2', 'Wynagrodzenie, a nie odszkodowanie – co mówią przepisy?'],
      ['p', 'Zacznijmy od podstawy prawnej, ale obiecuję – przełożymy to na ludzki język. Zgodnie z **art. 145 § 1 Kodeksu cywilnego**, jeżeli nieruchomość nie ma odpowiedniego dostępu do drogi publicznej, właściciel może żądać od właścicieli gruntów sąsiednich ustanowienia potrzebnej służebności drogowej. Przepis dodaje jednak kluczowy warunek: następuje to **za wynagrodzeniem**.'],
      ['p', 'Warto zwrócić uwagę na słowo „wynagrodzenie”. W prawie cywilnym to pojęcie szersze niż „odszkodowanie”.'],
      ['ul', [
        '**Odszkodowanie** naprawia szkodę (stratę).',
        '**Wynagrodzenie** jest ekwiwalentem za korzyść, jaką uzyskuje sąsiad, korzystając z Twojej ziemi, oraz rekompensatą za to, że Ty musisz znosić jego przejazdy.',
      ]],
      ['quote', 'Ważne: Służebność drogi koniecznej prawie nigdy nie jest darmowa. Nawet jeśli droga już fizycznie istnieje („wyjeżdżony szlak”), właścicielowi gruntu należy się zapłata za jego sformalizowanie prawne.'],
      ['h2', 'Jak ustala się wysokość wynagrodzenia?'],
      ['p', 'Polskie prawo nie podaje gotowego wzoru matematycznego, do którego podstawiamy metry kwadratowe i wychodzi wynik. W sprawach, w których doradzam, ostateczna kwota zależy od kilku czynników.'],
      ['h3', '1. Wartość rynkowa zajętego gruntu'],
      ['p', 'To baza wyliczeń. Jeśli pod drogę musisz oddać pas ziemi o powierzchni 100 m², biegły rzeczoznawca sprawdzi, ile warta jest ziemia w Twojej okolicy. Nie oczekuj jednak, że dostaniesz 100% wartości rynkowej tej części działki – w końcu nadal pozostajesz jej właścicielem, choć Twoje prawa są ograniczone.'],
      ['h3', '2. Utrata wartości „reszty” działki (nieruchomości obciążonej)'],
      ['p', 'To często najważniejszy argument w walce o wyższą stawkę.'],
      ['ul', [
        'Czy droga przebiega przez środek Twojego ogrodu, niszcząc go?',
        'Czy przez drogę konieczną Twoja działka staje się niesprzedawalna lub traci potencjał inwestycyjny (np. nie zmieścisz już drugiego domu)?',
        'Czy hałas i spaliny będą uciążliwe dla domowników?',
      ]],
      ['p', 'Im większa uciążliwość, tym wyższe powinno być wynagrodzenie.'],
      ['h3', '3. Jednorazowo czy okresowo?'],
      ['p', 'Wynagrodzenie może przybrać dwie formy:'],
      ['ul', [
        '**Opłata jednorazowa:** Płacisz raz i masz spokój. To najczęstsze rozwiązanie, preferowane przez sądy i strony, by nie generować konfliktów w przyszłości.',
        '**Świadczenie okresowe (renta):** Płacisz np. co miesiąc lub co rok. Stosowane rzadziej, zazwyczaj gdy strony tak się umówią.',
      ]],
      ['h2', 'Rola rzeczoznawcy majątkowego'],
      ['p', 'Jeśli nie dogadasz się z sąsiadem polubownie („przy kawie”), sprawa trafi do sądu. Sędzia nie zna się na cenach nieruchomości – on zna się na prawie. Dlatego w 99% przypadków sąd powoła **biegłego rzeczoznawcę majątkowego**.'],
      ['p', 'To biegły sporządza operat szacunkowy. Bierze pod uwagę ceny transakcyjne z okolicy, stopień ingerencji w prawo własności i lokalne uwarunkowania (tzw. „współczynnik K”).'],
      ['quote', 'Rada Mecenasa: Operat biegłego to nie pismo święte. Jako adwokat często składam zarzuty do opinii biegłych, wytykając im błędy logiczne lub przyjęcie niewłaściwych nieruchomości do porównania. To skuteczny sposób na zmianę wyceny.'],
      ['h2', 'Przykład z życia wzięty: sprawa Pana Tomasza'],
      ['p', 'Pan Tomasz ma dużą działkę, przez której skraj sąsiad chciał poprowadzić drogę do swojego nowo budowanego domu. Sąsiad proponował 2 000 zł, twierdząc, że to tylko „kawałek trawy”.'],
      ['p', 'Wycena rynkowa tego pasa gruntu wynosiła ok. 15 000 zł. Jednak podczas analizy sprawy zauważyłem, że poprowadzenie drogi w tym miejscu uniemożliwi Panu Tomaszowi rozbudowę jego warsztatu samochodowego, co było w jego planach od lat.'],
      ['p', '**Argumentacja:** Wykazaliśmy przed sądem, że ustanowienie służebności drastycznie obniża funkcjonalność całej nieruchomości Pana Tomasza, a nie tylko zajętego pasa.'],
      ['p', '**Finał:** Sąd zasądził wynagrodzenie jednorazowe w wysokości **45 000 zł**, uwzględniając tzw. szkodę lokalizacyjną i spadek wartości całej nieruchomości.'],
      ['h2', 'Podsumowanie: ile to kosztuje?'],
      ['p', 'Nie ma jednej kwoty. Może to być 5 000 zł, a może być 150 000 zł – wszystko zależy od specyfiki terenu. Pamiętaj jednak o złotej zasadzie: **najtańsza droga to ta ustalona u notariusza, a nie w sądzie.** Proces sądowy generuje koszty opinii biegłych (często kilka tysięcy złotych), które na koniec i tak ktoś musi pokryć.'],
      ['h3', 'Nie wiesz, czy propozycja sąsiada jest uczciwa?'],
      ['p', 'Sprawy o służebność potrafią skłócić rodziny na pokolenia. Nie warto działać pod wpływem emocji. Zanim zgodzisz się na kwotę lub pójdziesz z pozwem do sądu, **opisz sytuację w formularzu poniżej — bezpłatna wstępna analiza w ciągu 24 h**. W odpowiedzi:'],
      ['ul', [
        'spojrzę na mapę Twojej działki;',
        'ocenię szanse na ustanowienie drogi (lub obronę przed nią);',
        'podpowiem, jakie kroki prawne podjąć w pierwszej kolejności.',
      ]],
    ],
  },
  {
    slug: 'szerokosc-drogi-koniecznej',
    title: 'Szerokość drogi koniecznej – ile metrów musi mieć dojazd do domu?',
    excerpt: 'Dostęp do drogi publicznej to podstawa – bez niego działka jest w świetle prawa budowlanego praktycznie bezużyteczna. Ale co, gdy dostęp niby jest, ale tak wąski, że ledwo mieści się samochód? Albo gdy sąsiad zgadza się na służebność, ale chce wydzielić tylko 2,5 metra?',
    date: '15 stycznia 2026', iso: '2026-01-15', readTime: '3 min',
    category: 'Służebności', tags: ['Droga konieczna', 'Droga pożarowa', 'Pozwolenie na budowę'],
    cover: 'assets/blog-szerokosc-drogi.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/szerokosc-drogi-koniecznej',
    related: ['droga-konieczna', 'pozwolenie-na-budowe'],
    body: [
      ['lead', 'Dostęp do drogi publicznej to absolutna podstawa – bez niego Twoja działka jest w świetle prawa budowlanego praktycznie bezużyteczna. Ale co w sytuacji, gdy dostęp niby jest, ale tak wąski, że ledwo mieści się tam samochód osobowy? Albo gdy sąsiad zgadza się na ustanowienie służebności, ale chce wydzielić tylko 2,5 metra?'],
      ['p', 'Jako adwokat zajmujący się nieruchomościami często słyszę pytanie: „Panie Mecenasie, ile dokładnie metrów musi mieć ta droga?”. Odpowiedź – jak to w prawie – brzmi: to zależy. Ale spokojnie, w tym artykule wyjaśnię Ci dokładnie, od czego to zależy i o jakie szerokości warto walczyć w sądzie lub u notariusza.'],
      ['h2', 'Kodeks cywilny milczy o metrach. Co na to sądy?'],
      ['p', 'Zacznijmy od fundamentu, czyli **art. 145 Kodeksu cywilnego**. Przepis ten mówi, że jeżeli nieruchomość nie ma odpowiedniego dostępu do drogi publicznej, właściciel może żądać ustanowienia tzw. **drogi koniecznej** za wynagrodzeniem. Kluczowe słowo to: **„odpowiedni”**.'],
      ['p', 'Kodeks cywilny nigdzie nie podaje konkretnej liczby metrów. Nie znajdziesz tam zapisu o 3, 4 czy 5 metrach. Ustawodawca zostawił tę kwestię do oceny indywidualnej, zależnej od potrzeb konkretnej działki. Jednak w praktyce orzeczniczej (czyli w tym, jak wyrokują sądy), sędziowie posiłkują się **przepisami administracyjnymi i technicznymi**.'],
      ['p', 'Dlaczego? Ponieważ „odpowiednia” droga konieczna to taka, która pozwoli Ci nie tylko dojechać na działkę, ale też **uzyskać pozwolenie na budowę** i bezpiecznie użytkować dom.'],
      ['h2', 'Magiczna liczba: 3 metry (minimum absolutne)'],
      ['p', 'Większość inwestorów i geodetów dąży do szerokości minimum **3 metrów**. Wynika to z przepisów o warunkach technicznych, jakim powinny odpowiadać budynki i ich usytuowanie.'],
      ['ul', [
        'Zgodnie z prawem, szerokość jezdni dojazdowej nie może być mniejsza niż 3 metry.',
        'Zatem, jeśli walczysz w sądzie o drogę konieczną dla domu jednorodzinnego, 3 metry to zazwyczaj dolna granica, o którą walczymy.',
      ]],
      ['p', '**Uwaga:** 3 metry to szerokość samej jezdni (utwardzenia). Często pas służebności musi być szerszy (np. 3,5–4 m), aby uwzględnić pobocza, ewentualne ogrodzenie czy infrastrukturę.'],
      ['h2', 'Kiedy 3 metry to za mało? Pułapka „drogi pożarowej”'],
      ['p', 'To jest moment, w którym wielu inwestorów popełnia błąd. Zakładają, że 3 metry wystarczą, dogadują się z sąsiadem, a potem urząd odrzuca wniosek o pozwolenie na budowę. Dlaczego?'],
      ['p', 'Jeśli Twój dom będzie wymagał doprowadzenia **drogi pożarowej**, szerokość dojazdu musi wynosić zazwyczaj minimum **4 metry** (a w niektórych przypadkach wymagane są też tzw. mijanki). Kiedy droga konieczna musi być szersza?'],
      ['ul', [
        'Gdy droga jest bardzo długa i wąska (konieczność mijanek).',
        'Gdy lokalne ukształtowanie terenu wymusza szersze łuki (np. ostry zakręt, w który wóz strażacki nie wejdzie przy 3 metrach).',
        'Gdy MPZP (miejscowy plan zagospodarowania przestrzennego) narzuca specyficzne wymogi dla dróg wewnętrznych w danej okolicy.',
      ]],
      ['quote', 'Wskazówka Mecenasa: Zanim zgodzisz się na służebność u notariusza, skonsultuj się z architektem adaptującym projekt. Niech sprawdzi, czy dla Twojego konkretnego domu nie będzie wymagany szerszy dojazd ze względów przeciwpożarowych.'],
      ['h2', 'Służebność przechodu i przejazdu – a co z mediami?'],
      ['p', 'Pamiętaj, że droga konieczna to nie tylko asfalt czy kostka brukowa. W pasie drogowym często musimy poprowadzić media: prąd, wodę, gaz czy światłowód. Jeśli ustanowisz służebność o szerokości „na styk” (np. 3 metry między płotami), może się okazać, że nie ma gdzie bezpiecznie wkopać rur, zachowując wymagane prawem odległości od granicy i od siebie nawzajem. Dlatego często wnoszę w imieniu klientów o pas **4,5–5 metrów**, aby zapewnić tzw. pas techniczny.'],
      ['h2', 'Przykład z życia wzięty: sprawa Państwa Kowalskich'],
      ['p', 'Pan Marek i Pani Ewa kupili działkę w drugiej linii zabudowy. Sąsiad z pierwszej linii, Pan Jan, zgodził się na służebność, ale upierał się przy pasie szerokości 2,5 metra, twierdząc, że „osobówka się zmieści”. Klienci przyszli do mnie z gotowym projektem aktu notarialnego. Ostrzegłem ich, że przy 2,5 metra nie dostaną pozwolenia na budowę domu, a w razie pożaru ubezpieczyciel może odmówić wypłaty odszkodowania. Sprawa trafiła do sądu, ponieważ sąsiad nie chciał negocjować. Powołaliśmy biegłego geodetę i biegłego z zakresu pożarnictwa. Sąd orzekł służebność o szerokości 4 metrów, uznając, że interes bezpieczeństwa i możliwość zabudowy działki (społeczno-gospodarcze przeznaczenie) są ważniejsze niż nieznaczne zmniejszenie ogródka sąsiada. Dzięki temu Pan Marek i Pani Ewa dziś legalnie budują dom.'],
      ['h2', 'Podsumowanie – o jakiej szerokości pamiętać?'],
      ['ol', [
        '**3 metry** – to absolutne minimum techniczne dla dojścia i dojazdu do działek budowlanych.',
        '**4 metry i więcej** – często wymagane ze względów przeciwpożarowych lub przy skomplikowanym ukształtowaniu terenu.',
        '**Media** – pamiętaj, że w drodze muszą zmieścić się też rury i kable.',
      ]],
      ['p', 'Każda działka jest inna. To, co wystarczyło u Twojego szwagra, może nie wystarczyć u Ciebie ze względu na zapisy w miejscowym planie zagospodarowania.'],
      ['h3', 'Masz problem z dojazdem do działki?'],
      ['p', 'Nie podpisuj aktu notarialnego „w ciemno” i nie rezygnuj z marzeń o budowie, jeśli sąsiad robi problemy. Prawo jest po to, by Ci pomóc, ale trzeba umieć je odpowiednio zastosować.'],
      ['p', '**Opisz sprawę w formularzu poniżej — bezpłatna wstępna analiza w ciągu 24 h.** Ocenię, jakie masz szanse na uzyskanie odpowiedniej szerokości drogi, i powiem, jak wygląda procedura sądowa lub negocjacje. To nic nie kosztuje i do niczego nie zobowiązuje.'],
    ],
  },
  {
    slug: 'koszty-utrzymania-drogi-koniecznej',
    title: 'Kto ponosi koszty utrzymania drogi koniecznej – właściciel czy użytkownik?',
    excerpt: 'Dziura w nawierzchni, błoto po jesiennych deszczach albo pół metra śniegu o poranku. To moment, w którym dobre relacje sąsiedzkie wystawiane są na najcięższą próbę. Kto powinien chwycić za łopatę lub portfel? Właściciel gruntu, przez który biegnie droga, czy sąsiad, który z niej korzysta?',
    date: '16 stycznia 2026', iso: '2026-01-16', updated: '29 stycznia 2026', readTime: '3 min',
    category: 'Służebności', tags: ['Droga konieczna', 'Art. 289 KC', 'Sąsiedzi'],
    cover: 'assets/blog-koszty-utrzymania-drogi.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/koszty-drogi-koniecznej',
    related: ['droga-konieczna'],
    body: [
      ['lead', 'Dziura w nawierzchni, błoto po kostki po jesiennych deszczach albo pół metra śniegu o poranku. To moment, w którym dobre relacje sąsiedzkie często wystawiane są na najcięższą próbę. Kto powinien chwycić za łopatę lub portfel? Właściciel gruntu, przez który biegnie droga, czy sąsiad, który z niej korzysta, by dojechać do domu?'],
      ['p', 'Jako adwokat często spotykam się z przekonaniem, że „skoro to jego ziemia, to on powinien o nią dbać”. Prawo cywilne ma jednak na ten temat zupełnie inne zdanie.'],
      ['h2', 'Złota zasada: płaci ten, kto korzysta'],
      ['p', 'Aby rozstrzygnąć ten spór, musimy sięgnąć do **Kodeksu cywilnego**, a konkretnie do przepisów o służebnościach gruntowych. To właśnie służebnością jest prawo przejazdu i przechodu przez cudzą działkę (tzw. drogę konieczną).'],
      ['p', 'Zgodnie z ogólną zasadą prawną (wynikającą z art. 289 k.c.), obowiązek utrzymywania urządzeń potrzebnych do wykonywania służebności gruntowej obciąża **właściciela nieruchomości władnącej**. Mówiąc „po ludzku”:'],
      ['ul', [
        '**Nieruchomość władnąca** = działka sąsiada, który nie ma dostępu do drogi publicznej (Użytkownik).',
        '**Nieruchomość służebna** = Twoja działka, przez którą biegnie droga (Właściciel).',
      ]],
      ['p', 'W domyślnym wariancie ustawowym, to **sąsiad korzystający z drogi (Użytkownik) ma obowiązek o nią dbać**, a nie Ty – mimo że formalnie jesteś właścicielem gruntu.'],
      ['h2', 'Co wchodzi w skład „utrzymania drogi”?'],
      ['p', 'Przepisy mówią o „utrzymywaniu urządzeń”. W kontekście drogi koniecznej sądy interpretują to pojęcie bardzo szeroko. Do obowiązków Użytkownika należy więc zazwyczaj:'],
      ['ul', [
        '**Utwardzenie nawierzchni** (wysypanie tłucznia, położenie płyt, wylanie asfaltu).',
        '**Bieżące naprawy** (zasypywanie dziur, wyrównywanie kolein).',
        '**Utrzymanie czystości i przejezdności** (odśnieżanie zimą, usuwanie błota, koszenie trawy na pasie drogowym).',
      ]],
      ['p', 'Właściciel gruntu ma obowiązek jedynie... **znosić** to, że ktoś przez jego teren przejeżdża. Nie ma obowiązku inwestować własnych pieniędzy w to, aby sąsiadowi jeździło się wygodniej.'],
      ['h2', 'A co, jeśli z drogi korzystamy wspólnie?'],
      ['p', 'To najczęstszy scenariusz. Masz dużą działkę, wydzieliłeś drogę dojazdową, korzystasz z niej Ty, a na zasadzie służebności również Twój sąsiad z tyłu. Czy wtedy też tylko on płaci za wszystko?'],
      ['p', 'Prawo pozwala na pewną elastyczność. Choć zasada kodeksowa wskazuje na Użytkownika, to w praktyce sądowej i doktrynie przyjmuje się, że jeśli z drogi korzystają obie strony, **koszty powinny być dzielone**.'],
      ['p', 'Kluczowe jest tutaj słowo: **proporcjonalność**. Jeżeli Ty jeździsz samochodem osobowym raz dziennie, a sąsiad prowadzi firmę i wpuszcza tamtędy ciężki sprzęt budowlany, niesprawiedliwym byłoby dzielenie kosztów naprawy drogi po połowie.'],
      ['h2', 'Umowa ważniejsza niż ustawa'],
      ['p', 'Warto pamiętać, że przepis art. 289 Kodeksu cywilnego stosuje się wtedy, gdy strony nie umówiły się inaczej. Jako adwokat zawsze doradzam moim Klientom: **ustalcie to na piśmie**. Podczas ustanawiania służebności (u notariusza lub w sądzie) można wpisać konkretne zasady:'],
      ['ol', [
        'Kto i w jakiej części pokrywa koszty utwardzenia?',
        'Kto odpowiada za odśnieżanie?',
        'Czy właściciel gruntu ma prawo żądać dorzucenia się do remontu?',
      ]],
      ['p', 'Taki zapis w akcie notarialnym to najlepsza „szczepionka” na przyszłe konflikty.'],
      ['h3', 'Przykład z życia wzięty: sprawa Pana Marka'],
      ['p', 'Pan Marek (właściciel nieruchomości władnącej) przez lata korzystał z drogi gruntowej biegnącej przez pole Pani Janiny. Po obfitych deszczach droga stała się nieprzejezdna. Pan Marek zażądał od Pani Janiny, aby zamówiła wywrotkę gruzu i utwardziła teren, argumentując: „To Pani pole, Pani obowiązek”. Pani Janina odmówiła. Sprawa trafiła do mnie. Musiałem wyjaśnić Panu Markowi, że jego żądania są bezzasadne. Jako beneficjent służebności, to on musi sfinansować utwardzenie drogi, jeśli chce z niej korzystać. Pani Janina musi jedynie pozwolić mu na wykonanie tych prac (nie może ich blokować), ale nie musi dokładać do nich ani złotówki.'],
      ['h2', 'Podsumowanie'],
      ['ol', [
        'Co do zasady: za utrzymanie drogi koniecznej płaci ten, kto ma prawo z niej korzystać (sąsiad „odcięty”), a nie właściciel gruntu.',
        'Obowiązek ten obejmuje m.in. utwardzanie, naprawy i odśnieżanie.',
        'Jeśli z drogi korzystacie wspólnie, uczciwym i często stosowanym rozwiązaniem jest podział kosztów (najlepiej spisany w umowie).',
        'Właściciel gruntu nie może utrudniać remontu, ale nie musi go finansować.',
      ]],
      ['h3', 'Masz problem z sąsiadem o drogę?'],
      ['p', 'Prawo nieruchomości bywa skomplikowane, a emocje sąsiedzkie nie pomagają w trzeźwej ocenie sytuacji. Niezależnie od tego, czy jesteś właścicielem gruntu, czy osobą korzystającą z drogi, warto wiedzieć, na czym stoisz, zanim wydasz pieniądze na remont lub wejdziesz w spór sądowy.'],
      ['p', '**Opisz sprawę w formularzu poniżej — bezpłatnie, w ciągu 24 h powiem Ci, czy i jak mogę pomóc ją rozwiązać.**'],
    ],
  },
  {
    slug: 'slup-energetyczny-na-dzialce-przesuniecie',
    title: 'Słup energetyczny na działce: czy musisz płacić za jego przesunięcie?',
    excerpt: '„W 2007 roku kupiłem działkę budowlaną, na której końcu stoi słup linii średniego napięcia. Firma energetyczna twierdzi, że skablowanie linii i usunięcie słupa jest możliwe tylko na mój koszt. Czy to legalne? Czy naprawdę muszę płacić za ich infrastrukturę na mojej ziemi?”',
    date: '19 stycznia 2026', iso: '2026-01-19', readTime: '2 min',
    category: 'Służebność przesyłu', tags: ['Słupy na działce', 'Przesunięcie urządzeń', 'Pytanie klienta'],
    cover: 'assets/blog-slup-przesuniecie.jpg',
    source: 'https://www.mecenasodnieruchomosci.pl/post/słup-energetyczny-na-działce-czy-musisz-płacić-za-jego-przesunięcie',
    related: ['odszkodowanie-sluzebnosc-przesylu', 'bezumowne-korzystanie'],
    body: [
      ['h2', 'Pytanie klienta'],
      ['lead', '„Panie Mecenasie, mam problem. W 2007 roku kupiłem działkę budowlaną, na której końcu stoi słup linii średniego napięcia. Chciałbym go usunąć, żeby normalnie korzystać z terenu, ale firma energetyczna stawia sprawę twardo. Twierdzą, że skablowanie linii i usunięcie słupa jest możliwe tylko na mój koszt. Co więcej, nie chcą nawet podać szacunkowych kosztów, dopóki nie zrobię projektu za własne pieniądze! Czy to legalne? Czy naprawdę muszę płacić za ich infrastrukturę na mojej ziemi?”'],
      ['h2', 'Mecenas odpowiada'],
      ['p', 'To niestety klasyka gatunku. Zakłady energetyczne bardzo często wychodzą z założenia, że skoro to Tobie przeszkadza słup, to Ty powinieneś wyciągnąć portfel. Ale spokojnie – prawo nie zawsze stoi po ich stronie. Zanim zgodzisz się na jakiekolwiek koszty, musimy ustalić jedną kluczową rzecz: **czy ten słup stoi tam legalnie, czy „na dziko”?**'],
      ['p', 'To fundamentalna różnica, która całkowicie zmienia Twoją pozycję w negocjacjach.'],
      ['h3', 'Scenariusz 1: słup postawiono nielegalnie'],
      ['p', 'Jeśli okaże się, że zakład energetyczny postawił urządzenia bezprawnie (bez zgody właściciela, decyzji administracyjnej czy odpowiednich wpisów), jesteś na wygranej pozycji. Wtedy masz pełne prawo żądać usunięcia słupa na koszt przedsiębiorstwa przesyłowego. To ich problem, nie Twój. Jak to sprawdzić? Musisz zabawić się w detektywa:'],
      ['ul', [
        'zajrzyj w dokumentację geodezyjną – legalny słup powinien być ujawniony na mapach;',
        'zapytaj poprzedniego właściciela, czy podpisywał jakąkolwiek umowę z energetyką;',
        'sprawdź księgi wieczyste pod kątem służebności.',
      ]],
      ['h3', 'Scenariusz 2: słup stoi legalnie'],
      ['p', 'Tu sprawa jest trudniejsza. Jeśli zakład energetyczny ma „papiery” na ten słup, nie możesz po prostu kazać im go zabrać za darmo. W praktyce uzyskanie zgody na usunięcie takiej instalacji bywa trudne, a operatorzy często stawiają warunek: zgadzamy się, ale Ty płacisz.'],
      ['p', 'Jednak nawet w tej sytuacji nie jesteś bezbronny. Przysługują Ci konkretne roszczenia finansowe. Możesz domagać się od zakładu:'],
      ['ul', [
        'wykupienia fragmentu działki zajętej pod słup;',
        'zapłaty odszkodowania za bezumowne korzystanie z gruntu (i to do 10 lat wstecz!);',
        'ustalenia czynszu za to, że ich urządzenia stoją na Twojej ziemi w przyszłości.',
      ]],
      ['p', 'Warto też pamiętać, że odszkodowanie należy się również wtedy, gdy słup obniża wartość rynkową Twojej działki lub ogranicza jej funkcjonalność.'],
      ['p', '**Co to oznacza dla Ciebie w praktyce?** Nie wierz na słowo urzędnikom z zakładu energetycznego. Zanim wydasz złotówkę na projekt, sprawdź status prawny słupa. Może się okazać, że zamiast płacić im za usunięcie, to oni będą musieli zapłacić Tobie zaległe wynagrodzenie za korzystanie z Twojego gruntu.'],
      ['p', '**Zacznijmy od konkretów.** Masz mapy lub numer księgi wieczystej? Prześlij je w formularzu poniżej — bezpłatnie, w ciągu 24 h rzucę na to okiem i podpowiem, czy masz w ręku asy, by negocjować z energetyką jak równy z równym.'],
    ],
  }
);
window.BLOG.sort((a, b) => (b.iso || '').localeCompare(a.iso || ''));
