/* pillars-content.jsx — treści 10 stron filarów (obszarów praktyki). Ten sam format co
   BLOCK_CONTENT['roszczenia-deweloper'] w services-content.jsx. Ładowane po services-content.jsx. */
Object.assign(window.BLOCK_CONTENT, {

  'sprawdzenie-przed-zakupem': {
    h1: 'Sprawdzenie nieruchomości przed zakupem',
    introHeading: 'Siadam po Twojej stronie stołu.',
    subtitle: 'Mieszkanie, dom, działka — od dewelopera albo z rynku wtórnego. Zanim wpłacisz zadatek lub podpiszesz umowę, sprawdzam księgę wieczystą, umowę i ryzyka, o których sprzedający nie powie. Dostajesz jasną odpowiedź: kupować, negocjować czy odpuścić.',
    intro: 'Zakup nieruchomości to zwykle największa transakcja w życiu, a decyzję podejmuje się w kilka dni, pod presją „zaraz weźmie ktoś inny”. Sprzedający, pośrednik i deweloper są po jednej stronie stołu. Ja siadam po Twojej. Czytam księgę wieczystą łącznie z dokumentami, które w niej „siedzą”, sprawdzam umowę zdanie po zdaniu, weryfikuję stan planistyczny działki i to, czego nie widać w ogłoszeniu: służebności, hipoteki, roszczenia, drogę dojazdową, samowole budowlane. Wynik dostajesz w formie raportu w trzech kolorach — wiesz, co jest w porządku, co trzeba poprawić w umowie i co powinno Cię zatrzymać.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Znalazłeś mieszkanie albo dom i masz kilka dni na decyzję o zadatku.',
      'Deweloper przysłał umowę rezerwacyjną lub deweloperską „do podpisu bez zmian”.',
      'Kupujesz działkę i nie wiesz, czy na pewno da się na niej budować.',
      'W księdze wieczystej są wpisy, których nie rozumiesz: służebności, hipoteka, ostrzeżenie, roszczenie.',
      'Sprzedaje spadkobierca, współwłaściciele albo osoba działająca przez pełnomocnika.',
      'Bank prosi o dokumenty, a Ty nie wiesz, które są kluczowe i co w nich sprawdzić.',
    ],
    lists: [
      {
        eyebrow: 'Co sprawdzam',
        title: 'Więcej niż księga wieczysta.',
        kind: 'check',
        items: [
          { b: 'Stan prawny', t: 'własność, obciążenia, hipoteki, służebności, roszczenia i ostrzeżenia w KW — razem z dokumentami będącymi podstawą wpisów.' },
          { b: 'Umowę', t: 'rezerwacyjną, przedwstępną, deweloperską lub sprzedaży — kary, terminy, zadatek, zaliczka, odstąpienie, odpowiedzialność za wady.' },
          { b: 'Działkę', t: 'plan miejscowy albo warunki zabudowy, plan ogólny gminy, dostęp do drogi publicznej, media, klasę gruntu.' },
          { b: 'Sprzedającego i dewelopera', t: 'uprawnienie do sprzedaży, pełnomocnictwa, sytuację spółki, rachunek powierniczy, prospekt informacyjny.' },
          { b: 'Budynek i lokal', t: 'legalność zabudowy, pozwolenie na użytkowanie, samowole, zaległości wobec wspólnoty lub spółdzielni.' },
        ],
      },
      {
        eyebrow: 'Co dostajesz',
        title: 'Konkret, nie opinię na mailu.',
        kind: 'deliverables',
        items: [
          'Raport w trzech kolorach: zielone — bez uwag, żółte — do poprawy w umowie, czerwone — ryzyko, przy którym nie podpisuję bez zmian.',
          'Listę konkretnych zmian do umowy w formie gotowej do wysłania drugiej stronie albo notariuszowi.',
          'Odpowiedź na pytanie, czy cena i warunki są uzasadnione w świetle znalezionych ryzyk.',
          'Wsparcie w negocjacjach i przy akcie notarialnym — jeśli chcesz, uczestniczę zdalnie albo przygotowuję pytania do notariusza.',
          'Orientacyjny czas: sprawdzenie KW i umowy zwykle w 2–4 dni robocze, pełny audyt działki w 5–7.',
        ],
      },
    ],
    faq: [
      { q: 'Mam tylko numer księgi wieczystej i ogłoszenie. Czy to wystarczy, żeby zacząć?', a: 'Tak. Z numeru KW wyciągam większość informacji o stanie prawnym; resztę — umowę, prospekt, wypis z planu — ustalam po drodze i mówię Ci, o co poprosić sprzedającego. Nie musisz niczego kompletować przed pierwszym kontaktem.' },
      { q: 'Notariusz i tak sprawdza księgę wieczystą. Po co jeszcze adwokat?', a: 'Notariusz dba o ważność aktu i jest bezstronny — nie doradza żadnej ze stron, nie negocjuje w Twoim imieniu i zwykle nie analizuje dokumentów będących podstawą wpisów ani stanu planistycznego działki. Ja pracuję wyłącznie dla Ciebie i mówię wprost, czego nie podpisywać.' },
      { q: 'Deweloper mówi, że umowa jest standardowa i nie da się jej zmienić. To prawda?', a: 'Rzadko. Umowy deweloperskie są negocjowane częściej, niż deweloperzy przyznają — zwłaszcza terminy, kary umowne, zasady odbioru i odstąpienia. Nawet jeśli deweloper nie zgodzi się na zmiany, będziesz wiedział, jakie ryzyko bierzesz i czy warto.' },
      { q: 'Ile czasu zajmuje sprawdzenie?', a: 'Analiza księgi wieczystej i umowy: zwykle 2–4 dni robocze. Pełny audyt działki z planowaniem przestrzennym: 5–7 dni. Jeśli goni Cię termin podpisu, napisz to w zgłoszeniu — sprawdzę, czy dam radę szybciej.' },
      { q: 'Kupuję na kredyt. Czy to coś zmienia?', a: 'Tak — bank stawia własne wymagania (np. brak określonych obciążeń, ustanowienie hipoteki, harmonogram wypłat). Sprawdzam, czy umowa pozwala je spełnić w terminie, i pilnuję, żeby nie utknąć między wymaganiami banku a karami u sprzedającego.' },
      { q: 'Co, jeśli znajdziesz problem?', a: 'Nie kończę na „jest ryzyko”. Dostajesz konkretne rozwiązanie: zmianę zapisu, warunek w umowie, dokument do uzyskania przed podpisem, obniżenie ceny albo — gdy problem jest poważny — rekomendację odstąpienia od transakcji.' },
      { q: 'Kupuję działkę pod budowę domu. Co jest najważniejsze?', a: 'Trzy rzeczy: czy da się na niej legalnie budować (plan miejscowy lub warunki zabudowy, plan ogólny), czy ma prawny dostęp do drogi publicznej i czy nie ma ukrytych obciążeń. Od 2026 r. zasady wydawania warunków zabudowy zmieniają się — sprawdzam działkę w świetle nowych przepisów.' },
      { q: 'Czy sprawdzenie ma sens przy zakupie od rodziny lub znajomych?', a: 'Szczególnie wtedy. Problemy nie biorą się ze złej woli sprzedającego, tylko z historii nieruchomości: nieuregulowanych spadków, starych służebności, granic niezgodnych z ewidencją. Sprawdzenie chroni relację — wiadomo, co i jak porządkujecie przed podpisem.' },
    ],
    cta: {
      heading: 'Nie podpisuj w ciemno.',
      lead: 'Prześlij numer księgi wieczystej i umowę, jeśli ją masz. Bezpłatnie ocenię, czy widzę coś, co powinno Cię zatrzymać — i co warto sprawdzić dokładniej.',
    },
  },

  'transakcje-umowy': {
    h1: 'Transakcje i umowy',
    introHeading: 'Umowa to podział ryzyka, nie formalność.',
    subtitle: 'Sprzedaż, zakup, darowizna, zamiana, umowa przedwstępna, przygotowanie do aktu notarialnego. Przygotowuję i negocjuję umowy tak, żeby zabezpieczały Twoje pieniądze i Twoje terminy — a nie tylko przechodziły u notariusza.',
    intro: 'Umowa dotycząca nieruchomości to nie formalność przed notariuszem — to dokument, który przez lata rozstrzyga, kto ponosi ryzyko: kto traci zadatek, kto płaci karę za opóźnienie, kto odpowiada za wady, co się dzieje, gdy bank nie da kredytu albo druga strona zmieni zdanie. Większość sporów, które trafiają do mnie później, wynika z jednego niedopisanego zdania. Dlatego pracuję na etapie, gdy zdanie można jeszcze dopisać. Prowadzę transakcje od ustaleń, przez umowę przedwstępną, po akt notarialny i rozliczenie — dla kupujących, sprzedających i inwestorów.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Sprzedajesz nieruchomość i chcesz mieć pewność, że pieniądze wpłyną, a Ty nie zostaniesz z roszczeniami kupującego.',
      'Kupujesz i druga strona przysłała „swój” projekt umowy przedwstępnej.',
      'Transakcja jest nietypowa: współwłasność, spadek, pełnomocnik, obcokrajowiec, nieruchomość rolna, lokal z zaległościami.',
      'Zależysz od kredytu, sprzedaży innej nieruchomości albo decyzji urzędu i chcesz to zabezpieczyć w umowie.',
      'Chcesz przekazać nieruchomość w rodzinie — darowizną, dożywociem albo zamianą — i nie wiesz, która forma jest bezpieczna.',
      'Notariusz ma już termin, a Ty nie miałeś czasu przeczytać projektu aktu.',
    ],
    lists: [
      {
        eyebrow: 'Czym się zajmuję',
        title: 'Cała transakcja, nie tylko podpis.',
        kind: 'check',
        items: [
          { b: 'Umowy przedwstępne i rezerwacyjne', t: 'zadatek a zaliczka, terminy, warunki (kredyt, WZ, podział), odstąpienie, kary umowne.' },
          { b: 'Umowy sprzedaży', t: 'współpraca z notariuszem, weryfikacja projektu aktu, zabezpieczenie zapłaty (depozyt notarialny, harmonogram), wydanie nieruchomości.' },
          { b: 'Darowizny, dożywocie, zamiany', t: 'przekazanie majątku w rodzinie z zabezpieczeniem darczyńcy i bez niespodzianek podatkowych czy spadkowych.' },
          { b: 'Transakcje z ograniczeniami', t: 'grunty rolne (KOWR, prawo pierwokupu), nieruchomości z hipoteką, udziały we współwłasności, sprzedaż przez pełnomocnika.' },
          { b: 'Negocjacje', t: 'prowadzę je za Ciebie albo przygotowuję Ci argumenty i wersję umowy do przesłania.' },
        ],
      },
      {
        eyebrow: 'Jak pracuję',
        title: 'Zakres pracy.',
        kind: 'deliverables',
        items: [
          'Ustalam Twoje cele i słabe punkty transakcji — co musi się wydarzyć, żebyś czuł się bezpiecznie.',
          'Przygotowuję lub poprawiam umowę; zmiany wyjaśniam po ludzku, żebyś wiedział, o co negocjujesz.',
          'Kontaktuję się z drugą stroną, pośrednikiem i notariuszem — pilnuję, żeby ustalenia trafiły do aktu.',
          'Weryfikuję projekt aktu notarialnego przed terminem i przygotowuję listę pytań lub poprawek.',
          'Orientacyjny czas: umowa przedwstępna 2–3 dni robocze, kompleksowa obsługa transakcji — zgodnie z Twoim harmonogramem.',
        ],
      },
    ],
    faq: [
      { q: 'Zadatek czy zaliczka — co wybrać?', a: 'Zadatek dyscyplinuje obie strony: kto się wycofa, traci go albo płaci podwójnie. Zaliczka po prostu wraca. Wybór zależy od tego, kto ponosi większe ryzyko niedojścia transakcji — doradzam po analizie Twojej sytuacji, a nie „z automatu”.' },
      { q: 'Czy umowa przedwstępna musi być u notariusza?', a: 'Nie musi, ale forma notarialna daje Ci prawo dochodzić zawarcia umowy przed sądem, a nie tylko zwrotu zadatku. Przy nieruchomościach o dużej wartości albo gdy druga strona jest mniej wiarygodna, zwykle to rekomenduję.' },
      { q: 'Co, jeśli bank odmówi kredytu po podpisaniu umowy przedwstępnej?', a: 'Bez odpowiedniego zapisu tracisz zadatek. Dlatego wpisuję warunek uzyskania kredytu z konkretnym terminem i skutkiem — to standard, na który większość sprzedających się zgadza, jeśli jest dobrze sformułowany.' },
      { q: 'Sprzedaję mieszkanie. Czego mam się obawiać?', a: 'Trzech rzeczy: że pieniądze nie wpłyną w całości przed wydaniem lokalu, że kupujący po czasie zgłosi wady, i że rozliczenie mediów, czynszu lub ruchomości skończy się sporem. Wszystko to da się zabezpieczyć w umowie — zajmuję się tym.' },
      { q: 'Czy mogę sprzedać albo kupić nieruchomość przez pełnomocnika?', a: 'Tak, pełnomocnictwo musi mieć formę aktu notarialnego i odpowiednio szeroki zakres. Sprawdzam jego treść przed transakcją — źle sformułowane pełnomocnictwo to jedna z częstszych przyczyn odwołanych terminów u notariusza.' },
      { q: 'Kupuję działkę rolną. Czy potrzebuję zgody?', a: 'Zależy od powierzchni, położenia i tego, kim jesteś. Przy gruntach powyżej określonej powierzchni w grę wchodzi KOWR i prawo pierwokupu. Sprawdzam, czy transakcja jest w ogóle możliwa i jak ją poprowadzić bez zbędnych miesięcy oczekiwania.' },
      { q: 'Notariusz przysłał projekt aktu dzień przed terminem. Zdążysz?', a: 'Jeśli napiszesz od razu — zwykle tak. Weryfikacja projektu aktu to kilka godzin pracy. Zaznacz w zgłoszeniu, że sprawa jest pilna.' },
      { q: 'Darowizna czy dożywocie — jak przekazać dom dziecku?', a: 'Darowizna jest prostsza, dożywocie lepiej chroni rodziców (prawo do mieszkania i opieki wpisane do KW) i inaczej działa przy zachowku. Wybór ma skutki na dekady — omawiam obie drogi i ich konsekwencje dla całej rodziny.' },
    ],
    cta: {
      heading: 'Jedno zdanie w umowie potrafi kosztować więcej niż cała obsługa prawna.',
      lead: 'Prześlij projekt umowy albo opisz ustalenia z drugą stroną. Bezpłatnie wskażę, które zapisy są dla Ciebie ryzykowne i co dopisać przed podpisem.',
    },
  },

  'warunki-zabudowy-planowanie': {
    h1: 'Warunki zabudowy i planowanie przestrzenne',
    introHeading: 'Reforma zmienia zasady gry.',
    subtitle: 'Decyzje WZ, plany miejscowe, plan ogólny gminy, odrolnienie. Reforma planistyczna zmienia zasady gry — sprawdzam, czy na Twojej działce da się budować, i walczę o to w urzędzie, radzie gminy i sądzie administracyjnym.',
    intro: 'Od 2026 roku o tym, czy na działce wolno postawić dom, przesądza nowy dokument — plan ogólny gminy — a decyzje o warunkach zabudowy przestają być bezterminowe. Działki, które dziś bez trudu da się zabudować, mogą tę możliwość stracić. Prowadzę sprawy planistyczne od strony właściciela i inwestora: analizuję stan planistyczny działki, przygotowuję wnioski o WZ i pilnuję urzędu, składam uwagi do planów ogólnych i miejscowych, a gdy trzeba — zaskarżam decyzje i uchwały. Zdalnie, w całej Polsce, bo do analizy planistycznej potrzebuję numeru działki, nie wizyty.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Masz działkę bez planu miejscowego i chcesz zdążyć z warunkami zabudowy przed zmianą przepisów.',
      'Urząd odmówił WZ, zawiesił postępowanie albo miesiącami „analizuje” Twój wniosek.',
      'Gmina wykłada projekt planu ogólnego lub miejscowego, a Twoja działka ma trafić do strefy bez zabudowy.',
      'Kupujesz działkę i nie wiesz, czy będzie w obszarze uzupełnienia zabudowy.',
      'Nowy plan miejscowy obniżył wartość Twojej nieruchomości i zastanawiasz się nad odszkodowaniem.',
      'Planujesz inwestycję — dom, zabudowę wielorodzinną, magazyn, farmę fotowoltaiczną — i potrzebujesz strategii planistycznej.',
    ],
    lists: [
      {
        eyebrow: 'W czym pomagam',
        title: 'Od analizy działki do sądu administracyjnego.',
        kind: 'check',
        items: [
          { b: 'Analiza planistyczna działki', t: 'plan miejscowy, studium lub plan ogólny, decyzje WZ w okolicy, klasa gruntu, dostęp do drogi — z wnioskiem: da się budować czy nie i na jakich warunkach.' },
          { b: 'Warunki zabudowy', t: 'przygotowanie kompletnego wniosku, prowadzenie postępowania, ponaglenia i skargi na bezczynność, odwołania od odmów.' },
          { b: 'Plany ogólne i miejscowe', t: 'wnioski i uwagi do projektów, udział w konsultacjach, wnioski o zmianę planu, skargi na uchwały do sądu administracyjnego.' },
          { b: 'Odszkodowania planistyczne', t: 'gdy nowy plan uniemożliwia dotychczasowe korzystanie z działki albo obniża jej wartość.' },
          { b: 'Odrolnienie i wyłączenie z produkcji rolnej', t: 'zmiana przeznaczenia gruntów rolnych pod zabudowę.' },
        ],
      },
      {
        eyebrow: 'Jak pracuję',
        title: 'Zakres pracy.',
        kind: 'deliverables',
        items: [
          'Sprawdzam dokumenty planistyczne gminy i historię działki — dostajesz jasną odpowiedź, jakie masz możliwości i ile czasu.',
          'Przygotowuję wniosek lub uwagi z argumentacją prawną i orzecznictwem — urząd inaczej czyta pismo od adwokata.',
          'Prowadzę korespondencję z urzędem, pilnuję terminów i reaguję na bezczynność.',
          'Reprezentuję Cię przed Samorządowym Kolegium Odwoławczym, wojewodą i sądami administracyjnymi.',
          'Orientacyjny czas: analiza planistyczna 5–7 dni roboczych; postępowanie o WZ — zależnie od gminy, zwykle kilka miesięcy.',
        ],
      },
    ],
    faq: [
      { q: 'Mam już decyzję WZ sprzed lat. Czy coś tracę po reformie?', a: 'Nie. Decyzje wydane przed zmianami pozostają bezterminowe. Wyjątek: gdy gmina uchwali dla Twojego terenu plan miejscowy, WZ przestaje obowiązywać. Nowe decyzje są ważne 5 lat.' },
      { q: 'Co to jest obszar uzupełnienia zabudowy i dlaczego jest tak ważny?', a: 'To teren wskazany w planie ogólnym gminy, w którym po reformie nadal będzie można uzyskać warunki zabudowy. Działka poza tym obszarem bez planu miejscowego traci możliwość zabudowy na podstawie WZ. Sprawdzam, gdzie jest Twoja działka i co można jeszcze zrobić.' },
      { q: 'Urząd „analizuje” mój wniosek o WZ od pół roku. Co mogę zrobić?', a: 'Ponaglenie, a potem skarga na bezczynność lub przewlekłość — urząd ma ustawowe terminy, a ich przekroczenie może skutkować karą finansową dla organu. W praktyce dobrze napisane ponaglenie często wystarcza.' },
      { q: 'Dostałem odmowę WZ, bo „brak dobrego sąsiedztwa”. Czy warto się odwoływać?', a: 'Często tak — analiza sąsiedztwa bywa robiona schematycznie, a orzecznictwo daje sporo argumentów (np. co do zasięgu obszaru analizowanego). Oceniam decyzję i mówię szczerze, jakie są szanse.' },
      { q: 'Gmina chce w planie zmienić moją działkę na tereny zielone. Mam na to wpływ?', a: 'Tak, ale tylko w określonych oknach czasowych: wnioski po przystąpieniu do planu, uwagi po wyłożeniu projektu, a po uchwaleniu — skarga do sądu administracyjnego. Śledzę procedurę i składam pisma w Twoim imieniu.' },
      { q: 'Plan miejscowy obniżył wartość mojej działki. Należy mi się odszkodowanie?', a: 'Może się należeć — jeśli korzystanie z nieruchomości w dotychczasowy sposób stało się niemożliwe lub istotnie ograniczone, albo jej wartość spadła. Roszczenia są terminowe, więc warto sprawdzić sytuację szybko.' },
      { q: 'Czy mogę sprawdzić działkę pod WZ, zanim ją kupię?', a: 'Po reformie o WZ wnioskuje tylko osoba z tytułem prawnym do nieruchomości, więc „na próbę” już nie. Dlatego przed zakupem robię analizę planistyczną i zabezpieczam Cię warunkiem w umowie przedwstępnej.' },
      { q: 'Jesteś z Lublina, a moja działka jest w innym województwie. To problem?', a: 'Nie. Dokumenty planistyczne są jawne i dostępne online, a postępowania administracyjne prowadzę korespondencyjnie. Reprezentuję właścicieli działek z całej Polski.' },
    ],
    cta: {
      heading: 'Sprawdźmy Twoją działkę, zanim zmienią się przepisy.',
      lead: 'Podaj numer działki i gminę. Bezpłatnie ocenię, na jakim etapie jest Twoja gmina, czy działka ma szansę na zabudowę i co warto zrobić w pierwszej kolejności.',
    },
  },

  'proces-budowlany': {
    h1: 'Proces budowlany i nadzór',
    introHeading: 'Budowa to ciąg decyzji, które ktoś może zatrzymać.',
    subtitle: 'Pozwolenie na budowę, zgłoszenie, odstępstwa, legalizacja samowoli, kontrole PINB, spory z wykonawcą i sąsiadem. Pilotuję inwestycję przez urzędy i reaguję, gdy ktoś próbuje ją zatrzymać.',
    intro: 'Budowa to ciąg decyzji administracyjnych, terminów i osób, które mogą ją zablokować: urząd, nadzór budowlany, sąsiad, wykonawca. Jeden brak w dokumentacji albo źle sformułowane odwołanie potrafi zatrzymać inwestycję na rok. Pomagam inwestorom uzyskać pozwolenia i odstępstwa, odpowiadam na pisma nadzoru, prowadzę legalizacje samowoli budowlanych i procedury naprawcze, a także spory z wykonawcami o jakość i terminy. Sąsiadom, których budowa dotyka bezpośrednio, pomagam skutecznie bronić swoich praw — bez pieniactwa, ale konsekwentnie.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Urząd wezwał Cię do uzupełnienia wniosku o pozwolenie na budowę albo odmówił jego wydania.',
      'Nadzór budowlany (PINB) wszczął postępowanie, przysłał wezwanie lub zapowiedział kontrolę.',
      'Kupiłeś dom lub działkę z obiektem wybudowanym bez pozwolenia i chcesz go zalegalizować.',
      'Sąsiad odwołał się od Twojego pozwolenia albo Ty chcesz zakwestionować budowę obok.',
      'Wykonawca nie dotrzymuje terminów, prace mają wady, a umowa nie chroni Cię tak, jak myślałeś.',
      'Twój projekt wymaga odstępstwa od przepisów techniczno-budowlanych i nie wiesz, jak je uzyskać.',
    ],
    lists: [
      {
        eyebrow: 'W czym pomagam',
        title: 'Od wniosku do odbioru.',
        kind: 'check',
        items: [
          { b: 'Pozwolenia i zgłoszenia', t: 'strategia uzyskania decyzji, odpowiedzi na wezwania, odwołania od odmów i sprzeciwów.' },
          { b: 'Nadzór budowlany', t: 'reprezentacja w kontrolach i postępowaniach PINB, procedura naprawcza, legalizacja samowoli, obrona przed nakazem rozbiórki.' },
          { b: 'Odstępstwa od przepisów', t: 'wnioski o upoważnienie do odstępstwa od przepisów techniczno-budowlanych na nowych zasadach.' },
          { b: 'Spory z wykonawcą', t: 'umowy o roboty budowlane, odbiory, kary umowne, wady, rozliczenie po zerwaniu współpracy.' },
          { b: 'Sąsiedztwo', t: 'ochrona interesów osób trzecich w postępowaniu — i obrona inwestora przed bezzasadnym blokowaniem.' },
        ],
      },
      {
        eyebrow: 'Jak pracuję',
        title: 'Zakres pracy.',
        kind: 'deliverables',
        items: [
          'Analizuję dokumentację i pisma urzędu — ustalam, czego naprawdę dotyczy problem i jakie masz opcje.',
          'Przygotowuję pisma procesowe: odpowiedzi, odwołania, wnioski o legalizację, zażalenia — z argumentacją prawną i orzecznictwem.',
          'Reprezentuję Cię przed starostą, wojewodą, PINB, WINB i sądami administracyjnymi.',
          'W sporach z wykonawcą negocjuję, a gdy trzeba — prowadzę sprawę sądową z udziałem biegłego.',
          'Orientacyjny czas: odpowiedź na wezwanie lub odwołanie 3–5 dni roboczych; legalizacja samowoli — od kilku miesięcy.',
        ],
      },
    ],
    faq: [
      { q: 'Dostałem pismo z PINB. Co robić w pierwszej kolejności?', a: 'Nie ignorować i nie składać wyjaśnień „od serca”, zanim ktoś ich nie przeczyta. To, co napiszesz na starcie, kształtuje całe postępowanie. Prześlij mi pismo — odpowiem, jaki jest jego cel i co bezpiecznie odpowiedzieć.' },
      { q: 'Czy samowolę budowlaną da się jeszcze zalegalizować?', a: 'W większości przypadków tak — przez postępowanie legalizacyjne (z opłatą) albo uproszczoną legalizację dla obiektów starszych niż 20 lat, bez opłaty. Rozbiórka to ostateczność, nie reguła. Sprawdzam, która ścieżka jest dostępna.' },
      { q: 'Sąsiad odwołał się od mojego pozwolenia na budowę. Ile to opóźni budowę?', a: 'Odwołanie wstrzymuje wykonanie decyzji, ale nie każdy sąsiad jest stroną, a nie każdy zarzut ma znaczenie prawne. Analizuję jego pisma i przygotowuję odpowiedź tak, żeby postępowanie zamknąć jak najszybciej.' },
      { q: 'Budowa obok narusza moje prawa — zabiera światło, jest za blisko granicy. Co mogę zrobić?', a: 'Jako właściciel nieruchomości w obszarze oddziaływania masz status strony i możesz kwestionować pozwolenie, a przy naruszeniach — zgłosić sprawę do nadzoru. Oceniam, czy zarzuty mają podstawy, i formułuję je tak, żeby urząd musiał się nimi zająć.' },
      { q: 'Wykonawca porzucił budowę i żąda zapłaty za „wykonane prace”. Co dalej?', a: 'Kluczowe są umowa, protokoły i dokumentacja zdjęciowa stanu robót. Zabezpieczam dowody (często z udziałem rzeczoznawcy), rozliczam prace i wady, i dochodzę kar umownych lub odszkodowania — najpierw polubownie, potem sądowo.' },
      { q: 'Na czym polega nowa procedura naprawcza w nadzorze budowlanym?', a: 'Zamiast od razu nakazywać rozbiórkę czy wstrzymywać budowę, nadzór wskazuje nieprawidłowości i daje czas na ich usunięcie. To szansa, ale trzeba jej dobrze użyć — odpowiedzieć w terminie i wykazać, że naprawa jest wykonana lub możliwa.' },
      { q: 'Czy odstępstwo od przepisów techniczno-budowlanych to realna opcja?', a: 'Tak, zwłaszcza po zmianach z 2026 r., które porządkują procedurę. Wymaga dobrego uzasadnienia i często opinii projektanta lub rzeczoznawcy. Przygotowuję wniosek i prowadzę go z organem.' },
      { q: 'Urząd wydał decyzję, a ja przegapiłem termin odwołania. To koniec?', a: 'Niekoniecznie. W określonych sytuacjach można wnioskować o przywrócenie terminu, a w innych — o stwierdzenie nieważności lub wznowienie postępowania. Sprawdzam, która droga jest dostępna w Twoim przypadku.' },
    ],
    cta: {
      heading: 'Budowa nie może stać, bo urząd czeka na pismo.',
      lead: 'Prześlij decyzję, wezwanie albo umowę z wykonawcą. Bezpłatnie ocenię, o co naprawdę toczy się sprawa, jakie masz terminy i co zrobić najpierw.',
    },
  },

  'ksiegi-wieczyste-stan-prawny': {
    h1: 'Księgi wieczyste i regulacja stanu prawnego',
    introHeading: 'Porządkuję to, co blokuje wszystko inne.',
    subtitle: 'Brakujące wpisy, błędy w księdze, nieruchomości bez księgi, zasiedzenie, użytkowanie wieczyste, uzgodnienie treści KW z rzeczywistym stanem prawnym. Porządkuję to, czego nie da się sprzedać, zbudować ani odziedziczyć.',
    intro: 'Nieuregulowany stan prawny blokuje wszystko: sprzedaż, kredyt, pozwolenie na budowę, podział spadku. Dom po dziadkach bez księgi wieczystej, działka „w posiadaniu” od 40 lat bez aktu, wpis nieżyjącego właściciela, granice niezgodne z ewidencją, użytkowanie wieczyste do przekształcenia — takie sprawy leżą latami, bo nikt nie wie, od czego zacząć. Ja wiem. Ustalam, jakie dokumenty istnieją, czego brakuje i którą drogą — wieczystoksięgową, sądową czy administracyjną — najszybciej doprowadzić do stanu, w którym księga mówi prawdę i możesz swoją nieruchomością swobodnie dysponować.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Nieruchomość nie ma księgi wieczystej albo w księdze figuruje ktoś, kto nie żyje od lat.',
      'Użytkujesz działkę od kilkudziesięciu lat bez dokumentu własności i myślisz o zasiedzeniu.',
      'W KW jest błąd: zła powierzchnia, stara hipoteka, wpis, który powinien zostać wykreślony.',
      'Granice działki w terenie nie zgadzają się z ewidencją gruntów lub mapą.',
      'Masz użytkowanie wieczyste i chcesz przekształcić je we własność albo kwestionujesz opłatę.',
      'Notariusz odmówił sporządzenia aktu, bo „stan prawny jest nieuregulowany”.',
    ],
    lists: [
      {
        eyebrow: 'W czym pomagam',
        title: 'Każda droga do czystej księgi.',
        kind: 'check',
        items: [
          { b: 'Zakładanie i prostowanie ksiąg', t: 'wnioski wieczystoksięgowe, wykreślenie martwych wpisów, sprostowanie oznaczenia nieruchomości, ujawnienie budynków i praw.' },
          { b: 'Zasiedzenie', t: 'postępowanie sądowe o stwierdzenie nabycia własności przez zasiedzenie — dowody, świadkowie, dokumenty historyczne.' },
          { b: 'Uzgodnienie treści KW', t: 'powództwo o uzgodnienie treści księgi z rzeczywistym stanem prawnym, gdy wpis jest niezgodny z prawdą.' },
          { b: 'Użytkowanie wieczyste', t: 'przekształcenie we własność, bonifikaty, kwestionowanie aktualizacji opłaty rocznej.' },
          { b: 'Granice i ewidencja', t: 'rozgraniczenie, aktualizacja ewidencji gruntów i budynków, spory o przebieg granicy.' },
        ],
      },
      {
        eyebrow: 'Jak pracuję',
        title: 'Zakres pracy.',
        kind: 'deliverables',
        items: [
          'Badam księgę, dokumenty i archiwa (akty własności ziemi, decyzje uwłaszczeniowe, akty notarialne, orzeczenia) — ustalam, co istnieje, a czego trzeba dopiero „wytworzyć”.',
          'Wybieram najkrótszą skuteczną drogę i mówię Ci, ile potrwa i co jest potrzebne.',
          'Przygotowuję wnioski i pozwy, kompletuję dowody, kontaktuję się z geodetą, gdy potrzebna jest mapa.',
          'Reprezentuję Cię przed sądem wieczystoksięgowym, sądem cywilnym, starostą i innymi organami.',
          'Orientacyjny czas: wpis w KW — tygodnie do kilku miesięcy; zasiedzenie i uzgodnienie treści KW — postępowania wielomiesięczne.',
        ],
      },
    ],
    faq: [
      { q: 'Dom po rodzicach nie ma księgi wieczystej. Czy mogę go sprzedać?', a: 'Dopiero po założeniu księgi i wpisaniu Cię jako właściciela — a do tego potrzebny jest dokument potwierdzający tytuł (akt własności ziemi, postanowienie spadkowe, orzeczenie o zasiedzeniu). Ustalam, co masz, i doprowadzam sprawę do wpisu.' },
      { q: 'Ile lat trzeba posiadać nieruchomość, żeby ją zasiedzieć?', a: '20 lat w dobrej wierze, 30 lat w złej — liczonych od objęcia w samoistne posiadanie, z możliwością doliczenia okresu posiadania poprzedników. Kluczowe są dowody: kto płacił podatek, kto uprawiał, kto remontował. Pomagam je zebrać.' },
      { q: 'W księdze wieczystej wpisana jest hipoteka spłacona 30 lat temu. Jak ją usunąć?', a: 'Potrzebne jest oświadczenie wierzyciela o spłacie albo — gdy wierzyciel nie istnieje — postępowanie sądowe. Ustalam następcę prawnego banku lub instytucji i prowadzę sprawę do wykreślenia.' },
      { q: 'Sąsiad twierdzi, że płot stoi na jego działce. Kto ma rację?', a: 'Rozstrzyga przebieg granicy prawnej, nie płotu. Zaczynam od analizy dokumentów geodezyjnych; jeśli spór pozostaje, prowadzę rozgraniczenie u wójta lub przed sądem. Czasem okazuje się, że pas gruntu został już zasiedziany.' },
      { q: 'Czy warto przekształcić użytkowanie wieczyste we własność?', a: 'Zwykle tak — kończy coroczne opłaty i ryzyko ich aktualizacji, a bonifikaty potrafią znacząco obniżyć koszt. Sprawdzam, czy nieruchomość podlega przekształceniu z mocy prawa, czy na wniosek, i jaką bonifikatę możesz uzyskać.' },
      { q: 'Dostałem pismo o podwyżce opłaty za użytkowanie wieczyste o kilkaset procent. Mogę to zakwestionować?', a: 'Tak, w krótkim terminie od doręczenia — najpierw do Samorządowego Kolegium Odwoławczego, potem do sądu. Aktualizacje opierają się na operatach, które często można podważyć. Nie odkładaj tego: termin jest krótki.' },
      { q: 'Nie mam żadnych dokumentów — tylko wiedzę, że „to zawsze było nasze”. Czy jest szansa?', a: 'Często tak. Dokumenty bywają w archiwach państwowych, u geodety powiatowego, w starych aktach sądowych. Do tego dochodzą świadkowie i dowody posiadania. Sprawdzam, co da się odtworzyć, zanim powiem, jaka droga jest realna.' },
      { q: 'Prowadzisz sprawy w innym mieście? Nieruchomość jest w innym województwie.', a: 'Tak. Postępowania wieczystoksięgowe prowadzę korespondencyjnie, a w sprawach sądowych występuję przed sądami w całej Polsce. Mieszkasz za granicą? Też nie problem — większość klientów w tych sprawach obsługuję w pełni zdalnie.' },
    ],
    cta: {
      heading: 'Nieuregulowany stan prawny nie naprawi się sam.',
      lead: 'Podaj numer księgi wieczystej albo napisz, że jej nie ma, i opisz historię nieruchomości. Bezpłatnie ocenię, jaką drogą najszybciej uporządkować stan prawny i czego będzie trzeba.',
    },
  },

  'wspolwlasnosc-podzialy': {
    h1: 'Współwłasność, spadki i podział majątku',
    introHeading: 'Najpierw rachunek, potem emocje.',
    subtitle: 'Dział spadku, zniesienie współwłasności, podział majątku po rozwodzie, rozliczenie nakładów, zarząd wspólną nieruchomością. Pomagam wyjść ze współwłasności tak, żeby nikt nie został z niczym — albo z niesprawiedliwą spłatą.',
    intro: 'Wspólna nieruchomość rzadko jest wspólnym szczęściem. Rodzeństwo po spadku, byli małżonkowie, wspólnicy — każdy ma inne potrzeby, a jeden może blokować resztę. Sprawy o podział ciągną się latami nie dlatego, że prawo jest skomplikowane, ale dlatego, że emocje przykrywają rachunek. Pomagam go zrobić: ustalam, komu co przysługuje, jak wycenić nakłady i długi, kto ma realną zdolność do spłaty i jaki podział sąd zaakceptuje. Najpierw szukam ugody — jest szybsza i tańsza. Gdy jej nie ma, prowadzę sprawę sądową z jasną strategią.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Odziedziczyliście dom lub mieszkanie w kilka osób i nie możecie się dogadać, co z nim zrobić.',
      'Po rozwodzie pozostała wspólna nieruchomość, często z kredytem hipotecznym.',
      'Jeden ze współwłaścicieli mieszka w nieruchomości, nie płaci i nie zgadza się na sprzedaż.',
      'Włożyłeś w wspólną nieruchomość własne pieniądze — remont, spłatę kredytu — i chcesz to rozliczyć.',
      'Chcesz sprzedać swój udział albo odkupić udziały pozostałych.',
      'Sprawa o dział spadku już się toczy, ale czujesz, że idzie w złą stronę.',
    ],
    lists: [
      {
        eyebrow: 'W czym pomagam',
        title: 'Podział, który da się wykonać.',
        kind: 'check',
        items: [
          { b: 'Dział spadku', t: 'z ustaleniem składu i wartości majątku, rozliczeniem darowizn, zachowków i długów spadkowych.' },
          { b: 'Zniesienie współwłasności', t: 'podział fizyczny, przyznanie jednemu ze spłatą, sprzedaż — z argumentacją, który wariant jest dla Ciebie najlepszy.' },
          { b: 'Podział majątku po rozwodzie', t: 'nieruchomość z kredytem, nakłady z majątku osobistego, nierówne udziały, rozliczenie z bankiem.' },
          { b: 'Rozliczenie nakładów i korzystania', t: 'zwrot wydatków na wspólną rzecz, wynagrodzenie za wyłączne korzystanie, rozliczenie pożytków.' },
          { b: 'Zarząd i sprzedaż udziału', t: 'gdy współwłaściciele blokują decyzje — sądowe upoważnienie do czynności, sprzedaż udziału, ustanowienie zarządcy.' },
        ],
      },
      {
        eyebrow: 'Jak pracuję',
        title: 'Zakres pracy.',
        kind: 'deliverables',
        items: [
          'Ustalam stan prawny i skład majątku — kto ma jaki udział i jakie roszczenia wchodzą w grę.',
          'Proponuję wariant podziału z wyliczeniem spłat i sprawdzam, czy jest wykonalny finansowo.',
          'Prowadzę negocjacje ze współwłaścicielami lub ich pełnomocnikami; przygotowuję ugodę do notariusza albo sądu.',
          'Gdy ugody nie ma — składam wniosek do sądu, pilnuję wyceny biegłego i reprezentuję Cię na każdym etapie.',
          'Orientacyjny czas: ugoda 1–3 miesiące; postępowanie sądowe — zwykle od roku, zależnie od sądu i stopnia sporu.',
        ],
      },
    ],
    faq: [
      { q: 'Brat mieszka w domu po rodzicach i nie chce ani sprzedać, ani spłacić. Co mogę zrobić?', a: 'Każdy współwłaściciel może żądać zniesienia współwłasności — zgoda pozostałych nie jest potrzebna. Sąd przyzna dom bratu ze spłatą, jeśli ma zdolność ją wykonać, albo zarządzi sprzedaż. Dodatkowo możesz żądać wynagrodzenia za to, że korzysta z całości sam.' },
      { q: 'Komu sąd przyzna mieszkanie po rozwodzie?', a: 'Temu, kto wykaże zdolność do spłaty drugiej strony, a przy dzieciach — temu rodzicowi, z którym mieszkają. Sąd nie zmusi nikogo do przejęcia nieruchomości i spłaty wbrew woli. Kredyt hipoteczny dzielony nie jest — wobec banku nadal odpowiadacie oboje.' },
      { q: 'Spłaciłem sam kredyt za wspólne mieszkanie. Odzyskam te pieniądze?', a: 'Tak — raty zapłacone po ustaniu wspólności lub ponad swój udział podlegają rozliczeniu. Potrzebne są potwierdzenia przelewów. Zgłaszam to roszczenie w postępowaniu o podział; niezgłoszone w terminie może przepaść.' },
      { q: 'Czy muszę najpierw mieć stwierdzenie nabycia spadku?', a: 'Tak — dział spadku wymaga wcześniejszego ustalenia, kto jest spadkobiercą (postanowienie sądu albo akt poświadczenia dziedziczenia u notariusza). Jeśli tego nie ma, załatwiam oba etapy, często w jednym postępowaniu.' },
      { q: 'Ile trwa sprawa o dział spadku?', a: 'Ugodowo — kilka tygodni do kilku miesięcy. W sądzie, przy sporze o wartość i sposób podziału, zwykle od roku do dwóch, głównie przez opinie biegłych. Dlatego zawsze zaczynam od próby porozumienia.' },
      { q: 'Mogę sprzedać swój udział bez zgody pozostałych?', a: 'Tak, udział jest zbywalny. W praktyce kupujących jest mało i płacą poniżej wartości. Zwykle korzystniejsze jest zniesienie współwłasności — ale sama możliwość sprzedaży udziału bywa argumentem w negocjacjach.' },
      { q: 'Współwłaściciel wynajmuje wspólny lokal i zatrzymuje cały czynsz. To legalne?', a: 'Nie. Pożytki z rzeczy wspólnej przypadają współwłaścicielom proporcjonalnie do udziałów. Możesz żądać rozliczenia i swojej części czynszu, także za okres wstecz.' },
      { q: 'Jesteśmy zgodni, ale nie wiemy, jak to formalnie zrobić.', a: 'Wtedy sprawa jest prosta i szybka: przygotowuję umowę o dział spadku lub zniesienie współwłasności do notariusza, z rozliczeniem spłat i terminami. Koszt jest wielokrotnie niższy niż postępowanie sądowe.' },
    ],
    cta: {
      heading: 'Współwłasność da się zakończyć — bez wojny w rodzinie.',
      lead: 'Opisz, kto jest współwłaścicielem, jak korzystacie z nieruchomości i czego chcesz. Bezpłatnie ocenię, jaki podział jest realny, ile potrwa i jaka spłata wchodzi w grę.',
    },
  },

  'najem': {
    h1: 'Najem — dla właścicieli i najemców',
    introHeading: 'Pomagam obu stronom — nigdy w tej samej sprawie.',
    subtitle: 'Umowy najmu, najem okazjonalny i instytucjonalny, eksmisja, zaległości czynszowe, kaucja, wypowiedzenie. Zabezpieczam wynajmujących przed lokatorem, którego nie da się usunąć, i najemców przed umową, która zabiera im prawa.',
    intro: 'Najem to relacja, w której najwięcej problemów bierze się z umów pisanych „ze wzoru z internetu”. Wynajmujący dowiaduje się o ochronie praw lokatorów w chwili, gdy najemca przestaje płacić. Najemca odkrywa niedozwolone zapisy, gdy właściciel nie chce oddać kaucji. Pomagam obu stronom — nigdy w tej samej sprawie. Właścicielom: tworzę umowy, które realnie chronią (najem okazjonalny, protokoły, zabezpieczenia), prowadzę windykację i eksmisję zgodnie z prawem. Najemcom: sprawdzam umowy, egzekwuję zwrot kaucji, bronię przed bezprawnym wypowiedzeniem i „czyścicielami”.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Wynajmujesz mieszkanie i chcesz umowy, po której — w razie problemu — odzyskasz lokal w miesiące, nie lata.',
      'Najemca nie płaci od kilku miesięcy i nie reaguje na wezwania.',
      'Wynajmujesz lokal użytkowy albo cały budynek i potrzebujesz umowy „szytej na miarę”.',
      'Właściciel nie oddaje kaucji, wypowiedział umowę bez podstawy albo wchodzi do mieszkania bez zgody.',
      'Mieszkasz za granicą i zarządzasz najmem na odległość.',
      'Dostałeś pozew o eksmisję albo o zapłatę i nie wiesz, jak się bronić.',
    ],
    lists: [
      {
        eyebrow: 'Dla wynajmujących',
        title: 'Umowa, po której śpisz spokojnie.',
        kind: 'check',
        items: [
          { b: 'Najem okazjonalny i instytucjonalny', t: 'komplet dokumentów z oświadczeniem notarialnym — jedyna realna droga do szybkiej eksmisji.' },
          { b: 'Umowa i protokół zdawczo-odbiorczy', t: 'zapisy o kaucji, podwyżkach, naprawach, zwierzętach, podnajmie, wypowiedzeniu — skuteczne, a nie abuzywne.' },
          { b: 'Windykacja i wypowiedzenie', t: 'wezwania, wypowiedzenie zgodne z ustawą o ochronie praw lokatorów, pozew o zapłatę.' },
          { b: 'Eksmisja', t: 'pozew, wyrok, klauzula, komornik — cała droga poprowadzona legalnie, bez ryzyka sprawy karnej dla właściciela.' },
          { b: 'Najem komercyjny', t: 'lokale użytkowe, biura, magazyny — umowy dla właścicieli i przedsiębiorców.' },
        ],
      },
      {
        eyebrow: 'Dla najemców',
        title: 'Twoje prawa też mają zęby.',
        kind: 'check',
        items: [
          { b: 'Sprawdzenie umowy przed podpisem', t: 'klauzule niedozwolone, kaucja, kary, wypowiedzenie, obowiązki napraw.' },
          { b: 'Zwrot kaucji', t: 'wezwanie i pozew, gdy właściciel zatrzymuje kaucję bez podstawy albo „na odświeżenie”.' },
          { b: 'Obrona przed wypowiedzeniem i eksmisją', t: 'ocena, czy wypowiedzenie jest ważne; obrona w postępowaniu sądowym; lokal socjalny.' },
          { b: 'Naruszenia właściciela', t: 'wejście bez zgody, odcięcie mediów, wymiana zamków — reakcja prawna i roszczenia.' },
        ],
      },
    ],
    faq: [
      { q: 'Czym różni się najem okazjonalny od zwykłego?', a: 'Najem okazjonalny (dla właścicieli-osób fizycznych) wyłącza część ochrony lokatorów: po wygaśnięciu umowy najemca musi opuścić lokal, a właściciel — po klauzuli wykonalności — kieruje sprawę wprost do komornika, bez procesu o eksmisję. Wymaga oświadczenia notarialnego najemcy i zgłoszenia do urzędu skarbowego.' },
      { q: 'Najemca nie płaci trzeci miesiąc. Mogę wymienić zamki?', a: 'Nie — to przestępstwo (art. 191 § 1a KK) i droga do zapłaty zadośćuczynienia własnemu dłużnikowi. Legalna ścieżka: wezwanie z miesięcznym terminem, wypowiedzenie, pozew o eksmisję i zapłatę, komornik. Prowadzę ją tak, żeby trwała jak najkrócej.' },
      { q: 'Ile trwa eksmisja?', a: 'Przy najmie okazjonalnym — zwykle 2–4 miesiące od wygaśnięcia umowy. Przy zwykłym najmie — od kilku miesięcy do ponad roku, zależnie od sądu i tego, czy lokatorowi przysługuje lokal socjalny. Dlatego umowa ma takie znaczenie.' },
      { q: 'Właściciel nie oddaje kaucji od dwóch miesięcy. Co robić?', a: 'Kaucja podlega zwrotowi w ciągu miesiąca od opróżnienia lokalu, po potrąceniu udokumentowanych należności. Wysyłam wezwanie, a jeśli nie działa — pozew. Przy protokole zdawczo-odbiorczym bez uwag szanse są bardzo wysokie.' },
      { q: 'Czy właściciel może podnieść czynsz w trakcie umowy?', a: 'W umowie na czas określony — tylko jeśli przewiduje ona klauzulę waloryzacyjną. Poza tym podwyżka wymaga wypowiedzenia wysokości czynszu z zachowaniem ustawowych terminów i limitów. Sprawdzam, czy podwyżka, którą dostałeś, jest legalna.' },
      { q: 'Wynajmuję mieszkanie z zagranicy. Jak to bezpiecznie zorganizować?', a: 'Komplet dokumentów najmu okazjonalnego, szczegółowy protokół ze zdjęciami, pełnomocnictwo dla osoby w Polsce lub obsługa zdalna. Przygotowuję to w całości online — podpisy i notariusz da się załatwić bez Twojego przyjazdu.' },
      { q: 'Kto płaci za naprawy: ja czy najemca?', a: 'Drobne naprawy i konserwacja obciążają najemcę, poważne awarie instalacji i elementów budynku — właściciela. Granica bywa sporna, dlatego doprecyzowuję ją w umowie z konkretną listą.' },
      { q: 'Wynajmuję lokal pod sklep. Czy przepisy o ochronie lokatorów mnie dotyczą?', a: 'Nie — dotyczą tylko lokali mieszkalnych. W najmie komercyjnym strony mają dużą swobodę, co oznacza, że wszystko, czego nie wpiszesz do umowy, działa przeciw Tobie. Tu umowa jest jeszcze ważniejsza.' },
    ],
    cta: {
      heading: 'Dobra umowa najmu kosztuje mniej niż jeden miesiąc bez czynszu.',
      lead: 'Prześlij umowę — swoją albo tę, którą dostałeś do podpisu — lub opisz problem z najemcą czy właścicielem. Bezpłatnie ocenię, co Ci grozi i co da się zrobić.',
    },
  },

  'sluzebnosci-odszkodowania': {
    h1: 'Służebności, słupy na działce i odszkodowania',
    introHeading: 'Firmy przesyłowe liczą na Twoją niewiedzę.',
    subtitle: 'Słupy, linie, rury i gazociągi bez umowy, wynagrodzenie za bezumowne korzystanie, służebność przesyłu, droga konieczna, zasiedzenie służebności. Wyliczam, co Ci się należy, i egzekwuję to od firm przesyłowych i sąsiadów.',
    intro: 'Na setkach tysięcy polskich działek stoją słupy i biegną rury postawione dekady temu bez żadnej umowy. Właściciele latami nie wiedzą, że mogą żądać za to pieniędzy — a firmy przesyłowe wiedzą doskonale i liczą na przedawnienie albo zasiedzenie. Wyrok Trybunału Konstytucyjnego z grudnia 2025 r. odebrał im najważniejszy argument. Prowadzę sprawy o wynagrodzenie za bezumowne korzystanie (do 10 lat wstecz), o ustanowienie odpłatnej służebności przesyłu, o przesunięcie lub usunięcie urządzeń. Drugi front to sąsiedzi: droga konieczna, gdy działka nie ma dostępu do drogi publicznej, zasiedzenie służebności przejazdu, wynagrodzenie za korzystanie z cudzego gruntu.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Na Twojej działce stoi słup, transformator albo biegnie linia, gazociąg czy wodociąg — i nikt Ci za to nie płaci.',
      'Firma przesyłowa odpisała, że „nabyła służebność przez zasiedzenie” albo zaproponowała symboliczną kwotę.',
      'Chcesz budować, ale urządzenia przesyłowe blokują działkę — potrzebujesz ich przesunięcia.',
      'Twoja działka nie ma prawnego dostępu do drogi publicznej albo sąsiad zamknął dojazd, z którego korzystałeś od lat.',
      'Sąsiad żąda od Ciebie opłat za przejazd, który działa od pokoleń.',
      'Otrzymałeś propozycję umowy służebności od inwestora i nie wiesz, czy kwota jest uczciwa.',
    ],
    lists: [
      {
        eyebrow: 'Czego możesz żądać',
        title: 'Co Ci przysługuje.',
        kind: 'check',
        items: [
          { b: 'Wynagrodzenia za bezumowne korzystanie', t: 'do 10 lat wstecz — za każdy rok, w którym firma używała Twojej działki bez umowy.' },
          { b: 'Odpłatnej służebności przesyłu', t: 'jednorazowe wynagrodzenie za przyszłość, ustalone przez sąd na podstawie operatu rzeczoznawcy.' },
          { b: 'Przesunięcia lub usunięcia urządzeń', t: 'gdy blokują zabudowę, a istnieje inne rozwiązanie techniczne.' },
          { b: 'Drogi koniecznej', t: 'sądowego ustanowienia dojazdu przez działkę sąsiada — za wynagrodzeniem, po najmniej uciążliwej trasie.' },
          { b: 'Stwierdzenia zasiedzenia służebności', t: 'gdy od ponad 20–30 lat korzystasz z utwardzonej drogi przez cudzy grunt.' },
        ],
      },
      {
        eyebrow: 'Jak pracuję',
        title: 'Zakres pracy.',
        kind: 'deliverables',
        items: [
          'Ustalam, czy urządzenia mają podstawę prawną (decyzja, umowa, służebność) — od tego zależy, co i za jaki okres możesz żądać.',
          'Szacuję wysokość roszczenia na podstawie parametrów działki i orzecznictwa, żebyś wiedział, o co gra.',
          'Wzywam przedsiębiorstwo do zapłaty i negocjuję; większość firm zaczyna rozmawiać dopiero po piśmie od adwokata.',
          'Prowadzę postępowanie sądowe z udziałem biegłego rzeczoznawcy i geodety; pilnuję, żeby operat nie był zaniżony.',
          'Orientacyjny czas: wezwanie i negocjacje 1–3 miesiące; postępowanie sądowe zwykle 1–2 lata.',
        ],
      },
    ],
    faq: [
      { q: 'Słup stoi na działce od lat 70. Czy nie jest za późno?', a: 'Nie. Roszczenie o wynagrodzenie za bezumowne korzystanie obejmuje ostatnie 10 lat, a służebność przesyłu na przyszłość można ustanowić w każdym czasie. Wyrok TK z 2 grudnia 2025 r. (P 10/16) podważył zasiedzenie liczone z okresów sprzed 2008 r. — najczęstszy argument firm przesyłowych.' },
      { q: 'Ile mogę dostać za słup na działce?', a: 'Zależy od rodzaju urządzenia, powierzchni pasa ograniczonego użytkowania, przeznaczenia działki (budowlana czy rolna) i cen w okolicy. Za pojedynczy słup na gruncie rolnym — kilka tysięcy; za linię wysokiego napięcia przez działkę budowlaną — dziesiątki, czasem setki tysięcy. Wstępny szacunek robię bezpłatnie.' },
      { q: 'Firma przesyłowa twierdzi, że ma decyzję z czasów PRL. Co wtedy?', a: 'Stara decyzja wywłaszczeniowa może być skuteczną podstawą — ale musi istnieć, dotyczyć tej działki i tego urządzenia. Żądam jej okazania i sprawdzam. Zaskakująco często okazuje się, że jej nie ma albo dotyczy czegoś innego.' },
      { q: 'Kto płaci za przesunięcie słupa, gdy chcę budować?', a: 'Jeśli urządzenie stoi bez tytułu prawnego — co do zasady przedsiębiorstwo. Jeśli ma służebność lub decyzję — zwykle wnioskujący, chyba że umowa stanowi inaczej. Analizuję podstawę i negocjuję podział kosztów.' },
      { q: 'Moja działka nie ma dostępu do drogi. Sąsiad nie zgadza się na przejazd.', a: 'Sąd ustanowi drogę konieczną bez zgody sąsiada — za wynagrodzeniem, po trasie najmniej dla niego uciążliwej. Postępowanie wymaga biegłego geodety i rzeczoznawcy. Ustalam najlepszy wariant przebiegu i prowadzę sprawę.' },
      { q: 'Jeżdżę przez działkę sąsiada od 35 lat. Czy to już moje prawo?', a: 'Jeśli droga jest utwardzona (płyty, szuter, mostek — „trwałe i widoczne urządzenie”) i to Ty lub Twoi poprzednicy ją wykonaliście, są przesłanki zasiedzenia służebności. Sam ślad kół po trawie zwykle nie wystarcza. Oceniam dowody przed złożeniem wniosku.' },
      { q: 'Inwestor OZE proponuje mi umowę służebności pod kabel. Podpisać?', a: 'Nie przed sprawdzeniem: kwota, zakres pasa, ograniczenia zabudowy, czas trwania, kto usuwa urządzenia po zakończeniu inwestycji. Umowy inwestorów zabezpieczają głównie inwestora. Negocjuję warunki albo mówię, kiedy odejść od stołu.' },
      { q: 'Przegrałem już sprawę z powodu zasiedzenia. Da się coś zrobić?', a: 'Po wyroku TK z grudnia 2025 r. w określonych sytuacjach można wnosić o wznowienie postępowania — termin jest krótki, liczony od publikacji wyroku. Sprawdzam, czy Twoja sprawa się kwalifikuje.' },
    ],
    cta: {
      heading: 'Słup stoi na Twoim gruncie. Pieniądze należą się Tobie.',
      lead: 'Prześlij zdjęcia urządzeń, numer działki i pisma od firmy przesyłowej, jeśli je masz. Bezpłatnie oszacuję, o jakie kwoty gra się w Twojej sprawie i czy warto ją prowadzić.',
    },
  },

  'grunty-rolne-oze': {
    h1: 'Grunty rolne, dzierżawa i inwestycje OZE',
    introHeading: 'Ziemia rolna gra według własnych reguł.',
    subtitle: 'Obrót ziemią rolną, KOWR, dzierżawa pod fotowoltaikę i wiatraki, umowy z inwestorami, odrolnienie, klasy gruntów. Pomagam właścicielom ziemi zarabiać na niej bezpiecznie — i nie podpisać umowy, która zablokuje działkę na 30 lat.',
    intro: 'Ziemia rolna podlega osobnym regułom: ograniczeniom w obrocie, prawu pierwokupu KOWR, ochronie gruntów wysokich klas, podatkom. A do tego doszła fala inwestorów OZE z gotowymi umowami dzierżawy „do podpisu”. Widziałem umowy, które blokowały grunt na lata bez złotówki czynszu, przenosiły na właściciela ryzyko podatkowe i uniemożliwiały jego sprzedaż. Pomagam sprzedawać i kupować grunty rolne zgodnie z ustawą, negocjuję umowy dzierżawy pod fotowoltaikę i wiatraki tak, żeby to właściciel na nich zarabiał, prowadzę odrolnienie i sprawy z KOWR.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Inwestor zaproponował dzierżawę działki pod farmę fotowoltaiczną lub wiatrak i dał umowę do podpisu.',
      'Chcesz sprzedać albo kupić grunt rolny i nie wiesz, czy potrzebujesz zgody KOWR.',
      'Masz działkę rolną, na której chcesz budować — dom albo inwestycję.',
      'Dzierżawisz ziemię (jako właściciel lub rolnik) i umowa się kończy, jest wypowiadana lub nie jest wykonywana.',
      'Zastanawiasz się nad skutkami podatkowymi dzierżawy pod OZE (VAT, podatek od nieruchomości, KRUS).',
      'Ktoś wydobywa piasek, składuje odpady albo inaczej wykorzystuje Twoją działkę rolną bez zezwoleń.',
    ],
    lists: [
      {
        eyebrow: 'W czym pomagam',
        title: 'Ziemia rolna bez pułapek.',
        kind: 'check',
        items: [
          { b: 'Umowy dzierżawy pod OZE', t: 'analiza i negocjacje: czynsz i jego waloryzacja, okres blokady gruntu, podatki, rekultywacja, zabezpieczenia, prawo do sprzedaży działki.' },
          { b: 'Obrót gruntami rolnymi', t: 'sprzedaż i zakup zgodnie z ustawą o kształtowaniu ustroju rolnego, zgody i pierwokup KOWR, status rolnika indywidualnego.' },
          { b: 'Odrolnienie i zabudowa', t: 'zmiana przeznaczenia, wyłączenie z produkcji rolnej, zabudowa zagrodowa, WZ dla działki rolnej.' },
          { b: 'Dzierżawa rolna', t: 'umowy, wypowiedzenia, rozliczenia nakładów, spory między właścicielem a dzierżawcą.' },
          { b: 'Odpowiedzialność właściciela gruntu', t: 'nielegalne wydobycie kopalin, odpady, samowolne wykorzystanie działki przez osoby trzecie.' },
        ],
      },
      {
        eyebrow: 'Jak pracuję',
        title: 'Zakres pracy.',
        kind: 'deliverables',
        items: [
          'Sprawdzam działkę: klasa gruntu, plan miejscowy lub ogólny, dostęp do sieci i drogi — czy inwestycja jest w ogóle realna.',
          'Czytam umowę inwestora zdanie po zdaniu i przygotowuję listę zmian z uzasadnieniem — Ty decydujesz, o co walczyć.',
          'Negocjuję z inwestorem lub jego prawnikami; przy sprzedaży gruntu prowadzę procedurę z KOWR i notariuszem.',
          'Zabezpieczam kwestie podatkowe we współpracy z Twoim księgowym lub doradcą podatkowym.',
          'Orientacyjny czas: analiza umowy dzierżawy 3–5 dni roboczych; transakcja z udziałem KOWR — od kilku tygodni.',
        ],
      },
    ],
    faq: [
      { q: 'Czy na każdej działce rolnej można postawić farmę fotowoltaiczną?', a: 'Nie. Decydują klasa gruntu (realnie klasy IV–VI), zapisy planu miejscowego lub ogólnego oraz możliwość przyłączenia do sieci. Zanim podpiszesz umowę z inwestorem, sprawdzam, czy inwestycja ma szansę — bo umowa blokuje działkę nawet wtedy, gdy farma nigdy nie powstanie.' },
      { q: 'Inwestor chce podpisać umowę przedwstępną dzierżawy na 2–3 lata „na formalności”. To normalne?', a: 'To częsta praktyka, ale niebezpieczna: działka jest zablokowana, a czynsz płatny dopiero od uruchomienia farmy. Negocjuję opłatę za okres rezerwacji, maksymalny czas blokady i jasne warunki wygaśnięcia umowy.' },
      { q: 'Czy czynsz z dzierżawy pod fotowoltaikę jest zwolniony z VAT?', a: 'Nie — dzierżawa na cele inne niż rolnicze podlega VAT (23%), także gdy jesteś rolnikiem ryczałtowym. Jeśli prowadzisz działalność i jesteś czynnym podatnikiem VAT, faktura musi zawierać podatek. Trzeba to uwzględnić w negocjacji kwoty czynszu.' },
      { q: 'Kto płaci podatek od nieruchomości po postawieniu farmy na mojej ziemi?', a: 'Grunt pod farmą przestaje być opodatkowany podatkiem rolnym, a zaczyna — znacznie wyższym podatkiem od nieruchomości. Dobra umowa przenosi ten ciężar na inwestora. Zła — zostawia go właścicielowi.' },
      { q: 'Kupuję hektar ziemi rolnej pod dom. Potrzebuję zgody KOWR?', a: 'Zależy od powierzchni, położenia (w granicach miasta czy poza) i tego, czy jesteś rolnikiem indywidualnym. Działki do 1 ha kupuje się swobodniej; powyżej — wchodzą ograniczenia i pierwokup KOWR. Sprawdzam konkretną działkę przed umową przedwstępną.' },
      { q: 'Sprzedaję ziemię rolną. KOWR może mi ją „zabrać”?', a: 'KOWR może wykonać prawo pierwokupu lub nabycia w określonych sytuacjach — wtedy kupuje po cenie z umowy. Procedura wymaga zawiadomienia i odczekania terminów. Prowadzę ją tak, żeby transakcja nie utknęła z powodu braków formalnych.' },
      { q: 'Sąsiad pobiera piasek z mojej działki „za zgodą” sprzed lat. Czy mi coś grozi?', a: 'Tak — wydobycie kopalin bez koncesji to opłata podwyższona (40-krotność stawki), odpowiedzialność karna i podatkowa, a właściciel godzący się na proceder może zostać nią obciążony. Trzeba działać od razu: pisemnie cofnąć zgodę, udokumentować stan, zabezpieczyć się prawnie.' },
      { q: 'Dzierżawca nie płaci i nie schodzi z ziemi. Co mogę zrobić?', a: 'Wypowiedzenie umowy zgodnie z jej treścią i Kodeksem cywilnym (dzierżawa gruntów rolnych ma szczególne terminy), wezwanie do zapłaty, a potem pozew o zapłatę i wydanie nieruchomości. Sprawdzam umowę i wybieram najszybszą drogę.' },
    ],
    cta: {
      heading: 'Zanim podpiszesz umowę z inwestorem — przeczytajmy ją razem.',
      lead: 'Prześlij projekt umowy dzierżawy lub numer działki. Bezpłatnie ocenię, czy inwestycja jest realna, które zapisy działają przeciw Tobie i jaki czynsz jest rynkowy.',
    },
  },

  'obsluga-podmiotow-profesjonalnych': {
    h1: 'Obsługa prawna firm z rynku nieruchomości',
    introHeading: 'Znam Twoją branżę od środka.',
    subtitle: 'Deweloperzy, biura nieruchomości, zarządcy i wspólnoty, inwestorzy, firmy budowlane, fundusze najmu. Stała współpraca albo projekt — z prawnikiem, który zajmuje się wyłącznie nieruchomościami i odpowiada w godzinach, nie tygodniach.',
    intro: 'Firma działająca na rynku nieruchomości podpisuje dziesiątki umów rocznie, a każda z nich niesie ryzyko, którego koszt ujawnia się po latach. Ogólna kancelaria uczy się Twojej branży na Twój koszt. Ja znam ją od środka — po latach pracy w kancelarii SPCG, jednej z czołowych w Polsce, i w praktyce własnej, wyłącznie w prawie nieruchomości. Obsługuję deweloperów (umowy deweloperskie, prospekty, rachunki powiernicze, roszczenia nabywców), pośredników (umowy pośrednictwa, odpowiedzialność, spory o prowizję), wspólnoty i zarządców (uchwały, windykacja, roszczenia wobec dewelopera), inwestorów i firmy budowlane. W formie abonamentu albo projektowo — zdalnie, z jasnymi zasadami rozliczeń.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Twoja firma nie ma stałego prawnika, a umowy „jakoś się piszą” na wzorach z poprzednich lat.',
      'Masz prawnika ogólnego, ale sprawy nieruchomościowe zajmują mu za dużo czasu i kosztują za dużo.',
      'Nabywcy zgłaszają roszczenia: kary za opóźnienie, wady, metraż — i potrzebujesz strategii, nie gaszenia pożarów.',
      'Prowadzisz biuro nieruchomości i chcesz umów, które przetrwają kontrolę UOKiK i spór o prowizję.',
      'Zarządzasz wspólnotami i potrzebujesz wsparcia w uchwałach, windykacji i sporach z deweloperem.',
      'Realizujesz inwestycję i chcesz mieć prawnika od WZ po ostatni akt notarialny.',
    ],
    lists: [
      {
        eyebrow: 'Dla kogo',
        title: 'Znam Twoją branżę.',
        kind: 'check',
        items: [
          { b: 'Deweloperzy', t: 'umowy rezerwacyjne i deweloperskie, prospekty, DFG i rachunki powiernicze, odbiory, roszczenia nabywców, umowy z wykonawcami.' },
          { b: 'Biura nieruchomości', t: 'umowy pośrednictwa (zgodne z prawem konsumenckim), klauzule wyłączności, dochodzenie prowizji, odpowiedzialność pośrednika.' },
          { b: 'Wspólnoty i zarządcy', t: 'uchwały i ich zaskarżanie, windykacja, roszczenia wobec dewelopera za wady części wspólnych, umowy z dostawcami.' },
          { b: 'Inwestorzy i fundusze najmu', t: 'due diligence, transakcje, umowy najmu instytucjonalnego, strategia planistyczna, spory.' },
          { b: 'Firmy budowlane', t: 'umowy o roboty budowlane i podwykonawcze, odbiory, kary umowne, gwarancje zapłaty, spory.' },
        ],
      },
      {
        eyebrow: 'Formy współpracy',
        title: 'Abonament albo projekt.',
        kind: 'deliverables',
        items: [
          'Abonament: stała miesięczna kwota za określoną pulę godzin, priorytetowy czas reakcji, znajomość Twoich spraw i dokumentów — bez uczenia się firmy od nowa.',
          'Projekt: konkretna transakcja, inwestycja lub spór z wyceną z góry i jasnym zakresem.',
          'Audyt dokumentów: przegląd wzorów umów i procedur z listą ryzyk i gotowymi poprawkami.',
          'Zastępstwo procesowe: reprezentacja w sądach cywilnych i administracyjnych w całej Polsce.',
          'Zasady: odpowiedź w 24 h robocze, rozliczenie co miesiąc z zestawieniem czynności, żadnych niespodzianek w fakturze.',
        ],
      },
    ],
    faq: [
      { q: 'Czym abonament różni się od zlecania spraw pojedynczo?', a: 'Przewidywalnością kosztu i szybkością. W abonamencie znam Twoje umowy i historię spraw, więc odpowiadam od razu, bez „wdrażania się”. Przy pojedynczych zleceniach każda sprawa zaczyna się od zera. Dla firm z regularnym obrotem abonament wychodzi zwykle taniej.' },
      { q: 'Jak wygląda start współpracy?', a: 'Rozmowa o Twojej firmie i bieżących sprawach, przegląd wzorów umów i dokumentów, propozycja zakresu i wycena. Od pierwszego miesiąca dostajesz konkretne poprawki, nie prezentację.' },
      { q: 'Obsługujesz firmy z innych miast?', a: 'Tak — większość obsługi to dokumenty i korespondencja, które prowadzę zdalnie. Rozprawy i spotkania z kontrahentami w całej Polsce, spotkania osobiste w Lublinie i Warszawie.' },
      { q: 'Jesteśmy małym deweloperem — jedna inwestycja rocznie. Czy to ma sens?', a: 'Szczególnie wtedy. Duży deweloper ma dział prawny; mały ryzykuje całą inwestycją przez jeden błędny zapis w umowie deweloperskiej albo prospekcie. Projektowa obsługa jednej inwestycji od WZ po akty to najczęstszy model u moich klientów tej wielkości.' },
      { q: 'Prowadzę biuro nieruchomości. Klienci kwestionują prowizję po transakcji „za naszymi plecami”. Da się to zabezpieczyć?', a: 'Tak — dobrze napisana umowa pośrednictwa z klauzulą wyłączności i zapisem o transakcji z klientem wskazanym przez biuro broni się w sądzie. Wzory z sieci często zawierają klauzule niedozwolone, przez co całe zapisy o prowizji upadają. Robię audyt i poprawiam.' },
      { q: 'Wspólnota chce dochodzić wad od dewelopera. Kto może to zrobić?', a: 'Wspólnota po przelewie roszczeń od właścicieli albo właściciele indywidualnie. Ustalam, kto ma legitymację, przygotowuję uchwały i umowy cesji, prowadzę sprawę — od ekspertyzy po wyrok.' },
      { q: 'Czy zajmujesz się też prawem pracy, podatkami, RODO w naszej firmie?', a: 'Nie — tylko nieruchomościami i tym, co z nimi bezpośrednio związane. W innych obszarach polecam sprawdzonych specjalistów i koordynuję z nimi pracę, jeśli sprawa tego wymaga. Dzięki temu jestem dobry w tym, co robię.' },
      { q: 'Jak rozliczasz pracę?', a: 'Abonament — stała kwota miesięczna za ustaloną pulę godzin, ponad nią stawka godzinowa. Projekty — wycena z góry. Każdy miesiąc kończy zestawienie czynności. Wycenę przygotowuję po rozpoznaniu potrzeb firmy, bez zobowiązań.' },
    ],
    cta: {
      heading: 'Prawnik, który zna Twoją branżę, kosztuje mniej niż ten, który się jej uczy.',
      lead: 'Opisz firmę, skalę działalności i bieżące potrzeby. Bezpłatnie zaproponuję zakres współpracy i formę rozliczenia — abonament albo projekt.',
    },
  },

});
