/* services-lite-fill.jsx — full content for 7 pages that previously rendered the
   lite fallback. Loads AFTER services-b2b.jsx; merges into window.SERVICE_CONTENT.
   4 usługowe ("Ty" → doFor = "Co dla Ciebie robię"); 3 B2B (doFor = "Zakres współpracy"). */

Object.assign(window.SERVICE_CONTENT, {

  'nieruchomosci-rolne': {
    h1: 'Nieruchomości rolne (UKUR, KOWR)',
    subtitle: 'Kupujesz, sprzedajesz albo dzielisz grunt rolny i nie wiesz, czy wpadasz pod przepisy o ustroju rolnym? Sprawdzam status gruntu, potrzebę zgody KOWR i prawo pierwokupu — i prowadzę transakcję tak, żeby była ważna.',
    intro: 'Obrót ziemią rolną rządzi się osobnymi, surowymi przepisami — ustawą o kształtowaniu ustroju rolnego. To ona decyduje, czy grunt jest „rolny”, czy do zakupu potrzeba zgody KOWR, czy przysługuje prawo pierwokupu i jakie oświadczenia trzeba złożyć u notariusza. Pomyłka bywa dotkliwa: transakcja może okazać się nieważna, a grunt — przejęty przez KOWR. Ustalam status Twojej ziemi i prowadzę transakcję tak, żeby była bezpieczna i skuteczna.',
    introHeading: 'Ziemia rolna to osobne przepisy.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Kupujesz albo sprzedajesz działkę i nie wiesz, czy jest traktowana jako rolna.',
      'Notariusz wspomniał o zgodzie KOWR albo prawie pierwokupu.',
      'Chcesz podzielić albo przekazać grunt rolny w rodzinie.',
      'Masz działkę rolną i planujesz ją zabudować albo odrolnić.',
      'Nie wiesz, jakie oświadczenia musisz złożyć przy transakcji.',
      'Obawiasz się, że umowa może okazać się nieważna.',
    ],
    doFor: [
      'Ustalam, czy grunt jest nieruchomością rolną w rozumieniu przepisów o ustroju rolnym.',
      'Sprawdzam, czy transakcja wymaga zgody KOWR i czy przysługuje prawo pierwokupu.',
      'Weryfikuję ograniczenia w obrocie i pięcioletnie obowiązki nabywcy.',
      'Przygotowuję właściwe oświadczenia i dokumenty do umowy u notariusza.',
      'Dobieram bezpieczną ścieżkę transakcji, także przy przekazaniu w rodzinie (osoby bliskie).',
      'Prowadzę całą transakcję tak, żeby była ważna i nie narażała gruntu na przejęcie.',
    ],
    steps: [
      'Opisujesz transakcję — jaka działka, jaki areał, kto kupuje i sprzedaje.',
      'Dostajesz bezpłatną wstępną ocenę w 24 h — mówię, czy wchodzą przepisy o ustroju rolnym i jak przejść transakcję; podaję zakres, cenę i termin.',
      'Działam — sprawdzam status, przygotowuję dokumenty i prowadzę transakcję.',
      'Kupujesz albo sprzedajesz bezpiecznie — z ważną umową.',
    ],
    faq: [
      { q: 'Skąd wiem, czy grunt jest „rolny”?', a: 'Decyduje przeznaczenie i oznaczenie gruntu oraz przepisy o ustroju rolnym, a nie samo to, czy ktoś na nim gospodaruje. Sprawdzam ewidencję, plan miejscowy i księgę wieczystą i mówię jednoznacznie.' },
      { q: 'Kiedy potrzebna jest zgoda KOWR?', a: 'Gdy ziemię rolną powyżej ustawowego progu powierzchni chce kupić osoba niebędąca rolnikiem indywidualnym. Próg był ostatnio podnoszony, dlatego zawsze weryfikuję aktualny stan dla Twojej transakcji. Więcej na stronie o zgodzie KOWR.' },
      { q: 'Co to prawo pierwokupu i kogo dotyczy?', a: 'Przy sprzedaży ziemi rolnej pierwszeństwo zakupu może przysługiwać m.in. dzierżawcy albo KOWR. Trzeba wtedy zawrzeć umowę warunkową i odczekać na decyzję. Prowadzę to prawidłowo, żeby nie unieważnić transakcji.' },
      { q: 'Czy w rodzinie też obowiązują ograniczenia?', a: 'Osoby bliskie są zwolnione z większości ograniczeń — przekazanie ziemi np. dzieciom czy rodzeństwu jest prostsze. Sprawdzam, czy Twój przypadek się kwalifikuje.' },
      { q: 'Co grozi za pominięcie przepisów?', a: 'Nieważność umowy, a nawet możliwość przejęcia gruntu przez KOWR. Dlatego status ziemi ustalam przed transakcją, nie po.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo; umowę zawiera się u notariusza.' },
    ],
    cta: {
      heading: 'Ziemia rolna to osobne przepisy — sprawdźmy je, zanim podpiszesz.',
      lead: 'Opisz transakcję — bezpłatnie ocenię, czy wchodzą przepisy o ustroju rolnym i jak przejść ją bezpiecznie.',
    },
  },

  'dzierzawa-oze': {
    h1: 'Dzierżawa pod fotowoltaikę i wiatraki',
    subtitle: 'Firma OZE chce wydzierżawić Twój grunt na 25–30 lat pod panele albo wiatraki? Analizuję i negocjuję umowę po Twojej stronie — żeby czynsz był uczciwy, a grunt bezpieczny przez całą dekadę.',
    intro: 'Dzierżawa pod fotowoltaikę czy wiatraki potrafi dać właścicielowi stały, atrakcyjny dochód — ale to umowa wiążąca ziemię na kilkadziesiąt lat, pisana przez inwestora i pełna pułapek: symboliczny czynsz w wieloletnim okresie „przygotowań”, brak waloryzacji, słabe zabezpieczenie demontażu, zapisy pozwalające inwestorowi wyjść bez kosztów. Czytam i negocjuję taką umowę po Twojej stronie, żeby dochód był realny, a grunt wrócił do Ciebie w dobrym stanie.',
    introHeading: 'Twój grunt na 30 lat — podpisz świadomie.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Dostałeś od firmy OZE propozycję dzierżawy gruntu pod panele albo wiatraki.',
      'Umowa jest długa, niezrozumiała i wygląda na napisaną pod inwestora.',
      'Nie wiesz, czy oferowany czynsz jest rynkowy.',
      'Martwi Cię, co stanie się z gruntem po zakończeniu umowy.',
      'Inwestor proponuje symboliczną opłatę na okres „przygotowań”.',
      'Chcesz podpisać, ale najpierw wynegocjować bezpieczne warunki.',
    ],
    doFor: [
      'Analizuję całą umowę dzierżawy i wskazuję zapisy niekorzystne dla właściciela.',
      'Weryfikuję, czy czynsz jest rynkowy, i negocjuję jego wysokość oraz zasady na okres przygotowań.',
      'Wprowadzam coroczną waloryzację czynszu, bez ryzyka jego obniżenia.',
      'Zabezpieczam demontaż instalacji i przywrócenie gruntu do stanu rolnego na koszt inwestora, wraz z zabezpieczeniem finansowym.',
      'Wbudowuję prawo wyjścia z umowy, gdy inwestor nie płaci albo nie buduje.',
      'Sprawdzam wiarygodność inwestora i chronię Cię przed ryzykiem „handlu projektem”.',
    ],
    steps: [
      'Przesyłasz umowę — najlepiej z mapą i danymi o powierzchni.',
      'Dostajesz bezpłatną wstępną ocenę w 24 h — mówię, czy warunki są uczciwe i co wynegocjować; podaję zakres, cenę i termin.',
      'Negocjuję — czynsz, waloryzację, zabezpieczenia i warunki wyjścia.',
      'Podpisujesz bezpiecznie — z umową, która chroni Cię przez cały okres dzierżawy.',
    ],
    faq: [
      { q: 'Ile wynosi rynkowy czynsz za dzierżawę pod fotowoltaikę?', a: 'Stawki wahają się zwykle w granicach kilkunastu do ponad dwudziestu tysięcy złotych za hektar rocznie, zależnie od lokalizacji i projektu. Oferty znacznie wyższe bywają sygnałem, że inwestor liczy na dalszą odsprzedaż projektu. Weryfikuję to i negocjuję.' },
      { q: 'Na czym polega pułapka „okresu przygotowań”?', a: 'Inwestor często płaci symboliczną kwotę przez pierwsze 3–5 lat, zanim ruszy budowa — a grunt jest już zablokowany. Negocjuję wynagrodzenie za ten okres i prawo wyjścia, jeśli projekt nie rusza.' },
      { q: 'Czy odzyskam grunt w dobrym stanie po zakończeniu umowy?', a: 'Powinieneś — o ile umowa nakłada na inwestora obowiązek demontażu i przywrócenia gruntu do stanu rolnego, zabezpieczony finansowo. Bez tego zostajesz z problemem. Wpisuję takie zabezpieczenie do umowy.' },
      { q: 'Czy dzierżawa grozi zasiedzeniem mojej ziemi?', a: 'Nie — dzierżawca jest posiadaczem zależnym i nie nabędzie gruntu przez zasiedzenie. Dbam, by umowa jasno to potwierdzała.' },
      { q: 'Czy warto w ogóle podpisywać?', a: 'Często tak — to szansa na stały dochód z ziemi. Ale wyłącznie na uczciwych, dobrze zabezpieczonych warunkach. Mówię wprost, czy proponowana umowa się nadaje.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Twój grunt na 30 lat — podpisz dopiero, gdy umowa naprawdę Cię chroni.',
      lead: 'Prześlij umowę od firmy OZE — bezpłatnie ocenię, czy czynsz i warunki są uczciwe, i powiem, co wynegocjować.',
    },
  },

  'negocjacje-nieruchomosci': {
    h1: 'Negocjacje na rynku nieruchomości',
    subtitle: 'Masz wynegocjować cenę albo warunki zakupu lub sprzedaży nieruchomości i nie chcesz robić tego sam? Prowadzę negocjacje po Twojej stronie — rzeczowo, bez emocji i z argumentami, które działają.',
    intro: 'W transakcji nieruchomościowej negocjuje się nie tylko cenę — także termin, zadatek, warunki odstąpienia, stan wydania, podział kosztów i zabezpieczenia. Druga strona zwykle ma pośrednika albo prawnika, a emocje i przywiązanie do „wymarzonego” mieszkania osłabiają pozycję kupującego. Wchodzę w negocjacje jako Twój pełnomocnik — chłodno, rzeczowo i z prawną wiedzą o tym, co realnie da się ugrać.',
    introHeading: 'Negocjacje bez emocji, z argumentami.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Kupujesz albo sprzedajesz nieruchomość i chcesz wynegocjować lepsze warunki.',
      'Druga strona ma pośrednika albo prawnika, a Ty czujesz się na słabszej pozycji.',
      'Emocje utrudniają Ci twarde negocjacje o cenę.',
      'Chcesz wynegocjować nie tylko cenę, ale i zapisy umowy przedwstępnej.',
      'Utknęliście i rozmowy stanęły w miejscu.',
      'Zależy Ci, żeby ktoś prowadził rozmowy w Twoim imieniu.',
    ],
    doFor: [
      'Ustalam z Tobą cele i granice — cenę, warunki i to, z czego możesz ustąpić.',
      'Prowadzę negocjacje w Twoim imieniu — cena, termin, zadatek, warunki odstąpienia, stan wydania.',
      'Buduję argumentację opartą na stanie prawnym i technicznym nieruchomości (wady, obciążenia, ryzyka).',
      'Chronię Cię przed niekorzystnymi zapisami w umowie przedwstępnej i deweloperskiej.',
      'Odblokowuję rozmowy, które utknęły, i szukam rozwiązań akceptowalnych dla obu stron.',
      'Przekładam ustalenia na bezpieczną umowę.',
    ],
    steps: [
      'Opisujesz transakcję i cel — co kupujesz albo sprzedajesz i co chcesz osiągnąć.',
      'Dostajesz bezpłatną wstępną ocenę w 24 h — mówię, co realnie da się wynegocjować i jaką obrać strategię; podaję zakres, cenę i termin.',
      'Negocjuję — w Twoim imieniu, aż do uzgodnienia warunków.',
      'Masz lepsze warunki — przelane na bezpieczną umowę.',
    ],
    faq: [
      { q: 'Czy naprawdę da się jeszcze zbić cenę?', a: 'Bardzo często tak — zwłaszcza gdy negocjacje oprzeć na konkretach: wykrytych wadach, obciążeniach, sytuacji rynkowej albo stanie technicznym. Argument prawny działa lepiej niż samo „proszę o rabat”.' },
      { q: 'Negocjujesz tylko cenę?', a: 'Nie — równie ważne bywają termin, zadatek, warunki odstąpienia, stan wydania i podział kosztów. Czasem to one dają większą korzyść niż sama obniżka ceny.' },
      { q: 'Po co mi do tego prawnik?', a: 'Bo łączę chłodną, zewnętrzną pozycję negocjacyjną z wiedzą o tym, co da się ugrać i jak zabezpieczyć ustalenia w umowie. Ty nie musisz grać twardo — robię to za Ciebie.' },
      { q: 'Reprezentujesz kupującego czy sprzedającego?', a: 'Obu — ale w danej transakcji tylko jedną stronę. Prowadzę negocjacje po Twojej stronie.' },
      { q: 'Co, jeśli rozmowy i tak się nie powiodą?', a: 'Nic nie tracisz — jeśli warunki nie będą dla Ciebie korzystne, doradzę wyjście z transakcji, zanim się zwiążesz.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Nie negocjuj sam pod presją emocji. Zrobię to za Ciebie.',
      lead: 'Opisz transakcję i cel — bezpłatnie ocenię, co da się wynegocjować, i poprowadzę rozmowy po Twojej stronie.',
    },
  },

  'zgloszenie-budowy': {
    h1: 'Zgłoszenie budowy i robót',
    subtitle: 'Chcesz budować na zgłoszenie zamiast na pozwolenie i uniknąć sprzeciwu urzędu? Przygotowuję zgłoszenie tak, żeby przeszło bez przeszkód — i mówię wprost, kiedy zgłoszenie wystarczy, a kiedy nie.',
    intro: 'Wiele inwestycji — w tym domy jednorodzinne — można dziś zrealizować na zgłoszenie, bez pełnego pozwolenia na budowę. To szybsza i prostsza ścieżka: urząd nie wydaje decyzji, a jedynie w ciągu 21 dni może wnieść sprzeciw; brak sprzeciwu oznacza tak zwaną milczącą zgodę. Haczyk w tym, że cała odpowiedzialność za zgodność z prawem spada na inwestora, a błąd w dokumentach albo w ocenie obszaru oddziaływania kończy się sprzeciwem i opóźnieniem. Przygotowuję zgłoszenie tak, żeby przeszło za pierwszym razem.',
    introHeading: 'Zgłoszenie, które przejdzie za pierwszym razem.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Planujesz budowę i chcesz iść ścieżką zgłoszenia zamiast pełnego pozwolenia.',
      'Nie wiesz, czy Twoja inwestycja w ogóle kwalifikuje się do zgłoszenia.',
      'Budujesz dom jednorodzinny i słyszałeś o uproszczonej procedurze.',
      'Boisz się sprzeciwu urzędu i utraty czasu.',
      'Urząd wniósł już sprzeciw wobec Twojego zgłoszenia.',
      'Chcesz mieć pewność, że nie narazisz się na zarzut samowoli.',
    ],
    doFor: [
      'Oceniam, czy Twoja inwestycja może być realizowana na zgłoszenie, czy wymaga pozwolenia.',
      'Weryfikuję kluczowy punkt — czy obszar oddziaływania mieści się w granicach Twojej działki.',
      'Kompletuję zgłoszenie z wymaganymi dokumentami (projekt, oświadczenie o prawie do dysponowania nieruchomością na cele budowlane).',
      'Sprawdzam zgodność z planem miejscowym albo warunkami zabudowy, żeby uniknąć sprzeciwu.',
      'Reaguję na sprzeciw urzędu — składam odwołanie albo koryguję dokumentację.',
      'Doradzam przy uproszczonej procedurze dla domów jednorodzinnych (m.in. do 70 m²).',
    ],
    steps: [
      'Opisujesz inwestycję — co i gdzie chcesz budować.',
      'Dostajesz bezpłatną wstępną ocenę w 24 h — mówię, czy zgłoszenie wystarczy i jak je przeprowadzić bez sprzeciwu; podaję zakres, cenę i termin.',
      'Działam — kompletuję i składam zgłoszenie albo reaguję na sprzeciw.',
      'Budujesz legalnie — bez zbędnych opóźnień i ryzyka samowoli.',
    ],
    faq: [
      { q: 'Czym różni się zgłoszenie od pozwolenia na budowę?', a: 'Przy zgłoszeniu urząd nie wydaje decyzji — ma jedynie 21 dni na sprzeciw, a jego brak to milcząca zgoda. Jest szybciej i mniej formalnie, ale całą odpowiedzialność za zgodność z prawem ponosi inwestor. Pozwolenie jest wolniejsze, lecz daje mocniejszą, formalną ochronę.' },
      { q: 'Czy dom jednorodzinny można budować na zgłoszenie?', a: 'Tak, o ile obszar oddziaływania budynku mieści się w całości na Twojej działce. Domy do 70 m² na własne cele mieszkaniowe korzystają z jeszcze prostszej procedury. Sprawdzam, czy Twój projekt się kwalifikuje.' },
      { q: 'Co decyduje, czy zgłoszenie wystarczy?', a: 'Rodzaj i wielkość inwestycji, obszar oddziaływania oraz zgodność z planem miejscowym albo warunkami zabudowy. Ocena obszaru oddziaływania jest kluczowa — to najczęstsza przyczyna sprzeciwu. Weryfikuję ją zawczasu.' },
      { q: 'Ile czeka się na możliwość rozpoczęcia budowy?', a: 'Co do zasady 21 dni od kompletnego zgłoszenia, jeśli urząd nie wniesie sprzeciwu. Czasem urząd wydaje wcześniej zaświadczenie o braku podstaw do sprzeciwu, co pozwala ruszyć szybciej.' },
      { q: 'Urząd wniósł sprzeciw — co teraz?', a: 'Można złożyć odwołanie w ciągu 14 dni albo skorygować dokumentację i zgłosić ponownie. Analizuję przyczynę sprzeciwu i wybieram skuteczniejszą drogę.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo; zgłoszenie składa się do urzędu właściwego dla położenia nieruchomości.' },
    ],
    cta: {
      heading: 'Zgłoszenie zamiast pozwolenia — szybciej, o ile zrobione bez błędu.',
      lead: 'Opisz inwestycję — bezpłatnie ocenię, czy zgłoszenie wystarczy, i przygotuję je tak, żeby urząd nie wniósł sprzeciwu.',
    },
  },

  'obsluga-prawna-deweloperow': {
    h1: 'Obsługa prawna deweloperów',
    subtitle: 'Prowadzisz inwestycję deweloperską i potrzebujesz prawnika na cały cykl — od zabezpieczenia gruntu, przez dokumenty sprzedażowe, po posprzedaż? Zapewniam kompleksową obsługę zgodną z ustawą deweloperską.',
    intro: 'Projekt deweloperski to łańcuch ryzyk prawnych ciągnący się latami — od nabycia i zabezpieczenia gruntu, przez zgodność z ustawą deweloperską i Deweloperskim Funduszem Gwarancyjnym, prospekt i umowy z nabywcami, aż po obsługę roszczeń po zakończeniu sprzedaży. Błąd na którymkolwiek etapie potrafi zablokować sprzedaż albo obrócić się roszczeniami nabywców. Obsługuję deweloperów mieszkaniowych i komercyjnych na całym cyklu inwestycji — na stałe albo przy konkretnym projekcie.',
    introHeading: 'Cały cykl inwestycji pod jedną opieką.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Zabezpieczasz grunt pod inwestycję i chcesz pewnego tytułu prawnego.',
      'Uruchamiasz sprzedaż i potrzebujesz prospektu oraz umów zgodnych z ustawą deweloperską.',
      'Musisz ustawić rachunek powierniczy i obowiązki wobec Deweloperskiego Funduszu Gwarancyjnego.',
      'Mierzysz się z roszczeniami nabywców — wady, kary, odstąpienia.',
      'Realizujesz inwestycję komercyjną i negocjujesz umowy najmu albo sprzedaży.',
      'Chcesz jednego prawnika na cały cykl projektu.',
    ],
    doForEyebrow: 'Zakres współpracy',
    doForTitle: 'Zakres współpracy.',
    doFor: [
      'Zabezpieczam nabycie i tytuł prawny do gruntu, w tym due diligence i umowy.',
      'Przygotowuję dokumentację sprzedażową zgodną z ustawą deweloperską — prospekt, umowy deweloperskie i rezerwacyjne.',
      'Ustawiam obsługę rachunku powierniczego i obowiązki wobec Deweloperskiego Funduszu Gwarancyjnego.',
      'Prowadzę obsługę procesu sprzedaży i relacji z nabywcami.',
      'Zarządzam roszczeniami posprzedażowymi — wady, kary umowne, odstąpienia, rękojmia.',
      'Obsługuję inwestycje komercyjne — umowy najmu, sprzedaży i zabezpieczenia.',
    ],
    steps: [
      'Opisujesz inwestycję — jaki projekt, na jakim etapie i czego potrzebujesz.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Działam — zabezpieczam grunt, przygotowuję dokumentację sprzedażową i prowadzę projekt.',
      'Inwestycja poprowadzona bezpiecznie — od gruntu po posprzedaż.',
    ],
    faq: [
      { q: 'Co wymusza ustawa deweloperska i DFG?', a: 'Między innymi rachunek powierniczy dla środków nabywców, prospekt informacyjny i konkretną treść umów, a także składki na Deweloperski Fundusz Gwarancyjny. Ustawiam to tak, żeby sprzedaż była zgodna z przepisami od pierwszego lokalu.' },
      { q: 'Kiedy zacząć obsługę prawną projektu?', a: 'Najlepiej już na etapie gruntu — to tam powstają ryzyka, które później trudno naprawić. Im wcześniej, tym bezpieczniejsza cała inwestycja.' },
      { q: 'Obsługujesz też inwestycje komercyjne?', a: 'Tak — biurowe, handlowe i magazynowe, w tym umowy najmu, sprzedaży i zabezpieczenia. Nie tylko deweloperkę mieszkaniową.' },
      { q: 'Stała obsługa czy jeden projekt?', a: 'Obie opcje — więksi deweloperzy zwykle korzystają ze stałej obsługi, przy pojedynczej inwestycji rozliczam projekt.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Cały cykl inwestycji — od gruntu po posprzedaż — pod jedną prawną opieką.',
      lead: 'Opisz projekt — bezpłatnie ocenię ryzyka i zaproponuję zakres obsługi dopasowany do inwestycji.',
    },
  },

  'obsluga-prawna-biur-nieruchomosci': {
    h1: 'Obsługa prawna biur nieruchomości i pośredników',
    subtitle: 'Prowadzisz biuro nieruchomości i chcesz zabezpieczyć prowizję, umowy oraz zgodność z RODO i AML? Układam bezpieczne umowy pośrednictwa, chronię Twoje wynagrodzenie i biorę na siebie bieżące wsparcie.',
    intro: 'Praca pośrednika stoi na dwóch filarach: skutecznej umowie pośrednictwa i pewnej prowizji. Oba bywają kruche — nieszczelna umowa, obejście biura przez klienta, spór o wyłączność albo o to, komu należy się wynagrodzenie, potrafią pozbawić Cię zapłaty za wykonaną pracę. Do tego dochodzą obowiązki z RODO i przepisów o przeciwdziałaniu praniu pieniędzy. Zabezpieczam biura i pośredników prawnie — na stałe albo przy konkretnej sprawie.',
    introHeading: 'Pewna umowa i chroniona prowizja.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Chcesz umowy pośrednictwa, która realnie zabezpiecza Twoją prowizję.',
      'Klient próbuje obejść biuro i sfinalizować transakcję bez Ciebie.',
      'Toczysz spór o wynagrodzenie albo o wyłączność.',
      'Potrzebujesz zgodności z RODO i obowiązkami AML.',
      'Chcesz audytu ogłoszeń i wzorów dokumentów, które się obronią.',
      'Szukasz stałego wsparcia prawnego dla biura.',
    ],
    doForEyebrow: 'Zakres współpracy',
    doForTitle: 'Zakres współpracy.',
    doFor: [
      'Przygotowuję i opiniuję umowy pośrednictwa — z zabezpieczeniem prowizji i, gdy trzeba, wyłącznością.',
      'Chronię Twoje wynagrodzenie i dochodzę go, gdy klient obchodzi biuro albo odmawia zapłaty.',
      'Wdrażam zgodność z RODO i obowiązkami z zakresu przeciwdziałania praniu pieniędzy (AML).',
      'Audytuję ogłoszenia i materiały pod kątem ryzyk prawnych.',
      'Przygotowuję powtarzalne wzory dokumentów dla biura.',
      'Zapewniam bieżące wsparcie prawne i reprezentację w sporach.',
    ],
    steps: [
      'Opisujesz działalność — jak pracuje biuro i co chcesz zabezpieczyć.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Działam — układam umowy, wdrażam zgodność i chronię prowizję.',
      'Biuro zabezpieczone — pewne umowy, chronione wynagrodzenie, zgodność z przepisami.',
    ],
    faq: [
      { q: 'Jak zabezpieczyć prowizję przed obejściem biura?', a: 'Kluczowa jest dobrze skonstruowana umowa pośrednictwa z jasną podstawą wynagrodzenia i, gdy to zasadne, klauzulą wyłączności oraz zapisami na wypadek obejścia. Układam ją tak, by prowizja była należna i egzekwowalna.' },
      { q: 'Czy umowa pośrednictwa musi mieć formę pisemną?', a: 'Tak — wymaga formy pisemnej albo dokumentowej pod rygorem nieważności. Błąd formalny potrafi przekreślić prawo do prowizji, dlatego pilnuję tego szczególnie.' },
      { q: 'Co z RODO i AML w biurze?', a: 'Pośrednicy przetwarzają dane i podlegają obowiązkom przeciwdziałania praniu pieniędzy. Wdrażam procedury i dokumentację, żeby biuro było zgodne z przepisami i gotowe na kontrolę.' },
      { q: 'Stała obsługa czy jedna sprawa?', a: 'Obie opcje — biura zwykle korzystają ze stałego wsparcia, przy pojedynczym sporze rozliczam projekt.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Pewna umowa i chroniona prowizja — żebyś dostał zapłatę za swoją pracę.',
      lead: 'Opisz, jak działa Twoje biuro — bezpłatnie ocenię ryzyka i zaproponuję, co zabezpieczyć w pierwszej kolejności.',
    },
  },

  'obsluga-prawna-wspolnot': {
    h1: 'Obsługa prawna wspólnot mieszkaniowych',
    subtitle: 'Zarządzasz wspólnotą i mierzysz się z uchwałami, windykacją zaliczek i sporami z deweloperem? Zapewniam obsługę, która trzyma formalności w ryzach i skutecznie chroni interes wspólnoty.',
    intro: 'Wspólnota mieszkaniowa działa uchwałami — a te bywają zaskarżane, kwestionowane i obarczane błędami proceduralnymi, które potrafią je unieważnić. Do tego dochodzi codzienność: zaległe zaliczki, spory z deweloperem o wady części wspólnych, regulaminy i relacje z właścicielami. Obsługuję wspólnoty tak, żeby uchwały się broniły, pieniądze wracały, a roszczenia wobec dewelopera były skutecznie dochodzone — na stałe albo przy konkretnej sprawie.',
    introHeading: 'Uchwały, które się bronią.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Zarządzasz wspólnotą i chcesz, by uchwały były odporne na zaskarżenie.',
      'Właściciele zalegają z zaliczkami na koszty zarządu.',
      'Wspólnota ma wady części wspólnych po deweloperze i chce ich dochodzić.',
      'Potrzebujesz regulaminów i dokumentów, które się obronią.',
      'Toczysz spór z właścicielem albo z zarządcą.',
      'Szukasz stałego wsparcia prawnego dla zarządu wspólnoty.',
    ],
    doForEyebrow: 'Zakres współpracy',
    doForTitle: 'Zakres współpracy.',
    doFor: [
      'Przygotowuję i opiniuję uchwały oraz regulaminy tak, by były skuteczne i odporne na zaskarżenie.',
      'Prowadzę windykację zaliczek i innych należności wspólnoty, od wezwania po egzekucję.',
      'Dochodzę od dewelopera roszczeń za wady części wspólnych, w tym przez cesje roszczeń nabywców.',
      'Bronię uchwał wspólnoty w sporach sądowych o ich uchylenie albo nieistnienie.',
      'Reprezentuję wspólnotę w sporach z właścicielami, zarządcą i osobami trzecimi.',
      'Zapewniam bieżące wsparcie prawne dla zarządu.',
    ],
    steps: [
      'Opisujesz sprawę albo potrzebę — konkretny spór, windykacja czy stała obsługa.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Działam — przygotowuję uchwały, prowadzę windykację albo spór z deweloperem.',
      'Interes wspólnoty zabezpieczony — pewne uchwały, odzyskane pieniądze, dochodzone roszczenia.',
    ],
    faq: [
      { q: 'Ile czasu jest na zaskarżenie uchwały wspólnoty?', a: 'Uchwałę można zaskarżyć do sądu w terminie sześciu tygodni — to termin zawity, po którym prawo do zaskarżenia wygasa. Dlatego reaguję szybko, po którejkolwiek stronie sporu.' },
      { q: 'Jak odzyskać zaległe zaliczki?', a: 'Od wezwania, przez pozew (często w szybszym trybie), po egzekucję komorniczą. Prowadzę windykację seryjnie dla całej wspólnoty i odzyskuję też odsetki oraz koszty.' },
      { q: 'Czy wspólnota może dochodzić wad części wspólnych od dewelopera?', a: 'Tak — roszczenia z rękojmi mają nabywcy, ale można je zebrać we wspólną sprawę przez cesje i odpowiednie uchwały. Buduję taką sprawę i ją prowadzę.' },
      { q: 'Kto jest stroną w sporze o uchwałę?', a: 'Pozywa się albo pozwana jest wspólnota, nie poszczególni właściciele czy zarządca. Prowadzę te sprawy tak, by były poprawne formalnie.' },
      { q: 'Stała obsługa czy jedna sprawa?', a: 'Obie opcje — wspólnoty zwykle korzystają ze stałego wsparcia zarządu, przy pojedynczej sprawie rozliczam projekt.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Uchwały, które się bronią. Pieniądze, które wracają. Deweloper, który odpowiada.',
      lead: 'Opisz sprawę wspólnoty — bezpłatnie ocenię ryzyka i zaproponuję model współpracy.',
    },
  },

});
