/* services-b2b.jsx — Blok 11 (B2B) subpage content, PACZKA 1 (7 podstron).
   Loads AFTER services-content.jsx; merges into the existing SERVICE_CONTENT object
   so these tiles render the full service template instead of the lite fallback. */

Object.assign(window.SERVICE_CONTENT, {

  'obsluga-prawna-zarzadcow': {
    h1: 'Obsługa prawna zarządców nieruchomości',
    subtitle: 'Zarządzasz wspólnotami albo nieruchomościami komercyjnymi i potrzebujesz prawnika, który zna ten świat od środka? Zabezpieczam Twoje umowy o zarządzanie, prowadzę windykację i biorę na siebie spory.',
    intro: 'Zarządca nieruchomości działa na styku wielu interesów — właścicieli, wspólnoty, dostawców i najemców — i przy każdym z nich ryzykuje odpowiedzialnością. Dobrze skonstruowana umowa o zarządzanie, sprawna windykacja zaliczek i czynszów oraz szybkie wsparcie przy sporach to fundament spokojnej pracy. Wspieram zarządców prawnie — jednorazowo przy trudnej sprawie albo na stałe, jako Twój dział prawny na telefon i mail.',
    introHeading: 'Twój dział prawny na telefon i mail.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Zarządzasz wspólnotami albo nieruchomościami i chcesz zabezpieczyć swoje umowy o zarządzanie.',
      'Właściciele albo członkowie wspólnoty zalegają z zaliczkami i opłatami.',
      'Boisz się odpowiedzialności za decyzje podejmowane w ramach zarządu.',
      'Toczysz albo przewidujesz spór z właścicielem, dostawcą albo wspólnotą.',
      'Potrzebujesz wzorów uchwał, regulaminów i pism, które się obronią.',
      'Chcesz jednego prawnika do bieżących pytań i pilnych spraw.',
    ],
    doFor: [
      'Przygotowuję i opiniuję umowy o zarządzanie nieruchomością — z jasnym podziałem obowiązków i granicami odpowiedzialności.',
      'Prowadzę windykację zaliczek, czynszów i opłat eksploatacyjnych, od wezwania po egzekucję.',
      'Przygotowuję uchwały, regulaminy i dokumentację, którą posługujesz się na co dzień.',
      'Reprezentuję Cię w sporach z właścicielami, wspólnotami, najemcami i dostawcami.',
      'Doradzam w kwestiach odpowiedzialności zawodowej i cywilnej zarządcy.',
      'Zapewniam bieżące wsparcie prawne — stałe albo przy konkretnych sprawach.',
    ],
    steps: [
      'Opisujesz swoją działalność — co i dla kogo zarządzasz oraz gdzie widzisz ryzyka.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model współpracy: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Porządkuję dokumenty i procesy — umowy, windykację, wzory pism.',
      'Masz prawnika pod ręką — do bieżących pytań i szybkiej reakcji przy sporach.',
    ],
    faq: [
      { q: 'Za co odpowiada zarządca i jak to ograniczyć?', a: 'Zarządca odpowiada za należyte wykonywanie umowy o zarządzanie i staranność zawodową. Kluczem jest precyzyjny zakres obowiązków w umowie i dokumentowanie decyzji. Układam umowy tak, by odpowiedzialność była jasna i ograniczona do tego, na co realnie masz wpływ.' },
      { q: 'Jak sprawnie windykować zaległe zaliczki?', a: 'Od udokumentowanego wezwania, a przy braku reakcji — pozwem, często w szybszym trybie. Dobrze prowadzona windykacja odzyskuje też odsetki i koszty. Prowadzę ją seryjnie dla całych portfeli.' },
      { q: 'Czy pomożesz z uchwałami i regulaminami?', a: 'Tak. Przygotowuję i opiniuję uchwały oraz regulaminy tak, by były skuteczne i odporne na zaskarżenie.' },
      { q: 'Współpraca stała czy od sprawy?', a: 'Obie opcje. Przy większym portfelu stała obsługa jest wygodniejsza i tańsza; przy pojedynczym problemie rozliczam projekt. Dobieramy model do skali.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Zarządzaj spokojnie — prawną stronę wezmę na siebie.',
      lead: 'Opisz swoją działalność — bezpłatnie zaproponuję model współpracy i wskażę, co zabezpieczyć w pierwszej kolejności.',
    },
  },

  'obsluga-prawna-spoldzielni': {
    h1: 'Obsługa prawna spółdzielni mieszkaniowych',
    subtitle: 'Prowadzisz spółdzielnię i mierzysz się z uchwałami organów, przekształceniami praw do lokali i walnymi zgromadzeniami? Zapewniam obsługę, która wytrzyma zaskarżenia i spory członkowskie.',
    intro: 'Spółdzielnia mieszkaniowa to organizm prawny bardziej złożony niż wspólnota — z własnymi organami, statutem, prawami do lokali i wymagającym otoczeniem członkowskim. Wadliwie zwołane walne, źle przygotowana uchwała albo potknięcie przy przekształceniu prawa do lokalu potrafią sparaliżować działanie i skończyć się procesem. Obsługuję spółdzielnie tak, by decyzje organów były skuteczne, a formalności — odporne na zaskarżenie.',
    introHeading: 'Decyzje organów, które się obronią.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Zarządzasz spółdzielnią i chcesz, by uchwały organów były odporne na zaskarżenie.',
      'Przygotowujesz walne zgromadzenie albo zebranie i chcesz uniknąć błędów proceduralnych.',
      'Prowadzisz przekształcenia spółdzielczych praw do lokali w odrębną własność.',
      'Toczysz spory z członkami spółdzielni albo o statut i regulaminy.',
      'Windykujesz zaległe opłaty od członków i mieszkańców.',
      'Potrzebujesz stałego wsparcia prawnego dla zarządu i rady nadzorczej.',
    ],
    doFor: [
      'Przygotowuję i opiniuję uchwały organów spółdzielni oraz obsługuję walne zgromadzenia i zebrania.',
      'Prowadzę przekształcenia spółdzielczych praw do lokali w odrębną własność.',
      'Aktualizuję i opiniuję statut oraz regulaminy wewnętrzne.',
      'Reprezentuję spółdzielnię w sporach z członkami i osobami trzecimi, w tym o ważność uchwał.',
      'Prowadzę windykację opłat eksploatacyjnych i innych należności.',
      'Doradzam zarządowi i radzie nadzorczej w bieżących decyzjach.',
    ],
    steps: [
      'Opisujesz sprawę albo potrzebę — czy chodzi o konkretną uchwałę, przekształcenia, czy o stałą obsługę.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Działam — przygotowuję dokumenty, prowadzę procedury i reprezentuję spółdzielnię.',
      'Masz pewność proceduralną — decyzje organów, które się obronią.',
    ],
    faq: [
      { q: 'Jak nie dać się zaskarżyć przy uchwale walnego?', a: 'Klucz to prawidłowe zwołanie, porządek obrad, kworum i treść uchwały zgodna ze statutem i ustawą. Prowadzę te formalności krok po kroku, bo najczęstsze wygrane zaskarżenia biorą się z błędów proceduralnych.' },
      { q: 'Jak przebiega przekształcenie prawa do lokalu w odrębną własność?', a: 'Od weryfikacji stanu prawnego, przez uchwały i rozliczenia, po akt notarialny i wpis do księgi wieczystej. Prowadzę całą procedurę tak, by przeszła bez zakłóceń.' },
      { q: 'Spór z członkiem spółdzielni — jak go poprowadzić?', a: 'Zależnie od przedmiotu — od odpowiedzi na żądania, przez obronę uchwał, po proces. Reprezentuję spółdzielnię, dbając o jej interes i wizerunek.' },
      { q: 'Obsługa stała czy do konkretnej sprawy?', a: 'Obie opcje. Spółdzielnie zwykle korzystają ze stałej obsługi zarządu i rady; przy jednorazowej sprawie rozliczam projekt.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Uchwały, które się obronią. Procedury bez potknięć.',
      lead: 'Opisz sprawę albo potrzebę spółdzielni — bezpłatnie ocenię ryzyka i zaproponuję model współpracy.',
    },
  },

  'obsluga-prawna-firm-budowlanych': {
    h1: 'Obsługa prawna generalnych wykonawców i firm budowlanych',
    subtitle: 'Realizujesz kontrakty budowlane i potrzebujesz prawnika, który rozumie place budowy, podwykonawców i kary umowne? Zabezpieczam Twoje umowy o roboty, gwarancję zapłaty i prowadzę spory.',
    intro: 'W budownictwie pieniądze i ryzyko idą w parze: opóźnienia, roszczenia podwykonawców, kary umowne, spory o zakres i jakość robót potrafią zjeść marżę całego kontraktu. Dobrze napisana umowa o roboty budowlane, zabezpieczona gwarancja zapłaty i sprawne prowadzenie sporów to różnica między zyskownym a stratnym projektem. Wspieram generalnych wykonawców i firmy budowlane — od umowy po egzekucję należności.',
    introHeading: 'Różnica między zyskownym a stratnym kontraktem.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Negocjujesz albo realizujesz kontrakt budowlany i chcesz zabezpieczyć swoje interesy.',
      'Inwestor zwleka z płatnościami i myślisz o gwarancji zapłaty za roboty budowlane.',
      'Masz spór z inwestorem albo podwykonawcą o zakres, jakość albo wynagrodzenie.',
      'Grożą Ci kary umowne za opóźnienie albo sam chcesz je egzekwować.',
      'Zmagasz się z roszczeniami podwykonawców i odpowiedzialnością solidarną.',
      'Potrzebujesz wsparcia przy kontraktach na warunkach FIDIC.',
    ],
    doFor: [
      'Przygotowuję i negocjuję umowy o roboty budowlane — zakres, terminy, płatności, kary, odbiory, gwarancje.',
      'Zabezpieczam Twoje wynagrodzenie, w tym przez gwarancję zapłaty za roboty budowlane.',
      'Prowadzę spory z inwestorami i podwykonawcami — o wynagrodzenie, zakres i jakość robót.',
      'Zarządzam ryzykiem kar umownych — bronię przed nimi albo je egzekwuję.',
      'Doradzam przy odpowiedzialności solidarnej wobec podwykonawców i przy kontraktach FIDIC.',
      'Prowadzę windykację należności z kontraktów budowlanych.',
    ],
    steps: [
      'Opisujesz kontrakt albo spór — jaki projekt, jaka umowa i na czym polega problem.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Działam — negocjuję umowę, zabezpieczam płatności albo prowadzę spór.',
      'Kontrakt pod kontrolą — zabezpieczone wynagrodzenie i mniejsze ryzyko.',
    ],
    faq: [
      { q: 'Co daje gwarancja zapłaty za roboty budowlane?', a: 'To ustawowy instrument, który pozwala wykonawcy żądać od inwestora zabezpieczenia zapłaty — a brak takiego zabezpieczenia w wyznaczonym terminie daje podstawę do odstąpienia od umowy z winy inwestora. To realna dźwignia przy niepewnym płatniku; pomagam ją prawidłowo uruchomić.' },
      { q: 'Jak bronić się przed karami umownymi?', a: 'Przez wykazanie, że opóźnienie nie wynika z Twojej winy, oraz przez żądanie miarkowania kary, gdy jest rażąco wygórowana. Analizuję kontrakt i buduję obronę już na etapie korespondencji.' },
      { q: 'Odpowiadam za długi wobec podwykonawców inwestora?', a: 'Przy odpowiedzialności solidarnej to inwestor odpowiada za zapłatę podwykonawcom obok wykonawcy — ale zasady i zgłoszenia mają swoje rygory. Porządkuję to w umowach i bronię Cię przed nieuzasadnionymi roszczeniami.' },
      { q: 'Obsługa stała czy do projektu?', a: 'Obie opcje. Przy stałym pipelinie kontraktów opłaca się obsługa ciągła; przy jednym dużym kontrakcie rozliczam projekt.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Zabezpieczona umowa i pewna zapłata — zanim wejdziesz na budowę.',
      lead: 'Opisz kontrakt albo spór — bezpłatnie wskażę ryzyka i zaproponuję, jak zabezpieczyć Twoje wynagrodzenie.',
    },
  },

  'obsluga-prawna-architektow': {
    h1: 'Obsługa prawna pracowni architektonicznych i projektantów',
    subtitle: 'Projektujesz i chcesz, żeby umowy chroniły Twoje honorarium i prawa autorskie do projektu? Układam kontrakty projektowe, porządkuję kwestie autorskie i bronię przed nadmierną odpowiedzialnością.',
    intro: 'Projekt to Twój produkt i Twoja własność intelektualna — a jednocześnie źródło ryzyka, gdy umowa nie reguluje praw autorskich, nadzoru i odpowiedzialności za wady dokumentacji. Nieprecyzyjne przeniesienie praw, brak zapisów o polach eksploatacji i nadzorze autorskim czy zbyt szeroka odpowiedzialność potrafią kosztować więcej niż całe honorarium. Wspieram pracownie i projektantów, żeby ich praca była chroniona, a ryzyka — pod kontrolą.',
    introHeading: 'Twój projekt to Twoja własność — zabezpieczę ją.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Podpisujesz umowy projektowe i chcesz zabezpieczyć honorarium oraz prawa do projektu.',
      'Inwestor korzysta z projektu szerzej, niż uzgodniliście, albo bez zapłaty.',
      'Nie masz pewności, czy Twoje umowy prawidłowo regulują prawa autorskie i nadzór autorski.',
      'Grozi Ci odpowiedzialność za wady dokumentacji albo za opóźnienia w procesie.',
      'Chcesz jasno rozdzielić przeniesienie praw od licencji i pól eksploatacji.',
      'Potrzebujesz wzoru umowy, którego możesz używać przy kolejnych zleceniach.',
    ],
    doFor: [
      'Przygotowuję i opiniuję umowy projektowe — zakres, honorarium, terminy, odbiory, odpowiedzialność.',
      'Porządkuję prawa autorskie do projektu — przeniesienie albo licencja, pola eksploatacji, prawa zależne.',
      'Zabezpieczam nadzór autorski i zasady korzystania z dokumentacji przez inwestora.',
      'Ograniczam Twoją odpowiedzialność za wady dokumentacji do rozsądnych granic.',
      'Dochodzę honorarium i chronię projekt przed bezumownym wykorzystaniem.',
      'Przygotowuję powtarzalny wzór umowy dla Twojej pracowni.',
    ],
    steps: [
      'Opisujesz sytuację — jakie zlecenia realizujesz i co chcesz zabezpieczyć.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Działam — układam umowy, porządkuję prawa autorskie i bronię honorarium.',
      'Praca pod ochroną — jasne prawa, bezpieczne honorarium, ograniczone ryzyko.',
    ],
    faq: [
      { q: 'Przeniesienie praw czy licencja — co wybrać?', a: 'To zależy od modelu współpracy i honorarium. Przeniesienie oddaje prawa inwestorowi, licencja pozwala Ci je zachować i udzielać dalej. Kluczowe są pola eksploatacji — dobieram rozwiązanie tak, by chroniło Twój interes i wycenę.' },
      { q: 'Inwestor użył projektu poza umową — co mogę zrobić?', a: 'Jeśli wykorzystał go szerzej, niż pozwala umowa albo licencja, naruszył Twoje prawa. Można żądać zaprzestania i wynagrodzenia. Analizuję zakres uzgodnień i prowadzę sprawę.' },
      { q: 'Jak ograniczyć odpowiedzialność za wady dokumentacji?', a: 'Przez precyzyjny zakres opracowania, zasady odbioru i rozsądne limity odpowiedzialności w umowie. Formułuję je tak, byś nie odpowiadał za cudze błędy w procesie budowlanym.' },
      { q: 'Zrobisz wzór umowy dla mojej pracowni?', a: 'Tak. Przygotowuję powtarzalny, bezpieczny wzór dopasowany do rodzaju Twoich zleceń.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Twój projekt, Twoje prawa, Twoje honorarium — dobrze zabezpieczone.',
      lead: 'Opisz, jak pracujesz — bezpłatnie ocenię Twoje umowy i wskażę, co poprawić w prawach autorskich i odpowiedzialności.',
    },
  },

  'obsluga-prawna-geodetow': {
    h1: 'Obsługa prawna geodetów',
    subtitle: 'Prowadzisz prace geodezyjne i wchodzisz w spory o rozgraniczenia, podziały i ewidencję? Wspieram Cię prawnie — w sporach z zamawiającymi i urzędami oraz w kwestiach odpowiedzialności zawodowej.',
    intro: 'Praca geodety kończy się często tam, gdzie zaczyna się spór prawny: o granice, o podział, o wpis do ewidencji albo o odpowiedzialność za operat. Rozgraniczenia i podziały bywają zaskarżane, urzędy kwestionują dokumentację, a zamawiający próbują przerzucić na geodetę skutki cudzych błędów. Wspieram geodetów prawnie — zabezpieczam umowy, prowadzę spory i bronię przed nieuzasadnioną odpowiedzialnością.',
    introHeading: 'Gdzie kończy się pomiar, a zaczyna spór.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Prowadzisz rozgraniczenie albo podział, który stał się sporny.',
      'Urząd kwestionuje Twoją dokumentację albo odmawia aktualizacji ewidencji.',
      'Zamawiający nie płaci albo obwinia Cię za skutki, na które nie miałeś wpływu.',
      'Grozi Ci postępowanie w sprawie odpowiedzialności zawodowej.',
      'Chcesz zabezpieczyć swoje umowy na prace geodezyjne.',
      'Potrzebujesz prawnika, który rozumie procedury geodezyjne i ewidencyjne.',
    ],
    doFor: [
      'Przygotowuję i opiniuję umowy na prace geodezyjne — zakres, terminy, płatności, odpowiedzialność.',
      'Wspieram w sporach o rozgraniczenia i podziały nieruchomości, na etapie administracyjnym i sądowym.',
      'Reprezentuję Cię w kontaktach z urzędami przy aktualizacji ewidencji gruntów i budynków.',
      'Bronię przed nieuzasadnioną odpowiedzialnością wobec zamawiających i osób trzecich.',
      'Prowadzę sprawy z zakresu odpowiedzialności zawodowej.',
      'Dochodzę wynagrodzenia za wykonane prace geodezyjne.',
    ],
    steps: [
      'Opisujesz sprawę — jakie prace, jaki spór albo jaka potrzeba.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Działam — zabezpieczam umowy, prowadzę spór albo reprezentuję przed urzędem.',
      'Masz wsparcie prawne — w sporach, przed urzędem i w kwestiach odpowiedzialności.',
    ],
    faq: [
      { q: 'Rozgraniczenie stało się sporne — co dalej?', a: 'Gdy strony nie dojdą do porozumienia w trybie administracyjnym, sprawa trafia na drogę sądową. Prowadzę ją i dbam, by Twoja dokumentacja i rola były prawidłowo przedstawione.' },
      { q: 'Urząd kwestionuje moją dokumentację — jak reagować?', a: 'Analizuję podstawę zastrzeżeń i przygotowuję odpowiedź albo odwołanie. Często spór dotyczy interpretacji, którą da się skutecznie obronić.' },
      { q: 'Zamawiający obwinia mnie za cudze błędy — czy odpowiadam?', a: 'Odpowiadasz za własną staranność zawodową, nie za wszystko w procesie. Bronię przed przerzucaniem na geodetę odpowiedzialności, która do niego nie należy.' },
      { q: 'Obsługa stała czy do sprawy?', a: 'Obie opcje — przy stałym wolumenie zleceń sprawdza się obsługa ciągła, przy jednym sporze rozliczam projekt.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Tam, gdzie kończy się pomiar, a zaczyna spór — jestem po Twojej stronie.',
      lead: 'Opisz sprawę — bezpłatnie ocenię ryzyka i zaproponuję, jak Cię zabezpieczyć albo poprowadzić spór.',
    },
  },

  'obsluga-prawna-rzeczoznawcow': {
    h1: 'Obsługa prawna rzeczoznawców majątkowych',
    subtitle: 'Sporządzasz operaty i mierzysz się ze sporami o wyceny oraz odpowiedzialnością zawodową? Wspieram Cię prawnie — bronię Twoich operatów, ograniczam ryzyko i prowadzę bieżącą obsługę.',
    intro: 'Operat szacunkowy bywa kwestionowany z każdej strony — przez strony postępowania, organy i sądy — a rzeczoznawca ponosi odpowiedzialność zawodową i cywilną za swoją pracę. Umiejętna obrona operatu, dobrze skonstruowana umowa i rozsądnie ograniczona odpowiedzialność chronią zarówno Twoją wycenę, jak i Ciebie. Wspieram rzeczoznawców majątkowych prawnie — przy sporach o wyceny, w sprawach odpowiedzialności i na co dzień.',
    introHeading: 'Bronię Twoich wycen — i Ciebie.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Twój operat został zakwestionowany przez stronę, organ albo sąd.',
      'Grozi Ci postępowanie w sprawie odpowiedzialności zawodowej.',
      'Zamawiający albo osoba trzecia kieruje wobec Ciebie roszczenia z tytułu wyceny.',
      'Chcesz zabezpieczyć swoje umowy o sporządzenie operatu i ograniczyć odpowiedzialność.',
      'Potrzebujesz wsparcia przy ocenie operatu przez organizację zawodową.',
      'Szukasz prawnika, który rozumie warsztat wyceny i procedury.',
    ],
    doFor: [
      'Bronię Twoich operatów, gdy są kwestionowane w postępowaniach administracyjnych i sądowych.',
      'Reprezentuję Cię w sprawach z zakresu odpowiedzialności zawodowej rzeczoznawcy majątkowego.',
      'Odpieram roszczenia cywilne zamawiających i osób trzecich związane z wyceną.',
      'Przygotowuję i opiniuję umowy o sporządzenie operatu — z rozsądnym ograniczeniem odpowiedzialności.',
      'Doradzam przy ocenie operatu przez organizację zawodową i przy sporach o metodologię.',
      'Zapewniam bieżące wsparcie prawne dla Twojej działalności.',
    ],
    steps: [
      'Opisujesz sprawę — jaki operat, jaki spór albo jaka potrzeba.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Działam — bronię operatu, prowadzę sprawę o odpowiedzialność albo zabezpieczam umowy.',
      'Masz ochronę prawną — dla swoich wycen i dla siebie.',
    ],
    faq: [
      { q: 'Mój operat jest kwestionowany — jak go obronić?', a: 'Operat to sformalizowany dowód, który można podważyć tylko w sposób jednoznacznie zaprzeczający jego ustaleniom. Wykorzystuję to na Twoją korzyść — pokazuję, że zastrzeżenia nie spełniają tego wymogu, albo bronię metodologii przed organizacją zawodową.' },
      { q: 'Odpowiadam za skutki decyzji opartej na moim operacie?', a: 'Odpowiadasz za rzetelność i staranność wyceny, nie za sposób jej wykorzystania. Bronię przed przerzucaniem na rzeczoznawcę odpowiedzialności, która do niego nie należy.' },
      { q: 'Jak ograniczyć ryzyko w umowie?', a: 'Przez precyzyjny zakres zlecenia, cel wyceny i rozsądne limity odpowiedzialności. Układam umowy tak, by chroniły Cię bez zniechęcania zamawiających.' },
      { q: 'Obsługa stała czy do sprawy?', a: 'Obie opcje — przy stałym wolumenie zleceń sprawdza się obsługa ciągła, przy jednym sporze rozliczam projekt.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Bronię Twoich wycen — i Ciebie.',
      lead: 'Opisz sprawę albo potrzebę — bezpłatnie ocenię ryzyka i zaproponuję model współpracy.',
    },
  },

  'obsluga-prawna-tbs-sim-kooperatyw': {
    h1: 'Obsługa prawna TBS, SIM i kooperatyw mieszkaniowych',
    subtitle: 'Realizujesz społeczne budownictwo czynszowe albo inwestycję kooperatywy? Prowadzę obsługę prawną tych szczególnych form — od struktury i umów po najem, partycypacje i rozliczenia.',
    intro: 'Społeczne formy mieszkalnictwa rządzą się własnymi przepisami — innymi niż zwykła deweloperka czy najem komercyjny. Towarzystwa budownictwa społecznego i zastępujące je w nowych projektach społeczne inicjatywy mieszkaniowe działają na podstawie ustawy o społecznych formach rozwoju mieszkalnictwa, a kooperatywy mieszkaniowe — na podstawie odrębnej ustawy obowiązującej od 2023 roku. Każda z tych form ma inne zasady finansowania, umów i rozliczeń. Obsługuję je prawnie, żeby projekt był bezpieczny i zgodny z reżimem, w którym działa.',
    introHeading: 'Społeczne budownictwo ma swoje reguły.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Prowadzisz TBS albo SIM i potrzebujesz obsługi umów, najmu i partycypacji.',
      'Tworzysz nowy podmiot społecznego budownictwa i musisz ustawić strukturę oraz statut.',
      'Realizujesz inwestycję kooperatywy mieszkaniowej i potrzebujesz umowy członków oraz obsługi nabycia gruntu.',
      'Rozliczasz partycypacje, kaucje i najem w społecznym budownictwie czynszowym.',
      'Korzystasz ze wsparcia publicznego i chcesz mieć pewność zgodności z jego warunkami.',
      'Szukasz prawnika, który zna reżim społecznych form mieszkalnictwa.',
    ],
    doFor: [
      'Ustawiam strukturę i dokumenty założycielskie TBS, SIM oraz kooperatyw — statuty, umowy, regulaminy.',
      'Przygotowuję i obsługuję umowy najmu, partycypacji oraz rozliczenia w społecznym budownictwie czynszowym.',
      'Prowadzę obsługę inwestycji kooperatywy — umowę określającą zasady współdziałania członków i nabycie gruntu.',
      'Doradzam przy korzystaniu ze wsparcia publicznego i zgodności z jego warunkami.',
      'Reprezentuję w relacjach z gminą, KZN i innymi podmiotami zaangażowanymi w projekt.',
      'Prowadzę spory i windykację w ramach społecznego budownictwa.',
    ],
    steps: [
      'Opisujesz projekt — jaka forma, na jakim etapie i czego potrzebujesz.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Działam — ustawiam strukturę i umowy albo prowadzę konkretny etap inwestycji.',
      'Projekt na pewnym gruncie prawnym — zgodny z reżimem, w którym działasz.',
    ],
    faq: [
      { q: 'Czym różni się SIM od TBS?', a: 'SIM to następca TBS — od 2021 roku nie tworzy się już nowych towarzystw, a ich rolę przejęły społeczne inicjatywy mieszkaniowe. Istniejące TBS działają nadal albo przekształcają się w SIM. Obie formy budują mieszkania na wynajem na podobnych zasadach; dobieram i obsługuję właściwą.' },
      { q: 'Na czym polega kooperatywa mieszkaniowa?', a: 'To grupa osób, która wspólnie realizuje inwestycję mieszkaniową na własne potrzeby, na podstawie umowy określającej zasady współdziałania członków — od 2023 roku uregulowanej ustawowo, często z możliwością nabycia gruntu gminnego na preferencyjnych zasadach. Prowadzę taką inwestycję od strony prawnej.' },
      { q: 'Jak rozliczać partycypacje i kaucje w SIM/TBS?', a: 'Zgodnie z ustawą i umową partycypacyjną, z zachowaniem zasad zwrotu i waloryzacji. Przygotowuję dokumentację tak, by rozliczenia były jasne i odporne na spory.' },
      { q: 'Czy wsparcie publiczne nakłada dodatkowe rygory?', a: 'Tak — korzystanie ze środków publicznych wiąże się z warunkami, których naruszenie grozi zwrotem wsparcia. Pilnuję zgodności projektu z tymi warunkami.' },
      { q: 'Obsługa stała czy do projektu?', a: 'Obie opcje — podmioty społecznego budownictwa zwykle korzystają z obsługi ciągłej, kooperatywy częściej z obsługi jednej inwestycji.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Społeczne budownictwo ma swoje reguły — poprowadzę Cię przez nie bezpiecznie.',
      lead: 'Opisz projekt — bezpłatnie ocenię, jak ustawić strukturę i umowy zgodnie z reżimem, w którym działasz.',
    },
  },

});

Object.assign(window.SERVICE_CONTENT, {

  'obsluga-prawna-funduszy-prs': {
    h1: 'Obsługa prawna inwestorów instytucjonalnych i funduszy (PRS)',
    subtitle: 'Budujesz albo kupujesz portfele najmu instytucjonalnego? Prowadzę due diligence, transakcje pakietowe i dokumentację najmu — z myślą o skali i bezpieczeństwie inwestycji.',
    intro: 'Inwestycja instytucjonalna w najem to gra o dużą stawkę, w której ryzyko kryje się w szczegółach: w stanie prawnym pakietu, w konstrukcji transakcji, w umowach najmu i w zabezpieczeniach. Fundusze i inwestorzy PRS potrzebują partnera, który przeprowadzi rzetelne due diligence, zbuduje bezpieczną strukturę transakcji i przygotuje dokumentację najmu odporną na masową skalę. Wspieram takie podmioty na każdym etapie — od analizy po zarządzanie portfelem.',
    introHeading: 'Skala wymaga precyzji na każdym etapie.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Kupujesz albo budujesz portfel mieszkań na wynajem instytucjonalny.',
      'Planujesz transakcję pakietową albo nabycie w modelu forward.',
      'Potrzebujesz due diligence prawnego nieruchomości albo spółki celowej.',
      'Chcesz jednolitej, bezpiecznej dokumentacji najmu dla całego portfela.',
      'Zależy Ci na strukturze transakcji optymalnej pod kątem ryzyka.',
      'Zarządzasz portfelem i potrzebujesz stałego wsparcia prawnego.',
    ],
    doFor: [
      'Prowadzę due diligence prawne nieruchomości i spółek celowych przed nabyciem.',
      'Strukturyzuję i obsługuję transakcje pakietowe oraz nabycia w modelu forward.',
      'Przygotowuję jednolitą dokumentację najmu instytucjonalnego dla całego portfela.',
      'Negocjuję umowy nabycia, zabezpieczenia i warunki zawieszające.',
      'Doradzam przy zarządzaniu portfelem, cesjach i restrukturyzacjach.',
      'Zapewniam stałą obsługę prawną inwestycji w skali.',
    ],
    steps: [
      'Opisujesz inwestycję — jaki portfel albo transakcja i na jakim etapie.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Działam — prowadzę due diligence, strukturyzuję transakcję i przygotowuję dokumentację.',
      'Inwestycja zabezpieczona — na etapie nabycia i w bieżącym zarządzaniu.',
    ],
    faq: [
      { q: 'Co obejmuje due diligence przed nabyciem portfela?', a: 'Stan prawny nieruchomości i spółek, obciążenia, umowy najmu, roszczenia, zgodność z prawem budowlanym i planistycznym oraz ryzyka podatkowe do zaadresowania. Wynik ujmuję w formie, która wprost przekłada się na decyzję i cenę.' },
      { q: 'Kupować aktywa czy udziały w spółce?', a: 'To zależy od profilu ryzyka, podatków i celu inwestycji. Każdy wariant ma inne konsekwencje — analizuję je i rekomenduję strukturę optymalną dla Twojej transakcji.' },
      { q: 'Jak ujednolicić najem w dużym portfelu?', a: 'Przez wzorcową, bezpieczną dokumentację najmu dopasowaną do modelu instytucjonalnego, z zabezpieczeniami i procedurami skalowalnymi na setki lokali. Przygotowuję taki standard.' },
      { q: 'Obsługa stała czy do transakcji?', a: 'Obie opcje — fundusze zwykle łączą projektową obsługę transakcji ze stałym wsparciem przy zarządzaniu portfelem.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Skala wymaga precyzji. Zapewnię ją na każdym etapie inwestycji.',
      lead: 'Opisz portfel albo transakcję — bezpłatnie ocenię ryzyka i zaproponuję zakres współpracy.',
    },
  },

  'obsluga-prawna-inwestorow-flipping': {
    h1: 'Obsługa prawna inwestorów i firm flippingowych',
    subtitle: 'Kupujesz, remontujesz i sprzedajesz w tempie rynku? Prowadzę szybkie due diligence, umowy inwestycyjne i cesje — tak, żeby prawo nie hamowało Twojego obrotu.',
    intro: 'Flipping i inwestowanie w nieruchomości żyją tempem: okazja pojawia się i znika w kilka dni, a każdy przestój kosztuje. Jednocześnie pośpiech to najczęstsza przyczyna kosztownych błędów — w stanie prawnym, w umowie, w cesji, w rozliczeniu. Potrzebujesz prawnika, który nadąża za rynkiem i daje szybkie, jednoznaczne odpowiedzi. Wspieram profesjonalnych inwestorów tak, by transakcje były i szybkie, i bezpieczne.',
    introHeading: 'Szybko, ale bezpiecznie.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Kupujesz nieruchomości pod remont i odsprzedaż i działasz w tempie rynku.',
      'Potrzebujesz szybkiej weryfikacji stanu prawnego przed zakupem.',
      'Handlujesz cesjami umów deweloperskich albo przedwstępnych.',
      'Zawierasz umowy inwestycyjne ze wspólnikami albo finansującymi.',
      'Chcesz powtarzalnych wzorów, które przyspieszą kolejne transakcje.',
      'Zależy Ci na prawniku, który odpowiada od ręki, a nie za tydzień.',
    ],
    doFor: [
      'Prowadzę szybkie due diligence prawne przed zakupem — z jednoznaczną oceną ryzyka.',
      'Przygotowuję i negocjuję umowy nabycia, przedwstępne i inwestycyjne.',
      'Obsługuję cesje umów deweloperskich i przedwstępnych oraz ich rozliczenia.',
      'Zabezpieczam transakcje wspólne — umowy między inwestorami i z finansującymi.',
      'Przygotowuję powtarzalne wzory dokumentów pod Twój model działania.',
      'Reaguję szybko przy bieżących transakcjach — priorytetowo dla stałych klientów.',
    ],
    steps: [
      'Opisujesz swój model — co kupujesz, jak często i czego potrzebujesz najszybciej.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Działam szybko — weryfikuję, przygotowuję umowy i obsługuję cesje w tempie transakcji.',
      'Obrót bez przestojów — szybko, ale bezpiecznie.',
    ],
    faq: [
      { q: 'Jak szybko sprawdzisz stan prawny nieruchomości?', a: 'Przy typowej transakcji ekspresowo — księga wieczysta, obciążenia, stan planistyczny i najważniejsze ryzyka. Daję jednoznaczną odpowiedź „kupować / uwaga / nie”, bo w Twoim modelu liczy się czas.' },
      { q: 'Czy cesja umowy deweloperskiej jest bezpieczna?', a: 'Może być, jeśli dobrze skonstruowana i rozliczona — ale kryje pułapki (zgoda dewelopera, podatki, odpowiedzialność). Obsługuję cesje tak, by nie zostawiały Ci ryzyka po sprzedaży.' },
      { q: 'Zrobisz wzory pod moje transakcje?', a: 'Tak. Przygotowuję powtarzalne, bezpieczne wzory umów i cesji, które przyspieszają kolejne zakupy i sprzedaże.' },
      { q: 'Jak szybko reagujesz?', a: 'To sedno tej współpracy — stali klienci mają priorytet, a kontakt prowadzę przede wszystkim mailowo, więc odpowiedzi masz szybko i na piśmie.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce.' },
    ],
    cta: {
      heading: 'Nadążam za rynkiem — żeby prawo nie hamowało Twoich transakcji.',
      lead: 'Opisz swój model inwestowania — bezpłatnie ocenię, jak przyspieszyć i zabezpieczyć obrót.',
    },
  },

  'obsluga-prawna-deweloperow-oze': {
    h1: 'Obsługa prawna deweloperów OZE i firm dzierżawiących grunty',
    subtitle: 'Budujesz portfel gruntów pod fotowoltaikę i wiatraki? Prowadzę umowy dzierżawy, służebności, cesje i zabezpieczenia — tak, by projekt był bankowalny i odporny na spory z właścicielami.',
    intro: 'Projekt OZE stoi na gruncie — dosłownie i prawnie. O jego wartości i bankowalności decydują umowy dzierżawy, służebności przesyłu i drogowe, prawidłowo skonstruowane warunki zawieszające oraz cesje na spółki celowe i finansujących. Błąd w tytule prawnym do gruntu potrafi zablokować przyłączenie albo finansowanie całego przedsięwzięcia. Wspieram deweloperów OZE i firmy dzierżawiące grunty od zabezpieczenia terenu po zamknięcie finansowe.',
    introHeading: 'Projekt jest tyle wart, ile pewny jest tytuł do gruntu.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Budujesz portfel gruntów pod fotowoltaikę, wiatraki albo magazyny energii.',
      'Negocjujesz dzierżawy z właścicielami i chcesz umów bankowalnych.',
      'Potrzebujesz służebności przesyłu i dróg dojazdowych do infrastruktury.',
      'Planujesz cesje umów na spółki celowe albo na inwestora/finansującego.',
      'Zależy Ci na zabezpieczeniach i warunkach zawieszających chroniących projekt.',
      'Napotykasz spory albo roszczenia właścicieli gruntów.',
    ],
    doFor: [
      'Przygotowuję i negocjuję umowy dzierżawy gruntu pod OZE — z warunkami zawieszającymi, waloryzacją i zabezpieczeniami.',
      'Ustanawiam służebności przesyłu i drogi konieczne niezbędne dla infrastruktury.',
      'Obsługuję cesje umów na spółki celowe oraz na inwestorów i finansujących.',
      'Buduję strukturę tytułu prawnego do gruntu odporną na due diligence banku.',
      'Zabezpieczam projekt przed ryzykiem zasiedzenia, wypowiedzenia i sporów z właścicielami.',
      'Prowadzę spory i renegocjacje z właścicielami gruntów.',
    ],
    steps: [
      'Opisujesz projekt — jaki portfel, jaka technologia i na jakim etapie.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Działam — porządkuję dzierżawy, służebności i cesje pod bankowalność.',
      'Grunt gotowy pod finansowanie — tytuł prawny odporny na due diligence.',
    ],
    faq: [
      { q: 'Co czyni umowę dzierżawy OZE bankowalną?', a: 'Długi, pewny czas trwania, jednoznaczny tytuł do całego terenu, warunki zawieszające dopasowane do etapów projektu, prawo cesji, zabezpieczenia i brak ryzyk, które bank wychwyci w due diligence. Konstruuję umowy właśnie pod ten test.' },
      { q: 'Jak zabezpieczyć dojazd i przyłączenie?', a: 'Przez służebności drogi koniecznej i przesyłu ustanowione na całej trasie infrastruktury. Prowadzę ich ustanowienie, także sądowe, i pilnuję, by pokrywały realne potrzeby projektu.' },
      { q: 'Czy właściciel może wypowiedzieć umowę w trakcie projektu?', a: 'Dobrze skonstruowana umowa mocno to ogranicza i przewiduje skutki naruszeń po obu stronach. Zabezpieczam Cię przed nagłym wyjściem właściciela, a przy sporze reprezentuję dewelopera.' },
      { q: 'Obsługa portfela czy pojedynczego projektu?', a: 'Obie opcje — deweloperzy OZE zwykle korzystają ze stałej obsługi całego portfela dzierżaw.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Projekt OZE jest tyle wart, ile pewny jest tytuł do gruntu.',
      lead: 'Opisz portfel — bezpłatnie ocenię dzierżawy i służebności pod kątem bankowalności i wskażę ryzyka.',
    },
  },

  'obsluga-prawna-operatorow-najmu': {
    h1: 'Obsługa prawna operatorów najmu, PRS i condohoteli',
    subtitle: 'Zarządzasz najmem w cudzym imieniu, oferujesz gwarancje czynszu albo prowadzisz condohotel? Układam umowy najmu zwrotnego, modele podnajmu i zarządzania — z uczciwym rozłożeniem ryzyka.',
    intro: 'Modele operatorskie — najem zwrotny, gwarancje czynszu, podnajem, condohotel — opierają się na obietnicy dochodu dla właściciela i sprawności operatora. Problem w tym, że ryzyko bywa źle rozłożone: gwarancja czynszu potrafi obciążyć operatora ponad miarę, a przy condohotelach dochodzi wrażliwa relacja z nabywcami-konsumentami i uwaga regulatora. Układam te modele tak, by były rentowne, zgodne z prawem i odporne na spory.',
    introHeading: 'Model, który broni się finansowo i prawnie.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Zarządzasz najmem w imieniu właścicieli i potrzebujesz bezpiecznych umów operatorskich.',
      'Oferujesz gwarancje czynszu i chcesz uczciwie rozłożyć ryzyko.',
      'Prowadzisz albo uruchamiasz condohotel lub aparthotel.',
      'Budujesz model podnajmu i zarządzania na skalę.',
      'Sprzedajesz nabywcom jednostki z gwarantowanym dochodem i musisz zadbać o zgodność.',
      'Napotykasz spory z właścicielami, nabywcami albo najemcami.',
    ],
    doFor: [
      'Przygotowuję umowy najmu zwrotnego, zarządzania i podnajmu — z jasnym podziałem ryzyka.',
      'Konstruuję modele gwarancji czynszu odporne na wahania rynku i spory.',
      'Obsługuję prawnie projekty condohotelowe i aparthotelowe, w tym relacje z nabywcami.',
      'Dbam o zgodność oferty kierowanej do nabywców-konsumentów i o ryzyka regulacyjne.',
      'Reprezentuję operatora w sporach z właścicielami, nabywcami i najemcami.',
      'Zapewniam stałą obsługę prawną modelu operatorskiego.',
    ],
    steps: [
      'Opisujesz model — najem zwrotny, gwarancje, podnajem czy condohotel i na jakim etapie.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Działam — układam umowy i strukturę tak, by były rentowne i zgodne z prawem.',
      'Model pod kontrolą — uczciwie rozłożone ryzyko i mniejsza ekspozycja na spory.',
    ],
    faq: [
      { q: 'Jak rozłożyć ryzyko przy gwarancji czynszu?', a: 'Tak, by gwarancja była atrakcyjna dla właściciela, ale nie wywracała rentowności operatora przy pustostanach czy spadku stawek. Buduję mechanizmy urealniające gwarancję i zabezpieczające obie strony.' },
      { q: 'Czy condohotel niesie szczególne ryzyka prawne?', a: 'Tak — sprzedaż jednostek z obietnicą dochodu kierowana do konsumentów jest wrażliwa i przyciąga uwagę regulatora. Dbam o zgodność oferty i umów, by uniknąć zarzutu wprowadzania w błąd.' },
      { q: 'Jak zabezpieczyć umowę zarządzania najmem?', a: 'Przez jasny zakres, zasady rozliczeń, odpowiedzialność i wyjście z umowy. Układam ją tak, by chroniła operatora i była uczciwa wobec właściciela.' },
      { q: 'Obsługa stała czy do projektu?', a: 'Obie opcje — operatorzy zwykle korzystają ze stałej obsługi modelu, a przy uruchomieniu condohotelu z obsługi projektowej.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Model operatorski, który się broni — finansowo i prawnie.',
      lead: 'Opisz swój model — bezpłatnie ocenię rozłożenie ryzyka i zgodność oraz zaproponuję zakres współpracy.',
    },
  },

  'obsluga-prawna-najemcow-komercyjnych': {
    h1: 'Obsługa prawna najemców komercyjnych i sieci handlowych',
    subtitle: 'Wynajmujesz lokale albo powierzchnie pod działalność i sieć? Negocjuję umowy najmu po stronie najemcy — czynsz, indeksację, fit-out i bezpieczne wyjście z umowy.',
    intro: 'Umowy najmu komercyjnego pisze wynajmujący, więc naturalnie zabezpieczają jego. Dla najemcy — zwłaszcza sieci z wieloma lokalizacjami — kluczowe jest coś innego: przewidywalny czynsz i indeksacja, rozsądny podział kosztów fit-outu, elastyczność przy zmianach oraz realna możliwość wyjścia, gdy lokalizacja przestaje się opłacać. Negocjuję i porządkuję najmy po stronie najemcy, żeby warunki były uczciwe i policzalne.',
    introHeading: 'Najem po stronie najemcy — policzalny i elastyczny.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Negocjujesz najem lokalu albo powierzchni pod działalność.',
      'Rozwijasz sieć i chcesz jednolitych, bezpiecznych warunków w kolejnych lokalizacjach.',
      'Martwi Cię indeksacja czynszu i rosnące opłaty eksploatacyjne.',
      'Ponosisz koszty fit-outu i chcesz je uczciwie rozłożyć z wynajmującym.',
      'Chcesz mieć realną możliwość wyjścia z nierentownej lokalizacji.',
      'Toczysz spór z wynajmującym o czynsz, kaucję albo stan lokalu.',
    ],
    doFor: [
      'Negocjuję umowy najmu komercyjnego po stronie najemcy — czynsz, okres, opcje przedłużenia i wyjścia.',
      'Urealniam indeksację i podział opłat eksploatacyjnych oraz kosztów wspólnych.',
      'Porządkuję zasady fit-outu, kontrybucji wynajmującego i stanu zwrotu lokalu.',
      'Zabezpieczam elastyczność sieci — cesje, podnajem, zmiana profilu, wcześniejsze wyjście.',
      'Standaryzuję dokumentację najmu dla wielu lokalizacji.',
      'Prowadzę spory z wynajmującymi i rozliczenia kaucji.',
    ],
    steps: [
      'Opisujesz potrzebę — pojedynczy najem czy warunki dla sieci lokalizacji.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Działam — negocjuję warunki i porządkuję dokumentację po Twojej stronie.',
      'Najem policzalny i elastyczny — uczciwe warunki i bezpieczne wyjście.',
    ],
    faq: [
      { q: 'Jak okiełznać indeksację czynszu?', a: 'Przez jasny wskaźnik, ograniczenia wzrostu i przejrzysty katalog opłat eksploatacyjnych. Negocjuję zapisy tak, byś nie podpisywał się pod nieograniczonym wzrostem kosztów.' },
      { q: 'Kto powinien płacić za fit-out?', a: 'To kwestia negocjacji — często udaje się uzyskać kontrybucję wynajmującego albo okres bezczynszowy na pokrycie prac. Układam to tak, by nakłady rozłożyć uczciwie.' },
      { q: 'Czy mogę wyjść z nierentownej lokalizacji?', a: 'Zależy od umowy — dlatego opcje wyjścia, cesji i podnajmu trzeba wynegocjować na starcie. Wbudowuję je w umowę, żeby sieć zachowała elastyczność.' },
      { q: 'Obsługa stała czy do jednej umowy?', a: 'Obie opcje — sieci zwykle korzystają ze stałej obsługi kolejnych najmów, przy pojedynczym lokalu rozliczam projekt.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Najem po stronie najemcy — policzalny, elastyczny, uczciwy.',
      lead: 'Opisz najem albo plany sieci — bezpłatnie ocenię warunki i wskażę, co wynegocjować.',
    },
  },

  'obsluga-prawna-przedsiebiorstw-rolnych': {
    h1: 'Obsługa prawna przedsiębiorstw rolnych i właścicieli dużych areałów',
    subtitle: 'Prowadzisz duże gospodarstwo albo zarządzasz areałem? Obsługuję obrót ziemią i KOWR, dzierżawy, projekty OZE, scalenia i sukcesję — kompleksowo, z myślą o skali i ciągłości.',
    intro: 'Duży areał to duże pieniądze i duże ryzyka: obrót ziemią pod reżimem KOWR, dzierżawy, projekty OZE na gruntach, scalenia i podziały, wreszcie sukcesja, od której zależy przetrwanie gospodarstwa w kolejnym pokoleniu. Każdy z tych obszarów rządzi się osobnymi przepisami, a błąd potrafi kosztować grunt albo jego wartość. Obsługuję przedsiębiorstwa rolne i właścicieli dużych areałów kompleksowo — łącząc transakcje, kontrakty i planowanie sukcesji.',
    introHeading: 'Jeden prawnik do wszystkich spraw gospodarstwa.',
    whenTitle: 'Czy to Twoja sytuacja',
    whenHeading: '',
    when: [
      'Kupujesz albo sprzedajesz ziemię rolną pod reżimem KOWR i UKUR.',
      'Zawierasz albo porządkujesz dzierżawy na dużą skalę.',
      'Rozważasz projekt OZE na swoich gruntach albo negocjujesz dzierżawę z deweloperem.',
      'Planujesz scalenie, podział albo uporządkowanie stanu prawnego areału.',
      'Myślisz o sukcesji gospodarstwa i przekazaniu go następcom.',
      'Potrzebujesz jednego prawnika do wszystkich spraw gospodarstwa.',
    ],
    doFor: [
      'Obsługuję obrót ziemią rolną — zgody i pierwokup KOWR, status rolnika, ważność transakcji.',
      'Przygotowuję i porządkuję dzierżawy rolne oraz spory z dzierżawcami.',
      'Negocjuję dzierżawy pod OZE i zabezpieczam grunty przy projektach fotowoltaicznych i wiatrowych.',
      'Prowadzę scalenia, podziały i regulację stanu prawnego areału.',
      'Planuję i wdrażam sukcesję gospodarstwa — z zabezpieczeniem ciągłości i następców.',
      'Zapewniam stałą, kompleksową obsługę prawną przedsiębiorstwa rolnego.',
    ],
    steps: [
      'Opisujesz gospodarstwo i potrzebę — jaki areał, jakie sprawy i cele.',
      'Bezpłatna wstępna rozmowa w 24 h — proponuję model: stała obsługa albo pojedynczy projekt; podaję zakres, cenę i termin.',
      'Działam — prowadzę transakcje, kontrakty i planowanie sukcesji.',
      'Areał poukładany — bezpieczny obrót, dobre kontrakty i zabezpieczona przyszłość.',
    ],
    faq: [
      { q: 'Jak bezpiecznie handlować dużym areałem pod reżimem KOWR?', a: 'Przez prawidłowe wykazanie statusu nabywcy albo uzyskanie zgody KOWR, uwzględnienie pierwokupu i 5-letnich ograniczeń oraz właściwą kolejność czynności. Prowadzę transakcję tak, by była ważna i nie narażała gruntu na przejęcie.' },
      { q: 'Czy dzierżawa pod OZE się opłaca?', a: 'Bywa bardzo dochodowa, ale wiąże grunt na dekady i kryje pułapki w warunkach przygotowawczych oraz zabezpieczeniach. Negocjuję ją tak, by chroniła Twój interes na cały okres i na wypadek, gdyby projekt nie ruszył.' },
      { q: 'Jak zaplanować sukcesję gospodarstwa?', a: 'Przez dobór narzędzi prawnych zabezpieczających ciągłość i następców, z uwzględnieniem specyfiki obrotu ziemią rolną. Układam plan pod Twoją rodzinę i strukturę gospodarstwa.' },
      { q: 'Jeden prawnik do wszystkich spraw?', a: 'Tak — przy dużym areale stała, kompleksowa obsługa jest wygodniejsza i tańsza niż rozliczanie każdej sprawy osobno.' },
      { q: 'Czy zajmiesz się tym zdalnie?', a: 'Tak, w całej Polsce. Kontakt prowadzę przede wszystkim mailowo.' },
    ],
    cta: {
      heading: 'Duży areał wymaga jednego prawnika do wszystkiego. Jestem nim.',
      lead: 'Opisz swoje gospodarstwo — bezpłatnie ocenię potrzeby i zaproponuję zakres kompleksowej obsługi.',
    },
  },

});
